Sampling priority based trace publishing lanes
DataDog/dd-trace-java pull request #1782
Opened 2020-08-18 10:35 UTC by richardstartin

This introduces two queues, a primary queue and a secondary queue. Nothing should change for high priority traces (USER_KEEP/SAMPLER_KEEP) but low priority traces go into a queue which is drained less. This allows high priority traces to skip ahead low priority traces. This means, if we have to drop because we can't keep up with the rate traces are produced, we're more likely to drop low priority traces.

This also propagates information about sampling priority to the monitor so we can see whether the strategy really works in load tests.

2020-08-18 12:36 UTC, bantonsson commented on dd-trace-core/src/test/groovy/datadog/trace/common/writer/SpecifyPrioritization.groovy
> +  def "dead letters strategy sends drops unkept traces if the primary queue is full" () {
`s/sends drops/drops/`

2020-08-18 12:38 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
>              Thread.yield();
So are we calling `yeild` 50 times before we poll the second queue?

2020-08-18 12:40 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
>              Thread.yield();
This needs refinement

2020-08-18 12:44 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
>              Thread.yield();
I've changed it slightly, but it might be worth discussing.

2020-08-18 13:40 UTC, richardstartin commented
Need to pump up the coverage for the prioritisation strategies

2020-08-18 16:37 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Prioritization.java
> +      CountDownLatch latch = new CountDownLatch(2);
the countdown latch works nicely here...

2020-08-19 08:12 UTC, bantonsson requested changes
Looks good apart from some flushing confusion.

2020-08-19 08:12 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/FlushEvent.java
> +final class FlushEvent {
So there seems to be two `FlushEvent` classes. This one and one at `TraceProcessingWorker.FlushEvent`. We never seem to check for this one.

2020-08-19 09:35 UTC, bantonsson approved these changes
👍

2020-08-19 09:38 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/FlushEvent.java
> +final class FlushEvent {
> There can be only one...

2020-08-19 14:31 UTC, merged