Collect stacktrace for local root span
DataDog/dd-trace-java pull request #1806
Opened 2020-08-26 18:38 UTC by tylerbenson

For now save it as a tag similar to errors.

2020-08-26 19:08 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/processor/rule/ContextStackRule.java
> +    final StackTraceElement[] stack = span.getContextStack();
These things are huge, and spans live for quite a long time. Could you measure this over the course of **several hours** and pay attention to garbage collection logs?

2020-08-27 09:48 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/processor/rule/ContextStackRule.java
> +    final StackTraceElement[] stack = span.getContextStack();
There are also going to be a lot of duplicated stacks, so a way to de-dup them would be good. Even better if we could de-dup them before building the stacktrace string (ie. by doing some aggregate hash/digest over the stack elements)

2020-08-27 13:36 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/processor/rule/ContextStackRule.java
> +    final StackTraceElement[] stack = span.getContextStack();
yeah, we have some ideas for how to improve this... mostly around taking advantage of the 0.5 string table.  This PR was mainly to investigate the perf impact of such a change.

2020-08-27 21:26 UTC, tylerbenson commented on dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
> +      "trace.span.stacktrace.client.duration.millis";
@jpbempel here's the config key (prefix `dd.`) to adjust the threshold.

2020-08-28 00:56 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/processor/rule/ContextStackRule.java
> +    final StackTraceElement[] stack = span.getContextStack();
As usual, I'm not really fond of Rules.  I still think we need a better deferred value API.

I also think we can make better use of the StringBuilder here.  I was wondering if it could sized better.
I'm also wondering if we really need to call StringBuilder.toString() or if we could just pass the builder directly as a CharSequence.
But maybe that doesn't help because we'll end up wanting a StringTable look-up later.

I suppose more generally sending a String seems like a step backwards from our prior BLOB format.

2020-08-28 09:04 UTC, jpbempel requested changes

2020-08-28 11:32 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +        }
Fine grained synchronization like this also challenges the original intention to make this a simple `HashMap` and grant exclusive to the whole map for serialisation/rules processing in one go inside a `synchronized` block. cc @bantonsson 

This would also be avoided by just having a field called `spanKind`...

2020-08-28 16:42 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/processor/rule/ContextStackRule.java
> +    final StackTraceElement[] stack = span.getContextStack();
I've made the change to use StringBuilder.  As for the other items, I agree we need a better deferred value API.  Probably should be tied to a "typed key". I also think we need a better serialization format for stacktraces. The simple "toString" is prone to bloat.

2020-08-28 16:46 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +    return contextStack == null ? null : contextStack.getStackTrace();
I'm confused... Is this because the instructions can be reordered? The field is never set to null besides construction, so it can't go from a state of non-null to null.

2020-08-28 16:54 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +        }
I agree this would be improved by using a `spanKind` field.  I added a TODO for that.

I also applied the suggestion to move stacktrace creation outside of sync block.

2020-08-28 19:12 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +    if (contextStack == null
@jpbempel I found a bug here that impacted when the client contextStack was collected.  Probably explains why the tests were "identical".  Sorry about that.

2020-09-01 13:19 UTC, jpbempel approved these changes

2020-10-26 18:23 UTC, closed without merging