Add option to not treat async request timeouts as errors
DataDog/dd-trace-java pull request #1844
Opened 2020-09-08 11:13 UTC by mcculls

For scenarios where clients disconnect without explicitly closing connections it is useful to not treat timeouts as errors when recording spans.

The default behaviour remains the same (async request timeouts are treated as errors) but you can now set:
```
trace.servlet.timeout.asError=false
```
to not treat them as errors. These spans will still have the "timeout" tag set regardless of this setting.

2020-09-08 12:53 UTC, richardstartin approved these changes
Looks reasonable

2020-09-08 13:35 UTC, tylerbenson reviewed
Would it make sense to have the config key not be servlet specific?  Wouldn't the same config make sense for any http server?

2020-09-08 13:54 UTC, mcculls commented
@tylerbenson you mean `trace.servlet.asyncTimeout.asError` or `trace.servlet3.asyncTimeout.asError` to make clear this is specific to Servlet3 async timeouts?

2020-09-08 13:56 UTC, tylerbenson commented
I'm asking if there are other (non-servlet) frameworks that have similar behavior that we might in the future want to provide a similar option for.

2020-09-08 14:07 UTC, mcculls commented
Personally I feel better keeping this a servlet option, rather than something more general like `trace.asyncTimeout.asError` - if only because an asynchronous timeout for framework "Foo" might mean something different to an asynchronous servlet timeout. It's also easier to alias it to a more general option if we decide that makes sense than try to split it out later (especially once people set it in their config files)

2020-09-08 14:30 UTC, tylerbenson requested changes
ok, that's fine.  The current config also allows flexibility in the future:
`dd.trace.<instrumentation name>.async-timeout.is-error`

(note, we don't generally have camel case in config.  separate with `-`.)

2020-09-08 14:56 UTC, tylerbenson approved these changes

2020-09-08 14:56 UTC, tylerbenson commented on dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
> +      "trace.servlet.async-timeout.is-error";
I think my only remaining question is should the `is-` be removed? Don't have strong opinion either way though.

2020-09-08 15:02 UTC, mcculls commented on dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
> +      "trace.servlet.async-timeout.is-error";
Yes, I think that's reasonable: f04104f32 - avoids ending up with multiple `is` in the method name

2020-09-08 16:14 UTC, tylerbenson approved these changes

2020-09-09 05:32 UTC, lpriima approved these changes

2020-09-09 06:31 UTC, bantonsson approved these changes

2020-09-09 11:39 UTC, merged