Replace Thread CpuTime JMX access to a generic one
DataDog/dd-trace-java pull request #1866
Opened 2020-09-15 08:35 UTC by jpbempel

Instead of an interface for accessing just ThreadCpuTime from JMX,
we have a generic one, where we can add as many method we need when
accessing JMX.
Here we have added also getCurrentPid, but we could add access to
other JMX features like Thread dumps...

2020-09-15 09:29 UTC, jbachorik requested changes
Looks good!
I have just a few minor comments - rather 'food for thought' then requests.
The only thing I really think should be addressed is making `SystemAccess` class `final`.

2020-09-15 09:29 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/util/JmxSystemProvider.java
> +public class JmxSystemProvider implements SystemProvider {
A nit - would be good to have the specific implementations being `final` to encourage composition over inheritance (and make the whole API more evolvable by providing fewer potentially moving parts).

2020-09-15 09:29 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
> +public class SystemAccess {
This one should really be `final`. It is an API entry point and we don't really want its subclasses floating around when we keep on evolving this entry point.

2020-09-15 09:29 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
> +      log.info("Will not enable JMX access. Profiling is disabled.");
This makes me wonder - do we really need the `SystemAccess` tied to profiling? 
Not critical request but would be good to think about it.

2020-09-15 09:29 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/util/SystemProvider.java
> +public interface SystemProvider {
This provider is providing for `SystemAccess` - hence `SystemAccessProvider` would convey the intention better, IMO.

```suggestion
public interface SystemAccessProvider {
```

2020-09-15 09:47 UTC, jpbempel commented on dd-trace-core/src/main/java/datadog/trace/core/util/JmxSystemProvider.java
> +public class JmxSystemProvider implements SystemProvider {
I don't like to prevent any further modifications with final because it's always difficult to foresee any evolutions that we may need in the future. that's also an internal API here not critical.

2020-09-15 09:49 UTC, jpbempel commented on dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
> +public class SystemAccess {
This one is IMHO the less required to be final, there are only static methods. What would be the point to extend it?

2020-09-15 09:51 UTC, jpbempel commented on dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
> +      log.info("Will not enable JMX access. Profiling is disabled.");
I also don't see the need to be tied to profiling, but right now, only profiling is using it. 
This could test could be removed if we want to expose to a broad scope of the tracer.

2020-09-15 10:00 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/util/JmxSystemProvider.java
> +public class JmxSystemProvider implements SystemProvider {
Why would you extend this class to evolve the API? On the contrary, allowing uncontrolled inheritance may make it quite difficult to do the evolution without touching all the child types.

2020-09-15 10:02 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
> +public class SystemAccess {
Exactly. What would be the point? Yet, if someone decides to extend it for whatever strange reason you are for a surprise when evolving this class.
There is literally no downside to having this class final - it is an entry point to your API and there should never be any subclasses of this class.

2020-09-15 11:06 UTC, jpbempel commented on dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
> +public class SystemAccess {
If someone try to extend this class, it will not get what he thinks. it's a dumb mistake. On my side I will not have issue to evolve this class as there is not instance methods so not direct interactions with inherited classes.

2020-09-15 11:28 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
> +public class SystemAccess {
Ok. I hear you. It is up to you. I will stop bike-shedding here.

2020-09-15 11:30 UTC, jbachorik approved these changes
Not sure why so much resistance to making classes final but probably not worth more bike-shedding.

2020-09-15 16:44 UTC, richardstartin approved these changes
I'm also in the classes should be final unless intended to be extended camp, but am sure there are lots of cases where I could be shown to be a hypocrite on this one.

2020-09-15 17:21 UTC, jpbempel commented
🙄

2020-09-16 07:32 UTC, bantonsson approved these changes

2020-09-16 07:47 UTC, merged