WIP Port Reactor fixes from OTel
DataDog/dd-trace-java pull request #1876
Opened 2020-09-16 15:00 UTC by devinsba

Porting PR by @iNikem https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1189

2020-10-20 18:48 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
>      private final CoreTracer tracer;
Reverting changes here. Auto-formatter changed this when I was adding debug logging

2020-10-20 18:48 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
Reverting changes here. Auto-formatter changed this when I was adding debug logging

2020-10-20 18:48 UTC, devinsba commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBase.groovy
> +    callback?.call()
This changes the behavior of the test to pass. Will fix in follow up

2020-10-20 18:48 UTC, devinsba commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBase.groovy
> +  }
This disables a test that should pass. Will fix in follow up

2020-10-20 18:48 UTC, devinsba commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/SpringWebfluxTest.groovy
> +          childOf(span(0)) // FIXME this is wrong
This is another modeling issue but I don't feel as strongly about this one to fix it in a follow-up

2020-10-20 20:34 UTC, tylerbenson reviewed
Added some preliminary comments before digging into the core changes.

2020-10-20 20:34 UTC, tylerbenson commented on dd-java-agent/instrumentation/netty-4.1/src/test/groovy/ReactorNettyTest.groovy
> +class ReactorNettyTest extends AgentTestRunner {
Can this extend `HttpClientTest` instead?

2020-10-20 20:34 UTC, tylerbenson commented on dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
> +    assertTraces(2) {
Why should this result in two different traces?  from the input above, I would expect a single trace.

2020-10-20 20:34 UTC, tylerbenson commented on dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
> +      DDSpan parentSpan
Doesn't look like this is used.

2020-10-20 20:34 UTC, tylerbenson commented on dd-java-agent/instrumentation/reactor-core-3.1/src/test/groovy/ReactorCoreTest.groovy
> -    sleep(1)
👍

2020-10-20 20:34 UTC, tylerbenson commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/SpringWebfluxTest.groovy
> +        span(0) {
These are no longer needed... (same comment below)

2020-10-20 20:34 UTC, tylerbenson commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/SpringWebfluxTest.groovy
> +          childOf(span(0)) // FIXME this is wrong
Logically this seems like it should be a child of 1, not 0, right?  Might be worth understanding what's going on here.

2020-10-21 15:06 UTC, devinsba commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/SpringWebfluxTest.groovy
> +          childOf(span(0)) // FIXME this is wrong
The parent is the one at the time of the subscribe call, which is the root span, since it creates the stream that ends up calling the controller. So it ends up a sibling instead of child because the handler span doesn't exist yet at the time of stream construction

2020-10-21 15:08 UTC, devinsba commented on dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
> +    assertTraces(2) {
When doing `.subscribe()` the flow executes in a non blocking manner. So the parent and the set are in the first trace, but when the set finishes the trace reports and then the get will end up in it's own trace

2020-10-21 15:09 UTC, devinsba commented on dd-java-agent/instrumentation/netty-4.1/src/test/groovy/ReactorNettyTest.groovy
> +class ReactorNettyTest extends AgentTestRunner {
Maybe, I considered this test slightly redundant so just ported as is

2020-10-21 15:37 UTC, richardstartin requested changes
The reactor stuff looks great, I want the span names changed back to use the UTF8 constants though, otherwise 👍

2020-10-21 15:37 UTC, richardstartin commented on dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/rx/LettuceMonoDualConsumer.java
> +      span = startSpan("redis.query");
Can we put `REDIS_QUERY` back in as the span name here?

2020-10-21 15:37 UTC, richardstartin commented on dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
> +        .subscribeOn(Schedulers.newParallel("test"))
Can we also test on the elastic scheduler? Does this still work if you change the scheduler back?

2020-10-21 15:37 UTC, richardstartin commented on dd-java-agent/instrumentation/reactor-core-3.1/NOTICE.txt
> +This product contains a modified part of OpenTracing:
Is it OpenTracing or OpenTelemetry?

2020-10-21 15:37 UTC, richardstartin commented on dd-java-agent/instrumentation/reactor-core-3.1/src/main/java8/datadog/trace/instrumentation/reactor/core/TracingOperator.java
> +          || publisher.getClass().getName().startsWith("reactor.core.Scannable$Attr$")) {
Since this will happen a lot with few distinct inputs can we wrap this string comparison in a `ClassValue`?

2020-10-21 15:37 UTC, richardstartin commented on dd-java-agent/instrumentation/reactor-core-3.1/src/test/groovy/ReactorCoreTest.groovy
> +      .runOn(Schedulers.parallel())
I think parameterising the scheduler would be really helpful.

2020-10-21 15:37 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/WebClientTracingFilter.java
> +        span = startSpan("http.request", activeSpan().context());
Can we change the span names back to the way they were - this improves serialisation performance.

2020-10-21 18:14 UTC, richardstartin commented
Another note - can you clean the commit history up? There are 32 commits and messages like the ones below won't mean much to anyone tracking historical issues in the future.

```
not sure why java 8 requires this.....
Maybe
Test won't work
Missed classes
Fix a couple tests:
hmmmmmm
```

I think all of this could be squashed in to a single commit, with a description of the change.

2020-10-22 14:03 UTC, devinsba commented
I'll squash before merging. I need to copy the branch to keep my history for the follow up work

2020-10-22 14:06 UTC, devinsba commented on dd-java-agent/instrumentation/reactor-core-3.1/NOTICE.txt
> +This product contains a modified part of OpenTracing:
This NOTICE was copied from OTel, but their code was copied from OT

2020-10-22 14:38 UTC, devinsba commented on dd-java-agent/instrumentation/reactor-core-3.1/src/main/java8/datadog/trace/instrumentation/reactor/core/TracingOperator.java
> +          || publisher.getClass().getName().startsWith("reactor.core.Scannable$Attr$")) {
👍

2020-10-22 14:57 UTC, devinsba commented on dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
> +        .subscribeOn(Schedulers.newParallel("test"))
The test becomes flaky with the other scheduler. I'll make a mental note to update this test in my followup

2020-10-22 14:58 UTC, devinsba commented on dd-java-agent/instrumentation/netty-4.1/src/test/groovy/ReactorNettyTest.groovy
> +class ReactorNettyTest extends AgentTestRunner {
By redundant I mean that both of these clients are already covered by client tests. These are more like additional tests

2020-10-22 15:40 UTC, richardstartin approved these changes
Provisional on the commits being squashed.

2020-10-23 14:44 UTC, tylerbenson commented on dd-java-agent/instrumentation/netty-4.1/src/test/groovy/ReactorNettyTest.groovy
> +class ReactorNettyTest extends AgentTestRunner {
Do we have reactor netty client tests elsewhere?  I don't see any usage of `reactor.netty.http.client` in our codebase.

2020-10-23 14:48 UTC, devinsba commented on dd-java-agent/instrumentation/netty-4.1/src/test/groovy/ReactorNettyTest.groovy
> +class ReactorNettyTest extends AgentTestRunner {
reactor-netty is just the glue that wires netty to reactor. The client is covered by the netty and webflux client tests

2020-10-23 14:49 UTC, tylerbenson approved these changes

2020-10-23 14:56 UTC, merged