Add delay before Pending Trace submits to Writer
DataDog/dd-trace-java pull request #1916
Opened 2020-09-25 20:10 UTC by tylerbenson

Also update various tests.

2020-09-28 16:06 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      // FIXME: Does this still make sense to measure?
This is disabled by default, I would keep it in

2020-09-28 16:07 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +  private final ConcurrentLinkedQueue<PendingTrace> queue = new ConcurrentLinkedQueue<>();
Why `ConcurrentLinkedQueue`? Less contention? We have JCTools as a dependency now, consider using it here.

2020-09-28 16:07 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +  private final AtomicReference<Thread> thread = new AtomicReference<>();
what's that?

2020-09-28 16:08 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +    if (thread.get() == null) {
I think we should rework this to initialise the thread in the constructor and start the thread here.

2020-09-28 16:09 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +    Thread toClose = thread.getAndSet(null);
not keen

2020-09-28 16:12 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +      while (!Thread.interrupted()) {
I tend to use `Thread.currentThread().isInterrupted()` because it doesn't clear the interrupted status, not sure this is important though.

2020-09-28 16:15 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
I think it would be better to block (call `take()`) here than sleep and poll

2020-09-28 16:16 UTC, richardstartin commented
I don't like the lazy initialisation of the thread - is it necessary?

We should think about blocking on the queue instead of calling sleep.

2020-09-28 16:17 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
I tried to find something like that but I don't see that method.

2020-09-28 16:17 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +      if (thread.compareAndSet(null, newThread)) {
if we just do this in the constructor we can't create 2 of them

2020-09-28 16:23 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
If you take a queue which implements `java.util.concurrent.BlockingQueue` it should be there. If this queue handles all traces, I think we should look at using a bounded queue to prevent unbounded growth. `MpscBlockingConsumerArrayQueue` used in the reporting pipeline might be a better choice.

2020-09-28 16:28 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    lastReferenced = Clock.currentNanoTicks();
How often will this be called? Can we reuse a timestamp here?

2020-09-28 16:31 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        toClose.join();
I don't think we should do this. We are of secondary importance to the application. If we're shutting down, we need to shut down ASAP. Risking prevention of application shutdown to flush tracing data isn't right.

2020-09-28 16:33 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +    PendingTrace pendingTrace = queue.poll();
We can do this more efficiently with `drainTo` either on the `BlockingQueue` interface or JCTools `drain` method.

2020-09-28 16:34 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      // FIXME: Does this still make sense to measure?
Actually I agree we should remove this, the cost of the measurement is probably a lot higher than what we're measuring here.

2020-09-28 16:35 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
> +    context.getTrace().touch(); // Update timestamp
We have a timestamp here - maybe we should pass it through.

2020-09-28 16:50 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
> +    context.getTrace().touch(); // Update timestamp
The timestamp is a different resolution and clock type.

2020-09-28 17:02 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    lastReferenced = Clock.currentNanoTicks();
If this is `System.nanoTime()` based it can overflow and should be used for relative comparisons - where are they done?

2020-09-28 17:04 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        long delta = currentNanoTicks - lastReferenced;
Should this logic be encapsulated in `PendingTrace` so that it returns a boolean? What happens if someone unaware of this bit of logic here changes the time source it uses?

2020-09-28 17:12 UTC, dougqh commented on dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
> +    TEST_WRITER.waitForTraces(2)
I assume waitForTraces is really wait for chunks written?

I'm not sure that the tests should need to know about that.  That said, I think this is the pragmatic choice for now.
But long term, I think we should be waiting on a span count (preferably implied from the DSL) rather than having all the instrumentations tests know about the internal chunking of the publishing mechanism.

2020-09-28 17:13 UTC, dougqh commented on dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
> +    if (finishSpan) {
Fine for now, but this is another case of coupling the tests to the internals of the publishing system.

2020-09-28 17:15 UTC, dougqh commented on dd-java-agent/instrumentation/scala-concurrent/src/slickTest/groovy/SlickTest.groovy
> +      trace(2) {
I'm assuming this a non-functional reformatting.
This would be easier to review if those changes had been done in a separate commit -- preferably even a separate PR.

2020-09-28 17:16 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        toClose.join();
This thread is a daemon thread so not such a big deal.

2020-09-28 17:17 UTC, dougqh commented on dd-smoke-tests/cli/src/main/java/datadog/smoketest/cli/CliApplication.java
> +    Thread.sleep(1000);
Rather than sleeping, would it better to await completion?

2020-09-28 17:19 UTC, dougqh commented on dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
> +    assert new File(buildDirectory).isDirectory()
Files.isDirectory would be a bit cleaner and allocate less -- not that allocation is a problem in test

2020-09-28 17:22 UTC, dougqh commented
In the future, it would be nice to have a write-up that explains which parts have been changed & added.  That would make this change far easier to review.

2020-09-28 17:22 UTC, richardstartin requested changes
Two blockers for me

* Unbounded queue in `PendingTraceBuffer` - I'm worried about what happens with traffic bursts
* Non blocking consumer queue leading to needing to sleep or busy spin (I experimented with this, it just uses too much CPU for the use case), feels like the wrong queue choice.

I think there are other ways this could be improved, but they're not as important.

I should also note this is a huge improvement 👍

2020-09-28 17:33 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +      if (thread.compareAndSet(null, newThread)) {
Yes, this TRACE_MONITOR feels a tad bit messy.
Constructor might be problematic since it probably exposes a raw reference to PendingTraceBuffer.

I also think the AtomicReference is probably overkill.  volatile + double checking would be lighter.
Doesn't matter much here, but it is pattern we have throughout our code.

I also don't like that this creates a Thread and then may skip starting it.
I imagine that the backing OS resource probably isn't creating until start, but this still seems questionable for an expensive Object like Thread.

2020-09-28 17:35 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +      while (!Thread.interrupted()) {
Yes, agreed.

2020-09-28 17:37 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
Yes, an even if we don't do a BlockingQueue, we could do wait / notify ourselves -- definitely don't want to sleep.

2020-09-28 17:38 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        toClose.join();
I was wrong, this can indeed block shutdown despite being daemon

2020-09-28 17:39 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        Thread.currentThread().interrupt();
I think we should take out this sleep (as mentioned elsewhere), but the handling of InterruptedException here is a bit odd.

We might as well let it bubble up and break the containing loop.  Right now, we catch it just to reset the interrupt status and then bail the loop later.

2020-09-28 17:40 UTC, tylerbenson commented on dd-smoke-tests/cli/src/main/java/datadog/smoketest/cli/CliApplication.java
> +    Thread.sleep(1000);
Await what completion?

2020-09-28 17:42 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
Given that the queue is shared, sleeping here seems questionable.  I think if a new PendingTrace comes in, we want to wake up and evaluate it.

2020-09-28 17:44 UTC, tylerbenson commented on dd-java-agent/instrumentation/scala-concurrent/src/slickTest/groovy/SlickTest.groovy
> +      trace(2) {
This was a change that previously didn't assert anything on the `@Trace` span and I had to figure out what it was when trying to fix it.  I don't think this is a "non-functional" change.  It's still the same test but with slightly more assertions.

2020-09-28 17:44 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          // "write" it out to allow cleanup.
This comment is kind of cryptic.  And if we don't need to write, maybe, we should call a cleanUp routine directly instead.  I think that would be more clear.

Also, given that I don't think a PendingTrace has a definitive end, I'm curious what clean-up we are doing.

2020-09-28 17:46 UTC, tylerbenson commented on dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
> +    TEST_WRITER.waitForTraces(2)
I can see us merging traces of a common id together at some point.  Indeed this currently treats each call to write independently.

2020-09-28 17:46 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        long delta = currentNanoTicks - lastReferenced;
Yes, mixing time sources would be quite confusing.  We probably don't want to be calling System.currentTimeMillis directly here given that we allowed sub-ing out other time sources for spans.

2020-09-28 17:47 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
>        try (Recording recording = tracer.writeTimer()) {
This time is probably now a bit misleading.  We might want to this to be around the actual write.

2020-09-28 17:48 UTC, tylerbenson commented on dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
> +    if (finishSpan) {
I could probably roll back some of these changes after I made the change to `AgentTestRunner` to flush the buffer between traces.  Seemed better to leave though rather than play the game of deciding which were needed  and which weren't.

2020-09-28 17:48 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          pendingTrace.write();
timer here?

2020-09-28 17:49 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          queue.add(pendingTrace);
Should this have a health metric?  Should we track how many times we re-enqueue?

2020-09-28 17:49 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          pendingTrace.write();
timer here?

2020-09-28 17:51 UTC, dougqh commented on dd-java-agent/instrumentation/spring-data-1.8/src/test/groovy/SpringJpaTest.groovy
> +      activeSpan()
Why the call to activeSpan?  Are we relying on some side-effect in the test?

2020-09-28 18:02 UTC, tylerbenson commented on dd-java-agent/instrumentation/spring-data-1.8/src/test/groovy/SpringJpaTest.groovy
> +      activeSpan()
Instead of waiting for a specific number of traces to be reported, I decided it would be better to wait for a particular trace, so I return the span and wait for that span to be reported in a trace.

2020-09-28 18:04 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
>      if (isWritten.compareAndSet(false, true)) {
isWritten doesn't need to be AtomicBoolean if we're going to synchronize anyway.  This could simply be a volatile.

I also don't understand how is written works in the presence of partial flush or sending & then having late arriving spans that go beyond the time window.  

Does the PendingTrace get added back again?
Does a new PendingTrace get created?
Please explain.

More generally, I'm wondering whether PendingTrace is the write unit of granularity of writing.  In my PoC, I created a Batch that could be added to after being scheduled with the Writer.

I'm not decided on which is best, but there are definitely things to clean-up here.

2020-09-28 18:16 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          pendingTrace.write();
I'm going to put the timer inside `write` instead.

2020-09-28 18:16 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          pendingTrace.write();
I'm going to put the timer inside `write` instead.

2020-09-28 21:28 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        Thread.currentThread().interrupt();
I did it this way to avoid printing a lot of thrown `InterruptedException`'s in the logs. Would you prefer the try on the outside of the loop?

2020-09-28 21:30 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
The reason I sleep here is because anything new coming in is unlikely to meet the criteria of being old enough to report and we don't want to burn cycles popping off and re-adding traces.

2020-09-29 14:55 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  // FIXME: This is static instead of instance because we don't reliably close the tracer in tests.
Yes, I appreciate we're dealing with technical debt pragmatically here, but it would be nice not to need to do things like this.

2020-09-29 14:56 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +  public boolean lastReferencedNanosAgo(long nanos) {
nice

2020-09-29 14:57 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +  private static final int BUFFER_SIZE = 1024;
I would consider making this quite a lot bigger

2020-09-29 14:58 UTC, dougqh commented on dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
> +    TEST_WRITER.waitForTraces(2)
I think for now maybe we just rename waitForTraces because I think the name is quite misleading.

However, I do consider it major maintenance problem that the internals of the pending trace / writer mechanism are leaking into the tests for every instrumentation.

2020-09-29 14:58 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        new MessagePassingQueue.Consumer<PendingTrace>() {
Maybe allocate a private static final instance

2020-09-29 14:59 UTC, dougqh commented on dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
> +    if (finishSpan) {
As I said, I think this is fine for now, but it does represent a problem with our layering.

2020-09-29 15:00 UTC, dougqh commented on dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
> +    if (finishSpan) {
As I said, I think this is fine for now, but I do think it represents a significant deficiency in our abstracting & layering.

2020-09-29 15:00 UTC, dougqh commented on dd-java-agent/instrumentation/scala-concurrent/src/slickTest/groovy/SlickTest.groovy
> +      trace(2) {
Ah, okay.

2020-09-29 15:02 UTC, dougqh commented on dd-java-agent/instrumentation/spring-data-1.8/src/test/groovy/SpringJpaTest.groovy
> +      activeSpan()
Ah, I didn't realize that groovy also does implicit return.  Now, I follow.

2020-09-29 15:06 UTC, richardstartin commented
I think there's been some force pushing, but I can't see all the changes I requested in the commit

2020-09-29 15:07 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +    closed = true;
I believe this was where the `Thread.join()` was, and is no longer here.

2020-09-29 15:08 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
The sleeping has been removed 👍

2020-09-29 15:09 UTC, richardstartin approved these changes

2020-09-29 15:26 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      pendingTraceBuffer.enqueue(this);
So I'm a bit afraid that holding back traces when we actually reach zero will make all our traces back up in this buffer, while it's actually only the ones that were we don't reach zero that we need to force flush at a certain interval.
What is it that we want to achieve longterm with this change?

2020-09-29 16:15 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      // FIXME: Does this still make sense to measure?
I moved it elsewhere.

2020-09-29 16:15 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +  private final ConcurrentLinkedQueue<PendingTrace> queue = new ConcurrentLinkedQueue<>();
done.

2020-09-29 16:16 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +    if (thread.get() == null) {
done.

2020-09-29 16:16 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +      while (!Thread.interrupted()) {
done.

2020-09-29 16:16 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
done.  Using `take` now that I'm using a blocking queue.

2020-09-29 16:17 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +      if (thread.compareAndSet(null, newThread)) {
I've replaced with a single thread per instance.

2020-09-29 16:17 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        toClose.join();
done.  No longer joining.

2020-09-29 16:17 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +    PendingTrace pendingTrace = queue.poll();
done

2020-09-29 16:18 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        long delta = currentNanoTicks - lastReferenced;
done. Logic is contained in `PendingTrace` now.

2020-09-29 16:19 UTC, tylerbenson commented on dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
> +    assert new File(buildDirectory).isDirectory()
done.

2020-09-29 16:22 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
@richardstartin , I still have sleep in this case.  if only one item is added to the queue, then it would run a hot loop until the time limit reached for publishing without this sleep.

2020-09-29 16:23 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          // "write" it out to allow cleanup.
I removed this for now.  I'll add it back in with a better comment later if I need.  (I can't remember which test case was failing without this.)

2020-09-29 16:23 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
>        try (Recording recording = tracer.writeTimer()) {
moved.

2020-09-29 16:25 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +    closed = true;
yep.  it's been removed.

2020-09-29 16:27 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      pendingTraceBuffer.enqueue(this);
The goal is to eventually remove all reference counting/continuations.  This slight async delay should cover most of the cases which would cause async work to be split up without continuations.

2020-09-29 16:36 UTC, dougqh commented on dd-smoke-tests/cli/src/main/java/datadog/smoketest/cli/CliApplication.java
> +    Thread.sleep(1000);
You are waiting for the reporting of a trace.  Can that be done more explicitly?

2020-09-29 16:40 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    if (writer instanceof DDAgentWriter) {
Rather than doing an instanceof check on DDAgentWriter, it would make more sense to add a flush method onto the Writer.

2020-09-29 16:42 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    public Factory(CoreTracer tracer, PendingTraceBuffer pendingTraceBuffer) {
Should the constructor be public?

2020-09-29 16:45 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (isWritten.get()) {
Okay, so short-circuit clean-up if we've already written.
I still need clarification on the lifecycle of PendingTrace object to understand if this is correct.

2020-09-29 16:52 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
Newly added yes, but there's other stuff in the queue as well.

Consider, two traces arrive at roughly the same time...
PendingTrace 1
PendingTrace 2

Dequeue PendingTrace 1 - trace 1 has been touched
Dequeue PendingTrace 2 - trace 2 has not been touched

This approach will stall processing PendingTrace 2.  I think that's likely to be a problem.

2020-09-29 16:53 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        Thread.currentThread().interrupt();
Why would the InterruptedException show up in the logs?  You can catch inside the loop and break.

2020-09-29 16:55 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
> +  def setup() {
Can you explain a bit more what's happening here?
Why do we need to start & wait now?

2020-09-29 16:57 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy
> +      tracer.pendingTraceFactory.create(DDId.ONE),
As aside, I think we could have maintained the old API and that would have kept the diff easier to read.
Pending.create could internally do tracer.pendingTraceFactory.create.

2020-09-29 16:59 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (isWritten.get()) {
Since I am putting each individual PendingTrace into the `AgentTaskScheduler` with no way to cancel those tasks when they're done (it relies on GC to discard the tasks), this seemed like a good way to reduce that impact.

2020-09-29 16:59 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
> +    writer.waitForTraces(1)
I'd like to understand why we needed to add this in so many places.

2020-09-29 17:00 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy
> +      tracer.pendingTraceFactory.create(DDId.ONE),
good point... didn't think about that.

2020-09-29 17:01 UTC, dougqh requested changes
It was probably lost among other comments.  But I need an explanation of what the lifecycle of PendingTrace is in the presence of a partial flush or late arriving spans.

It appears that once a write happens.  We assuming the PendingTrace is done for a good.  I find this a bit surprising.  Do we then create another PendingTrace to replace it?

I think it is important to clarify this both for review, but also to clear document this in the class itself.

2020-09-29 17:02 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
> +    writer.waitForTraces(1)
This test (and many others where I had to add this) was relying on the trace being immediately written to the writer below:
```
writer == [[scope.span()]]
```

2020-09-29 17:08 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
> +  def setup() {
`SpanFactory.WRITER.start()` ensures that there aren't any traces in the writer already.  (If there are, then the `waitForTraces` calls below doesn't wait for the right trace.)

The reason `waitForTraces` is needed is because that allows the span processing to be applied before validating the final state of the span.

2020-09-29 17:11 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (isWritten.get()) {
To answer the question about the partial flush, that is reported as a separate list of spans and association with the pending trace is no longer needed.

I think there is a good question about late arriving spans that I need to consider further.

2020-09-29 17:36 UTC, dougqh commented on dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseClientTest.groovy
> +    waitForTraces = {
Is this not equivalent to...
```
TEST_WRITER.waitForTraces(1)
waitForTraces = true
```

2020-09-29 17:42 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    PENDING_TRACE_BUFFER.close();
Can PENDING_TRACE_BUFFER.close raise an exception?
If so, this should have a try / finally.

Generally, I'm just assuming close could do try / finally for each step for safety.

2020-09-29 17:57 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
> +    writer.waitForTraces(1)
Part of the reason, I'd put more of the delay logic into the Writer in my PoC was to avoid these types of problems.
Doing so, allowed the tests to use a simple synchronous writer.

As I've said elsewhere, I don't think every test should need to aware of all these publishing mechanism details.
For now, I think we need to leave it alone, but it is a code smell.

2020-09-29 18:16 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +          sleep();
Thinking about this a bit more, I think we might want to change this a bit to handle the case where several traces arrive at the same time that are all frequently delayed.  I think that's likely to come up often with async web frameworks.

I think we might want to burn through the queue until we arrive back where we started.  Once we get back to the start, I think we might want to wait.  But honestly, I'm not entirely sure.

I'm also concerned that we're going to be churning and creating a lot of Nodes in the Queue.  One way to fix that would to use a LinkedTransferQueue, but I think a simple size restricted BlockingQueue is probably our best choice.

2020-09-30 08:23 UTC, bantonsson requested changes
I would like to understand how the end result is supposed to work, to be able to review this properly, and have a few questions.

1. When you say that the goal is to remove all reference counting, does that include all types of counting, including if we have an open `Span` on a `Trace`? If that's the case then what happens to:
    - A `Trace` that is being flushed eagerly, and there are still things happening on that `Trace` like a new `Span`, or an old `Span` closing?
    - Tests verifying correctness of opening and closing spans in an instrumentation? How do you know if it's your code doing the right thing or the flush force writing the `Trace`?
2. I assume that one of the future goals is to flush traces that become stale, but I don't think we need to relax the writing of a fully closed `Trace` to do that, and in relaxing the _closing_ of a `Trace` we will make things even less deterministic and harder to test and verify.
3. Another goal is the complete removal of the sets of `WeakReference` in `PendingTrace` and this can also be achieved while still providing efficient reference counting and strict _closing_ of traces.

2020-10-01 14:06 UTC, tylerbenson commented on dd-smoke-tests/cli/src/main/java/datadog/smoketest/cli/CliApplication.java
> +    Thread.sleep(1000);
Unfortunately the smoke test doesn't have an option for that.  Any ideas on a better way to do so?  Add a flush to the public API?

2020-10-01 14:07 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        Thread.currentThread().interrupt();
Without that catch, I was seeing the exception printed out quite a bit when I ran the tests.

2020-10-01 14:12 UTC, tylerbenson commented on dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseClientTest.groovy
> +    waitForTraces = {
I only really need the `TEST_WRITER.waitForTraces(1)`, but that returns a void, and statements in `where` blocks in spock must make an assignment.

2020-10-01 17:30 UTC, dougqh commented on dd-smoke-tests/cli/src/main/java/datadog/smoketest/cli/CliApplication.java
> +    Thread.sleep(1000);
Yes, I think adding a flush would be a better approach than sleeping.  Right now, we're just creating the potential for sporadic test failures.

Or, maybe, we're just not asserting anything -- in which case, we don't need the sleep at all.

2020-10-01 17:36 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +    if (thread.get() == null) {
I suppose we only have one but I think AtomicReference might overkill.  volatile + double checking would be sufficient.  We can leave this as is.

2020-10-01 19:29 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    lastReferenced = Clock.currentNanoTicks();
I think the raciness of lastReferenced is fine, but I think this warrants a comment.

2020-10-01 20:46 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +    if (thread.get() == null) {
This is out of date... I updated this a few days ago.

2020-10-01 20:47 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    PENDING_TRACE_BUFFER.close();
that close method only calls `interrupt()` on the worker thread with no blocking, so this should not throw any exceptions.

2020-10-01 20:50 UTC, tylerbenson commented on dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
> +    TEST_WRITER.waitForTraces(2)
What would you prefer the name to be?

2020-10-01 20:52 UTC, tylerbenson commented on dd-smoke-tests/cli/src/main/java/datadog/smoketest/cli/CliApplication.java
> +    Thread.sleep(1000);
We are asserting that traces are reported.  Would you like the flush added in this PR or a separate one?

2020-10-01 20:56 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        Thread.currentThread().interrupt();
I went ahead and moved the catch outside the loop and removed the `@SneakyThrows`, but it still needs to do something with the exception.  Would you prefer just ignore it since it doesn't matter if the interrupt flag is set at that point?

2020-10-01 20:58 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
>      if (isWritten.compareAndSet(false, true)) {
noted... this will likely go away in a future refactor anyway.  I did rename it to align with the new system.

2020-10-01 20:58 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +  private static final int BUFFER_SIZE = 1024;
is 4096 big enough?

2020-10-01 21:03 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      pendingTraceBuffer.enqueue(this);
Maybe we need to have two different types of PendingTrace.  One that does strict ref counting and another with this timeout mechanism.

2020-10-01 21:12 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    public Factory(CoreTracer tracer, PendingTraceBuffer pendingTraceBuffer) {
Changed to package visible.

2020-10-01 21:14 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (isWritten.get()) {
I removed this short circuit and fixed the late arrival flush.  The clean method will be removed in the future when we no longer track all the references.

2020-10-01 21:16 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    lastReferenced = Clock.currentNanoTicks();
could you be more specific?

2020-10-01 21:38 UTC, tylerbenson commented on dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
> +    TEST_WRITER.waitForTraces(2)
FYI, In this specific case it is actually two separate traces.

2020-10-05 18:00 UTC, dougqh commented on dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
> +    TEST_WRITER.waitForTraces(2)
What are you calling a trace?  Do the spans have the same trace ID?  If so, I call that one trace.
If this is now two separate traces, I would be concerned since that would be an unrelated functional change.

Please clarify

2020-10-05 18:02 UTC, dougqh commented on dd-smoke-tests/cli/src/main/java/datadog/smoketest/cli/CliApplication.java
> +    Thread.sleep(1000);
Separate is fine.

2020-10-05 18:10 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletResponseTest.groovy
>      TEST_WRITER.clear()
Having to wait & clear everywhere is a code smell for me, but we'll leave improved testing for another PR.

2020-10-05 18:11 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    PENDING_TRACE_BUFFER.flush();
This probably needs a try / finally.  Otherwise, there's a risk the writer isn't flushed.

2020-10-05 18:15 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
> +        Thread.currentThread().interrupt();
What else does it need to do something with the exception?  It interrupted the loop that's what it should do.  There's no requirement that we need to log or propagate.

2020-10-05 18:17 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
> +    def lastSpan = root
What is being changed here?  Is this a non-functional change?

2020-10-05 18:19 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
> +    buffer.worker.join(1000)
I think we should get out the habit of poking into the internals as part of tests.
Admittedly, this case is borderline, since it is in the same package.

2020-10-05 18:22 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
> +    return AgentTaskScheduler.INSTANCE.workQueue.any { task ->
Yes, to solve that, I think you'd have to have a way to get reference directly to the Task.  I'm not sure it is worth the trouble, so this is fine for now.

2020-10-05 18:23 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/TraceInterceptorTest.groovy
> +        return []
I'm assuming this change is just clean-up.

2020-10-05 18:24 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/TraceInterceptorTest.groovy
> +    if (score == 0) {
This code isn't immediately obvious.  I think some comments would help.

2020-10-05 18:25 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
> +    writer.waitForTraces(3)
These are cumulative?  That seems bad from composability perspective, but again, test clean-up can come later.

2020-10-05 18:28 UTC, dougqh commented on dd-trace-ot/src/ot31CompatabilityTest/groovy/OT31ApiTest.groovy
> +  def writer = new ListWriter()
Non-functional?

2020-10-05 18:59 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    PENDING_TRACE_BUFFER.flush();
It doesn't declare any exceptions to be thrown (unless the drain destination is null, which is hardcoded so it shouldn't).  I don't have a problem adding one just in case though.

Do you want me to add that?

2020-10-05 19:00 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> + * This class implements the following data flow rules when a Span is finished:
I think this probably needs some elaboration -- not necessarily as header doc, but I'm expect more documentation inside PendingTrace & PendingTraceBuffer.  I'd like a better high-level view of the overall flow that someone can read without reading over all the comment to understand what's happening.

2020-10-05 19:05 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
> +    def lastSpan = root
I had to change this to avoid the root span getting finished in order to maintain the spirit of the test, otherwise all the spans get reported and the `expect` is much different.

2020-10-05 19:07 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
> +    buffer.worker.join(1000)
I think this is important to ensure the thread is stopped properly.  Previously I had close as a blocking call, but Richard asked me to remove that.

2020-10-05 19:08 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/TraceInterceptorTest.groovy
> +        return []
The code that calls `onTraceComplete` expects a non-null response.  I was getting an NPE at one point when I ran the tests, so I changed all of them to be safe.

2020-10-05 19:10 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
> +    writer.waitForTraces(3)
It's cumulative until the writer is cleared.

2020-10-05 19:11 UTC, tylerbenson commented on dd-trace-ot/src/ot31CompatabilityTest/groovy/OT31ApiTest.groovy
> +  def writer = new ListWriter()
this is a functional change.  previously the writer was shared across all test executions, so late arriving spans could impact other tests.  With this change, the writer is recreated for each test so that is not a problem.

2020-10-05 20:00 UTC, dougqh approved these changes

2020-10-05 20:27 UTC, tylerbenson commented on dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
> +    TEST_WRITER.waitForTraces(2)
there is a separate trace generated that isn't linked to the parent (as mentioned in the comment).  Previously it was likely not a problem because we only ever looked at the first span, but it can cause instability in the test.

2020-10-05 20:37 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> + * This class implements the following data flow rules when a Span is finished:
That's what I tried to do with this comment.  Provide enough context at the conditions to understand what is going on.

2020-10-05 20:58 UTC, merged

2020-10-06 06:28 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +        expireReference(false);
I know I'm late to the game, but I noticed this while rebasing my branch on top of latest master, and you can most definitely have a `continuation` on a root span, so this is not correct. The effect is that a number of tests run noticeably slower (as in I can see it on the test counter incrementing slowly), and the new tests that didn't wait now needs to wait for the tracer.

2020-10-06 11:12 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +        expireReference(false);
Opened a PR #1955