Revert "inherit the async propagation from enclosing scope" and always propagate
DataDog/dd-trace-java pull request #1951
Opened 2020-10-05 21:25 UTC by tylerbenson

2020-10-09 13:49 UTC, dougqh commented
I don't understand the need to revert the inheritance change.  I think that change should be left in place until we remove async propagation entirely.

2020-10-09 13:52 UTC, dougqh commented on dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
> +    (scope as TraceScope).isAsyncPropagating()
It seems strange to be checking this in OpenTracing & OpenTelemetry tests.
I'm not sure this assertion is adding much value.

2020-10-09 13:57 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
> +    final ScopeStack scopeStack = scopeStack();
I think this diff is from the inheritance revert.  As mentioned below, I don't think inheritance should be reverted as part of this change.

2020-10-09 13:59 UTC, dougqh requested changes
Reverting inheritance needs justification, I don't believe that needs to be part of this PR.
I actually believe reverting would be a significant step backwards.

2020-11-18 17:56 UTC, tylerbenson commented
Closing for now.  We can revisit when we're ready to make more changes.

2020-11-18 17:56 UTC, closed without merging