Write out a trace as soon as possible
DataDog/dd-trace-java pull request #1955
Opened 2020-10-06 11:10 UTC by bantonsson

This change ensures that we write out a trace as soon as its reference count reaches zero.

2020-10-06 14:07 UTC, tylerbenson approved these changes

2020-10-06 14:07 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (count == 0) {
Please update the class comment with the new flow.

2020-10-06 14:34 UTC, devinsba approved these changes

2020-10-06 14:46 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (count == 0) {
Yes, I debated whether this was necessary or not.

I was also a little hesitant because of how this might work in the late arriving situations.  If we take out one continuation at a time, we'll end up sending small batches.

That will work well for our tests, but I think it is less clear what we want in production.
I suspect this is probably the right choice for production as well since it reduces how long we're holding traces, but we just need to verify carefully.

2020-10-06 15:32 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (count == 0) {
So one idea would to be only do direct write when `count == 0` if the trace is a rootSpan or it has not been written.

2020-10-06 15:39 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (count == 0) {
I think this is what you're suggesting, but the write when `count == 0` should probably only apply if the root span is finished and not written.

2020-10-06 15:39 UTC, tylerbenson requested changes
let's resolve the above discussion first.

2020-10-06 15:50 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (count == 0) {
Yes, I changed the code to `if (count == 0 && (isRootSpan || !rootSpanWritten.get())) {`

2020-10-06 15:50 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (count == 0) {
Comment at top has been updated

2020-10-06 15:58 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
> +      return span == span.getLocalRootSpan();
Think it'd be worth capturing this detail in a field?

2020-10-06 16:01 UTC, tylerbenson approved these changes

2020-10-06 17:41 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    if (count == 0) {
Yes, that works for me.

2020-10-07 07:27 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
> +      return span == span.getLocalRootSpan();
Maybe. I mean the code would be run the same number of times (once), and the `Continuation` instance would get larger.

2020-10-07 07:59 UTC, richardstartin approved these changes

2020-10-07 12:25 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
> +      return span == span.getLocalRootSpan();
No longer necessary

2020-10-07 12:27 UTC, bantonsson commented
I realized that I had complicated the logic unnecessarily, and removed some of the changes. The only special handling is that now we write out directly if the count reach zero and the trace has not been written.

2020-10-07 13:05 UTC, tylerbenson approved these changes

2020-10-07 13:19 UTC, merged