inject fields once at the root of the type hierarchy
DataDog/dd-trace-java pull request #2007
Opened 2020-10-19 19:40 UTC by richardstartin

does field injection in the highest concrete type still a subtype of the context store key class, which prevents from adding a field to every class in the hierarchy.

2020-10-19 19:46 UTC, tylerbenson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldInjectionVisitor.java
> +              Opcodes.ACC_PROTECTED | Opcodes.ACC_TRANSIENT,
Are the fields accessed directly or are there generated accessor methods added?

2020-10-19 19:50 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldInjectionVisitor.java
> +              Opcodes.ACC_PROTECTED | Opcodes.ACC_TRANSIENT,
public accessors are generated so this shouldn't be necessary

2020-10-19 22:26 UTC, tylerbenson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +  private String getInjectionTarget(TypeDescription typeDescription) {
It's a bit difficult for me to understand how this method is able to identify the correct classes to instrument. Perhaps a comment would help?

2020-10-20 06:51 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +  private String getInjectionTarget(TypeDescription typeDescription) {
I don't think the logic is particularly complicated

2020-10-20 09:25 UTC, mcculls commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +        break;
I'm not sure we can short-circuit the search here if you want to get the closest class to `Object` that implements the key interface. If ByteBuddy's `getInterfaces` method behaves like reflection then it will only tell you what the class declared as its interfaces at that level, and not all the interfaces it implements.

For example:
```
class A implements Runnable {
  public void run() {}
}

class B extends A {}

class C extends B {}

class D extends C {}
```
With the above code we'd field-inject `D`, `C`, and `A`.

There are also cases where sub-classes re-declare the interfaces they implement:

```
class A implements Runnable {
  public void run() {}
}

class B extends A {}

class C extends B {}

class D extends C implements Runnable {}
```

Not to mention cases where an interface extends another interface:
```
interface R extends Runnable {}

class A implements R {
  public void run() {}
}

class B extends A {}

class C extends B {}

class D extends C implements Runnable {}
```

Since this is an optimization then we don't need to do an exhaustive search - but I think it's worth checking against a few frameworks to see if we miss any chances to skip field injection.

2020-10-20 09:34 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +        break;
Yes, you're right (the first paragraph was clear enough but thanks for the example) - I added a test for this and removed the short circuit.

2020-10-20 10:06 UTC, mcculls commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +      for (TypeDescription.Generic iface : superClass.getInterfaces()) {
We'll still miss a chance to optimize if the class hierarchy implements an interface that extends the key type (since this only checks directly declared interfaces, and not the interfaces they extend) but I think that's OK as widening the search to include transitive interfaces could be expensive.

2020-10-20 10:13 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +      for (TypeDescription.Generic iface : superClass.getInterfaces()) {
You're right, but this should work for all the types we're interested in injecting (we need to stop doing this for `Runnable` for other reasons). This kind of matching is done repetitively, and I think the structure of the types we care about, at least for the purpose of field injection, could be memoized cheaply so we don't need to do so many traversals.

2020-10-20 10:15 UTC, mcculls approved these changes

2020-10-20 10:46 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +      for (TypeDescription.Generic iface : superClass.getInterfaces()) {
Having said that, I would be amazed if traversing the hierarchy when we already know there's a subtype relationship outweighs the cost of unnecessary transformation, or the long term cost of carrying extra fields around.

2020-10-20 10:49 UTC, mcculls commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +      for (TypeDescription.Generic iface : superClass.getInterfaces()) {
true - if you do extend the search to cover transitive interfaces then you might want to consider a local cache to track which interfaces you've seen

2020-10-20 11:29 UTC, bantonsson requested changes
Nice idea. Have some questions that I would like answered.

2020-10-20 11:29 UTC, bantonsson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +     * explicit about that.
I think that the javadoc is very clear:
>  Returns the interfaces directly implemented by the class or interface represented by this object.

2020-10-20 11:29 UTC, bantonsson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +          break;
Do we think that it's common to have a sub-class that is re-implementing and interface? This looks like it will try super-classes even though it found a direct implementation of an interface in the current class.

2020-10-20 11:29 UTC, bantonsson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +      String superClassName = superClass.asRawType().getTypeName();
It feels like we are missing to check the `typeDescription` for interface implementations. This code jumps straight to the `superClass`.

2020-10-20 11:55 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +     * explicit about that.
This is an existing comment

2020-10-20 11:56 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +      String superClassName = superClass.asRawType().getTypeName();
This is discussed above.

2020-10-20 11:56 UTC, richardstartin commented
@bantonsson it's not clear which changes you are requesting.

2020-10-20 11:57 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +          break;
It's looking for the class closest to `java.lang.Object` to inject the field in to, so it will go up the hierarchy, but remember that this class implements the interface.

2020-10-20 12:00 UTC, bantonsson commented
I just wanted to get a chance to review again, and this is the only way 😉

2020-10-20 12:06 UTC, bantonsson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +     * explicit about that.
It's still broken...

2020-10-20 12:06 UTC, bantonsson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +          break;
Yes, I can see now that you discussed this with @mcculls and it's fine if we assume that it's common enough.

2020-10-20 12:07 UTC, bantonsson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +      String superClassName = superClass.asRawType().getTypeName();
Ah yes, the other matcher before this one.

2020-10-20 12:08 UTC, bantonsson approved these changes
👍

2020-10-20 12:13 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +     * explicit about that.
Yes, I agree. There are also a few missing articles which certainly justifies a cleanup.

2020-10-20 13:14 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +      for (TypeDescription.Generic iface : superClass.getInterfaces()) {
For more context to anyone else reviewing, the single case that I considered making this for is `ForkJoinTask`. Whether you're using the streams API or `RecursiveAction` etc.  the API depends on being able fork lots of tiny objects but there are often at least two levels of class inheritance. This won't make much difference to wide interface inheritance hierarchies.

2020-10-20 14:29 UTC, tylerbenson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +    Boolean keyTypeIsClass = KEY_TYPE_IS_CLASS.get(keyType);
Very slim edge case that is probably not worth considering:  It is possible for this result to be different on different classloaders within a single jvm.

2020-10-20 14:36 UTC, tylerbenson approved these changes

2020-10-20 14:43 UTC, richardstartin commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
> +    Boolean keyTypeIsClass = KEY_TYPE_IS_CLASS.get(keyType);
I'm fairly sure there would be a `ClassCastException` in any instrumentation using a context store if your edge case existed in practice.

2020-10-20 14:44 UTC, merged