Change `asyncPropagating` default to true
DataDog/dd-trace-java pull request #2008
Opened 2020-10-19 19:43 UTC by tylerbenson

2020-10-20 06:09 UTC, richardstartin commented on dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/ElasticsearchBreakTraceInstrumentation.java
> +public class ElasticsearchBreakTraceInstrumentation implements Instrumenter {
Could you add a comment to explain why this is necessary?

2020-10-20 06:10 UTC, richardstartin commented on dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/ElasticsearchBreakTraceInstrumentation.java
> +public class ElasticsearchBreakTraceInstrumentation implements Instrumenter {
Could you add a comment to explain how this differs from the other `ElasticsearchBreakTraceInstrumentation`?

2020-10-20 06:10 UTC, richardstartin commented on dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/ElasticsearchBreakTraceInstrumentation.java
> +public class ElasticsearchBreakTraceInstrumentation implements Instrumenter {
Could you add a comment to explain how this differs from the other `ElasticsearchBreakTraceInstrumentation`?

2020-10-20 06:10 UTC, richardstartin commented on dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/ElasticsearchBreakTraceInstrumentation.java
> +public class ElasticsearchBreakTraceInstrumentation implements Instrumenter {
Could you add a comment to explain how this differs from the other `ElasticsearchBreakTraceInstrumentation`?

2020-10-20 06:11 UTC, richardstartin commented on dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/ElasticsearchBreakTraceInstrumentation.java
> +public class ElasticsearchBreakTraceInstrumentation implements Instrumenter {
Could you add a comment to explain how this differs from the other `ElasticsearchBreakTraceInstrumentation`?

2020-10-20 06:27 UTC, richardstartin commented on dd-java-agent/instrumentation/java-concurrent/src/test/groovy/NettyExecutorInstrumentationTest.groovy
>  class NettyExecutorInstrumentationTest extends AgentTestRunner {
How do we avoid diffs like this? One option is for you to uninstall the plugin which edits code unrelated to the change you've made when you save files as I believe you are now in a minority in using it. If we want consistent formatting of test files, note that I run `./gradlew spotlessApply` before I commit every time I commit, but reformatting of test files is disabled; I think it should have been enabled. The status quo is unsustainable.

2020-10-20 14:00 UTC, dougqh commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
> -        final TraceScope scope = continuation.activate();
I wasn't expected the set to true blocks to be removed in this first step.
I was assuming we just set async propagation will to true and that's it.

2020-10-20 14:01 UTC, dougqh requested changes
As first step, I would prefer we set async propagation to true, but not remove the places in the code where we explicitly set to true.

I would assume that the default behavior would then be semantically equivalent to this.
However, not removing the set(true) would give us to override the default and return to the prior behavior.

2020-10-20 16:31 UTC, tylerbenson commented on dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
> +    (scope as TraceScope).setAsyncPropagation(false)
This was not a new gotcha... it was returning the state to false so the rest of the test could remain the same.  I could just as easily invert the test.

2020-10-20 20:45 UTC, tylerbenson commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
> -        final TraceScope scope = continuation.activate();
I've reverted those changes and added a flag we can flip to change the default again.

2020-10-21 10:11 UTC, richardstartin commented on dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
> +    (scope as TraceScope).setAsyncPropagation(false)
I'm picking up on why it's necessary to make this change at all - won't this break a lot of manually traced applications if it's strictly necessary to invert the flag?

2020-10-21 13:16 UTC, tylerbenson commented on dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
> +    (scope as TraceScope).setAsyncPropagation(false)
Previously we were relying on the implicit default state. In the `expect` block below, we are explicitly asserting:
```
    !(scope as TraceScope).isAsyncPropagating()
    (scope as TraceScope).capture() == null
```

This is not something a customer would likely be doing.

Changing the default requires this test to change.  Would you prefer continuing to rely on the default and change the asserts or make the expected state implicit up front?

2020-10-21 16:28 UTC, richardstartin approved these changes

2020-10-21 18:32 UTC, dougqh approved these changes

2020-10-22 18:55 UTC, merged