Add a routing span to vertx 3.5
DataDog/dd-trace-java pull request #2069
Opened 2020-11-12 16:18 UTC by devinsba

2020-11-13 15:32 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapper.java
> +  public void handle(final RoutingContext routingContext) {
I'm not sure what the right way to use the routing path/regex is in this case. I don't really like the pattern of modifying one span just to start another. It's also not clear to me what the correct methods to call are

2020-11-13 16:32 UTC, richardstartin approved these changes

2020-11-13 16:38 UTC, bantonsson approved these changes

2020-11-17 18:56 UTC, tylerbenson requested changes
Main question is around span name and resource name.

2020-11-17 18:56 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapper.java
> +      actual.handle(event);
Should this be wrapped in a scope?

2020-11-17 18:56 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapperAdvice.java
> +    }
I think some comments here would be helpful.

2020-11-17 18:56 UTC, tylerbenson commented on settings.gradle
> +include ':dd-java-agent:instrumentation:vertx-rx-3.5'
Is the `rx` project only for testing?  If so, consider putting it as a sub project to `web`.

2020-11-17 18:56 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/VertxHttpServerTest.groovy
> +      operationName "vertx.router"
I don't think `vertx.router` is the right name here.  I think it should be something like `vertx.controller` or `vertx.action` instead.

2020-11-17 18:56 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapper.java
> +    DECORATE.afterStart(span);
I think it would be useful to set the span's resource name to `actual`'s class name.

2020-11-17 18:56 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapper.java
> +      actual.handle(routingContext);
If there's any chance of this throwing an exception, you should catch and add it to the span.

2020-11-18 15:03 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapper.java
> +      actual.handle(event);
It will be inside the scope from the other handler. Either directly or through async propagation

2020-11-18 15:08 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapper.java
> +    DECORATE.afterStart(span);
For most use cases I would expect this to be an anonymous class. I don't feel that is all that useful but I can be convinced

2020-11-18 15:10 UTC, devinsba commented on settings.gradle
> +include ':dd-java-agent:instrumentation:vertx-rx-3.5'
It's likely we need specific instrumentation for rx. And considering the version difference I don't really think as a sub project makes sense

2020-11-18 17:51 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapper.java
> +    DECORATE.afterStart(span);
Since this isn't a measured span, the cardinality requirements are less strict.  I think an anonymous class name would still be more useful than nothing.

2020-11-18 18:14 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/VertxHttpServerTest.groovy
> +      operationName "vertx.router"
I'll go with `vertx.route-handler` to stick with the frameworks vocabulary

2020-11-18 19:46 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/VertxTestServer.java
> +package server;
The test was not behaving correctly when this server was written in Groovy with regards to the exception

2020-11-19 15:10 UTC, tylerbenson approved these changes

2020-11-19 15:10 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapper.java
> +    span.finish();
you might want to put the `span.finish()` in a try/finally in case the handle throws an exception.

2020-11-19 15:14 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapper.java
> +    span.finish();
Good call. Done

2020-11-19 18:11 UTC, merged