remove analytics sample rate rule
DataDog/dd-trace-java pull request #2098
Opened 2020-11-19 21:41 UTC by richardstartin

2020-11-19 21:44 UTC, tylerbenson approved these changes

2020-11-19 21:47 UTC, tylerbenson requested changes
Actually, I don't think we can do this since it's publicly documented to set as a tag: https://docs.datadoghq.com/tracing/legacy_app_analytics/?tab=java#custom-instrumentation

2020-11-19 22:02 UTC, tylerbenson approved these changes

2020-11-19 22:24 UTC, lpriima approved these changes

2020-11-19 22:24 UTC, lpriima commented on dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java
> +        new DBStatementRule(), new ResourceNameRule(), new ErrorRule(), new URLAsResourceNameRule()
👍  ?

2020-11-19 22:26 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java
> +        new DBStatementRule(), new ResourceNameRule(), new ErrorRule(), new URLAsResourceNameRule()
spotless...

2020-11-20 08:02 UTC, bantonsson requested changes
Only one question about difference in behavior.

2020-11-20 08:02 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +          if (value instanceof Number) {
So the old code tried to convert a `String` into a `Double`, but now we just drop it. Is that intended?

2020-11-20 08:02 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +        if (value instanceof Number) {
Here as well...

2020-11-20 08:56 UTC, richardstartin commented
@bantonsson I thought that behaviour was silly so I removed it. I've put it back along with the tests.

2020-11-20 09:41 UTC, bantonsson approved these changes

2020-11-20 09:52 UTC, merged