Combine CoreSpan with AgentSpan
DataDog/dd-trace-java pull request #2105
Opened 2020-11-20 21:10 UTC by tylerbenson

Because CoreSpan was in core, it could not be used by instrumentation.  With AgentSpan being the primary API, it can be used in instrumentation.

I also cleaned up some other duplicate/unnecessary methods in the process. (`spanName` getter/setter)

2020-11-20 21:52 UTC, richardstartin requested changes
I don't understand the rationale for this

2020-11-20 21:54 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregator.java
> +  void publish(List<? extends AgentSpanData> trace);
This is a constraining change

2020-11-20 21:54 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
> +      for (AgentSpanData span : trace) {
Reduces flexibility

2020-11-27 12:01 UTC, richardstartin commented
The reason this interface exists at the moment is to break dependencies between sampling/metrics/processing and `DDSpan`/`DDSpanContext`, which I think are in need of refactoring. The reason for the recursive type bound is that I think this will probably be useful in the future, but hard to add later. The interface isn't the final solution, but it's not useless. It's also not a stable interface, and I don't really want it escaping into our API, or for our own instrumentation to create impediments to changing it at the moment, so I'm not in favour of the changes here.

2020-12-04 17:23 UTC, tylerbenson commented
I'm going to close this for now and revisit when it's more important.

2020-12-04 17:23 UTC, closed without merging