simplify tag interceptors
DataDog/dd-trace-java pull request #2113
Opened 2020-11-23 22:08 UTC by richardstartin

2020-11-24 10:48 UTC, bantonsson approved these changes
Nice cleanup

2020-11-24 20:10 UTC, randomanderson requested changes
While the code is much simpler, this PR loses the ability to turn interceptors off.  Specifically, PeerService and ServletContext toggles are used in the wild.

2020-11-24 21:58 UTC, richardstartin commented
@randomanderson I'm not sure. These classes' configuration is based on the simple name of each class, which was changed without notice in #1565, and nobody has complained or asked for a migration path after that change. What concerns you was evidently not considered in #1565, which doesn't make it right, but I find it unlikely that the configurability was in use. Do you have information at odds with this?

2020-11-24 22:06 UTC, richardstartin commented
We wrote this in the release notes for [0.55.0](https://github.com/DataDog/dd-trace-java/releases/tag/v0.55.0), but didn't mention the impact on configuration.

```
Span Decorators are no longer accessible #1565
These were actually removed with the separation from OpenTracing, but this hides it further.
```

2020-11-26 16:46 UTC, richardstartin commented on dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
> -  def "adding span personalisation using Decorators"() {
this use case no longer exists, and hasn't existed since April/May

2020-11-26 16:47 UTC, richardstartin commented on dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
> -    tracer.addTagInterceptor(new ServiceNameTagInterceptor(tag, true))
now we add the splitting tag into a set

2020-11-26 16:47 UTC, richardstartin commented on dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
> +    decorator                   | enabled
maintain legacy names (difficult to respect the old names now though)

2020-11-26 16:48 UTC, richardstartin commented
@randomanderson the config flags are back 👍

2020-11-26 16:49 UTC, richardstartin commented
no release notes because there is no user impact

2020-11-26 19:18 UTC, richardstartin commented on dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoClientTest.groovy
> -        "$Tags.DB_STATEMENT" {
This just duplicates data and mongo queries can be very large

2020-11-26 19:19 UTC, richardstartin commented on dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ClientTest.groovy
> -        "$Tags.DB_STATEMENT" {
Removing data duplication

2020-11-26 19:21 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/RuleFlags.java
> +    RESOURCE_NAME("ResourceNameRule"),
These names all derive from the simple class names which were used as config at some point in the past. As to whether these are really used, we'll never know, but the names have been changed without notice or mention in release notes in the past, so this configurability may or may not be important to maintain.

2020-11-26 19:22 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +package datadog.trace.core.taginterceptor;
All tag interception logic is now encapsulated in this class. If you want to know what will happen to a tag, step away from the debugger and just look here...

2020-11-26 19:22 UTC, richardstartin commented on dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
> -    when:
This is now handled by the mongo decorators

2020-11-26 19:25 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +    if (null == value || "".equals(value)) {
This will probably have a decent impact on performance, because a lot of the time no lock needs to be acquired. Previously, with the hybrid tag interceptor and rules based approach, we would have to contend for the locks, possibly find some space in the map to temporarily store the tag value, and only then decide that the tag value should really have been a field all along, or that the tag value is useless.

2020-11-26 19:27 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
>      }
Unrelated to this PR, but what's below is incredibly wasteful:

```java

      context.setAllTags(defaultSpanTags);
      context.setAllTags(tags);
      context.setAllTags(coreTags);
      context.setAllTags(rootSpanTags);
```

We're passing effectively constant values through tag interceptors over and over again here.

2020-11-27 07:27 UTC, bantonsson approved these changes
👍 Only one small question

2020-11-27 07:27 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
>      }
Yes indeed. The whole builder mechanism needs more cleanup.

2020-11-27 07:27 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/RuleFlags.java
> +    RESOURCE_NAME("ResourceNameRule"),
Add a comment explaining that in the file?

2020-11-27 07:27 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +package datadog.trace.core.taginterceptor;
Nice

2020-11-27 07:27 UTC, bantonsson commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +    span.setResourceName(statement);
Is there anything in the backend that relies on this `tag` being set?

2020-11-27 08:14 UTC, richardstartin commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +    span.setResourceName(statement);
We were removing it before sending for all but Mongo. I will find out if Mongo spans need the statement set.

2020-11-27 08:42 UTC, richardstartin commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +    span.setResourceName(statement);
I got confirmation this is not required in the backend or the agent. It _might_ be an historical user preference.

2020-11-27 10:11 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/RuleFlags.java
> +    RESOURCE_NAME("ResourceNameRule"),
Done

2020-11-28 06:30 UTC, lpriima approved these changes

2020-11-28 06:30 UTC, lpriima commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/RuleFlags.java
> +  private final boolean[] flags;
BitSet or even just `byte` with masks, since we have only 7 legacy names

2020-11-30 09:17 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/RuleFlags.java
> +  private final boolean[] flags;
Actually, if we used a `BitSet` it would take up quite a bit more space, if that's what we care about, because it uses `long[]` as its storage and has an `int` and a `boolean` field. We could use a `byte`, but would have to change it if we ever added two more flags. I think `boolean[]` is probably the most obvious choice here.

2020-11-30 17:44 UTC, tylerbenson approved these changes
👍

2020-11-30 18:12 UTC, randomanderson approved these changes

2020-11-30 18:23 UTC, merged