Optimise DDSpanContext footprint
DataDog/dd-trace-java pull request #2201
Opened 2020-12-14 21:04 UTC by richardstartin

2020-12-14 21:58 UTC, tylerbenson approved these changes

2020-12-14 22:41 UTC, richardstartin commented on dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV05PayloadTest.groovy
> +    int tracesRequiredToOverflowBody = (traceMapper.messageBufferSize() + traceSize - 1) / traceSize
this was an arithmetic error which just happened to work before

2020-12-15 08:56 UTC, bantonsson approved these changes

2020-12-15 08:56 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +            .getTagInterceptor()
Not directly related to the change, but maybe hoist this access out of the loop?

2020-12-15 08:56 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> -  private final ExclusiveSpan exclusiveSpan;
Nice find.

2020-12-15 09:20 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +            .getTagInterceptor()
Done

2020-12-15 09:22 UTC, richardstartin commented
I've added a JOL based test in case the instance size accidentally grows

2020-12-15 10:45 UTC, richardstartin commented
For future reference I had to take some care to avoid `HashMap` resizing to make sure this was a net positive and wasn't moving the problem elsewhere. Ultimately, the problem is using a `HashMap<String, Object>` to model data we mostly know at compile time, rather than only for user-defined custom tags.

2020-12-15 11:09 UTC, richardstartin commented
After fixing the baggage initialisation 
<img width="1191" alt="Screenshot 2020-12-15 at 11 08 35" src="https://user-images.githubusercontent.com/16439049/102207434-013aa780-3ec6-11eb-8971-20bb876513ea.png">

2020-12-15 15:03 UTC, tylerbenson requested changes

2020-12-15 15:08 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +  private volatile Map<CharSequence, Number> metrics = EMPTY_METRICS;
I'm not so sure it does. It's clearly synchronized where accessed.

2020-12-15 15:15 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +  private volatile Map<CharSequence, Number> metrics = EMPTY_METRICS;
yes, but synchronized on `spanId`, which I have no objection to... just not obvious.

2020-12-15 15:18 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +  private volatile Map<CharSequence, Number> metrics = EMPTY_METRICS;
there was already a comment in the relevant synchronized block, which was added precisely because it wasn't obvious. That said, I hadn't clocked that we're also doing a map lookup each time we want to check what the sampling priority is, so added a properly synchronized method to do that. I will change the representation of the sampling to something a bit leaner in a follow up PR.

2020-12-15 15:21 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +    return metrics;
This method should probably be removed since access to the map is no longer thread safe and the guarding lock is private. How widely is it used?

2020-12-15 15:36 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +    return metrics;
it's only accessed from a single thread after the span has been finished. The writes to the map are synchronized in case they come from different threads, but after the context is effectively sealed it's let out, in much the same way the `unsafeTags` are, and this makes it much cheaper to iterate over.

2020-12-15 15:38 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +    return metrics;
The method should probably be renamed to "unsafe" or document the specific use case it is enabling then.

2020-12-15 16:03 UTC, tylerbenson approved these changes

2020-12-15 16:32 UTC, merged