Tomcat 5.5+ instrumentation
DataDog/dd-trace-java pull request #2311
Opened 2021-01-19 22:17 UTC by tylerbenson

This instrumentation overrides the generic servlet instrumentation and provides a more holistic view of the actual lifecycle of a tomcat request. Particularly important is the better detection of final http status code when an exception is thrown and a different status is returned via an exception handler.

Request/Response objects are always recycled so we use that as the last possible point to ensure the most accurate status code.

(The release notes should indicate that this is a pretty significant change in instrumentation for anyone using Tomcat and to be aware when upgrading. This includes possible impact to duration metrics due to an increased measurement scope.)

2021-01-19 22:22 UTC, richardstartin commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/RequestExtractAdapter.java
> +    Enumeration<String> headerNames = carrier.getMimeHeaders().names();
Is this the best `Request` has to offer? I was hoping at this level there would be lower level APIs.

2021-01-19 22:24 UTC, richardstartin reviewed
Looks good. I'm surprised how little code is required per container, or how little was saved by treating the servlet API generically.

2021-01-19 22:25 UTC, tylerbenson commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/RequestExtractAdapter.java
> +    Enumeration<String> headerNames = carrier.getMimeHeaders().names();
Yes.  You requested similar with the Jetty advice, so I explicitly looked this time and there isn't any way to get an enumeration of the pairs together.

2021-01-19 22:30 UTC, tylerbenson commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/RequestExtractAdapter.java
> +    Enumeration<String> headerNames = carrier.getMimeHeaders().names();
Specifically here's the API we're dealing with: https://tomcat.apache.org/tomcat-5.5-doc/catalina/docs/api/org/apache/tomcat/util/http/MimeHeaders.html

2021-01-19 22:40 UTC, tylerbenson commented
@richardstartin I kind of lucked out in finding an instrumentation point that was so steady over the desired version range so as to not require a bunch of modules like I did for jetty.  Took some digging to find the right level to instrument... the object recycling pattern also helps quite a bit in knowing the last possible point of use.

2021-01-20 10:02 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
Is this intentional? I thought the idea was to get the correct status?

2021-01-20 14:58 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
The original servlet instrumentation still has the same behavior, but this won't be called when tomcat/jetty instrumentation is applied.

2021-01-20 18:03 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
I know, but that's not what I'm asking. I thought the driver for going down to the container level was to get accurate status codes, not to lift and shift the servlet instrumentation into container specific instrumentation. If we're still guessing the status code, what's the benefit?

2021-01-20 18:08 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
Apologies, I had missed that this is in the servlet 3 advice.

2021-01-20 18:09 UTC, richardstartin approved these changes

2021-01-20 18:12 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
`Servlet3Advice` is for the generic servlet instrumentation, not the new tomcat/jetty specific instrumentation.

2021-01-21 17:13 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
I'm thinking this in terms of progress enhancement.  Right now, this code gets us decent broad coverage.  As we fill-in more and more server instrumentations maybe we won't need this anymore.

So I think the right choice is to skip when we know we are using a more feature rich server instrumentation.

2021-01-21 17:15 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/request-3.gradle
> +  testCompile project(':dd-java-agent:instrumentation:tomcat-5.5') // See if there's any conflicts.
Not for this PR, but I think we need to rethink our approach to testing.  Increasingly, I think we should move our tests out into separate parallel components.  And I think those components should use a full tracer rather than just a single instrumentation.

2021-01-21 17:16 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
> +      if (!isDispatch) {
The conditional calling of onResponse feels a little messy.  Why do we need that?

2021-01-21 17:18 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
> +        if (((HttpServletResponse) event.getSuppliedResponse()).getStatus()
I know that this shared code in Advice classes is a bit hard to pull out, but this duplication is rather ugly.

2021-01-21 17:55 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
> +          "error.msg" { it == null || it == EXCEPTION.body || it == CUSTOM_EXCEPTION.body }
The need for this much boolean logic in the test strikes me as messy and hard to follow.

I think this stems from reusing pieces that are too large which requires placing conditional logic in the test.
I think reusing smaller pieces would be much easier to follow.

Right now, this feels hard to trace from what we're actually testing.

2021-01-21 17:57 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
> +    return [REDIRECT, ERROR, NOT_FOUND].contains(endpoint)
I probably would have left this as is.  In test code, I think this is fine.  But I'd be opposed elsewhere since this is less efficient.

2021-01-21 17:58 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
> +    } else if (endpoint == EXCEPTION || endpoint == CUSTOM_EXCEPTION) {
Quite minor, but this repetition feels a little messy.  A helper function might help a bit here.

2021-01-21 18:02 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +            response.status = CUSTOM_EXCEPTION.status
Okay, so we're testing this via an ErrorHandle that makes sense to me, but I assume there are other places/APIs that a user could use as well.  I think we need to make sure to check Filter, web.xml config, etc as well.

2021-01-21 18:04 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TestServlet3.groovy
> +        context.addListener(new AsyncListener() {
Okay, I worry a bit about forcing the server into non-standard way of functioning.
But from the comment, it sounds like it makes sense in this instance.

2021-01-21 18:05 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TestServlet3.groovy
> +            case CUSTOM_EXCEPTION:
It looks like these factories are repeated in multiple places.  Is there not a better way to share this code?

2021-01-21 18:07 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
>      addServlet(context, "/dispatch" + REDIRECT.path, dispatchServlet)
I don't think we need to fix this now, but...

It seems like it would have been better to create a number of different servlet instances rather than push so much conditional logic into the test servlet.

2021-01-21 18:09 UTC, dougqh commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/RequestExtractAdapter.java
> +    Enumeration<String> headerNames = carrier.getMimeHeaders().names();
Yes, I'm surprised the new version isn't better, but so it is.

2021-01-21 18:15 UTC, dougqh commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/ResponseInstrumentation.java
> +  public ResponseInstrumentation() {
Definitely not part of this PR, but I'm wondering if we need to tackle some of the revised instrumentation concepts.
It seems like this tomcat instrumentation is really tomcat that depends on servlet.
It also seems like there are really multiple instrumentations that make up the single logical tomcat instrumentation.

Those instrumentations should all be activated as a single atom.

But we can come back to that _after_ we've fixed addressed the more user visible aspect of the server integrations.

2021-01-21 18:19 UTC, dougqh commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatServerInstrumentation.java
> +      adapter.service(null, null);
Again not for this PR, but yes, the need to use muzzleCheck definitely suggests that we need to work on atomically activating a family of instrumentations.

2021-01-21 18:23 UTC, dougqh commented on dd-java-agent/instrumentation/tomcat-5.5/src/test/groovy/TomcatServletTest.groovy
> +class TomcatServletTest extends AbstractServletTest<Embedded, Context> {
It feels like we might have gone slightly overboard with the generics here.
I feel like having an Embedded member var in the each test might have been easier to follow.

I don't feel strongly about this.  Just food for thought.

2021-01-21 19:02 UTC, tylerbenson commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatServerInstrumentation.java
> +      adapter.service(null, null);
This wasn't strictly necessary, but muzzle doesn't check the availability of the method we are instrumenting (unless it's called by the advice somewhere, which it usually isn't).  I added this call to ensure that the range match takes that into consideration.

2021-01-21 19:09 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
> +      if (!isDispatch) {
When we do an async dispatch, there are times when the status code can be set differently from the root server span. (Specifically the wrong one being set by the servlet instrumentation and the correct one being set by the tomcat/jetty instrumentation.) I opted to not report status code on this span rather than risk it being incorrect.

2021-01-21 19:12 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
> +        if (((HttpServletResponse) event.getSuppliedResponse()).getStatus()
This particular class isn't an advice class, so we can refactor it better.  Can you be more specific about what duplication you'd like removed?

2021-01-21 19:15 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
> +    return [REDIRECT, ERROR, NOT_FOUND].contains(endpoint)
I understand this is less performant, but it seemed a worthy tradeoff for consistency.  There are other places in this PR where the list is 5 elements long, so the improved readability seemed better to me.

2021-01-21 19:19 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +            response.status = CUSTOM_EXCEPTION.status
Ok, I can add those test cases.  Do you want it added to this PR or can it be a separate PR?

2021-01-21 19:23 UTC, tylerbenson commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/ResponseInstrumentation.java
> +  public ResponseInstrumentation() {
Not arguing your point, but just to clarify... from what I was able to see Tomcat isn't really usable independent from Serlvet, unlike Jetty, which doesn't require it.

2021-01-21 19:24 UTC, tylerbenson commented on dd-java-agent/instrumentation/tomcat-5.5/src/test/groovy/TomcatServletTest.groovy
> +class TomcatServletTest extends AbstractServletTest<Embedded, Context> {
Here the generics are certainly not necessary.  This is purely an artifact of copy/paste from the original `AbstractServletTest`

2021-01-21 19:26 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
>      addServlet(context, "/dispatch" + REDIRECT.path, dispatchServlet)
This might be worth adding to the backlog to refactor.

2021-01-22 08:50 UTC, richardstartin commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/RequestExtractAdapter.java
> +    Enumeration<String> headerNames = carrier.getMimeHeaders().names();
This didn't look right and what's been said here about the API isn't accurate. The headers can be iterated over without a quadratic loop using these methods

https://tomcat.apache.org/tomcat-5.5-doc/catalina/docs/api/org/apache/tomcat/util/http/MimeHeaders.html#getName(int)
 https://tomcat.apache.org/tomcat-5.5-doc/catalina/docs/api/org/apache/tomcat/util/http/MimeHeaders.html#getValue(int)

```java
MimeHeaders headers = carrier.getMimeHeaders();
for (int i = 0; i < headers.size(); ++i) {
     MessageBytes header = headers.getName(i);
     MessageBytes value = headers.getValue(i);
     if (!classifier.accept(header.toString(), value.toString())) {
        return;
      }
}
```

`MessageBytes` has a lot of [support](https://tomcat.apache.org/tomcat-5.5-doc/catalina/docs/api/org/apache/tomcat/util/buf/MessageBytes.html) for the obvious inefficiency above - converting headers and values we don't even know we're interested in yet into strings - but there was pushback against there being a little bit of code duplication when using lower level APIs. What's above is still more efficient than getting an enumeration and doing a linear search for each value in the enumeration.

2021-01-22 08:51 UTC, richardstartin requested changes
Please make use of `MimeHeaders`' support for linear time context extraction

2021-01-22 09:06 UTC, richardstartin commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/RequestExtractAdapter.java
> +    Enumeration<String> headerNames = carrier.getMimeHeaders().names();
Sensibly, the string is actually cached anyway, and may have been initialised already, or would be initialised later without the tracer existing. https://github.com/apache/tomcat/blob/681f2afccc2f22ff5fc3d80ad7e77dbeecd083b2/java/org/apache/tomcat/util/buf/MessageBytes.java#L163L166

2021-01-22 10:45 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
Nit: this is boxing an `int` outside of the default range of the `Integer` cache.

2021-01-22 10:46 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
> +          span.setTag(Tags.HTTP_STATUS, 500);
Boxing

2021-01-22 19:45 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
> +          "error.msg" { it == null || it == EXCEPTION.body || it == CUSTOM_EXCEPTION.body }
Good call out.  I cleaned this up some and discovered the exception wasn't being set in some cases I was expecting it, so I updated the decorators to capture it properly.

2021-01-22 19:46 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
> +    } else if (endpoint == EXCEPTION || endpoint == CUSTOM_EXCEPTION) {
replaced with `endpoint.throwsException`

2021-01-22 20:08 UTC, tylerbenson commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/RequestExtractAdapter.java
> +    Enumeration<String> headerNames = carrier.getMimeHeaders().names();
@richardstartin good call out.  I made that change and was able to find a similar API in jetty. Thanks for the idea.

2021-01-22 20:09 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
This was being done in several other places too, so I applied the cache lookup everywhere.

2021-01-25 10:05 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
Previously, we had this logic in `RequestDispatcherDecorator`

```java
        int status = (int) STATUS_CODE_METHOD.invokeExact((HttpServletResponse) response);
        if (status > UNSET_STATUS) {
          if (throwable != null && status == HttpServletResponse.SC_OK) {
            span.setTag(Tags.HTTP_STATUS, SERVER_ERROR);
            span.setError(true);
          } else {
            span.setTag(Tags.HTTP_STATUS, HTTP_STATUSES.get(status));
            if (SERVER_ERROR_STATUSES.get(status)) {
              span.setError(true);
            }
          }
```

and we had the following

```java
private static final Integer SERVER_ERROR = 500;
```

so we could avoid boxing and avoid the lookup (which is cheap but not free), but it looks like there are indeed a few other places where this idiom was in place. Could we use the constant where the value is known in this PR please (otherwise someone else will have to take the time to apply the change after the branch is merged)?

2021-01-25 21:36 UTC, tylerbenson commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
> +            span.setTag(Tags.HTTP_STATUS, 500);
good catch.  I've replaced that with a static final in `HttpServerDecorator` rather than using the cache directly.

2021-01-26 00:13 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
> +      if (!isDispatch) {
Hmm, that makes me wonder if there isn't a better place to instrument.  At the very least, I think this needs a lot more commenting as to what is going on here and why.

2021-01-26 00:15 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
> +        if (((HttpServletResponse) event.getSuppliedResponse()).getStatus()
This is repeating the same exception/500 status code handling in multiple places.  Also, this location isn't using the caching as mentioned in another comment.

2021-01-26 00:17 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +            response.status = CUSTOM_EXCEPTION.status
I'm inclined to say this PR because right now I don't have a lot of confidence that the end user is actually fixed.

2021-01-26 00:21 UTC, dougqh commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/ResponseInstrumentation.java
> +  public ResponseInstrumentation() {
Yes, I understand that Tomcat requires Servlet -- that's what I said originally.
However, Servlet is intended to be used without Tomcat.

As said, not for this PR, but I think we need to rethink instrumentation and test dependencies.

2021-01-26 00:23 UTC, dougqh commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatServerInstrumentation.java
> +      adapter.service(null, null);
Now, I'm more confused.  Why not just build that functionality into muzzle?

2021-01-26 00:24 UTC, dougqh commented on dd-java-agent/instrumentation/tomcat-5.5/src/test/groovy/TomcatServletTest.groovy
> +class TomcatServletTest extends AbstractServletTest<Embedded, Context> {
Okay.  I have noticed a tendency to overuse generics throughout the code base that I find more constraining than helpful.

2021-01-26 10:09 UTC, richardstartin approved these changes
My concerns have been addressed.

2021-01-28 15:56 UTC, bantonsson approved these changes

2021-01-28 18:06 UTC, tylerbenson commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatServerInstrumentation.java
> +      adapter.service(null, null);
That's certainly something that could be done, but I don't have a good idea for how to do that.  I think the way matching works makes this difficult.

2021-01-28 22:16 UTC, tylerbenson commented
I think I've resolved all the concerns...

2021-01-28 22:16 UTC, merged