Various Netty Instrumentation Improvements
DataDog/dd-trace-java pull request #2415
Opened 2021-02-16 15:45 UTC by tylerbenson

* More accurate placement of the tracing handlers within the pipeline
* Better span context async propagation
* Works better with proxy+ssl for asynchttpclient

(The first commit is likely not interesting to review as it is a simple refactor to add a method parameter.)

2021-02-17 16:57 UTC, bantonsson approved these changes

2021-02-17 16:57 UTC, bantonsson commented on dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
> +  int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null) {
Is this really necessary? I thought the idea with default arguments was that you didn't have to copy them to all places.

2021-02-17 17:02 UTC, tylerbenson commented on dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
> +  int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null) {
Unfortunately they still have to be declared otherwise the signature doesn't match.  I'd really like us to get to using a spec object instead of all the arguments.

2021-02-17 18:42 UTC, richardstartin approved these changes
That's quite a diff to trawl through...

2021-02-17 19:57 UTC, dougqh commented on dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
> +  int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null) {
Yes, all the repetition of default values feels like a step backwards.

Could this be done by having two methods instead?
int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null) {
  return doRequestImpl(method, uri, headers, body, callback);
}

Putting it all into a parameters object would also be fine...

int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null) {
  return doRequestImpl(new RequestImpl(method, uri, headers, body, callback));
}

2021-02-17 20:01 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelHandlerContextInstrumentation.java
> +      if (channelSpan == null || channelSpan == activeSpan()) {
I take this is because there are multiple entries into scopeSpan.  Is that not true for close as well?  It isn't immediately clear to me that is properly balanced.

2021-02-17 20:04 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelHandlerContextInstrumentation.java
> +      NettyHttpClientDecorator.DECORATE.afterStart(null);
muzzleCheck still confuses me.  Isn't this already covered by including the helper classes?  Why are we checking our own decorator?

2021-02-17 20:09 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java
> +      return CallDepthThreadLocalMap.incrementCallDepth(handler.getClass());
So we're relying on handler class to sufficiently differentiate these cases.
But if netty switched to having one handler class configured in multiple ways, then this approach would break down.

I think I'm willing to accept that as meaningful forward progress for now, but this code still makes me uneasy.

2021-02-17 20:11 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java
>        try {
I think with switching to assigning to the local first, we could move the try down after the if / else if instanceof checks.

2021-02-17 20:16 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
> +  private static Class<ChannelHandler> SSL_HANDLER;
final

2021-02-17 20:16 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
> +  public static HttpClientRequestTracingHandler INSTANCE = new HttpClientRequestTracingHandler();
final

2021-02-17 20:18 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
> +      sslHandler = Class.forName("io.netty.handler.ssl.SslHandler");
Class.forName initializes the class -- thus changing class initialization order.  It is better to call Class.forName(name, boolean, ClassLoader).

2021-02-17 20:19 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/NettyHttpClientDecorator.java
> +    if (request.getMethod().equals(HttpMethod.CONNECT)) {
Having to construct a URI object feels quite heavy weight.  I realize that's a problem with our decorators, so I suppose not for this PR.

2021-02-17 20:20 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/HttpServerResponseTracingHandler.java
> +  public static HttpServerResponseTracingHandler INSTANCE = new HttpServerResponseTracingHandler();
final

2021-02-17 20:23 UTC, dougqh requested changes
I feel quite strongly that as is the testing is a step backwards in terms of maintainability.  I think we need to find a better solution to that before this can go in.

I also have some questions about the instrumentation itself that I would like to see answered.

There are also a lot of places where fields haven't been declared final which will impede constant propagation by the JIT.

2021-02-17 20:25 UTC, dougqh commented on dd-java-agent/testing/src/test/groovy/server/HttpProxyTest.groovy
> +/* Don't actually need AgentTestRunner, but it messes up the classloader for AgentTestRunnerTest if this runs first. */
Yes, we need to get to the bottom of that.  Tests shouldn't be this tricky to write.

2021-02-17 20:38 UTC, richardstartin commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/NettyHttpClientDecorator.java
> +    if (request.getMethod().equals(HttpMethod.CONNECT)) {
This was removed for the server decorators where possible because the parsing done in `URI`'s constructor is expensive. `URI` construction was not removed for the netty server instrumentation either, and I frequently see this showing up in customer profiles. Getting rid of `URI` construction would be a very good outcome, but I agree that it's not for this PR.

2021-02-18 10:45 UTC, bantonsson commented on dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
> +  int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null) {
So I just tried to use default arguments the way I expect them to work here https://github.com/DataDog/dd-trace-java/pull/2416 (on top of this PR) by changing all the overriding methods:
```
from:
int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null)
to:
int doRequest(String method, URI uri, Map<String, String> headers, String body, Closure callback) 
```
And it works just fine. Everything built and the tests were green.

2021-02-18 10:54 UTC, bantonsson commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelHandlerContextInstrumentation.java
> +      if (channelSpan == null || channelSpan == activeSpan()) {
This just gives `close` a `NoopAgentScope` to close, if we don't activate a new scope, and that will do nothing, so I think it balances out just fine.

2021-02-19 21:31 UTC, tylerbenson commented on dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
> +  int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null) {
Sorry, I misunderstood your initial question.  I can remove all the default values as you suggested.

@dougqh I could have split it into two methods, but it would mean making the methods non-abstract. I opted for the refactor instead.

2021-02-19 21:33 UTC, tylerbenson commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelHandlerContextInstrumentation.java
> +      if (channelSpan == null || channelSpan == activeSpan()) {
Yeah, the idea being we don't want to change the scope, so return a no-op scope to avoid requiring a null check below.

2021-02-19 21:34 UTC, tylerbenson commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelHandlerContextInstrumentation.java
> +      NettyHttpClientDecorator.DECORATE.afterStart(null);
This is another case where the instrumentation doesn't apply in the same way as other instrumentation.  Adding the reference to the decorator was the easiest way to keep it in sync.

2021-02-19 21:36 UTC, tylerbenson commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java
> +      return CallDepthThreadLocalMap.incrementCallDepth(handler.getClass());
This specific change was actually already in place for netty 4.1 but wasn't applied consistently to 4.0.

2021-02-22 08:43 UTC, bantonsson approved these changes

2021-02-22 08:46 UTC, richardstartin approved these changes

2021-02-22 14:45 UTC, dougqh commented on dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
> +  int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null) {
I'm not sure what the issue is with making the outer method non-abstract.  What I'd proposed is that the outer method should be final and the inner method which contains the real guts should still be abstract.

I think that would be better than all the code duplication created by the default methods.

2021-02-22 14:46 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java
> +      return CallDepthThreadLocalMap.incrementCallDepth(handler.getClass());
Okay, it would still be nice to the answers to the questions that I posed above.

2021-02-22 15:08 UTC, tylerbenson commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java
>        try {
If we didn't have the finally, then I agree putting the try inside the null check is the best option.
But we still need to have the try for the finally case. Is there any benefit in assigning `toAdd` outside rather than inside the try?

2021-02-22 15:09 UTC, tylerbenson commented on dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
> +  int doRequest(String method, URI uri, Map<String, String> headers = [:], String body = "", Closure callback = null) {
I removed the default arg initialization duplication, so now the main change is adding the additional `body` argument.

2021-02-22 15:50 UTC, dougqh commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java
>        try {
Yes, that makes sense.  I overlooked the finally.  In part because I didn't see anything that we're obviously acquiring.

2021-02-22 15:50 UTC, dougqh approved these changes

2021-02-22 16:32 UTC, tylerbenson commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java
> +      return CallDepthThreadLocalMap.incrementCallDepth(handler.getClass());
I don't really have a good solution...

2021-02-22 16:33 UTC, merged