Move the adaptive sampler to a shared location.
DataDog/dd-trace-java pull request #2418
Opened 2021-02-18 15:47 UTC by jbachorik

The rate limiting sampler is not specific to exception profiling only so it should live in a more generic space.

The change is rather harmless - just moving the actual sampler implementation to `internal-api` project. Since the `agent-bootstrap` already depends on `internal-api` no further changes are needed.

2021-02-18 18:54 UTC, richardstartin commented on internal-api/internal-api.gradle
> +  enableJunitPlatform = true
✌🏻

2021-02-18 18:55 UTC, richardstartin commented on internal-api/internal-api.gradle
> +}
Does this mean we no longer test `internal-api` on JDK7?

2021-02-18 18:59 UTC, richardstartin requested changes
We can't stop compiling and testing internal-api on JDK7. Perhaps extract an interface and move the implementation into a JDK8 module under utils, with a stub implementation and a factory, then load the JDK8 implementation based on a version check.

2021-02-18 19:02 UTC, richardstartin commented on internal-api/src/main/java8/datadog/trace/api/sampling/AdaptiveSampler.java
>        final Duration windowDuration,
(Stating the obvious) Java time was introduced in JDK8, so this implementation would need to be moved out of `internal-api`

2021-02-19 09:30 UTC, jbachorik commented
Well, my intention was to have just the one source root to be compiled with Java 8 to avoid creating a new module just for this one class. Apparently, it is not that easy even with the gradle black magic :(

BTW, with move to ASM 9 to support JDK 16 bytecode level the support for Java 7 will be gone as ASM itself is compiled to level 52 (Java 8) 🤷

2021-02-19 10:39 UTC, jbachorik commented
The `AdaptiveSampler` implementation has been moved to a separate submodule of `internal-api`.

Since it is used in an already Java 8+ code in the bootstrap I would like to avoid jumping through several facade/reflection hoops in order to use it. The appropriate checks are done at the top level when the whole profiler subsystem is enabled for Java 8+.

2021-02-19 12:20 UTC, richardstartin commented
> BTW, with move to ASM 9 to support JDK 16 bytecode level the support for Java 7 will be gone as ASM itself is compiled to level 52 (Java 8) 🤷

Yes, I agree, maintaining support for JDK7 is holding us back, but we we have users on JDK7 and can't drop it until the product decision has been made.

2021-02-19 16:36 UTC, jbachorik commented
>  we have users on JDK7 and can't drop it until the product decision has been made

My (slightly offtopic) point was that with ASM 9 you don't have the choice any more :(

Anyway, for this PR I pulled out the Java 8 specific code to a separate module to make it more explicit (also, it makes the build much simpler).

2021-02-19 16:44 UTC, richardstartin commented
> My (slightly offtopic) point was that with ASM 9 you don't have the choice any more :(

I got it, and this will force the issue soon, as it presents a dichotomy between JDK7 and JDK17

2021-03-02 14:54 UTC, richardstartin commented on dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
> +  main_java11Compile project(':internal-api:internal-api-8')
Why `compileOnly` -> `compile`?

2021-03-02 14:56 UTC, richardstartin commented
[This](https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/6680/workflows/df90c0db-113f-421d-a3f6-5e0427d40f80/jobs/132917) looks problematic

```
java.lang.NoClassDefFoundError: datadog/trace/api/sampling/AdaptiveSampler
	at datadog.trace.bootstrap.instrumentation.exceptions.ExceptionSampler.<init>(ExceptionSampler.java:25)
	at datadog.trace.bootstrap.instrumentation.exceptions.ExceptionSampler.<init>(ExceptionSampler.java:21)
	at datadog.trace.bootstrap.instrumentation.exceptions.ExceptionProfiling.<init>(ExceptionProfiling.java:26)
	at datadog.trace.bootstrap.instrumentation.exceptions.ExceptionProfiling.<clinit>(ExceptionProfiling.java:11)
	at java.lang.Class.forName(Class.java:377)
	at AgentTestRunnerTest.classpath setup(AgentTestRunnerTest.groovy:50)
```

2021-03-03 15:07 UTC, jbachorik commented
👋  All tests are finally passing 🎉

2021-03-03 15:20 UTC, tylerbenson approved these changes

2021-03-03 15:20 UTC, tylerbenson commented on internal-api/internal-api-8/internal-api-8.gradle
> +apply plugin: "idea"
This is probably not needed.

2021-03-03 15:20 UTC, tylerbenson commented on internal-api/internal-api-8/src/test/java/datadog/trace/api/sampling/AdaptiveSamplerTest.java
> +  private static final Logger log = LoggerFactory.getLogger(AdaptiveSamplerTest.class);
Use `@Slf4j` on class instead.

2021-03-03 20:52 UTC, richardstartin approved these changes

2021-03-05 14:05 UTC, merged