Add support for Oracle proprietary JFR implementation
DataDog/dd-trace-java pull request #2466
Opened 2021-03-05 11:00 UTC by jbachorik

This change adds support for the proprietary Oracle JFR implementation which is available for JDK 8 since JDK 8u40.

It adds a new `Controller` implementation which is using (undocumented) JFR MBeans to control JFR and collect the recorded data. Most of this implementation was shamelessly copied from JMC - just slightly simplified as this code does not need to deal with the whole problem space JMC is covering.

For testing there needs to be `JAVA_ORACLE8_HOME` env variable defined pointing to a valid Oracle JDK 8u40 or newer installation (must not be OpenJDK 8 because that contains the open source JFR implementation). This will require a change in the CI image which needs to be adjusted to download and set up such JDK binary.

Although the `ProfilingIntegrationContinuousProfilesTest` test is disabled I re-enabled it locally and it is passing for Oracle JDK 8 as well as all the previously supported JDK versions.

2021-03-08 13:28 UTC, thegreystone commented
We can still support the scope event if we want to, with a similar strategy to the one I used in my  jfr-tracer open tracing thingy:
https://github.com/opentracing-contrib/java-jfr-tracer

2021-03-08 13:37 UTC, jbachorik commented
@thegreystone We would need to build that particular source root against Oracle JDK. While achievable I foresee a lot of hoops to be hopped to get this properly configured in gradle agent build :( 
How important is it to have the custom events? Perhaps, it should be a different PR so we have at least something in the meantime.

2021-03-08 15:02 UTC, jpbempel approved these changes
LGTM overall, just some comments

2021-03-08 15:18 UTC, thegreystone commented
> @thegreystone We would need to build that particular source root against Oracle JDK. While achievable I foresee a lot of hoops to be hopped to get this properly configured in gradle agent build :(
> How important is it to have the custom events? Perhaps, it should be a different PR so we have at least something in the meantime.

Nah, I think it should be possible to have a build-time-only shim.

2021-03-08 15:19 UTC, thegreystone commented
And yes, we can definitely have a separate PR for it. :)

2021-03-09 09:22 UTC, bantonsson requested changes
Don't know enough about the internals of JFR, but I trust the other ppl, and the code looks good.

Would like the comment changed and some  answers to the posted questions.

2021-03-09 09:37 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkController.java
> + * This is the implementation of the controller for OpenJDK. It should work for JDK 11+ today, and
> I assume it means that this code would miscategorize those JDKs that still have the Oracle string in the javas.vendor property?

Since this is just for JDK 8 there should (AFAIK) not be other distributions with vendor 'Oracle'. Otherwise I would need to attempt load a specific class to find out whether we are running on Oracle distribution.

2021-03-09 09:53 UTC, jpbempel commented on dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkController.java
> + * This is the implementation of the controller for OpenJDK. It should work for JDK 11+ today, and
That was my point above, some distros for 8 still keep Oracle in vendor (at least upstream build that you can find in OprnJDK image and Liberica)

2021-03-09 09:57 UTC, jbachorik commented
@bantonsson It seems like I can not reply to some of your comments 🤷 
Regarding `lombok.NonNull` -> changed to `javax.annotation.Nonnull` instead (the lombok version was used by mistake).

2021-03-09 09:58 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/RecordingData.java
> +import lombok.NonNull;
No. This is a mistake. Should be using `javax.annotaion.Nonnull` instead. Fixed.

2021-03-09 10:08 UTC, jbachorik commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +      if (System.getProperty("java.vendor").contains("Oracle")) {
@jpbempel Is this the case for JDK 8 also? This branch will be taken only for JDK 8. I checked Liberica, Amazon, Zulu and AdoptOpenJDK and neither of them is reporting vendor as 'Oracle'.

Anyway, if this seems to be insufficient I will rather try loading a class that is known to exist only in the Oracle JDK 8 - just to be sure.

2021-03-09 10:17 UTC, jbachorik commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +      if (System.getProperty("java.vendor").contains("Oracle")) {
I have added an additional check for `java.runtime.name` as recommended. 
Anyway, this is just a a best-effort guess since there is no official specification as how Oracle JDK should be detected.

2021-03-09 10:18 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkController.java
> + * This is the implementation of the controller for OpenJDK. It should work for JDK 11+ today, and
I checked those JDKs and they have 'Oracle' in `java.specification.vendor` but `java.vendor` contains the actual JDK supplier. But I added the recommended check for `java.runtime.name` just to be sure.

2021-03-09 10:20 UTC, jpbempel commented on dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkController.java
> + * This is the implementation of the controller for OpenJDK. It should work for JDK 11+ today, and
yeah checked again Liberica it's ok,
though upstream build contains Oracle : tested with image openjdk:8u262-jdk

```
java.vendor: Oracle Corporation
java.runtime.name: OpenJDK Runtime Environment
```

2021-03-09 10:26 UTC, bantonsson approved these changes

2021-03-09 10:35 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkController.java
> + * This is the implementation of the controller for OpenJDK. It should work for JDK 11+ today, and
Fixed

2021-03-09 14:29 UTC, merged