[CIAPP] Add test.parameters tag to TestNG tests
DataDog/dd-trace-java pull request #2531
Opened 2021-03-23 13:20 UTC by drodriguezhdez

Add `test.parameters` tag to TestNG tests.

2021-03-25 08:14 UTC, nachoBonafonte approved these changes

2021-03-25 08:24 UTC, tonyredondo requested changes

2021-03-25 08:24 UTC, tonyredondo commented on dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java
> +  private String buildParametersTagValue(final ITestResult result) {
Please note the output format for `test.parameters` contains an `arguments` submap with the name of the parameter + the value.  is like: 
![image](https://user-images.githubusercontent.com/69803/112442077-bc879d80-8d4b-11eb-9865-52eb5291b04b.png)

2021-03-25 08:44 UTC, drodriguezhdez commented on dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java
> +  private String buildParametersTagValue(final ITestResult result) {
Fixed!

2021-03-25 08:50 UTC, tonyredondo commented on dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java
> +  private String buildParametersTagValue(final ITestResult result) {
now you have the submap, but the key is an `index`, and the value is the parameter `name` isn't?

Should be the name and the actual parameter value. In my example the argument is called `secondsPassed` and the value of the argument for that execution was `60`.

2021-03-25 09:50 UTC, drodriguezhdez commented on dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java
> +  private String buildParametersTagValue(final ITestResult result) {
It's not possible to know the parameter name, just the value. That's why I use an index as best-effort approach.

2021-03-25 09:59 UTC, tonyredondo commented on dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java
> +  private String buildParametersTagValue(final ITestResult result) {
Oh ok, thanks for clarifying that.

2021-03-25 09:59 UTC, tonyredondo approved these changes

2021-03-29 07:46 UTC, bantonsson approved these changes

2021-03-29 11:15 UTC, merged