Flag to setMeasured(true) for any instrumentation; test for Hystrix
DataDog/dd-trace-java pull request #2576
Opened 2021-04-06 05:00 UTC by lpriima

2021-04-06 07:37 UTC, richardstartin commented
I thought we agreed this would be hystrix specific, since there is a specific demand to do this for hystrix. If this is done generically, it can't be revoked. If there is subsequent demand for metrics on more integrations, we can consider the generic option.

2021-04-07 12:14 UTC, richardstartin approved these changes

2021-04-07 13:07 UTC, bantonsson requested changes
👍

2021-04-07 13:07 UTC, bantonsson commented on dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixDecorator.java
> +        System.err.println("span.setMeasured(true);");
Leftover?

2021-04-07 17:24 UTC, richardstartin approved these changes

2021-04-07 17:42 UTC, bantonsson approved these changes

2021-04-07 23:13 UTC, merged