Vert.x 3.9 Redis client instrumentation
DataDog/dd-trace-java pull request #2618
Opened 2021-04-16 14:25 UTC by bantonsson

2021-04-16 14:51 UTC, richardstartin commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +                    interfaces[interfaces.length - 1] = "java/lang/Cloneable";
I wonder if it's better to over allocate a little to avoid resizes, 4 feels like a happy medium to me

2021-04-16 19:24 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +  public AgentBuilder.Transformer transformer() {
I think this warrants better docs. Not easy to follow what's happening.

2021-04-16 19:44 UTC, tylerbenson reviewed
interesting strategy with the clone...

2021-04-16 19:44 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +    final AgentSpan span = DECORATE.startAndDecorateSpan(method.getName());
Should the span be put into scope somewhere?

2021-04-16 19:44 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +      packageName + ".RequestImplMuzzle",
Doesn't seem like this should be a helper class.

2021-04-16 19:44 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/ResponseHandlerWrapper.java
> +    }
I believe in this situation we would usually capture the parent span from when the request was made then activate that for the callback execution after finishing the client span. Does that pattern not apply well here?

2021-04-16 19:44 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/VertxRedisClientDecorator.java
> +      new ConcurrentHashMap<>(201 * 4 / 3, 0.75f);
Does this really need to be a CHM? Wouldn't `DDCaches` be better?

2021-04-16 19:44 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisRxForkedTest.groovy
> +  String runWithParentAndHandler(final Request request) {
Do you have any tests where another span is created in the callback/handler? I'd like to see the parent/child relationship there when there is a parent and no parent (similar to http client tests).

2021-04-19 08:59 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/ResponseHandlerWrapper.java
> +    }
Well, that depends on what you want to measure. If you think that the time for whole request to `redis`, and not only the processing of the reply, should be included in the span, then it's too late to start the span here.

2021-04-19 09:03 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +    final AgentSpan span = DECORATE.startAndDecorateSpan(method.getName());
It is put into scope in the `ResponseHandlerWrapper`.

2021-04-19 09:06 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +      packageName + ".RequestImplMuzzle",
Why do you say that? This `Instrumenter` needs to have some `Advice` connected to it, to be muzzled properly, and if I reference an `Advice` I need to add it as a helper class.

2021-04-19 09:10 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisRxForkedTest.groovy
> +  String runWithParentAndHandler(final Request request) {
All of them create a `handler` span inside the actual response processing `redisSpan`.

2021-04-19 12:16 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +                    interfaces[interfaces.length - 1] = "java/lang/Cloneable";
So I don't think that you're allowed to have an array with `null` interfaces in it.

2021-04-19 13:07 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/VertxRedisClientDecorator.java
> +      new ConcurrentHashMap<>(201 * 4 / 3, 0.75f);
Yup, `DDCaches` would probably do just fine here.

2021-04-19 21:38 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +      packageName + ".RequestImplMuzzle",
Advice classes should never need to be added as helper classes. If you do, then it suggests you have a problematic reference somewhere.

2021-04-20 05:43 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +      packageName + ".RequestImplMuzzle",
Thanks for pointing that out. Don't know why I thought I needed to add it as a helper class. Now I need to clean that up in the places where I added it recently, that has passed review 😉

2021-04-20 09:16 UTC, richardstartin commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisInstrumentation.java
> +        "datadog.trace.bootstrap.instrumentation.api.UTF8BytesString");
I think we should use `UTF8BytesString.class.getName()` in case we move it, similar for boolean, we won't/can't inject it, it will have been loaded already, its name won't change, but it's more consistent if we always define the values the same way.

2021-04-20 09:17 UTC, richardstartin commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +    return Collections.singletonMap(named("?"), packageName + ".RequestImplMuzzle");
`named("?")`??

2021-04-20 09:21 UTC, richardstartin commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/VertxRedisClientDecorator.java
> +  private final DDCache<String, UTF8BytesString> commandCache = DDCaches.newFixedSizeCache(201);
Then is 201 enough space to memoise them all? `FixedSizeCache` overwrites on collision rather than using a resolution strategy. I would use `ConcurrentHashMap` or `DDCaches.newUnboundedCache(201 * 4 / 3)`

2021-04-20 09:22 UTC, richardstartin approved these changes

2021-04-20 10:18 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +    return Collections.singletonMap(named("?"), packageName + ".RequestImplMuzzle");
Yeah, I should definitely comment this. The transformer should never match. It's the only way that I found to get `muzzle` to do _the right thing_™️

2021-04-20 10:20 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/VertxRedisClientDecorator.java
> +  private final DDCache<String, UTF8BytesString> commandCache = DDCaches.newFixedSizeCache(201);
The cache size will be aligned up to `256`, and I'm pretty sure that not all commands are used in a normal application, but I can increase it.

2021-04-20 10:21 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisInstrumentation.java
> +        "datadog.trace.bootstrap.instrumentation.api.UTF8BytesString");
Yes, I can change that.

2021-04-20 10:36 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +    return Collections.singletonMap(named("?"), packageName + ".RequestImplMuzzle");
🤦‍♂️ I should just have a false matcher here...

2021-04-20 14:49 UTC, tylerbenson requested changes
I think we need to fix the parent/callback context relationship before merging.

2021-04-20 14:49 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +        new BooleanMatcher<MethodDescription>(false), packageName + ".RequestImplMuzzle");
See also: `none()`

2021-04-20 14:49 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
> +                    // Add a clone method that calls the protected shallow clone method in Object
A comment indicating what the precursor java code looks like would be helpful.

2021-04-20 14:49 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +    final AgentSpan span = DECORATE.startAndDecorateSpan(method.getName());
yeah, but not until the response... I'm saying is it worth scoping this method call?

2021-04-20 14:49 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/ResponseHandlerWrapper.java
> +    }
I didn't say start the span here.  I'm saying the client span should be finished before `handle` is called.  `handle` should be scoped by the parent span of the client span.
IE:
```
[----------parent-----------]
 [---client--][--callback--]
```

2021-04-20 14:49 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisTestBase.groovy
> +      basicSpan(it, "handler", span(2))
based on my example above, the `handler` span should be a child of the parent, not the client span.

2021-04-20 15:35 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +    final AgentSpan span = DECORATE.startAndDecorateSpan(method.getName());
Nope, since we don't support vertx futures.

2021-04-20 15:37 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/ResponseHandlerWrapper.java
> +    }
So this is confusing to me. Grouping the handler processing as part of the operation felt natural, but maybe it should be different. Do you propose that I create the `[--callback--]` span as well to measure the processing separately, or should that be left up to the user to do?

The code in the vertx mysql client does this exact same thing (not tests to check it though 😔), so that needs to be fixed as well.

2021-04-20 16:01 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/ResponseHandlerWrapper.java
> +    }
the callback span shouldn't be created automatically but was a demonstration of if a user did create a span in the callback (similar to our http client tests).

2021-04-21 12:15 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +    final AgentSpan span = DECORATE.startAndDecorateSpan(method.getName());
I've changed this based on your feedback around the spans and how they should relate. The client span is now activated and scoped here.

2021-04-21 12:16 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/ResponseHandlerWrapper.java
> +    }
This has now been changed to work they way you describe.

2021-04-21 12:17 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisRxForkedTest.groovy
> +  String runWithParentAndHandler(final Request request) {
Added tests without a `parent` span.

2021-04-21 14:30 UTC, tylerbenson approved these changes
Nice work.  Optional changes and questions remaining.

2021-04-21 14:30 UTC, tylerbenson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisTestBase.groovy
> +      redisSpan(it, command, span(1)) // name is redis.query
The spans in this order are a bit confusing to me.  How do you ensure this order is consistent?

2021-04-22 06:58 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisTestBase.groovy
> +      redisSpan(it, command, span(1)) // name is redis.query
Sorting by name

2021-04-22 10:50 UTC, merged