Hazelcast Instrumentation
DataDog/dd-trace-java pull request #2658
Opened 2021-04-25 02:53 UTC by darylrobbins

From Hazelcast version 3.6 onwards. Client-side instrumentation only.

2021-04-25 23:34 UTC, darylrobbins commented
I am not sure what the build failure is but it's happening in the Hibernate instrumentation and appears to be intermittent.

2021-04-26 08:33 UTC, richardstartin commented
There is an intermittent issue with building Hibernate (and Elasticsearch) on circleci, so don't worry about it if you see that. All the failures I looked at just now were related to Hazelcast though.

2021-04-26 08:41 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +                    "replace",
If these methods call in to a common place where the `SyncAdvice` could be applied, that would be a lot better. It's worth remembering that apply advice is basically splicing `byte[]`s together, and the less of it we do, the less impact we have on application startup time.

2021-04-26 08:41 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +                    "values")),
ditto

2021-04-26 08:43 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +                    "toArray")),
Again, _if it's possible_ to factor this out so the advice is applied to common utility methods all of these methods call, please do it.

2021-04-26 08:46 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +      // automatically for us.
I don't know the Hazelcast API very well, but is it possible to do get the same guarantees by only instrumenting the top level method so we don't need to track call-depth?

2021-04-26 08:51 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/v4/ClientInvocationInstrumentation.java
> +    final Map<ElementMatcher<MethodDescription>, String> transformers = new HashMap<>(2);
It doesn't make much sense to size the map like this because the load factor is 0.75 and two elements are added below, meaning the map will always be resized. Since we do create hundreds of these, I do think it's a good practice to set the sizes though, so I recommend setting it to 4 so another transformer could be added without needing to change this line.

2021-04-26 09:07 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/HazelcastInstanceInstrumentation.java
> +        "com.hazelcast.client.impl.HazelcastClientProxy");
Does this instrument the right places? Looking at `com.hazelcast.client.impl.clientside.HazelcastClientProxy` ([here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/clientside/HazelcastClientProxy.java)) it really is just a proxy to `com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl`, which may have simpler instrumentation points, and not all of the methods in the transformers are defined (e.g. of the ones I spot checked, there is no `getAtomicLong` or `getLock`, but there is a `getReliableTopic` and `getXAResource`). 

Of the methods which do exist on `com.hazelcast.client.impl.clientside.HazelcastClientProxy`, within `com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl` they all call in to `getDistributedObject ` which would allow for simpler instrumentation and less of it.

2021-04-26 09:12 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +  private static final String PROXY_PACKAGE = "com.hazelcast.client.proxy";
I can't find this package on the v3.6 tag of hazelcast, is it generated?

2021-04-26 09:19 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +                    "replace",
It's possible that `ClientInvocation` would have a smaller surface area, since all of these lead to a `ClientInvocation`, the only complication is the correlation of the `Future` it produces with the invocation itself. https://github.com/hazelcast/hazelcast/blob/fb720d9e7f4b7643c31fdb61e9b83b6ca8ecc552/hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocation.java#L53

2021-04-26 09:24 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +public class DistributedObjectInstrumentation extends Instrumenter.Tracing {
I haven't inspected everything this instrumentation covers but I couldn't find anything here which I don't think could be handled by tracing `ClientInvocation`, which would reduce our footprint and simplify this. Have you considered instrumenting `ClientInvocation` and ruled it out for some reason I haven't considered?

2021-04-26 09:34 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +public class DistributedObjectInstrumentation extends Instrumenter.Tracing {
I noticed that `ClientInvocation` is instrumented elsewhere (there's a lot of code in this diff) - is there a reason that instrumentation can't be extended to handle these cases?

2021-04-26 09:59 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +          InstrumentationContext.get(DistributedObject.class, HazelcastInstance.class).get(that));
This clearly couldn't be done in the `ClientInvocation` instrumentation.

2021-04-26 10:03 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectInstrumentation.java
> +          InstrumentationContext.get(DistributedObject.class, HazelcastInstance.class).get(that));
This wouldn't be required if the `ClientInvocation` instrumentation got the instance name from `HazelcastClientInstanceImpl.getName` (`HazelcastClientInstanceImpl` would be a field value).

2021-04-26 10:04 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/HazelcastInstanceInstrumentation.java
> +public class HazelcastInstanceInstrumentation extends Instrumenter.Tracing {
I don't think this instrumentation would be required if the Hazelcast instance name were taken from the `HazelcastClientInstanceImpl.getName()`

2021-04-26 10:22 UTC, richardstartin requested changes
This is a very welcome contribution, but the implementation a very complicated. My concerns surround the propagation of the instance name to the invocation, which involves transforming `DistributedObject` to hold a hard reference to `HazelcastInstance`, so that the instance name is available when the span is started in the client proxy. 

Field injection can have unanticipated consequences like preventing garbage collection of the context value, increases the size of the host object, and can lead to locking of the host object. 

The instance name is actually available to `ClientInvocation` and can be read when the invocation proceeds, so this should be simple to fix. This means we can just get rid of the `HazelcastInstanceInstrumentation` and its associated context stores.

I haven't figured out how propagate the method name from the proxy down to the `ClientInvocation` but there are a few attributes to rule out extracting similar information from in the `ClientInvocation`. The `ClientMessage` and object name look like good candidates for enriching the `ClientInvocationInstrumentation`. Please investigate extracting attributes similar to the proxy's method name from the context available within `ClientInvocation` so that we can remove `DistributedObjectInstrumentation`. If that's not possible, then I would see justification for `DistributedObjectInstrumentation`'s existence.

2021-04-26 13:53 UTC, darylrobbins commented
> This is a very welcome contribution, but the implementation a very complicated. 

Yes, the instrumentation for 3.9 and beyond is a lot simpler based on the `ClientInvocation`. The problem before that is the `ClientInvocation` doesn't have the objectName and the `ClientMessage` doesn't have the operationName. The easiest answer would be to support only 3.9+ but the version I care about is 3.8 at the moment.

In theory, we could create our own operation name with a mapping table of message types, but that's a lot of manual labour and still leaves us without an object name. The object name is like the table name, so it's important information to have. We really have no good way to get it, since it doesn't appear consistent how it's represented in the message.

This is why I ended up instrumenting the entire public interface for 3.6.

> The instance name is actually available to `ClientInvocation` via the `HazelcastClientInstanceImpl` and can be read when the invocation proceeds, so this should be simple to fix. This means we can just get rid of the `HazelcastInstanceInstrumentation` and its associated context stores.

Yes, this would work for the 3.6 instrumentation but maybe not as well for the 3.9+ unless we started the span on the invocation of the constructor rather than on invocation.

> I haven't figured out how propagate the method name from the proxy down to the `ClientInvocation` but there are a few attributes to rule out extracting similar information from in the `ClientInvocation`. The `ClientMessage` and object name look like good candidates for enriching the `ClientInvocationInstrumentation`. Please investigate extracting attributes similar to the proxy's method name from the context available within `ClientInvocation` so that we can remove `DistributedObjectInstrumentation`. If that's not possible, then I would see justification for `DistributedObjectInstrumentation`'s existence.

Yes, this is what I did for 3.9+ but as I mention above, the ClientInvocation just doesn't have the information needed until 3.9.

2021-04-26 17:07 UTC, darylrobbins commented
> Does this sound like a reasonable approach? If simplifying the 3.9+ instrumentation is more work than it's worth to you given that you're on 3.8, perhaps we could limit the scope of this PR to 3.8, so you get tracing for your applications in return for the effort you've already put in, and we don't have to take on the risk. We could then do a 3.9+ instrumentation in house.

This is actually exactly what I've done. I think you may have only looked at the 3.6 instrumentation. There are actually 4 versions of the Hazelcast instrumentation in there with finally tuned muzzle rules. The 3.9 instrumentation already takes the ClientInvocation approach. They moved the classes around in 3.11, so that's a small update. Then, in 4.0, there are a few additional features I leverage but it's the same general approach since 3.9.

2021-04-26 17:16 UTC, darylrobbins commented
> We could always field inject the name (i.e. a plain old string value) into `ClientInvocation` on exit from its constructor.

Would this be done using the ContextStore or a different approach? Is the main risk to stay away from linking to a complex entity with this approach?

2021-04-26 17:50 UTC, richardstartin commented
> This is actually exactly what I've done. The 3.6 instrumentation is the only one that operates on the DistributedObject public interface. From the 3.9 instrumentation and beyond, they operate entirely on the ClientInvocation. I migrated to the simpler approach as soon as it was possible. The 3.11 instrumentation is mostly the same but they moved around the classes a bit. The 4.0 instrumentation has a few additional capabilities but it's the same general approach.

I apologise for mixing things up - instrumentation is hard to review because both the framework and the code in the change needs to be considered. There is a lot of _code_ to review here, let alone the surrounding context of the client library, and it would be easier to review if the changes were made in smaller units - either in separate PRs or in separate commits for each version of the library. 

As things stand, we have the following:

1. A complex 3.6-3.8 instrumentation which is the one you need to trace your own applications. I would be ok with accepting this one as is, but we need this to be disabled by default and independently of other versions of the instrumentation because of its complexity.
2. A much simpler `ClientInvocation` based instrumentation for 3.9-3.10. I don't have any concerns about this one.
3. a 3.11 instrumentation which instruments `ClientInvocation` and `ClientMessage`, and includes a context store from `ClientInvocation` to `HazelcastInstance` which makes me uneasy. I think this could be merged with 3.9 if the `ClientInvocationInstrumentation` added a context store to field inject the instance name in to `ClientInvocation`, even if it's not necessary for 3.9 and 3.10.
4. A 4.0 instrumentation which again injects `HazelcastInstance` into `ClientInvocation`, where I think we could just inject the instance name instead, but doesn't look like it can be merged into a 3.9 instrumentation because the library has changed too much. 

If the instance name were captured and injected in to `ClientInvocation` in the `ClientInvocation` constructor, is there any reason not to merge the 3.9 and 3.11 instrumentations?

2021-04-26 18:06 UTC, darylrobbins commented
> There is a lot of _code_ to review here, let alone the surrounding context of the client library, and it would be easier to review if the changes were made in smaller units - either in separate PRs or in separate commits for each version of the library.

> I apologise for mixing things up - instrumentation is hard to review because both the framework and the code in the change needs to be considered. There is a lot of _code_ to review here, let alone the surrounding context of the client library, and it would be easier to review if the changes were made in smaller units - either in separate PRs or in separate commits for each version of the library.

Sorry about that. It was about 2 days of work that I was working on in parallel, so I created a single unit to support from past to present. I'll aim for smaller PR's in the future.

> As things stand, we have the following:
> 
> 1. A complex 3.6-3.8 instrumentation which is the one you need to trace your own applications. I would be ok with accepting this one as is, but we need this to be disabled by default and independently of other versions of the instrumentation because of its complexity.

I have removed the use of the contextStore from this one based on your suggestions. I will call it `hazelcast_legacy` to separate from the more modern integration. I'd suggest we make this an undocumented feature so it can be killed off when we no longer need to support it easily.

> 2. A much simpler `ClientInvocation` based instrumentation for 3.9-3.10. I don't have any concerns about this one.

> 3. a 3.11 instrumentation which instruments `ClientInvocation` and `ClientMessage`, and includes a context store from `ClientInvocation` to `HazelcastInstance` which makes me uneasy. I think this could be merged with 3.9 if the `ClientInvocationInstrumentation` added a context store to field inject the instance name in to `ClientInvocation`, even if it's not necessary for 3.9 and 3.10.

Actually, the lack of instance name in 3.9-3.10 is an accidental omission. I'll see what I can do. The main reason these were split was because Hazelcast moved around some of the classes I was depending on in 3.11. Is there a good way to support this scenario in the same instrumentation?

> 4. A 4.0 instrumentation which again injects `HazelcastInstance` into `ClientInvocation`, where I think we could just inject the instance name instead, but doesn't look like it can be merged into a 3.9 instrumentation because the library has changed too much.

Yes, this should be doable.

> If the instance name were captured and injected in to `ClientInvocation` in the `ClientInvocation` constructor, is there any reason not to merge the 3.9 and 3.11 instrumentations?

See above.

2021-04-26 18:14 UTC, richardstartin commented
> Sorry about that. It was about 2 days of work that I was working on in parallel, so I created a single unit to support from past to present. I'll aim for smaller PR's in the future.

It's not a big deal but would be appreciated in the future (thanks for the contributions!).

> The main reason these were split was because Hazelcast moved around some of the classes I was depending on in 3.11. Is there a good way to support this scenario in the same instrumentation?

Which class names changed? `com.hazelcast.client.spi.impl.ClientInvocation`, `com.hazelcast.client.impl.protocol.ClientMessage`, `com.hazelcast.core.HazelcastInstance`, and `com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl` don't seem to have changed.

2021-04-26 18:25 UTC, darylrobbins commented
The main reason for the 3.11 version was that `com.hazelcast.client.impl.HazelcastClientInstanceImpl` moved to `com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl`. Is there a good way to handle this in the same instrumentation?

2021-04-26 18:33 UTC, darylrobbins commented
The reason for the `ClientMessageInstrumentation` is that the `operationName` field of the `ClientMessage` is not exposed as a setter until 4.0. Is there any way to access a private member of a field from an instrumentation?

2021-04-26 18:37 UTC, richardstartin commented
> The main reason for the 3.11 version was that `com.hazelcast.client.impl.HazelcastClientInstanceImpl` moved to `com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl`. Is there a good way to handle this in the same instrumentation?

Since it implements `com.hazelcast.core.HazelcastInstance`, you could match it with `namedOneOf("com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl", "com.hazelcast.client.impl.HazelcastClientInstanceImpl")` and reference it as `com.hazelcast.core.HazelcastInstance` wherever it's required in Java code. If any implementation methods not on that interface are relied on, forget about it and keep the instrumentations separate.

2021-04-26 18:39 UTC, richardstartin commented
> The reason for the `ClientMessageInstrumentation` is that the operationName field of the `ClientMessage` is not exposed as a setter until 4.0. Is there any way to access a private member of a field from an instrumentation?

Yes, but it would be complicated to do within dd-trace-java and what you have done feels like a reasonable trade-off to me. Thanks for explaining the rationale.

2021-04-26 18:42 UTC, darylrobbins commented
> Since it implements `com.hazelcast.core.HazelcastInstance`, you could match it with `namedOneOf("com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl", "com.hazelcast.client.impl.HazelcastClientInstanceImpl")` and reference it as `com.hazelcast.core.HazelcastInstance` wherever it's required in Java code. If any implementation methods not on that interface are relied on, forget about it and keep the instrumentations separate.

Hmm, that's weird. I already had the namedOneOf() in there. I thought I had tried and it didn't liked it when I used HazelcastInstance as the parameter in the Advice, but seems to be working now, so maybe we can kill off the 3.11 instrumentation after all.

2021-04-26 18:46 UTC, darylrobbins commented
One issue I had with the lower level instrumentation at the `ClientInvocation` level is that the invocations sent can change by the version, which can be a pain in the tests. For example, some higher level operations are made up of several lower level operations and the implementation evolves across versions. I think the added insight you get from seeing all the messages involved is valuable, but can make it difficult to have consistent tests.

Do you have a good pattern for ignoring certain traces in the test? I wasn't able to find much beyond the ES53 instrumentation but the approach didn't seem to work for me.

2021-04-26 18:50 UTC, richardstartin commented
> Do you have a good pattern for ignoring certain traces in the test? I wasn't able to find much beyond the ES53 instrumentation but the approach didn't seem to work for me.

@tylerbenson do you have any suggestions here?

2021-04-26 19:07 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/DistributedObjectDecorator.java
> +        e.printStackTrace();
`log.debug`

2021-04-26 19:09 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/v4/ClientInvocationDecorator.java
> +        e.printStackTrace();
`log.debug`

2021-04-26 19:09 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/v4/ClientInvocationDecorator.java
> +    return span;
just return the span

2021-04-26 19:10 UTC, richardstartin commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/v3_9/ClientInvocationDecorator.java
> +    return span;
Just return the span

2021-04-26 19:16 UTC, richardstartin commented
This is looking good. There are a few minor comments about logging. Also please consider inlining any decorator methods which only do one thing to the span into the advice.

2021-04-26 19:22 UTC, tylerbenson commented
> Do you have a good pattern for ignoring certain traces in the test?

You can do a couple different things:
1. Split up the earliest test from the latest.  This is usually best if the result is significantly different. (Remove the block containing the `dirName` from the `latestDepTest` declaration.)
2. Configure the test to dynamically detect which library version is being used and modify the test behavior accordingly.  (Better if difference is minimal.)
3. Make the assert section more flexible via removing/filtering out specific spans or making certain tags optional.

2021-04-26 23:41 UTC, darylrobbins commented
> > Do you have a good pattern for ignoring certain traces in the test?
> 
> You can do a few different things:

It works now for all supported versions. I removed a few tests that were particularly prone to this issue, for example the Reliable Topic one, which is implemented on top of the ring buffer.

2021-04-27 00:39 UTC, darylrobbins commented
Please pay particular attention to the enhancement I made to `ListWriter` for filtering out traces before they're written. This allowed me to filter out the noisy Client.* operations which can sometimes happen seemingly randomly in the tests.

2021-04-27 07:33 UTC, richardstartin approved these changes
This looks very good, thanks

2021-04-28 16:26 UTC, tylerbenson requested changes
main problem is the `sourceCompatibility`. I think it would have been obvious if our build was actually working.

2021-04-28 16:26 UTC, tylerbenson commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/v3_9/ClientInvocationInstrumentation.java
> +    final Map<ElementMatcher<MethodDescription>, String> transformers = new HashMap<>(2);
Needs to be 3 or 4 because of the load factor.

2021-04-28 16:26 UTC, tylerbenson commented on dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/hazelcast-4.0.gradle
> +targetCompatibility = JavaVersion.VERSION_1_8
You can't set source compatibility like this as this would prevent the instrumentation class from being loaded in Java 7. You need a block like this at the top:
```
ext {
  minJavaVersionForTests = JavaVersion.VERSION_1_8
  maxJavaVersionForTests = JavaVersion.VERSION_1_8
}
```

That will result in a `java8` source set being created (see ratpack's gradle file for example).

2021-04-29 15:42 UTC, tylerbenson commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/hazelcast-3.6.gradle
> +  compileOnly group: 'com.hazelcast', name: 'hazelcast-all', version: '3.8'
I don't see anything specific to async in your instrumentation (just tests), so maybe this could be declared as compile for 3.6, but test with 3.8?

2021-04-29 15:52 UTC, tylerbenson requested changes
A few minor changes then I think we're good to merge. Nice work.

2021-04-29 15:52 UTC, tylerbenson commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/v3/ClientInvocationInstrumentation.java
> +package datadog.trace.instrumentation.v3;
can we make the package name `datadog.trace.instrumentation.hazelcast36`

2021-04-29 15:52 UTC, tylerbenson commented on dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/v3_9/ClientInvocationDecorator.java
> +package datadog.trace.instrumentation.v3_9;
can we make the package name `datadog.trace.instrumentation.hazelcast39`
(Though if you prefer `_` separation on version, no objection there...)

2021-04-29 15:52 UTC, tylerbenson commented on dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/v4/ClientListenerInstrumentation.java
> +package datadog.trace.instrumentation.v4;
`datadog.trace.instrumentation.hazelcast4`

2021-04-29 15:52 UTC, tylerbenson commented on dd-java-agent/instrumentation/hazelcast/hazelcast.gradle
> +apply from: "$rootDir/gradle/java.gradle"
Delete file

2021-04-29 15:52 UTC, tylerbenson commented on settings.gradle
> +include ':dd-java-agent:instrumentation:hazelcast'
```suggestion
```

2021-04-29 16:31 UTC, tylerbenson commented
Also linking to this discussion regarding wire propagation for future reference: https://groups.google.com/g/hazelcast/c/i6FAz4LL1H8

2021-04-30 11:04 UTC, darylrobbins commented
I moved the instrumentations to the root level dd-java-agent/instrumentation directory since Gradle was complaining when they resided inside a hazelcast directory, which wasn't itself a Gradle module.

2021-04-30 14:33 UTC, tylerbenson approved these changes
Looks good! Nice work.

2021-05-04 17:22 UTC, merged