don't notify scope listeners if trace is eligible for dropping
DataDog/dd-trace-java pull request #2661
Opened 2021-04-27 14:43 UTC by richardstartin

2021-04-27 14:54 UTC, tylerbenson approved these changes

2021-04-27 15:23 UTC, jbachorik approved these changes

2021-04-29 14:48 UTC, charliegracie approved these changes

2021-04-29 15:13 UTC, bantonsson approved these changes
Funny that you're using that byte for `flags`. I happen to be doing the exact same thing for other purposes in my experiments...

2021-04-29 15:24 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
> +      if (span.eligibleForDropping()) {
This will also not change the information for the loggers. Is that expected?

2021-04-29 15:27 UTC, bantonsson requested changes
Could we have a quick discussion about the implications on other listeners than profiling?

2021-04-29 15:57 UTC, bantonsson approved these changes

2021-05-04 07:50 UTC, bantonsson commented
Is there anything holding this back, or can it be merged?

2021-05-04 08:56 UTC, richardstartin commented
@bantonsson if you have changes in this area, please don't hold back to avoid a merge conflict.

2021-05-04 09:17 UTC, bantonsson commented
Ok. The only overlap is the `flags` field. I'll align the naming.

2021-05-04 13:17 UTC, merged