Disable OldObjectSample if the JDK doesn't support it
DataDog/dd-trace-java pull request #2727
Opened 2021-05-14 14:48 UTC by luhenry

Ensure that the OldObjectSample event isn't enabled when the JDK doesn't support it. It requires [1] which is in JDK 17, but not yet in 11 (it was backported then reverted) nor 8.

[1] https://bugs.openjdk.java.net/browse/JDK-8258414

2021-05-17 08:14 UTC, jbachorik requested changes

2021-05-17 08:14 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
> +    if (recordingSettings.get("jdk.OldObjectSample#enabled") == "true") {
This would probably be better if you use `if(Boolean.parseBoolean(recordingSettings.get("jdk.OldObjectSample#enabled"))` to assert the enablement - eg `True` would be a valid 'truish' value but comparing to `true` would not detect it.

2021-05-17 08:14 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
> +        log.debug("This JDK doesn't support OldObjectSample JFR event, disabling it.");
This message is a bit tricky to get right - the JDKs are supporting `OldObjectSample` event but the implementation makes it too expensive to use in real life applications.
Maybe something along the line `Memory leak detection is not supported for this JDK. Disabling OldObjectSample JFR event.`?

2021-05-17 08:30 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
> +        log.debug("This JDK doesn't support OldObjectSample JFR event, disabling it.");
How about `Inexpensive memory leak detection is not supported for this JDK. Disabling OldObjectSample JFR event.`? I think that conveys even better the message that we are disabling it because it's expensive.

2021-05-17 11:46 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
> +        log.debug("This JDK doesn't support OldObjectSample JFR event, disabling it.");
Sounds good to me. 
/cc @thegreystone - does that sound ok?

2021-05-17 12:07 UTC, thegreystone commented on dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
> +        log.debug("This JDK doesn't support OldObjectSample JFR event, disabling it.");
It's not detection, and not necessarily memory leaks. How about "Live Object Profiling" or something along those lines?

2021-05-17 13:21 UTC, bantonsson commented
@luhenry FYI, the `muzzle` failure is completely unrelated to your changes. We're working on a fix.

2021-05-17 13:22 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
> +        log.debug("This JDK doesn't support OldObjectSample JFR event, disabling it.");
Going for `Inexpensive live object profiling is not supported for this JDK. Disabling OldObjectSample JFR event.`

2021-05-17 15:25 UTC, jbachorik approved these changes

2021-05-17 15:42 UTC, luhenry commented
All tests are passing, except for `muzzle`.

2021-05-19 08:31 UTC, jpbempel approved these changes

2021-05-19 11:00 UTC, mar-kolya approved these changes
It would be really great to add tests for this change if possible.

2021-05-19 11:28 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java
> +      assertEquals(false, true);
You can do `fail()` here.

2021-05-19 11:29 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java
> +      assertEquals(false, true);
Also, I don't think we are ever running the test on JDK 17 trunk 😬

2021-05-19 12:00 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java
> +      assertEquals(false, true);
That last assert shouldn't have been committed, let me revert.

2021-05-19 12:03 UTC, luhenry commented
> It would be really great to add tests for this change if possible.

@mar-kolya I added a test at `dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java`. Ideally, we would rely on a more actionable condition in the test (like a WhiteBox that surfaces whether the runtime actually support what we want rather than based on a version), but I don't know of any feature to do that.

2021-05-19 14:43 UTC, merged