Liza/b3 single header
DataDog/dd-trace-java pull request #2841
Opened 2021-06-18 14:46 UTC by lizapressman

2021-06-18 14:56 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +        if (TRACE_ID_KEY.equalsIgnoreCase(key) && (traceId == null || traceId == DDId.ZERO)) {
I think it would be better to invert the order of this &&, because the `traceId` value checks are much cheaper so if they don't pass we don't have to do the string compare.

2021-06-18 15:06 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +                  final String[] headers = firstValue.split("-");
Looking at the spec, I think we need to check the length of this array. From my reading I see 3 outcomes we care about:

1: only sampling exists

2: Trace ID and span ID exists

>=3: Trace ID and span ID and sampling exists

2021-06-18 15:19 UTC, lizapressman commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +                  final String[] headers = firstValue.split("-");
So here I was trying to avoid having to split for the case where we were only given samplingPriority because I figured it was safe to assume if the length of firstValue is 1, then that's our samplingPriority. I think you're right that I should to add a check for either length of headers = 2 (traceId-spanId) or 3 (traceId-spanId-sampling) after I do split in that else

2021-06-18 19:48 UTC, tylerbenson reviewed
Nice work!

2021-06-18 19:48 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +import java.util.TreeMap;
`./gradlew spotlessApply`

2021-06-18 19:48 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +  private static final String B3_KEY = "b3";
I suggest adding a link to https://github.com/openzipkin/b3-propagation#single-header in the comments.

2021-06-18 19:48 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +        setter.set(carrier, B3_KEY, injectedB3Id);
Based on the format: `b3={TraceId}-{SpanId}-{SamplingState}-{ParentSpanId}`
I think you need to ensure these are always set.

2021-06-18 19:48 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +        String injectedB3Id = injectedTraceId + '-' + injectedSpanId;
Sometimes the compiler will optimize this for you, but since we're doing a fair bit of concatenation, I suggest using a `StringBuilder` ensure we're doing the right thing.

2021-06-18 19:48 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +        } else if (samplingPriority == defaultSamplingPriority() && SAMPLING_PRIORITY_KEY.equalsIgnoreCase(key)) {
I assume you're doing this to prevent conflicts between the different types of b3 formats.  I think this warrants a comment...

2021-06-18 19:48 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +                  final String[] headers = firstValue.split("-");
`string.split` is a relatively expensive operation for hot codepaths (debatable if this is one), and less desirable because of the extra allocations it requires.  It shouldn't be too difficult to avoid the split and search using `indexOf`.  Look at `JDBCConnectionUrlParser` for a really messy example of this.

2021-06-18 19:48 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
> +    b3      | traceId | spanId | samplingPriority | expectedTraceId | expectedSpanId | expectedSamplingPriority
invariants can be declared in the `where` block without being in the table like this:
```
traceId = 1G
spanId = 2G
```

Then you only need the items that actually change to be in the table.

2021-06-18 20:18 UTC, lizapressman commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +        } else if (samplingPriority == defaultSamplingPriority() && SAMPLING_PRIORITY_KEY.equalsIgnoreCase(key)) {
I'll add a comment but this was to give priority to the b3 header so if we've already propagated trace/span/sampling through b3 we won't overwrite this when the trace span or sampling headers come in.

2021-06-21 15:58 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
> +import static datadog.trace.core.propagation.B3HttpCodec.*
We generally avoid wildcard imports... You can increase the threshold in your IDE config.

2021-06-21 16:01 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +          injectedB3Id.append('-').append(injectedSamplingPriority);
I think the sampling decision needs to always be added... I don't think you want this in an if block.

2021-06-21 16:02 UTC, devinsba requested changes
I have to look more closely at the inject code but there is a change needed in the parsing logic from my reading

2021-06-21 16:02 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +        }
From my reading of the spec, the first section can be sampling decision if there isn't a second section. I think you will need a check for that here

2021-06-21 16:04 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +          injectedB3Id.append('-').append(injectedSamplingPriority);
It does not actually _need_ to be added, but it doesn't make a ton of sense for it to not be there, but that was also true with the older b3 headers

2021-06-21 16:05 UTC, lizapressman commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +        }
that was what I was doing in the if check above where I check if the length is only 1 because I assumed if we're given just "0" or just "1" then that is the sampling decision. Is that not an extensive enough check?

2021-06-21 16:05 UTC, lizapressman commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +          injectedB3Id.append('-').append(injectedSamplingPriority);
From my understanding and reading about b3 headers, I thought the options are either traceId and spanId, just sampling, or all three. Is this not correct?

2021-06-21 16:06 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +        }
Oh I missed that. Sorry

2021-06-21 16:14 UTC, lizapressman commented on dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
> +import static datadog.trace.core.propagation.B3HttpCodec.*
only had that set for java and missed it for groovy! Thanks

2021-06-21 17:40 UTC, devinsba approved these changes

2021-06-21 21:05 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +          injectedB3Id.append('-').append(injectedSamplingPriority);
ok, I guess I was mistaken.  Any risk of this breaking existing customers that are using the legacy b3 format if this isn't the case?

2021-06-21 21:07 UTC, tylerbenson approved these changes

2021-06-21 21:07 UTC, tylerbenson commented on dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpInjectorTest.groovy
> +import static datadog.trace.core.propagation.B3HttpCodec.*
Still have the wildcard.

2021-06-22 12:58 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +          injectedB3Id.append('-').append(injectedSamplingPriority);
The logic didn't change for legacy b3, my reading of this code is that it duplicates that logic into b3 single which also is a valid header state

2021-06-22 13:13 UTC, lizapressman commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
> +          injectedB3Id.append('-').append(injectedSamplingPriority);
The b3, as it is now, is just adding to the existing headers. This table here (https://github.com/DataDog/architecture/blob/master/rfcs/apm/integrations/b3-header-propagation/rfc.md) implies sampling is not necessary

2021-06-22 17:15 UTC, merged