Refactor communication into shared module
DataDog/dd-trace-java pull request #2892
Opened 2021-07-06 15:40 UTC by cataphract

2021-07-06 15:43 UTC, bantonsson commented on communication/src/test/java/datadog/communication/serialization/msgpack/MsgPackWriterTest.java
> +                      Assert.assertArrayEquals(data, unpacker.readPayload(length));
The things in `Assert.*` should already be imported.

2021-07-06 15:47 UTC, bantonsson commented on dd-trace-core/src/traceAgentTest/groovy/MetricsIntegrationTest.groovy
> +@Ignore("requires unreleased trace agent image to pass")
This is some very old code that reappeared.

2021-07-06 17:13 UTC, richardstartin commented
Can we merge my simple debug logging before this so I don't need to resolve a huge merge conflict #2887

2021-07-07 10:14 UTC, ValentinZakharov commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +    builder =
Result assignments of `builder` methods calls - looks redundant (here and everywhere in the method).
If no specific reason for that.

2021-07-07 10:14 UTC, ValentinZakharov commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +            .addHeader(DATADOG_META_LANG_INTERPRETER_VENDOR, JAVA_VM_VENDOR);
I'm sorry, I don't get, why did you decide to move `DATADOG_META_LANG_INTERPRETER_VENDOR` assignment outside this method?
I mean, we still set the same value for `DATADOG_META_LANG_INTERPRETER_VENDOR` but in several places around the code.

2021-07-07 10:19 UTC, richardstartin commented on dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/CheckpointEmissionTest.groovy
> +    2 * TEST_CHECKPOINTER.onRootSpanPublished(_, _)
This seems to have reverted a fix for this test and needs to be reverted itself

2021-07-07 10:21 UTC, richardstartin commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
> +        metricsEnabled && featuresDiscovery.supportsMetrics() ? "true" : "");
This is wrong - the agent may be downgraded and no longer support metrics, which is why this was volatile before.

2021-07-07 10:23 UTC, richardstartin requested changes
This looks like a positive improvement, I made a couple of comments which need to be addressed.

2021-07-07 10:37 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +      sharedCommunicationObjects = new SharedCommunicationObjects();
I'm sorry, it seems creating new `SharedCommunicationObjects` here is never called, because we are instantiating sco in `InstallDatadogTracerCallback`.
Was it done to avoid possible NPE in some specific scenarios?

2021-07-07 13:07 UTC, cataphract commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +    builder =
right, in this case it's not needed. Some more complex builders are either immutable or they are more complex and return different types after a method call, but it's not the case here.

2021-07-07 13:09 UTC, cataphract commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +            .addHeader(DATADOG_META_LANG_INTERPRETER_VENDOR, JAVA_VM_VENDOR);
This class was in dd-trace-core and was moved to the communication module. `DDTraceCoreInfo` remains in dd-trace-core, so it cannot be used anymore. Information about the JVM can be kept here, but `DATADOG_META_TRACER_VERSION` needs to be provided by dd-trace-core (hence the new `headers` parameter). Does this answer your comment?

2021-07-07 13:18 UTC, cataphract commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +      sharedCommunicationObjects = new SharedCommunicationObjects();
This is needed for the tests, which create `CoreTracer`s providing almost nothing to its builder.

2021-07-07 13:20 UTC, ValentinZakharov commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +            .addHeader(DATADOG_META_LANG_INTERPRETER_VENDOR, JAVA_VM_VENDOR);
I see, thanks, I missed the movement reason.

2021-07-07 13:21 UTC, cataphract commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
> +        metricsEnabled && featuresDiscovery.supportsMetrics() ? "true" : "");
Good catch; I've changed it back to calculating the value of the header on each call.

2021-07-07 13:57 UTC, richardstartin commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +              new ThreadPoolExecutor(
This has happened before with the profile uploader and should be avoided because it creates bootstrapping nondeterminism at startup.

2021-07-07 14:04 UTC, mcculls commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +              new ThreadPoolExecutor(
If you know you'll only need a bit of concurrency then `AgentTaskScheduler` can act as an `Executor` - I'd suggest adding a new `AgentThread` entry for this particular case, then create a `AgentTaskScheduler` for that entry. (We try to avoid creating too many agent-related threads as each one takes resources away from the main application.)

Alternatively I'd recommend using the existing `AgentThreadFactory` to supply threads as they are excluded/ignored by certain operations - again using a new `AgentThread` entry for this case, so the thread can be clearly identified.

2021-07-07 15:18 UTC, bantonsson commented on communication/communication.gradle
> +    'datadog.communication.http.OkHttpUtils.OkHttpUtilsThreadFactory',
Wasn't this removed?

2021-07-07 15:33 UTC, cataphract commented on communication/communication.gradle
> +    'datadog.communication.http.OkHttpUtils.OkHttpUtilsThreadFactory',
Yes; removed.

2021-07-07 15:34 UTC, cataphract commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +              new ThreadPoolExecutor(
All right, I've changed it to use `AgentThreadFactory`.

2021-07-07 15:50 UTC, richardstartin approved these changes
Thanks for doing this - it looks good to me.

2021-07-07 15:53 UTC, cataphract commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +              new ThreadPoolExecutor(
Actually, I've changed my mind and I'm gonna use always the sync path of httputils. That way, I can have just one instance of `OkHttpClient`. Then on the appsec side I do the async call in a separate thread using `AgentTaskScheduler`. The only problem I see is that the queue is unbound there and I don't want to risk requests queueing up indefinitely. I'm making `taskCount` public so that I can query it before then. I know the check will not be race-free, but it shouldn't matter if the max size of the queue is exceeded by one or two tasks. wdyt?

2021-07-07 15:58 UTC, bantonsson approved these changes

2021-07-08 09:48 UTC, merged