Add 'root' as service name to avoid lengthy tomcat naming for '/'
DataDog/dd-trace-java pull request #2924
Opened 2021-07-13 19:01 UTC by lizapressman

2021-07-14 18:50 UTC, devinsba requested changes

2021-07-14 18:50 UTC, devinsba commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
I think I would call this `root-servlet`

2021-07-14 18:50 UTC, devinsba commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatDecorator.java
> +        contextPath = Config.get().getRootContextServiceName();
I think the original code is still needed so the use of the Config as a fallback should be an else block

2021-07-14 19:02 UTC, lizapressman commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
Do you mean name it DEFAULT_ROOT_SERVLET_CONTEXT_SERVICE_NAME or set it to "/root-servlet"? I assume the first but just want to double check

2021-07-14 19:04 UTC, devinsba commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
I mean the second. And I don't think the `/` is required but if it is then with it

2021-07-14 19:06 UTC, lizapressman commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatDecorator.java
> +        contextPath = Config.get().getRootContextServiceName();
I'm not sure that's right. I inverted the nots here so it changes the name of contextPath to "/root" or whatever the config is if it's empty and sets the tag no matter what. So the span tag either gets set to the contextPath that was taken from the request or if there was no context path in the request it grabs the config.

2021-07-14 19:08 UTC, devinsba commented on dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatDecorator.java
> +        contextPath = Config.get().getRootContextServiceName();
Wow missed the change of !, my bad

2021-07-14 19:14 UTC, lizapressman commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
so removing the / doesn't break anything but in general the servlet context seems to include the / in front:

<img width="300" alt="Screen Shot 2021-07-14 at 3 13 27 PM" src="https://user-images.githubusercontent.com/35850765/125679433-fc7d0894-6241-424b-a835-fe87a0056921.png">

so removing it from the default service name makes it slightly inconsistent. Should I leave it for consistency or remove?

2021-07-14 19:19 UTC, devinsba commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
If we are going to keep that consistency then we should set it to `/` here since that is most correct and then use the config value in `TagInterceptor.interceptServletContext`

2021-07-14 19:21 UTC, lizapressman commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
Sorry, what do you mean by use the config value in TagInterceptor.interceptServletContext

2021-07-14 19:27 UTC, lizapressman commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
Currently the service name is getting propagated correctly because I am updating the context path to the default and setting the tag to that context path. So the '/' trimming in TagInterceptor.interceptServletContext is trimming the value as if "/root" is just any typical context path it's given

2021-07-14 19:29 UTC, lizapressman commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
<img width="848" alt="Screen Shot 2021-07-14 at 3 28 50 PM" src="https://user-images.githubusercontent.com/35850765/125681425-99c3e3c6-ef69-4692-aa20-60801fbd9943.png">

Heres what I'm seeing on the trace. service name is root-servlet and servlet context is /root-servlet

2021-07-14 19:30 UTC, devinsba commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
Sorry I guess what I'm saying is, the correct value for the `servlet.context` would really be `/` in this case, but obviously that doesn't work once the tag gets to the interceptor because it won't affect the service name. So we would need to detect `/` as the tag value there and then substitute

2021-07-14 19:33 UTC, lizapressman commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
ohhh so we want to see just "/" as context and service name should be "root-servlet"? I'll go ahead and modify that

2021-07-14 19:34 UTC, devinsba commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root";
That makes the most sense to me as far as consistency goes. I don't think we want the context to be a path that doesn't exist

2021-07-15 13:38 UTC, devinsba approved these changes
:+1: no need to wait for me to review again after the one quick change

2021-07-15 13:38 UTC, devinsba commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  public static final String DEFAULT_SERVLET_ROOT_CONTEXT_SERVICE_NAME = "/root-servlet";
Because this is being used directly in `span.setServiceName(Config.get().getRootContextServiceName());` you'll want to drop the `/` from the beginning

2021-07-15 21:05 UTC, richardstartin approved these changes
👍🏻

2021-07-15 21:29 UTC, merged