Add config option to disable context propagation for specified JMS topics and queues
DataDog/dd-trace-java pull request #2943
Opened 2021-07-19 19:50 UTC by lizapressman

2021-07-19 20:32 UTC, mcculls commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          Destination destination = message.getJMSDestination();
`MessageConsumerState` already extracts details of the destination for its resource name:

https://github.com/DataDog/dd-trace-java/blob/v0.83.2/dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/SessionInstrumentation.java#L87

You could add an extra field to `MessageConsumerState` to store the destination name separately from the resource name, that way we'd only try to extract it once. (This would also mean you wouldn't need the extra try...catch here.)

2021-07-19 20:33 UTC, devinsba requested changes

2021-07-19 20:33 UTC, devinsba commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          }
Looks like you can move the catch up to here so that the rest of the instrumentation will work even if we can't figure out the queue/topic name

2021-07-19 20:33 UTC, devinsba commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
> +        if (!Config.get().getJMSPropagationDisabledTopicsAndQueues().contains(destinationName)) {
I think we would want to inject if destinationName is null also so we don't break if we end up in an unexpected environment

2021-07-19 20:33 UTC, devinsba commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          if (!Config.get().getJMSPropagationDisabledTopicsAndQueues().contains(destinationName)) {
Same here with null

2021-07-19 20:39 UTC, mcculls commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          if (!Config.get().getJMSPropagationDisabledTopicsAndQueues().contains(destinationName)) {
Should we consider having a default destination name instead of `null`?  That would work better with immutable collections like the ones that `tryMakeImmutableSet` returns on recent JDKs (otherwise you'll get an NPE if you do `contains(null)`

A default name would also mean users could decide whether to turn off propagation or not for nameless messages.

2021-07-19 20:48 UTC, mcculls commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          e.printStackTrace();
Remember to change these to debug log messages

2021-07-19 20:49 UTC, lizapressman commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          Destination destination = message.getJMSDestination();
Would it not be better to add this anyway so at least it's not being done on the consumer side? And then leave it for the Producer since we don't have consumer state info for that side

2021-07-19 21:42 UTC, richardstartin commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          Destination destination = message.getJMSDestination();
This isn't quite right. `JMSMessage.getJMSDestination()` returns the destination the message was _sent_ to (see [here](https://docs.oracle.com/javaee/6/api/javax/jms/Message.html#getJMSDestination())). A common pattern is for the broker to map topics to queues, which decouples producers from consumers, so `JMSMessage.getJMSDestination()` may return a topic name it is unaware of when consuming from a queue. This is why the `SessionInstrumentation` injects the destination name into the `MessageConsumer`. This is not a theoretical problem, having impacted a customer who complained that resource names for a queue included the name of an upstream topic, and would have impacted JMS based systems I have worked on in the past.

This doesn't matter for producers because `JMSMessage.getJMSDestination()` returns the destination the message is sent to  - the producer doesn't care where the broker routes the message.

2021-07-20 13:44 UTC, lizapressman commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          Destination destination = message.getJMSDestination();
So I just pushed up the changes that Stuart suggested for the consumer side. Does making that change fix this issue? Or is there more that I'm not quite getting? Cause now I'm using the SessionInstrumentation as opposed to the JMSMessage.getJMSDestination()

2021-07-20 13:45 UTC, devinsba commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  private final Set<String> JMSPropagationDisabledTopicsAndQueues;
I think you want these variable names lowercase

2021-07-20 13:48 UTC, richardstartin commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
> -  @SuppressWarnings("unchecked")
This is still an unchecked cast

2021-07-20 13:49 UTC, richardstartin commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          Destination destination = message.getJMSDestination();
Yes, this is just to provide background context and to explain why producers don't need special treatment.

2021-07-20 14:12 UTC, lizapressman commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  private final Set<String> JMSPropagationDisabledTopicsAndQueues;
The way the classes for JMS are named made it seem like JMS should be uppercase? is this not true?

2021-07-20 14:14 UTC, devinsba commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  private final Set<String> JMSPropagationDisabledTopicsAndQueues;
Java naming convention is that acronyms at the start of variable names are all lowercase

2021-07-20 15:10 UTC, devinsba approved these changes

2021-07-20 18:34 UTC, tylerbenson commented on dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
> +      "jms.propagation.disabled.topics.and.queues";
instead of `topics.and.queues` this might be abbreviated to `destinations`.

2021-07-20 18:35 UTC, tylerbenson commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +            || destinationName == null) {
null check should go first.

2021-07-20 18:43 UTC, lizapressman commented on dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
> +      "jms.propagation.disabled.topics.and.queues";
I did discuss this with Doug before starting this and he said destinations probably isn't totally accurate. I do agree though that this name is pretty long and it would be nice to shorten it, but do you think destinations is best?

2021-07-20 19:46 UTC, lizapressman commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          if (!Config.get().getJMSPropagationDisabledTopicsAndQueues().contains(destinationName)) {
Not totally sure what the change would need to be here - should I just be setting destinationName to some default name instead of null here?

2021-07-20 20:27 UTC, lizapressman commented on dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
> +          if (!Config.get().getJMSPropagationDisabledTopicsAndQueues().contains(destinationName)) {
And what should the default name be? Any thoughts on naming?

2021-07-21 19:58 UTC, tylerbenson approved these changes

2021-07-22 14:10 UTC, merged