Request body interception for Servlet
DataDog/dd-trace-java pull request #2961
Opened 2021-07-26 18:10 UTC by cataphract

2021-07-26 19:27 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +        (RequestContext ctx_, StoredBodySupplier supplier) -> {
For now, I think this is fine.  However, I think we might want to avoid lambdas in general because they'll be for start-up.  We also want to avoid capturing lambdas to avoid extra allocation.

2021-07-26 19:29 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
> +    request = DECORATE.wrapRequest(span, httpServletRequest);
I thought we'd gotten rid of most the wrapping.  I know we had a few servers where wrapping ServletRequest or ServletResponse was causing problems.

2021-07-26 19:30 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
> +      "datadog.trace.instrumentation.servlet.http.common.BodyCapturingHttpServletRequest",
I think we need to think about separating about the appsec parts of instrumentation.
As is, this will cause us to inject more classes which will consume additional metaspace even when we're not using appsec.

2021-07-26 19:31 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
> +      "datadog.trace.instrumentation.servlet.http.common.BodyCapturingHttpServletRequest",
The wrappers also worry me.  Have we run the server framework test with these changes?  If not, we definitely should.

2021-07-26 19:33 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
> +      "datadog.trace.instrumentation.servlet.http.common.BodyCapturingHttpServletRequest",
I'm not sure how it fits with Config, but I simple solution would be only return the extra classes when appsec is enabled.  Although, then we need to careful about referring to those classes.

I think we probably just need to make a stronger separation between core tracing & app sec.  Same for profiling

2021-07-26 19:35 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
> +      "datadog.trace.instrumentation.servlet.http.common.BodyCapturingHttpServletRequest",
Wrappers also worry me.  I know there was at least one server that tries to cast directly to its servletrequest class.
We need to make sure to run all the server unit tests to make sure this is sound.

My other thought was to annotation any wrapper classes.  Then run a pessimistic static analysis over any supported libraries.  If we find a cast to any child class of the wrapped interface, then we can pessimistically assume we have a problem.

2021-07-26 19:40 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  public synchronized void appendData(char[] chars, int start, int end) {
I worry about the overhead of synchronization.  I assume this will be biased towards one thread, so it is probably fine.

2021-07-26 19:41 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  public String get() {
Would a CharSequence suffice?  Or, something that doesn't allocate every time?

2021-07-26 19:42 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  private char[] storedBody;
Why not use CharBuffer & ByteBuffer for this?

2021-07-26 19:44 UTC, dougqh commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +  public static boolean appSecEnabled = false;
I hate that these fields are final, but that aside.  Why does this need to be public?

2021-07-26 19:46 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +  public Optional<String> getStoredRequestBody() {
I'd prefer to avoid using Optional, since it creates extra allocation that we don't really need.
I also prefer to avoid the use of String as well.

2021-07-27 11:57 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
> +    request = DECORATE.wrapRequest(span, httpServletRequest);
It's true that, in principle, wrapping can cause problems here. These are the options I considered for instrumenting servlet (i.e., not considering here instrumenting details of specific servers):

1. instrument subclasses of `HttpServlet`, and wrap the `HttpServletRequest` argument on the `service` method (similar for filters); this wrapper than wraps the results of `getInputStream` / `getReader`. This is the option I went for.
2. instrument directly subclasses of `HttpServletRequest` and intercept calls to `getInputStream` / `getReader`; wrap the result.
3. Instrument directly `ServletInputStream` / `BufferedReader`.

I think we can discard 3. immediately; even if we could identify the buffered reader instances of interest, instrumenting `BufferedReader` would be too heavy-handed.

The reason I didn't go for 2. is because wrapping request objects is more common than wrapping servlets, and it is what we've been doing at Sqreen. If these methods themselves wrap the inputstream/reader for buffering the request entity, we may be tricked into double-wrapping ourselves, at least with the `instanceof` check we have. Now, perhaps this detection could be done with other means (maybe setting a request attribute once we've done some wrapping), or on balance 2. is still better than 1., but this was my thinking.

2021-07-27 12:00 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
> +      "datadog.trace.instrumentation.servlet.http.common.BodyCapturingHttpServletRequest",
> I think we need to think about separating about the appsec parts of instrumentation.
> As is, this will cause us to inject more classes which will consume additional metaspace even when we're not using appsec.

This flows from the design choice of having an appsec-agnostic "Instrumentation Gateway"; it means the appsec module will not be itself responsible for instrumentation. Still, in this design the extra instrumentation could be avoided if we require that the IG callbacks be set early in the application startup — then we can skip all the advice that exists in support of that callback.

2021-07-27 12:04 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
> +      "datadog.trace.instrumentation.servlet.http.common.BodyCapturingHttpServletRequest",
> My other thought was to annotation any wrapper classes. Then run a pessimistic static analysis over any supported libraries. If we find a cast to any child class of the wrapped interface, then we can pessimistically assume we have a problem.

I would think you'd need to check all the non-library code as well. A user could have setup a filter that wraps the request, and then downcast further down the line.

2021-07-27 12:06 UTC, cataphract commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  public synchronized void appendData(char[] chars, int start, int end) {
Yeah, in principle you'll be reading the whole data in one thread so there is no contention. But you still need to guard against the possibility that stream is used in different threads. I couldn't think of a better way of optimizing the usual path, but I'm open to suggestions.

2021-07-27 12:55 UTC, cataphract commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  public String get() {
The idea here is that this method is generally called only once: to get the final value that is then distributed to the appsec modules for inspection. It is possible, though, that some RASP appsec module is interested in all the data read so far, in which case, yes, we'd be building multiple (but distinct) strings. An option would be expose the storage directly, but this would be difficult to harmonize between the inputstream and reader paths.

2021-07-27 12:55 UTC, cataphract commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +  public static boolean appSecEnabled = false;
An artifact from an aborted change. I'll change it back.

2021-07-27 13:03 UTC, cataphract commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  private char[] storedBody;
You mean as wrappers of the arrays? I need to grow them. I don't think I'd given it any thought, but it seems a bit of an overkill here. All I need is to keep an offset and advance, not marks limits and other misc stuff Char/ByteBuffer support.

2021-07-27 13:04 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +  public Optional<String> getStoredRequestBody() {
I'll make it nullable then. As for the `String`, I've commented elsewhere.

2021-07-27 13:39 UTC, devinsba commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
> +      "datadog.trace.instrumentation.servlet.http.common.BodyCapturingHttpServletRequest",
We have a way to create instrumentation classes that are tied to specific features, perhaps we should create a new sub-class for app sec like the one for profiling: https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java#L383

2021-07-27 20:06 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
> +    request = DECORATE.wrapRequest(span, httpServletRequest);
I do agree that wrapping Request objects is likely to be safer than wrapping Servlets.  Wrapping only ServletInputStream would be strictly safer than wrapping both.

The proof is on the author to convince that wrapping is safe.  Our general rule is that you must run the server tests when you modify something that touches a server.  Since you touched the servlet instrumentation, you must run tests for as many servlet containers as possible, but I'm most interested in the ones that were troublesome previously.

I agree that instrumenting BufferedReader probably isn't viable.  However instrumenting the server specific subclasses of ServletInputStream might not be so bad.

2021-07-27 20:09 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
> +      "datadog.trace.instrumentation.servlet.http.common.BodyCapturingHttpServletRequest",
My requirement for AppSec is quite simple.  There must be a minimum of additional classes loaded when AppSec is disabled.  There must be zero additional classes injected when AppSec is enabled.

If the instrumentation gateway doesn't satisfy those requirements, then the gateway design must be rethought.

2021-07-27 22:06 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  public String get() {
It actually wouldn't be very hard to expose a view into the buffer and have that coexist with InputStream/Reader.

As long as the InputStream/Reader doesn't rewind, you just need to provide a view over the previously written bytes.
I cannot remember if there's a rewind capability, if there is then you might just need to version the buffer if it is rewound into a published segment.

In either case, this is pretty easy to support and reduces allocation considerably.

2021-07-27 22:08 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  private char[] storedBody;
I was just curious as to the reason.  Those classes are often intrinsified and often perform better than the handrolled version.

2021-07-27 22:10 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredByteBody.java
> +  private final AtomicBoolean listenerNotified = new AtomicBoolean();
If notification is once and only once, you don't need an AtomicBoolean.   A volatile + synchronized would be sufficient and allocate less memory.

2021-07-27 22:14 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  public synchronized void appendData(char[] chars, int start, int end) {
Yes, I understand the multi-threading concern.  I'm just leery of adding additional locking.

2021-07-27 22:18 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
> +    request = DECORATE.wrapRequest(span, httpServletRequest);
You are also correct that checking the framework code for checkcast / instanceof is not sufficient to guarantee correctness.  Indeed worse case, the tracer should make a completely world assumption and should never wrap.

I don't think that's entirely practical.  However, we should endeavor to prove that we're not violating any casts inside the servers which we can relatively easily test and analyze.

2021-07-27 22:38 UTC, dougqh requested changes
My 3 main concerns are...
1 - Injecting extra classes - strictly forbidden when AppSec is off
2 - Wrappers - we need to verify that these are safe
3 - Allocation - As far as I can tell, the allocation of the String can easily be eliminated

2021-07-27 23:04 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
> +      "datadog.trace.instrumentation.servlet.http.common.BodyCapturingHttpServletRequest",
@dougqh Please see https://github.com/DataDog/dd-trace-java/pull/2961/commits/ca9106bd519a81afc8f41397dcb4ad1a1718fa95 , which wraps only the is/reader. I've also used the strategy @devinsba suggested to avoid applying the instrumentation if appsec if off

2021-07-28 16:17 UTC, cataphract commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  public String get() {
I can do this for char array variant, but not for the byte + charset variant. That is, unless I decode possibly the whole string and then discard it for every operation (for instance, to implement `CharSequence::getLength()`).

This is the current implementation for `StoredByteBody`:

```java
  @Override
  public synchronized String get() {
    if (this.storedBodyLen == 0) {
      return "";
    }
    if (this.charset != null) {
      return new String(this.storedBody, 0, this.storedBodyLen, this.charset);
    }

    if (isWellFormed(this.storedBody, 0, this.storedBodyLen)) {
      return new String(this.storedBody, 0, this.storedBodyLen, UTF_8);
    }

    return new String(this.storedBody, 0, this.storedBodyLen, ISO_8859_1);
  }
```

To keep this logic, the only possibility I see would be to keep instead of a `byte[]` a `char[]` and then:
1. keep the incomplete code unit sequences in a separate buffer. How big this buffer must be depends on the encoding, though.
2. if we don't have an encoding set, assume at first 7-bit ascii. When we find a sequence that looks like UTF-8, decode as UTF-8.
3. when we find a bad UTF-8 code unit sequence, go back, reencode everything as UTF-8 and interpret each individual byte as latin1.

2021-07-28 16:18 UTC, cataphract commented on internal-api/src/main/java/datadog/trace/api/http/StoredByteBody.java
> +  private final AtomicBoolean listenerNotified = new AtomicBoolean();
It turns out this is read in a synchronized method, so a plain boolean will do.

2021-07-29 15:47 UTC, cataphract commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  public String get() {
Ok, I implemented something in those lines in https://github.com/DataDog/dd-trace-java/pull/2961/commits/de68f0ed928e65e6448dd52ccf7b575f891f0029

2021-07-29 17:54 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +    if (this.storedBodyLen == 0) {
Yes, this looks better.  I'd still like to better understand how the call to native code is being done.

To keep overhead down, we don't to be copying from Java to native either.  We should be able to reduce that by use direct allocation.

2021-07-29 17:59 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
>    private CaseInsensitiveMap<List<String>> collectedHeaders = new CaseInsensitiveMap<>();
final?

2021-07-29 17:59 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
>    private List<StringKVPair> collectedCookies = new ArrayList<>(4);
final?

2021-07-29 18:00 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +  public void setStoredRequestBodySupplier(StoredBodySupplier storedRequestBodySupplier) {
What's the threading model of this class?  I'm concerned by the amount of mutability.

2021-07-29 18:01 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +    subscriptionService.registerCallback(
I think I need to understand the subscriptionService better.  I generally feel that generic callback systems are overly complicated for what instrumentation needs to be doing, but for now, I'm reserving judgment.

2021-07-29 18:02 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +          if (rawRequestBodySubInfo.isEmpty()) {
All these checks seem easy to mess up to me, but if we're only added a few of these then I think it is probably fine.

2021-07-29 18:08 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/BufferedReaderWrapper.java
> +    storedCharBody.appendData('\n');
I'm not sure just assuming '\n' is okay.  Traditionally, Windows would \r\n and old Macs would send \r\r.

2021-07-29 18:10 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/BufferedReaderWrapper.java
> +      for (int i = initPos; i < initPos + read; i++) {
This is likely to be inefficient.

CharBuffer supports some view operations & bulk transfer operations.  It would be better to use those.

2021-07-29 18:16 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletInputStreamWrapper.java
> +      storedByteBody.maybeNotify();
Why are we notifying on every write?

2021-07-29 18:19 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletInputStreamWrapper.java
> +      storedByteBody.maybeNotify();
So we're trying to notify on end?  numRead == 0 doesn't mean end?
It means no data available or the read was interrupted (potentially by kernel, etc).

If you want end, that's numRead == -1.  Out of curiosity, why not use servlet ReadListener?

2021-07-29 18:23 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +// XXX: this must be made thread-safe
The lack of clear threading model here is concerning.  Regardless of the threading model, I think it would be better to reduce the mutability.

2021-07-29 18:25 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +  public void setStoredRequestBodySupplier(StoredBodySupplier storedRequestBodySupplier) {
Where do we set this?

2021-07-29 18:28 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +  private volatile EventProducerService.DataSubscriberInfo rawRequestBodySubInfo;
As mentioned elsewhere, I think this subscriber system might be overkill an ill-performing.  The fact that we feel we need a cache for it -- only makes me more convinced that something simpler would be better.

2021-07-29 18:31 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +    return new String[] {
So this is split into its own instrumentation -- good.
Why do we need the delegating listeners?  That seems rather heavy weight.

2021-07-29 18:37 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/IGDelegatingStoredBodyListener.java
> +    // due to how the module boundaries are done, StoredBodySupplier cannot implement
I see, so this is the reason for the delegation.  I'm not opposed to pushing StoredBodySupplier to generally available location if need be.  I'd prefer that to wrappers on top of wrappers.

We could also use a more generic type that we push into core.  Mostly, I just think we talk through the whole notification system.

2021-07-29 18:39 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/IGDelegatingStoredBodyListener.java
> +    this.bodyStartCallback.apply(ctx, storedByteBody);
Listeners on top of callbacks on top of listeners worries me because of both CPU & memory overhead

2021-07-29 18:52 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletInputStreamWrapper.java
> +      storedByteBody.appendData(b, 0, numRead);
If I remember correctly storedByteBody has a limit as to how much it accepts, shouldn't that be checked here.
Do you notify when you reach the limit or do you wait until the stream ends?

2021-07-29 19:14 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +    return new String[] {
I saw elsewhere this was from StoredBodyListener-s being incompatible across modules.  I think that's the problem we actually need to solve -- that and just discussing the overall flow of data.

2021-07-29 19:17 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredByteBody.java
> +  private static ThreadLocal<CharsetEncoder> UTF8_ENCODER_CACHE =
final

2021-07-29 19:17 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredByteBody.java
> +    private ThreadLocal<Object[]> cache = new ThreadLocal<>();
final

2021-07-29 19:22 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +      RequestContext requestContext = agentSpan.getRequestContext();
So lack of a requestContext short circuits wrapping?  Good

2021-07-29 19:23 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +      CallbackProvider cbp = AgentTracer.get().instrumentationGateway();
Does this mean we're still wrapping when no rule is consuming the body?  If so, I think that's a problem.

2021-07-29 19:24 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +          servletInputStreamWrapper.setCharset(charset);
Why not set the charSet in the ServletInputStreamWrapper constructor?
I don't see a data dependence that prevents it.

2021-07-30 07:49 UTC, cataphract commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +    if (this.storedBodyLen == 0) {
Sorry, what native code are you referring to?

2021-07-30 07:52 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +    if (this.storedBodyLen == 0) {
I suppose, it's about send data to WAF via JNI.

2021-07-30 07:56 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/BufferedReaderWrapper.java
> +    storedCharBody.appendData('\n');
It is true that assuming `\n` is problematic. Unfortunately, there are no better options, because the wrapped `BufferedReader` may have discarded a LF, CR, CR + LF, or nothing at all (EOF). We just can't know.

2021-07-30 08:40 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletInputStreamWrapper.java
> +      storedByteBody.maybeNotify();
I'm fixed the problems with the zeros.

As for the second point, that's only available for Servlet 3.1+. Plus the original implementation would do the notification as soon as the size limit was reached; it did not wait until the original stream reached the end.

2021-07-30 08:48 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +// XXX: this must be made thread-safe
Originally this was only storing headers and request uri, which would presumably would be all delivered from the same thread (the same that created the object). With the request body changes, things got a bit more complicated, though since there are really no consumers of the request body now, it's not an immediate concern. I'll make some adjustments, though, really no reason to leave it in a semi-broken state.

2021-07-30 08:49 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +  public void setStoredRequestBodySupplier(StoredBodySupplier storedRequestBodySupplier) {
`GatewayBridge`, on the `REQUEST_BODY_START` callback.

2021-07-30 09:51 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +  private volatile EventProducerService.DataSubscriberInfo rawRequestBodySubInfo;
There are, alas, two subscription systems involved. The instrumentation gateway, and an appsec internal one. The appsec one allows modules to subscribe an arbitrary number of data "addresses", i.e., labels for data. This is what's being cached here, the set of subscribers that are interested in a at least one address in a particular bundle of data. The cache avoids our having to calculate this union set each time.

2021-07-30 09:54 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletInputStreamWrapper.java
> +      storedByteBody.appendData(b, 0, numRead);
`appendData` will be a noop if the limit was reached. Though I see that with the refactoring of `StoredByteBody`, it will still decode data that will then be discarded. I'll improve that a bit.

2021-07-30 12:50 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +      CallbackProvider cbp = AgentTracer.get().instrumentationGateway();
Indeed it does. We need to track the subscriptions across the two levels of listeners to prevent this, but I'll implement it.

2021-07-30 12:50 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +      CallbackProvider cbp = AgentTracer.get().instrumentationGateway();
Indeed it does. We need to track the subscriptions across the two levels of listeners to prevent this, but I'll implement it.

2021-07-30 12:50 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +          servletInputStreamWrapper.setCharset(charset);
Good point.

2021-08-02 13:21 UTC, cataphract commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +    return new String[] {
Actually the reason presented seems not to apply anymore since I moved some around modules. It would be possible to change StoredCharBody/StoredByteBody to, instead of receiving a listener, receive at least the `RequestContext`. It could also get the two callbacks directly, or get the InstrumentationGateway and look them up, or even get nothing else extra and lookup the InstrumentationGateway statically twice (for start or for end). In terms of prettiness of design, the current one is IMO the best as StoredCharBody/StoredByteBody need not known any details about the notification mechanism, but I understand the extra indirection has a cost. I can change it for the middle alternative, as the last one is a pain to unit test and requires looking up the agent tracer and IG  twice, at the cost of storing an extra field.

2021-08-02 13:25 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +// XXX: this must be made thread-safe
I've made some changes that fix the problem with the request body supplier likely accessible from multiple threads in the future. As for the "initial data" fields (request uri, headers, ip), there is still no synchronization involved as I assume they all come from the same thread (or if they end up being processed in several threads, that the changes made in earlier rounds are published to later rounds of the http header processing). I think it's a reasonable assumption, though I may be wrong here for some of the supported web servers.

2021-08-04 12:23 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/http/StoredByteBody.java
> +    private ThreadLocal<Object[]> cache = new ThreadLocal<>();
Still missing `final`

2021-08-05 09:21 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +    if (this.storedBodyLen == 0) {
@dougqh The preparation of the parameters and the actual call to the native code is done by the `libsqreen` dependency, that lives in its own repo, and which currently serialize the data into a direct `ByteBuffer` that the native code access directly. A future optimization could definitely be to use a direct `ByteBuffer` for the message body and pass this to the native code without copying/serializing it, but that is a slightly larger undertaking.

2021-08-05 09:27 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  private char[] storedBody;
If we in the future want to pass the message body directly to the `libsqreen` and native code, then we could do a direct `ByteBuffer` here with `MAX_SIZE` since the pages won't be committed until they are used.

2021-08-05 12:05 UTC, bantonsson approved these changes
LGTM

Apart from performance optimizations that would require changes in `libsqreen` I think that all bigger things have been addressed.

2021-08-06 07:16 UTC, bantonsson approved these changes

2021-08-06 07:16 UTC, bantonsson commented on dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/HttpHeaderFetchingHelper.java
> +public final class HttpHeaderFetchingHelper {
👍

2021-08-06 07:21 UTC, bantonsson commented
@dougqh Would you mind taking another look at the changes made, and if they address your concerns?

2021-08-12 01:45 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventDispatcher.java
> +    List<EventType> res = new ArrayList<>();
I'm guessing this is set-up rarely enough that this isn't a big deal, but I'm still curious...

Is it worth sizing the res ArrayList to the values array.  How often are listeners empty?  We could always trim to capacity afterwards.

2021-08-12 01:49 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventDispatcher.java
>      ArrayList<T> ts = new ArrayList<>(numElements);
I see this already here, but I'm still curious about a couple things.

Why do we need to null fill a List?
If the list doesn't need to grow, then this could be done more efficiently as.

return Arrays.asList(new Object[numElements]);

2021-08-12 01:54 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +  private volatile StoredBodySupplier storedRequestBodySupplier;
If we're assuming this is written and read by the same thread, why is this volatile?
Or, conversely why are the other fields not volatile?

I'm skeptical that the single thread assumption is sound.

2021-08-12 02:02 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +  private volatile EventProducerService.DataSubscriberInfo rawRequestBodySubInfo;
I see.  So why doesn't the appSec internal one, just present the full union of requested subscriptions?
Doesn't this mean we're recreating this union logic in every language?

2021-08-12 02:06 UTC, dougqh commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +      EVENT_DEPENDENCIES.put(EventType.REQUEST_BODY_START, l(Events.REQUEST_BODY_START));
I don't particularly love Maps for these types of things because we're adding immoral memory footprint.
A static routine that does switch & return would be lower overhead.

At the very least, it would be good to size the Maps appropriately.

2021-08-12 02:07 UTC, dougqh commented on dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyByteBodyInstrumentation.java
> +    /* we're assuming here none of these methods call the other instrumented methods */
Okay, that's fine for now.

2021-08-12 02:09 UTC, dougqh commented on dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyByteBodyInstrumentation.java
> +          // purposefully left blank
We should make a way to report these unexpected exceptions, but that's a general tracer problem -- not for this PR.

2021-08-12 02:11 UTC, dougqh commented on dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyByteBodyInstrumentation.java
> +      if (ret == -1) {
I see, so instrumenting the individual read methods.  Nice.

2021-08-12 02:14 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletInputStreamWrapper.java
> +      storedByteBody.maybeNotify();
Okay

2021-08-12 02:19 UTC, dougqh commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
> +    return new String[] {
I fine with seeing how this pans out in time.

I don't necessarily find the indirection prettier myself.  I think all the components are still pretty aware of the notification system conceptually.  The indirection would only really be useful in my view if we were going to swap out components and dynamically wire things up.  Since we're not likely to do that, I don't see a great deal of value in it.

2021-08-12 02:21 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
> +    for (int i = 0; i < MAX_EVENTS; i++) {
callbacks.size() will actually be less confusing for the optimizer.

2021-08-12 02:24 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +  private char[] storedBody;
Yes, that's what I was thinking.  When I was prototyping reducing cost to native / embedded runtimes previously, I ended up using direct buffers to eliminate the copying.

2021-08-12 02:26 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
> +    if (this.storedBodyLen == 0) {
Alright, we can wait on that I suppose.  I'm a little worried we might design ourselves into a corner performance wise, but I guess we'll deal with that later on.

2021-08-12 02:29 UTC, dougqh approved these changes
I'm unblocking for now, but I do have one big concern still.

I'm confused by the threading model the AppRequestContext.  Specifically, the mix of non-volatile and volatile mutable fields.

I also have a several performance nits, but nothing, I think absolutely has to be fixed at this time.

2021-08-12 10:18 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventDispatcher.java
> +    List<EventType> res = new ArrayList<>();
This is only called on initialization, to determine what hooks to use the instrumentation gateway side. But I guess giving the capacity to the constructor wouldn't hurt.

2021-08-12 10:34 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventDispatcher.java
>      for (int i = 0; i < numElements; i++) {
Turns out this method isn't called anymore.

2021-08-12 10:49 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
> +  private volatile StoredBodySupplier storedRequestBodySupplier;
It's not necessarily read by the same thread. There is this public method:

```
  /** @return the portion of the body read so far, if any */
  public CharSequence getStoredRequestBody() { // ...
```

that could, at least in principle, be called from other threads that have access to the `AppSecReqContext`. The other fields:

```
  // assume these will always be written and read by the same thread
  private String savedRawURI;
  private final CaseInsensitiveMap<List<String>> collectedHeaders = new CaseInsensitiveMap<>();
  private List<StringKVPair> collectedCookies = new ArrayList<>(4);
  private boolean finishedHeaders;
  private String ip;
```

need not be volatile because they're only accessed through package-private methods which are called by IG hooks. Their purpose is to collect different pieces about the request so that they can be published and delivered in one go to the appsec bits (currently the WAF).

The assumption here is that the instrumentations calling the producer side of the IG provide all these different bits on the same thread (though I suppose the actual requirements are weaker; there could be some form of synchronization for us to accidentally piggyback on). If there is some http server for which this doesn't hold, this needs to be revisited.

2021-08-12 11:18 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +      EVENT_DEPENDENCIES.put(EventType.REQUEST_BODY_START, l(Events.REQUEST_BODY_START));
The problem with the switches is that they don't work with all the types. In particular, `Address` is not an enum. I'll adjust the capacity though

2021-08-12 15:48 UTC, merged