luhenry/checkpoint-sequence-validator
DataDog/dd-trace-java pull request #2962
Opened 2021-07-27 10:35 UTC by luhenry

No tests should be added with this disable. This disable is only used to track which integrations needs fixing. Adding more means we are regressing the status quo.

2021-07-27 10:36 UTC, luhenry commented
Depends on https://github.com/DataDog/dd-trace-java/pull/2959

2021-07-27 11:21 UTC, richardstartin commented
As discussed, most of these are caused by jetty server (the test server for the http client tests) rather than the instrumentations themselves so I think it's better to just fix that first so there are fewer false positives.

2021-07-28 12:27 UTC, richardstartin submitted a review, later dismissed

2021-07-28 12:35 UTC, richardstartin commented on dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/groovy/AkkaActorTest.groovy
> +})
I checked these manually and there seems to be a bug in the validation, because it rejects valid sequences of events such as 

```
=== Activity checkpoints by thread ordered by time
===== Invalid event sequences were detected. Affected spans are highlited by '***'
Test worker:                                      |-startSpan/1-|-suspend/1-|-suspend/1-|-endSpan/1-|----------|-----------|----------|-----------------|-----------|----------------|-------------|-----------|-----------------|
akka-actors-test-akka.actor.default-dispatcher-5: |-------------|-----------|-----------|-----------|-resume/1-|-endTask/1-|-resume/1-|-***suspend/1***-|-endTask/1-|----------------|-------------|-----------|-----------------|
akka-actors-test-akka.actor.default-dispatcher-2: |-------------|-----------|-----------|-----------|----------|-----------|----------|-----------------|-----------|-***resume/1***-|-startSpan/2-|-endSpan/2-|-***endTask/1***-|
```

2021-07-28 12:43 UTC, richardstartin commented on dd-java-agent/instrumentation/akka-concurrent/src/test/groovy/AkkaExecutorInstrumentationTest.groovy
>  class AkkaExecutorInstrumentationTest extends AgentTestRunner {
This test does not produce invalid results when I run it.

2021-07-28 12:44 UTC, richardstartin commented on dd-java-agent/instrumentation/akka-concurrent/src/test/groovy/ForkJoinPoolPropagationTest.groovy
> +})
This test also does not report invalid results when I run it

2021-07-28 12:45 UTC, richardstartin commented on dd-java-agent/instrumentation/akka-concurrent/src/test/groovy/RejectedExecutionTest.groovy
> +})
This test does not report invalid results when I run it

2021-07-28 12:46 UTC, richardstartin commented on dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
> +@IgnoreIf({ Boolean.parseBoolean(env.VALIDATE_CHECKPOINTS) })
This test does not report invalid results when I run it

2021-07-28 12:47 UTC, richardstartin commented on dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
> +@IgnoreIf({ Boolean.parseBoolean(env.VALIDATE_CHECKPOINTS) })
ditto

2021-07-28 12:54 UTC, richardstartin commented on dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/ApacheHttpAsyncClientTest.groovy
> +})
This is correct - there are two kinds of errors
1. not suspending after redirects
2. not resuming on failure

2021-07-28 12:57 UTC, richardstartin commented on dd-java-agent/instrumentation/datastax-cassandra-4/src/test/groovy/CassandraClientTest.groovy
> +})
This makes things look worse than they are, there is a single error caused by netty during setting up the client: ```
=== Invalid checkpoint events encountered
resume/1 (thread: s0-admin-0)

=== Activity checkpoints by thread ordered by time
===== Invalid event sequences were detected. Affected spans are highlited by '***'
Test worker: |-startSpan/1-|-suspend/1-|----------|-suspend/1-|-suspend/1-|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|----------|----------|-----------|----------|----------------|-startSpan/2-|-suspend/2-|----------|-----------|-endSpan/2-|-startSpan/3-|-suspend/3-|----------|-----------|-endSpan/3-|-startSpan/4-|-suspend/4-|----------|-----------|-endSpan/4-|-endSpan/1-|-startSpan/5-|-suspend/5-|----------|-----------|-endSpan/5-|
s0-admin-0:  |-------------|-----------|-resume/1-|-----------|-----------|-suspend/1-|----------|-endTask/1-|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|-resume/1-|-endTask/1-|-----------|-resume/1-|-endTask/1-|-----------|-resume/1-|-endTask/1-|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-suspend/1-|-suspend/1-|----------|-----------|-suspend/1-|----------|-----------|-suspend/1-|-----------|----------|-----------|----------|-----------|-suspend/1-|----------|-----------|-suspend/1-|----------|-----------|-suspend/1-|----------|-----------|-----------|-suspend/1-|----------|-----------|-----------|----------|-----------|-suspend/1-|-suspend/1-|-suspend/1-|----------|-----------|-suspend/1-|----------|-----------|-resume/1-|-resume/1-|-endTask/1-|-resume/1-|-***resume/1***-|-------------|-----------|----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|
s0-admin-1:  |-------------|-----------|----------|-----------|-----------|-----------|-resume/1-|-----------|-suspend/1-|----------|-endTask/1-|-----------|-----------|----------|-----------|-suspend/1-|----------|-----------|-suspend/1-|----------|-----------|-suspend/1-|----------|-----------|-suspend/1-|----------|-----------|-----------|-suspend/1-|----------|-----------|----------|-----------|-----------|-----------|-resume/1-|-endTask/1-|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-----------|-resume/1-|-endTask/1-|-----------|-resume/1-|-endTask/1-|-----------|-resume/1-|-suspend/1-|-endTask/1-|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|-----------|----------|-----------|-----------|-resume/1-|-endTask/1-|----------|----------|-----------|----------|----------------|-------------|-----------|----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|
s0-io-0:     |-------------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|-resume/1-|-----------|-suspend/1-|-endTask/1-|-resume/1-|-endTask/1-|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-resume/1-|-endTask/1-|-suspend/1-|-----------|-resume/1-|-endTask/1-|-resume/1-|-endTask/1-|-----------|-----------|----------|-----------|-----------|-resume/1-|-endTask/1-|-----------|-suspend/1-|-resume/1-|-endTask/1-|-resume/1-|-endTask/1-|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|----------|----------|-----------|----------|----------------|-------------|-----------|----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|
s0-io-1:     |-------------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|-resume/1-|-suspend/1-|-endTask/1-|-resume/1-|-endTask/1-|-----------|-----------|-----------|-resume/1-|-endTask/1-|-----------|----------|-----------|----------|----------|-----------|----------|----------------|-------------|-----------|-resume/2-|-endTask/2-|-----------|-------------|-----------|-resume/3-|-endTask/3-|-----------|-------------|-----------|-resume/4-|-endTask/4-|-----------|-----------|-------------|-----------|----------|-----------|-----------|
s1-io-1:     |-------------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|----------|----------|-----------|----------|----------------|-------------|-----------|----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|-------------|-----------|----------|-----------|-----------|-----------|-------------|-----------|-resume/5-|-endTask/5-|-----------|
```

This would be very easy to fix.

2021-07-28 12:58 UTC, richardstartin commented on dd-java-agent/instrumentation/dropwizard/src/test/groovy/DropwizardAsyncTest.groovy
> +})
This is indeed completely broken.

2021-07-28 12:59 UTC, richardstartin commented on dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseAsyncClientTest.groovy
> +})
Couchbase is broken in general, but close to being functional. It should be possible to parse most of the event stream.

2021-07-28 13:00 UTC, richardstartin commented on dd-java-agent/instrumentation/akka-http-10.0/src/latestDepTest/groovy/AkkaHttp102ServerInstrumentationTests.groovy
> +})
These do all seem to be broken - this will require some manual emission of events given the complicated scope handing.

2021-07-28 13:01 UTC, richardstartin commented on dd-java-agent/instrumentation/okhttp-2/src/test/groovy/OkHttp2AsyncTest.groovy
> +})
There is a scope leak here, which can be fixed the way it was done for OkHttp3 recently (easy).

2021-07-28 13:03 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-concurrent/src/test/groovy/ForkJoinPoolPropagationTest.groovy
> +})
This doesn't report invalid sequences of events when I run it several times

2021-07-28 13:04 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-concurrent/src/test/groovy/RejectedExecutionTest.groovy
> +})
Doesn't report invalid sequences of events when I run it repeatedly

2021-07-28 13:05 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-concurrent/src/test/groovy/ScalaExecutorInstrumentationTest.groovy
> +})
Looks like there's a bug in this instrumentation because this shouldn't happen

```
=== Invalid checkpoint events encountered
resume/7 (thread: ForkJoinPool-1-worker-11)

=== Activity checkpoints by thread ordered by time
===== Invalid event sequences were detected. Affected spans are highlited by '***'
Test worker:              |-startSpan/7-|-suspend/7-|-suspend/7-|----------|----------------|-------------|-----------|-endSpan/7-|
ForkJoinPool-1-worker-13: |-------------|-----------|-----------|-resume/7-|----------------|-startSpan/8-|-endSpan/8-|-----------|
ForkJoinPool-1-worker-11: |-------------|-----------|-----------|----------|-***resume/7***-|-------------|-----------|-----------|
```

2021-07-28 13:07 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-concurrent/src/test/groovy/ScalaInstrumentationTest.groovy
> +})
I couldn't get this one to produce invalid events

2021-07-28 13:07 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-concurrent/src/test/scala/ScalaConcurrentTests.scala
> +@IgnoreIf({ Boolean.parseBoolean(env.VALIDATE_CHECKPOINTS) })
This isn't a test class

2021-07-28 13:10 UTC, richardstartin commented on dd-java-agent/instrumentation/spray-1.3/src/test/groovy/SprayServerTest.groovy
> +})
Interleaved spans which suggests an instrumentation bug, probably not worth fixing because this is a very old framework

2021-07-28 13:12 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-jms-3.1/src/test/groovy/SpringSAListenerTest.groovy
> +})
This one is mislabeled by the validation, probably the same bug affecting akka actors:

```
=== Activity checkpoints by thread ordered by time
===== Invalid event sequences were detected. Affected spans are highlited by '***'
Test worker:                                    |-startSpan/1-|-suspend/1-|----------|-----------|----------|-----------|----------|-----------|-endSpan/1-|-----------|-----------------|-----------|----------------|-----------------|-----------------|----------------|-----------------|-----------------|----------------|-----------------|-------------|-----------|
ActiveMQ VMTransport: vm://embedded-broker#3-1: |-------------|-----------|-resume/1-|-suspend/1-|----------|-suspend/1-|----------|-endTask/1-|-----------|-----------|-----------------|-----------|----------------|-----------------|-----------------|----------------|-----------------|-----------------|----------------|-----------------|-------------|-----------|
ActiveMQ BrokerService[embedded-broker] Task-1: |-------------|-----------|----------|-----------|-resume/1-|-----------|----------|-----------|-----------|-----------|-***suspend/1***-|-endTask/1-|----------------|-----------------|-----------------|----------------|-----------------|-----------------|----------------|-----------------|-------------|-----------|
ActiveMQ VMTransport: vm://embedded-broker#2-1: |-------------|-----------|----------|-----------|----------|-----------|-resume/1-|-----------|-----------|-endTask/1-|-----------------|-----------|----------------|-----------------|-----------------|----------------|-----------------|-----------------|----------------|-----------------|-------------|-----------|
ActiveMQ BrokerService[embedded-broker] Task-2: |-------------|-----------|----------|-----------|----------|-----------|----------|-----------|-----------|-----------|-----------------|-----------|-***resume/1***-|-***suspend/1***-|-***endTask/1***-|----------------|-----------------|-----------------|----------------|-----------------|-------------|-----------|
ActiveMQ VMTransport: vm://embedded-broker#0-2: |-------------|-----------|----------|-----------|----------|-----------|----------|-----------|-----------|-----------|-----------------|-----------|----------------|-----------------|-----------------|-***resume/1***-|-***suspend/1***-|-***endTask/1***-|----------------|-----------------|-------------|-----------|
ActiveMQ Session Task-1:                        |-------------|-----------|----------|-----------|----------|-----------|----------|-----------|-----------|-----------|-----------------|-----------|----------------|-----------------|-----------------|----------------|-----------------|-----------------|-***resume/1***-|-***endTask/1***-|-------------|-----------|
container-1:                                    |-------------|-----------|----------|-----------|----------|-----------|----------|-----------|-----------|-----------|-----------------|-----------|----------------|-----------------|-----------------|----------------|-----------------|-----------------|----------------|-----------------|-startSpan/2-|-endSpan/2-|
```

2021-07-28 13:15 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/SingleThreadedSpringWebfluxTest.groovy
> +})
Span interleaving on the same thread, almost certainly attributable to netty, which puts the validity of the spans themselves into question.

2021-07-28 13:16 UTC, richardstartin commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisAPITestBase.groovy
> +})
More same thread span interleaving, same problem as webflux, root cause = netty

2021-07-28 13:32 UTC, luhenry commented on dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/groovy/AkkaActorTest.groovy
> +})
cc @jbachorik

2021-07-28 14:11 UTC, devinsba commented on dd-java-agent/instrumentation/guava-10/src/test/groovy/ListenableFutureTest.groovy
Is that file above `dd-java-agent/instrumentation/guava-10/.attach_pid31645` intentionally added?

2021-07-28 14:11 UTC, devinsba commented on dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/groovy/AkkaActorTest.groovy
> +  Boolean.parseBoolean(env.VALIDATE_CHECKPOINTS) && !Boolean.parseBoolean(env.FORCE_VALIDATE_CHECKPOINTS)
Is it possible to make this logic a method or field so that we can mark it deprecated to give feedback against use?

2021-07-28 14:26 UTC, richardstartin commented
I spot checked a few more of these, the no suspend chronologically after span end rule is quite pervasive, and this is a fundamental feature of the way async propagation works, and I think that should be addressed before this can be merged.

2021-07-28 21:38 UTC, dougqh commented on dd-java-agent/instrumentation/spray-1.3/src/test/groovy/SprayServerTest.groovy
> +})
Yes, agreed

2021-07-28 21:40 UTC, dougqh commented on dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/SingleThreadedSpringWebfluxTest.groovy
> +})
Yes, we're going to start focusing on overhauling netty related things.  We'll start with fixing the server spans first, but we should sort this out soon thereafter.

2021-07-29 00:11 UTC, tylerbenson commented
Converting this to draft till it's ready for review.

2021-07-29 08:29 UTC, luhenry commented
It's ready to merge as-is. We should disable the tests that gets fixed over the next few days as we fix them.

2021-07-29 17:55 UTC, tylerbenson requested changes

2021-07-29 17:55 UTC, tylerbenson commented on dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringTemplateTest.groovy
> +})
This PR seems to disable a huge number of tests just because they fail the checkpoint validation.  Why would we want to do this?

2021-07-29 20:06 UTC, luhenry commented on dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringTemplateTest.groovy
> +})
It's only disabled if you specify the `VALIDATE_CHECKPOINTS` environment variable. The goal is to _add_ a configuration to CI that do define the `VALIDATE_CHECKPOINTS` environment variable to check that any new or known-to-be-working instrumentations do not regress.

2021-07-30 06:10 UTC, richardstartin commented on dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/ApacheHttpAsyncClientTest.groovy
> +})
This is now fixed, so this should be removed if not done so already

2021-07-30 06:12 UTC, richardstartin commented on dd-java-agent/instrumentation/micronaut-http-server-netty-2/src/test/groovy/MicronautTest.groovy
> +})
Should be removed when the validation bug is fixed

2021-07-30 06:14 UTC, richardstartin commented on dd-java-agent/instrumentation/mule-4/src/test/groovy/mule4/MuleForkedTest.groovy
> +})
Should be removed once the validation bug is fixed

2021-07-30 06:15 UTC, richardstartin commented on dd-java-agent/instrumentation/mule-4/src/test/groovy/mule4/MuleHttpServerForkedTest.groovy
> +})
Should be removed once the validation bug is fixed

2021-07-30 06:15 UTC, richardstartin commented on dd-java-agent/instrumentation/rediscala-1.8.0/src/test/groovy/RediscalaClientTest.groovy
> +})
Fixed

2021-07-30 06:15 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-concurrent/src/test/groovy/ScalaExecutorInstrumentationTest.groovy
> +})
Fixed

2021-07-30 06:16 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/src/forkedTest/groovy/Scala210PromiseForkedTests.groovy
> +})
Should be removed once the validation bug is fixed

2021-07-30 06:16 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/src/forkedTest/groovy/Scala210PromiseForkedTests.groovy
> +})
Should be removed once the validation bug is fixed

2021-07-30 06:16 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/src/test/groovy/Scala210PromiseTests.groovy
> +})
Should be removed once the validation bug is fixed (entire file)

2021-07-30 06:16 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/src/forkedTest/groovy/Scala213PromiseForkedTests.groovy
> +})
Should be removed once the validation bug is fixed (entire file)

2021-07-30 06:17 UTC, richardstartin commented on dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/src/test/groovy/Scala213PromiseTests.groovy
> +})
Should be removed once the validation bug is fixed (entire file)

2021-07-30 06:18 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:19 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Maybe add a comment that this is only for timeouts

2021-07-30 06:19 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:20 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:21 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:21 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:23 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Definitely broken

2021-07-30 06:25 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:26 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Timeouts only

2021-07-30 06:26 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:27 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:28 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:28 UTC, richardstartin commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
> +@spock.lang.IgnoreIf({ datadog.trace.agent.test.checkpoints.TimelineValidator.ignoreTest() })
Can't reproduce

2021-07-30 06:31 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-jms-3.1/src/test/groovy/SpringSAListenerTest.groovy
> +})
Validation bug

2021-07-30 06:34 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/SingleThreadedSpringWebfluxTest.groovy
> +})
Out of order closes

2021-07-30 06:36 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/SpringWebfluxTest.groovy
> +})
Out of order closes

2021-07-30 06:36 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/SingleThreadedSpringWebfluxTest.groovy
> +})
OOO closes

2021-07-30 06:36 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/SpringWebfluxTest.groovy
> +})
OOO closes

2021-07-30 06:37 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBasicTest.groovy
> +})
OOO closes

2021-07-30 06:37 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBuilderReuseTest.groovy
> +})
OOO closes

2021-07-30 06:37 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientDoAfterTerminateTest.groovy
> +})
OOO closes

2021-07-30 06:38 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientDoOnSuccessOrErrorTest.groovy
> +})
OOO closes

2021-07-30 06:38 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientDoOnSuccessTest.groovy
> +})
OOO closes

2021-07-30 06:38 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientDoOnTerminateTest.groovy
> +})
OOO closes

2021-07-30 06:38 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientFilterBuilderReuseTest.groovy
> +})
OOO closes

2021-07-30 06:38 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientFilterTest.groovy
> +})
OOO closes

2021-07-30 06:38 UTC, richardstartin commented on dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientFiltersRemovedTest.groovy
> +})
OOO closes

2021-07-30 06:40 UTC, richardstartin commented on dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
> +})
Can't reproduce

2021-07-30 06:41 UTC, richardstartin commented on dd-java-agent/instrumentation/elasticsearch/transport-7.3/src/test/groovy/Elasticsearch73TransportClientTest.groovy
> +})
Can't reproduce

2021-07-30 06:43 UTC, richardstartin commented on dd-java-agent/instrumentation/dropwizard/src/test/groovy/DropwizardTest.groovy
> +})
OOO closes

2021-07-30 06:43 UTC, richardstartin commented on dd-java-agent/instrumentation/dropwizard/src/test/groovy/DropwizardAsyncTest.groovy
> +})
OOO closes

2021-07-30 06:45 UTC, richardstartin commented on dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyFilterchainServerTest.groovy
> +})
OOO closes

2021-07-30 06:46 UTC, richardstartin commented on dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyAsyncTest.groovy
> +})
OOO closes

2021-07-30 06:46 UTC, richardstartin commented on dd-java-agent/instrumentation/guava-10/src/test/groovy/ListenableFutureTest.groovy
> +})
Validation bug

2021-07-30 06:47 UTC, richardstartin commented on dd-java-agent/instrumentation/jetty-client-9.1/src/test/groovy/JettyClientTest.groovy
> +})
Fixed

2021-07-30 06:47 UTC, richardstartin commented on dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy
> +})
Validation bug

2021-07-30 06:49 UTC, richardstartin commented on dd-java-agent/instrumentation/grizzly-2/src/test/groovy/GrizzlyAsyncTest.groovy
> +})
OOO closes

2021-07-30 06:50 UTC, richardstartin commented on dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/ApacheHttpAsyncClientTest.groovy
> +})
Fixed

2021-07-30 06:50 UTC, richardstartin commented on dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/ApacheHttpAsyncClientNullCallbackTest.groovy
> +})
Fixed

2021-07-30 06:50 UTC, richardstartin commented on dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/ApacheHttpAsyncClientCallbackTest.groovy
> +})
Fixed

2021-07-30 06:50 UTC, richardstartin commented on dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/groovy/AkkaActorTest.groovy
> +})
Validation bug

2021-07-30 07:34 UTC, luhenry commented
I updated the PR to use `CheckpointValidator.excludeAllValidations()` in all places. I'll now go over each of them and refine the excluded validations.

2021-07-30 14:29 UTC, luhenry commented
> Need to remove the trailing `/` from `dd-java-agent/instrumentation/` - otherwise the gradle tasks are rendered with `::` which makes gradle very unhappy :(
> 
> Also, do you think you could extract this script to this project root dir so running the check would be just the matter of executing the script?

Let me update this comment as with https://github.com/DataDog/dd-trace-java/pull/2962/files#diff-665e0998b12c1cecaf05e11ccd4f0784c37c1c7c4db53b8d857a3e2314d7be57R55-R58 it's a lot easier to see which mode can be re-enabled.

2021-07-30 14:34 UTC, luhenry commented
@tylerbenson the `VALIDATE_CHECKPOINTS` env variable has been removed and checkpoint sequence validator runs on every tests without disabling them.

2021-07-30 14:36 UTC, jbachorik approved these changes
LGTM

2021-07-30 14:44 UTC, devinsba approved these changes
LGTM as long as we are OK marking the method/class deprecated

2021-07-30 14:44 UTC, devinsba commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +  static void excludeValidations(CheckpointValidationMode... modes) {
Can we mark this deprecated since we don't want people adding this anywhere that it isn't currently?

2021-07-30 14:47 UTC, jbachorik commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +  static void excludeValidations(CheckpointValidationMode... modes) {
If that helps ... 
`Config` has been deprecated for a while and it is happily being used and extended :)

2021-07-30 14:49 UTC, dougqh commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +  static void excludeValidations(CheckpointValidationMode... modes) {
The difference is that Config is published API; checkpoint validation is not.

2021-07-30 14:50 UTC, devinsba commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +  static void excludeValidations(CheckpointValidationMode... modes) {
Good point, I guess since PR review wouldn't show it that wouldn't help a review catch it either. Maybe we should change the method to be more antagonistic. Like `thisTestShowsBuggyAsyncBehavior` or something that makes it obvious to a reviewer

2021-07-30 15:01 UTC, jbachorik commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +  static void excludeValidations(CheckpointValidationMode... modes) {
Yes. That was my point - having the annotation there does not draw the required attention during the review and the author would probably just ignore the deprecation anyway.
Ideally, there would be a kind of signature check where eg. each project would have 'last-known' exclusions but that would be too much work for a little benefit.

So, changing the name to something like @devinsba suggested or just have it in all caps like `EXCLUDEVALIDATIONS` should help to get the desire attention during review.

2021-07-30 15:09 UTC, luhenry commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +  static void excludeValidations(CheckpointValidationMode... modes) {
I renamed it to `DONOTUSE_excludeValidations_DONOTUSE`

2021-08-11 09:32 UTC, jbachorik commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidationMode.groovy
> +  THREAD_SEQUENCE,
A nit: Can you split the doc here so we have each mode properly documented?

2021-08-11 09:33 UTC, jbachorik approved these changes

2021-08-11 11:10 UTC, merged