WIP
DataDog/dd-trace-java pull request #2968
Opened 2021-07-28 18:16 UTC by jbachorik

2021-07-29 13:07 UTC, luhenry approved these changes
The idea would be to update https://github.com/DataDog/dd-trace-java/pull/2962 to use `CheckpointValidator.excludeValidations` in place of `IgnoreIf`?

2021-07-29 15:37 UTC, jbachorik commented
> The idea would be to update #2962 to use CheckpointValidator.excludeValidations in place of IgnoreIf?

Yes. Where it would make sense.

2021-07-29 17:37 UTC, richardstartin approved these changes

2021-07-30 05:47 UTC, richardstartin commented
@jbachorik does this contain a fix for the no suspend chronologically after a span end rule? That one is invalidating 5-10 instrumentations and this is a basic consequence of how async propagation works, so needs to be accepted.

2021-07-30 08:46 UTC, luhenry requested changes

2021-07-30 08:46 UTC, luhenry commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +          invalidEvents.add([event, CheckpointValidationMode.THREAD_SANITY])
Typo:
```suggestion
          invalidEvents.add([event, CheckpointValidationMode.THREAD_SEQUENCE])
```

2021-07-30 09:27 UTC, luhenry commented
> @jbachorik does this contain a fix for the no suspend chronologically after a span end rule? That one is invalidating 5-10 instrumentations and this is a basic consequence of how async propagation works, so needs to be accepted.

If there is any work needed there, please let me update https://github.com/DataDog/dd-trace-java/pull/2962 first, it's getting increasingly frustrating to go through the 90+ test classes manually that are needs to be annotated differently.

2021-07-30 10:32 UTC, luhenry approved these changes

2021-07-30 10:46 UTC, luhenry requested changes

2021-07-30 10:46 UTC, luhenry commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +        if (!excludedValidations.contains(CheckpointValidationMode.SEQUENCE)) {
Duplicate.

2021-07-30 11:19 UTC, luhenry commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +        if (!suspendResumeValidator.onEvent(event)) {
I would have `if (!suspendResumeValidator.onEvent(event) || !threadSequenceValidator.onEvent(event))` to avoid adding duplicate events.

2021-07-30 11:31 UTC, jbachorik commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +        if (!suspendResumeValidator.onEvent(event)) {
`invalidEvents` is a set so they will be deduplicated

2021-07-30 11:32 UTC, jbachorik commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
> +        if (!suspendResumeValidator.onEvent(event)) {
But yes, could be simplified now that we don't use different validation modes checks.

2021-07-30 11:45 UTC, luhenry approved these changes

2021-07-30 12:57 UTC, merged