API design for suppressing spans from being created for a scope.
DataDog/dd-trace-java pull request #3001
Opened 2021-08-12 19:48 UTC by tylerbenson

Actual implementation of span suppression to follow in separate PR.

2021-08-13 09:02 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  public SuppressScope suppress(final CharSequence spanName) {
Would the use case of suppressing multiple spans in one `SupressScope` be valid?

2021-08-13 14:24 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  public SuppressScope suppress(final CharSequence spanName) {
Are you suggesting maybe use a var-arg instead/in addition to?

2021-08-13 14:32 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
> +    SuppressScope suppress(CharSequence spanName);
I don't particularly want to create another object for this.  I think we actually should get away from creating objects for Scopes as well.

2021-08-13 14:34 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    boolean added = SPAN_SUPPRESSION.get().add(spanName);
I don't believe CharSequence supports a meaningful hashCode.  To put it in a HashSet, you probably have to String.valueOf.

2021-08-13 14:34 UTC, tylerbenson commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
> +    SuppressScope suppress(CharSequence spanName);
This allows for the try-with-resources style call and simplified cleanup.  You would rather have it return a boolean?

2021-08-13 14:36 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  public SuppressScope suppress(final CharSequence spanName) {
No suggestion - just figuring out the use case.

2021-08-13 14:36 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  private static final ThreadLocal<Set<CharSequence>> SPAN_SUPPRESSION =
I'm not sure Tracer is the right place for this.

Given that is contextual, I think this should be placed closer to the other scope management.

2021-08-13 14:37 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +      return new SuppressScope() {
I think it would be fine to just let the caller do unsuppress(name).  We don't need an extra object for this.

2021-08-13 14:39 UTC, dougqh commented on dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
> +    def span = tracer.buildSpan("suppressedSpan").start()
We'll need a lot more testing here.

We need to show how suppression interacts with...
- activation
- child span creation
- baggage

2021-08-13 14:51 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
> +    SuppressScope suppress(CharSequence spanName);
Yes, I know it supports try-with-resources clean-up, but that adds significant overhead that we don't need.  We also don't need a boolean.

All we need is...
TraceContext.suppress(operationName);
try {
  ...
} finally {
  TracerContext.unsuppress(operationName);
}

2021-08-13 15:01 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +          return new HashSet<>();
This is probably oversized for this use case.  I honestly wonder if we should use a flat sized set until we reach some limit.

2021-08-13 15:15 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  public SuppressScope suppress(final CharSequence spanName) {
There are a couple use cases, we're playing with addressing.

In one situation, we get _extra_ spans because of iterating over message objects multiple times.
This can happen Kafka Streams for complex queries.
This can happen with Spring when iterates over the collection once before then handing it to the Kafka listener.

In those situations, we want to suppress the spans from those initial iterations for the complex cases.  But in the simpler cases, where the object is iterated just once we want the spans.

I think we'll have to hook this mechanism up to one of those cases before we know if this is really the right solution.

The other case that we're thinking about is nested server spans or nested client spans.  The client case is easier to understand, so I'll use it as the example.

If you consider, jms on top of sqs on top of http.  The end user typically only needs to see layer with which they are interacting.  In this example, jms.

2021-08-13 15:22 UTC, dougqh reviewed
I'm quite convinced we need span suppression, but I less convinced of the driving mechanism.  And I think we'll only know that when we try in the context of one of our problems.

I think we might be more successful separating out the span portion -- which I think should be less controversial.

My thinking is that we just add a suppress() method onto SpanBuilder and then work through the details of activation, child creation, baggage, and context propagation.

2021-08-13 15:40 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    boolean added = SPAN_SUPPRESSION.get().add(spanName);
Our implementation of `UTF8BytesString` does.  Since this is intended as an internal API, perhaps I should use that type specifically instead?

2021-08-13 16:08 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +      return new SuppressScope() {
done.

2021-08-13 16:09 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +          return new HashSet<>();
I set it to size 4 for now to account for the load factor.

2021-08-13 16:09 UTC, tylerbenson commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
> +    SuppressScope suppress(CharSequence spanName);
done.

2021-08-13 16:10 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    boolean added = SPAN_SUPPRESSION.get().add(spanName);
I switched to `UTF8BytesString` specifically. We can relax that in the future if needed.

2021-08-13 16:53 UTC, tylerbenson commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  private static final ThreadLocal<Set<CharSequence>> SPAN_SUPPRESSION =
I put it in here because it will also need to be referenced by the SpanBuilder for the suppression.

2021-08-16 19:32 UTC, dougqh requested changes
This looks more efficient than the previous version, but I still think we need a demonstration of usefulness before we merge this.

2021-08-19 18:49 UTC, tylerbenson commented
Closing for now as I think we have a better work around.

2021-08-19 18:49 UTC, closed without merging