[AppSec] Added smoke test to validate WAF
DataDog/dd-trace-java pull request #3010
Opened 2021-08-17 15:35 UTC by ValentinZakharov

2021-08-17 18:14 UTC, devinsba reviewed
I'm interested in opinions from others on the spring-boot version.

As far as a smoke test goes, at some point it would probably be good to have an app that includes spring-security to ensure there aren't interoperability issues

2021-08-17 18:14 UTC, devinsba commented on dd-smoke-tests/appsec/springboot/springboot.gradle
> +  implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '1.5.18.RELEASE'
This is a really old version of spring-boot, can we at least bump up into the 2.x line of releases? I don't have data on what versions our customers use but a lot of the customer issues recently have at least been 2.x

2021-08-18 09:13 UTC, bantonsson commented on dd-smoke-tests/appsec/springboot/springboot.gradle
> +  implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '1.5.18.RELEASE'
Yes, everything below `2.3.x` is considered EOL by Spring.

2021-11-29 09:35 UTC, bantonsson requested changes
Looks good. Only minor things.

2021-11-29 09:35 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/ReportStrategy.java
> +        Config.get().getAppSecReportMaxTimeout() * 1000L * 1000L * 1000L;
Could switch this to `TimeUnit.SECONDS.toNanos(...)`?

2021-11-29 09:35 UTC, bantonsson commented on dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
> +  public static final int TIMEOUT_SECS = 30
The comment makes no sense to me, since it's the total time it would take from the request is **done** to the AppSec attack has been reported.

2021-11-29 09:35 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +    appSecReportMaxTimeout = configProvider.getInteger(APPSEC_REPORT_TIMEOUT_SEC, 30);
Comment says 60, but code says 30

2021-11-29 23:19 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/ReportStrategy.java
> +        Config.get().getAppSecReportMaxTimeout() * 1000L * 1000L * 1000L;
Switched

2021-11-29 23:20 UTC, ValentinZakharov commented on dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
> +  public static final int TIMEOUT_SECS = 30
Ah, I'm sorry, blind copy-paste. Removed redundant code.

2021-11-29 23:20 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +    appSecReportMaxTimeout = configProvider.getInteger(APPSEC_REPORT_TIMEOUT_SEC, 30);
Old comment - fixed.

2021-11-30 07:22 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +    appSecReportMaxTimeout = configProvider.getInteger(APPSEC_REPORT_TIMEOUT_SEC, 30);
Well, the comment might be old, but the tests seem to think that it should be 60 seconds since this fails `subsequent event of same type should wait 1 min`

2021-11-30 07:25 UTC, bantonsson approved these changes

2021-11-30 21:27 UTC, merged