Complete appsec Attack report
DataDog/dd-trace-java pull request #3023
Opened 2021-08-20 16:07 UTC by cataphract

2021-08-23 13:30 UTC, bantonsson requested changes
I think sending the whole `AgentSpan` exposes too many things.

2021-08-30 05:56 UTC, bantonsson commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +          cbp.getCallback(Events.REQUEST_ENDED);
@cataphract That will do for now. The issue is also pulling out the map of tags, which will create a copy every time, but that can be optimized later.

2021-08-30 05:57 UTC, bantonsson approved these changes

2021-08-30 05:58 UTC, bantonsson commented
The failing tests are due to a broken merge on `master`. Rebase and it should be gone.

2021-08-30 14:07 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +    if (cbp == null) {
Should we also check if `span` is not null?

2021-08-30 16:12 UTC, cataphract commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +    if (cbp == null) {
It's supposed tot be guaranteed non-null, as the annotation `@NonNull` indicates. If you check the caller, you see that `span` must be non-null for the code to even reach this place.

2021-08-30 21:49 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +    String method = null;
I'm sorry, I don't really understand, why did you move `method` declaration and null assignment outside the `if` block as it was initially?

2021-08-30 21:58 UTC, cataphract commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +    String method = null;
I guess an artifact of an earlier change I walked back from. I'll change it back.

2021-08-30 22:09 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/gateway/IGSpanInfo.java
> +public interface IGSpanInfo {
I'm sorry, I don't get why did you decide to use separated interface? It seems, we can use `AgentSpan` directly to get same functionallity.

2021-08-30 22:19 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +  private static void callIGCallbackURI(
Here we use two callbacks in order, for `URI` and `METHOD`. May be it make sense to commit everything with some single callback to reduce amount of IG calls?
Unless you foresee the need for a separate commit for other web servers in the future.

2021-08-30 22:28 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +          cbp.getCallback(Events.REQUEST_ENDED);
@bantonsson I got your point, but still don't like idea populate interfaces. If we follow this way, we may need (in future) add more extra interfaces for another specific cases.
May be it makes sense to have some read-only interface for all available fields (ex: ImmutableSpan) with getters only. WDYT?

2021-08-31 09:55 UTC, bantonsson commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +          cbp.getCallback(Events.REQUEST_ENDED);
@ValentinZakharov I think that is exactly what this interface is, only that we don't expose all the things prematurely.

2021-08-31 13:53 UTC, cataphract commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +  private static void callIGCallbackURI(
I've merged them together.

2021-08-31 19:41 UTC, ValentinZakharov approved these changes

2021-09-01 16:47 UTC, merged