Dump information when a profile fails to upload because it's too big
DataDog/dd-trace-java pull request #3046
Opened 2021-08-30 08:55 UTC by luhenry

When receiving a 413 error code, we only know that the profile is too
big to be accepted by the backend. However, we have no idea why the
profile is too big.

With this change, we try to extract information about the size of the
events and log it to the command line. This allows us to ask customers
for more informations, and react accordingly. For example, if the
profile is too big due to too many exceptions being thrown and
overloading the profile, we can advise the customer to disable the
Exception profiler.

2021-08-30 09:30 UTC, jbachorik requested changes

2021-08-30 09:30 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
> +                    JfrCliHelper.invokeOn(data, ioLogger);
Should this be executed on a dedicated worker thread not to block the http client response?

2021-08-30 09:30 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +    System.err.println("Hello World (1)");
These should be perhaps gone :)

2021-08-30 09:30 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +        process.waitFor();
Should there be a timeout here - just in case so a broken profile or binary image of 'jfr' does not block the profiler uploader?

2021-08-30 09:30 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +        if (line.matches("^=+$")) {
Might be worth it to pre-compile the pattern - otherwise it will be re-compiled for each line.

2021-08-30 09:30 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +        String[] columns = line.trim().split("\\s+", 3);
Probably also a candidate for pre-compiled regex.

2021-08-30 09:30 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/util/JfrCliHelperTest.java
> +      verify(ioLogger).error(eq("Failed to gather information on recording, can't find `jfr`"));
OpenJDK 8 with JFR is containing the `jfr` tool - only Oracle JDK 8 is missing that.

2021-08-30 11:13 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
> +                    JfrCliHelper.invokeOn(data, ioLogger);
It's already executing in an Executor. See https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java#L205-L212

2021-08-30 11:50 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
> +                    JfrCliHelper.invokeOn(data, ioLogger);
🆗

2021-08-30 11:54 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +    new AgentThreadFactory(PROFILER_HTTP_DISPATCHER));
Sorry for the per-partes review.
I think that `AgentTaskScheduler` is the preferred to a generic `ExecutorService` - which can be instrumented by the tracer and it is not really desirable.

2021-08-30 11:55 UTC, jbachorik approved these changes

2021-08-30 13:11 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +    new AgentThreadFactory(PROFILER_HTTP_DISPATCHER));
Right now, the `AgentTaskScheduler` doesn't really support waiting the underlying item of work or catching an exception in the underlying work item. I tried workarounds with CountDownLatch and storing the exception but to no avail.

2021-08-30 13:12 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +    new AgentThreadFactory(PROFILER_HTTP_DISPATCHER));
The `ThreadPoolExecutor` is also what's used in the `ProfileUploader`, so any issue with it would also show up there.

2021-08-31 11:26 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +    new AgentThreadFactory(PROFILER_HTTP_DISPATCHER));
Right. Makes sense.

2021-09-10 09:03 UTC, bantonsson approved these changes

2021-09-10 09:04 UTC, mcculls commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +      tmp.deleteOnExit();
what about long running server applications?  how about using a `finally` block to remove the `tmp` file after we've streamed the result output from the command?

2021-09-10 09:12 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +      tmp.deleteOnExit();
Let me add that.

2021-09-10 09:41 UTC, mcculls commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +      Path jfr = Paths.get(System.getProperty("java.home"), "bin", "jfr");
is there a reason we need to call an external command and scrape it's output vs. just calling `jdk.jfr.consumer.RecordingFile` ? I believe that's what the tool is using to parse the recording.

2021-09-10 09:44 UTC, mcculls commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +        stdout = lineSeparatorRegex.split(out.toString());
Do we know how big this output is going to be? Is there a danger we could blow the application's heap just trying to find out why the recording was so large?

2021-09-10 09:46 UTC, mcculls requested changes
I'm not 100% sold on this solution of forking an external process and parsing its output, so I'd prefer if this isn't merged for now

2021-09-10 10:58 UTC, luhenry commented
There is no way to do that with the `RecordingFile` API since we can't get the size of an Event. And I'm not a fan of having to invoke into internal APIs when we have this alternative.

2021-09-10 11:02 UTC, mcculls commented
I'd be ok with just reporting that the profile recording was too large (maybe include the size of the recording) for now while we look into alternatives

2021-09-10 11:03 UTC, luhenry commented
>I'd be ok with just reporting that the profile recording was too large (maybe include the size of the recording) for now while we look into alternatives

I'm not ok with just reporting it's too large. We have no information that would allow us to help customers through escalations when they regularly hit the profile size limit, and this is what this change is trying to address.

2021-09-10 11:22 UTC, mcculls commented
I'd also be ok with putting the process part under a feature flag that defaults to off, so it can be enabled for debugging purposes.

2021-09-10 12:01 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +      Path jfr = Paths.get(System.getProperty("java.home"), "bin", "jfr");
You cannot get the size of an Event through `jdk.jfr.consumer.RecordingFile`.

2021-09-10 12:09 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
> +        stdout = lineSeparatorRegex.split(out.toString());
The classes you would need to use are private implementations - while it would be easy to use them in Java 8 it would become more complicated in the modular world where we would need either ask the user to add opens or do that in our agent. Unfortunately, doing it in the agent would require either using reflection to invoke the `redefineModule` method or having one agent for Java 8 and one for Java 9+

2021-09-10 12:19 UTC, luhenry commented
I've added the `profiling.upload.summary-on-413` config flag to control whether that feature is enabled. I'll update the documentation in [Profiler Troubleshooting](https://docs.datadoghq.com/tracing/profiler/profiler_troubleshooting/).

2021-09-10 12:20 UTC, mcculls approved these changes
thanks for adding the feature-flag

2021-09-10 14:03 UTC, merged