Fix scope activation in vertx-redis client
DataDog/dd-trace-java pull request #3077
Opened 2021-09-17 15:38 UTC by jbachorik

2021-09-23 14:23 UTC, luhenry commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +    AgentTracer.activeScope().close();
Should we store the scope in a "local" variable?

2021-09-23 14:25 UTC, luhenry requested changes

2021-09-23 14:25 UTC, luhenry commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisAPITestBase.groovy
> +    //    CheckpointValidator.excludeValidations_DONOTUSE_I_REPEAT_DO_NOT_USE(
Remove

2021-09-23 14:30 UTC, jbachorik commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +    AgentTracer.activeScope().close();
Yeah. I thought about that but that would have required wrapping the scope and the boolean state into a new object. So, I went for less allocations ...
But definitely can be changed if the allocations are acceptable and we want more safety (eg. not closing some stray scope by chance).

2021-09-23 14:44 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +    AgentTracer.activeScope().close();
I think you can use https://javadoc.io/doc/net.bytebuddy/byte-buddy/1.10.4/net/bytebuddy/asm/Advice.Local.html to declare the scope variable

2021-09-23 16:57 UTC, jbachorik commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +    AgentTracer.activeScope().close();
done

2021-09-23 16:57 UTC, jbachorik commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisAPITestBase.groovy
> +    //    CheckpointValidator.excludeValidations_DONOTUSE_I_REPEAT_DO_NOT_USE(
gone

2021-09-24 07:45 UTC, luhenry approved these changes

2021-09-24 14:22 UTC, devinsba approved these changes

2021-09-24 14:24 UTC, merged