[WIP][CIAPP] CI Visibility Mode v1
DataDog/dd-trace-java pull request #3114
Opened 2021-10-05 13:53 UTC by drodriguezhdez

This PR is a refactor to the CI App implementation into a new CI Visibility Mode.

This mode includes:

* Custom initialization entrypoint. (TBD)
* Custom `CITracer` implementation that sets new sampler and agentwriter instances
* Custom `CIAgentWriter` to do transformations and filtering before sending the payload to accomplish CI Visibility requirements. (TBD)
* Testing framework integrations are now only enabled when running in CI Visibility mode (TBD)

2021-10-05 17:09 UTC, dougqh commented on dd-trace-core/ci-visibility/src/main/java/datadog/trace/ci/writer/CIWriter.java
> +package datadog.trace.ci.writer;
I don't like the use of inheritance.  I think this is better handled through configuration & composition.

2021-10-05 17:09 UTC, dougqh commented on dd-trace-core/ci-visibility/src/main/java/datadog/trace/ci/writer/CIAgentWriter.java
> +public class CIAgentWriter implements CIWriter {
I don't like the use of inheritance. I think this is better handled through configuration & composition.

2021-10-05 17:13 UTC, dougqh commented on dd-trace-core/ci-visibility/src/main/java/datadog/trace/ci/metrics/CIStatsDClientFactory.java
> +    if (!config.isHealthMetricsEnabled()) {
It looks like we're repeating code from elsewhere in the tracer.  Why?

2021-10-05 17:14 UTC, dougqh commented on dd-trace-core/ci-visibility/src/main/java/datadog/trace/ci/CITracerFactory.java
> +      final Config config, SharedCommunicationObjects commObjects) {
I don't think many parallel objects are necessary.  Just configuration and a different composition of supporting objects for the Tracer.

2021-10-05 17:14 UTC, dougqh commented on dd-trace-core/ci-visibility/src/main/java/datadog/trace/ci/CITracer.java
> +
I don't want completely different Tracer for CI.

2021-10-05 17:16 UTC, dougqh requested changes
I think this change set is headed in the wrong direction.
I don't want to create a whole set of parallel classes for CI.

To the best of my knowledge, CI only needs a slightly differently configured sending pipeline.  That can be accomplished through configuration objects and strategy composition.

2021-11-11 16:19 UTC, drodriguezhdez commented
https://github.com/DataDog/dd-trace-java/pull/3196

2021-11-11 16:19 UTC, closed without merging