Feature/add db split by instance type suffix
DataDog/dd-trace-java pull request #3174
Opened 2021-11-01 13:00 UTC by mohammedalics

### Problem

#### Given: 
- `DB_CLIENT_HOST_SPLIT_BY_INSTANCE` is set to `true` and
-  The database name is the same as the service name (for example `jdbc:postgresql://db.example.com:5432/myservice` gives database name `myservice`)

#### Expected: 
Two services with the same name `myservice` but different types. one of type web and another of type db. 

#### Actual:
Found only one service with name `myservice` of type web (and no database service). All database traces are mapped to the web service. 

#### Proposed fix:
Introduce a new boolean variable `DB_CLIENT_HOST_SPLIT_BY_INSTANCE_TYPE_SUFFIX` to control adding the database type as a suffix to the database service name in case of `DB_CLIENT_HOST_SPLIT_BY_INSTANCE` sets to `true`. For instance `myservice_postgresql`

2021-11-01 13:19 UTC, devinsba requested changes

2021-11-01 13:19 UTC, devinsba commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +                ? instanceName + "_" + dbType()
```suggestion
                ? instanceName + "-" + dbType()
```

Please update to a hyphen

2021-11-02 11:05 UTC, bantonsson approved these changes

2021-11-02 11:05 UTC, bantonsson commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +                : instanceName);
I'm fine with this as long as we're aware that there is no caching for this, while for example the `JDBCDecorator` caches the `instanceName` to avoid recreating the strings.

2021-11-02 13:51 UTC, devinsba commented
We'd like to add some tests before merging. I can take a look this afternoon, unless you have time to add a couple before I get to it

2021-11-03 14:24 UTC, devinsba commented
@mohammedalics can you enable modifications from maintainers: 
![image](https://user-images.githubusercontent.com/139938/140078668-92838317-2e6f-4637-bd52-04a93ec2e7b2.png)

2021-11-03 15:54 UTC, devinsba commented
Thanks @mohammedalics

2021-11-03 15:55 UTC, merged

2021-11-08 14:09 UTC, mohammedalics commented
@devinsba Do you have an idea when this change will be released?

2021-11-08 15:17 UTC, devinsba commented
Looks like there will be a release over the next couple days assuming we don't run into any roadblocks. Keep an eye out for 0.90.0