Try using perf before itimer for CPU sampling in async-profiler
DataDog/dd-trace-java pull request #3195
Opened 2021-11-11 11:04 UTC by luhenry

2021-11-11 11:32 UTC, jbachorik submitted a review, later dismissed

2021-11-11 14:53 UTC, devinsba approved these changes

2021-11-11 14:53 UTC, devinsba commented on dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
> +      cmd.append(",event=cpu,interval=").append(getCpuInterval());
I noticed the `.append('b')` and m were removed in this change, just wanted to make sure that's intentional

2021-11-11 14:58 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
> +      cmd.append(",event=cpu,interval=").append(getCpuInterval());
Oh, good catch. We need those postfixes such that we don't have to write unit conversion routines.
It is easier to have everything in bytes('b') and milliseconds('m').

2021-11-11 14:59 UTC, jbachorik requested changes
Please, add back the unit postfixes.

2021-11-11 17:31 UTC, jbachorik approved these changes

2021-11-11 17:54 UTC, jbachorik commented on dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
> +  public static final String PROFILING_ASYNC_CPU_MODE_DEFAULT = "itimer";
This is inconsistent with the comment at https://github.com/DataDog/dd-trace-java/pull/3195/files#diff-49635e629af4a1c72f11d4e54984a895cf058f1bd535193e3d0433c7b394330dR252

Is the 'cpu' profiling mode not working?

2021-11-12 08:06 UTC, luhenry commented on dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
> +  public static final String PROFILING_ASYNC_CPU_MODE_DEFAULT = "itimer";
Test suite is passing locally with `cpu` (aka perf with fallback to itimer), but rather than shipping a version of dd-trace-java which may potentially be broken, I rather add a config knob that we can easily set in staging for dogfooding. And once the tradeoff is better understood, we can switch the default.

2021-11-12 08:06 UTC, luhenry commented on dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
> +  public static final String PROFILING_ASYNC_CPU_MODE_DEFAULT = "itimer";
And I've fixed the comment at https://github.com/DataDog/dd-trace-java/pull/3195/files#diff-49635e629af4a1c72f11d4e54984a895cf058f1bd535193e3d0433c7b394330dR252

2021-11-12 12:27 UTC, merged