[AppSec] Fixed tags reported by AppSec
DataDog/dd-trace-java pull request #3216
Opened 2021-11-19 15:41 UTC by ValentinZakharov

2021-11-19 16:28 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +  private static Set<String> getEnvTags() {
I find it weird that this is not available in the `Config` and if it isn't, then maybe it should be?

2021-11-19 17:23 UTC, cataphract reviewed
@ValentinZakharov Is the problem here that `Config.getGlobalTags()` has too much stuff and `spanInfo.getTags() even more? It would indeed seem that the better course of action would be to add that to `Config`,  otherwise sources of configuration other than environment variables will not be used. Also, it's strange to have this `IGSpanInfo` with a `getTags` that is never used by appsec.

2021-11-23 13:31 UTC, bantonsson requested changes
I'm still not sure what you are trying to fix. Maybe a description in the PR of what is wrong and what is expected would help.

2021-11-23 13:31 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +      tags.putAll(parseStringIntoMapOfNonEmptyStrings(System.getenv(propertyNameToEnvironmentVariableName(TAGS))));
I don't see why you would need to do this? The line above already goes through the `env` and `properties`

2021-11-23 15:04 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +      tags.putAll(parseStringIntoMapOfNonEmptyStrings(System.getenv(propertyNameToEnvironmentVariableName(TAGS))));
Fixed.
I was wrong with expected format of `DD_TAGS`.

2021-11-24 06:39 UTC, bantonsson commented
@ValentinZakharov I can see what you are doing here, but I still don't know why you are doing the change. What is is that AppSec expects? A user could use the tracing API (ot or dd) to override a global tag in a span, and what would you expect to have in that field then?

2021-11-24 09:50 UTC, ValentinZakharov commented
I additionally clarified with the collect engineer. The AppSec Events don't care about any overrides in the span. The goal is to propagate the tags manually configured by customer using `DD_TAGS` env variable.

2021-11-24 10:04 UTC, bantonsson approved these changes

2021-11-24 10:05 UTC, merged