WIP - Inform JMXFetch of service names to support multi-service
DataDog/dd-trace-java pull request #3236
Opened 2021-12-03 19:45 UTC by devinsba

2021-12-03 19:45 UTC, devinsba commented on dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
> +  api('com.datadoghq:jmxfetch:0.44.3') {
Waiting on this to release

2021-12-07 21:08 UTC, devinsba commented on dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java
> +  private final ReentrantReadWriteLock.WriteLock writeLock = readWriteLock.writeLock();
Instead of managing all the locking I could use `Collections.synchronizedMap` but I don't think that would really change the performance at all

2021-12-07 21:10 UTC, devinsba commented on dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java
> +    return Integer.MAX_VALUE;
When we have a chance to change this API we should change the range of values that users can use to allow us to jump first or last in line

2021-12-08 09:38 UTC, mcculls commented on dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java
> +  private static final Set<String> IGNORED_ENTRY_SPAN_TYPES =
Would it be better to list the span types that we want to collect service names from? That would be a smaller list and would be less likely to accidentally cause performance issues when a new span type is added.

2021-12-08 09:56 UTC, mcculls commented on dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java
> +    implements TraceInterceptor, ServiceNameProvider {
Another option to using a `TraceInterceptor` would be to do this in the decorator - you could either put the logic in the `BaseDecorator` or in a more specific decorator and capture the service name in something like `afterStart` or `beforeFinish`. This would also let you be more specific about which instrumentations and/or span types capture the service name.

2021-12-08 10:03 UTC, bantonsson commented on dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java
> +      return Arrays.asList(serviceNames.keySet().toArray(new String[0]));
I have a hard time figuring out how often `getServiceNames()` will be called, but it looks like it will at least be called once for every JMX attribute (is this once per _fetch_ as well?). How often do we expect the `serviceNames` map to be updated, as in a new thing is added, and would it make more sense to just do some more checks on the write side, and have a `CopyOnWriteArrayList` or something similar for the returned list?

2021-12-08 14:25 UTC, devinsba commented on dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java
> +      return Arrays.asList(serviceNames.keySet().toArray(new String[0]));
Reads are done, once per attribute per bean refresh. So by default once per attribute per 10 minutes

2021-12-08 14:27 UTC, devinsba commented on dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java
> +    implements TraceInterceptor, ServiceNameProvider {
beforeFinish could probably work. Because of things like split-by-tag though this would have to happen late in the span lifecycle

2021-12-10 11:04 UTC, bantonsson commented on dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java
> +  private final int serviceNamesSize = 0;
This should not be a `final`, but a `volatile` or the reads could be constant propagated, and avoided.

2021-12-10 11:06 UTC, bantonsson requested changes
Looks god apart from the `final` field.

2021-12-10 12:45 UTC, devinsba commented on dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java
> +  private final int serviceNamesSize = 0;
Thanks for catching that

2021-12-10 12:47 UTC, bantonsson approved these changes

2022-01-06 21:25 UTC, ygree approved these changes
LGTM

2022-01-10 16:09 UTC, bantonsson approved these changes

2022-01-10 16:45 UTC, charliegracie approved these changes

2022-01-10 17:18 UTC, merged