[AppSec] Event reporting via Span tags
DataDog/dd-trace-java pull request #3259
Opened 2021-12-12 22:47 UTC by ValentinZakharov

# What Does This Do
Removed legacy AppSec event reporting mechanism and replaced with reporting via Span tags.
When attack detected, event stored as a json string in top span in the tag `_dd.appsec.json`.

# Motivation
The legacy implementation was unreliable and had lack of consistency. Many private betta customers were complaining about problems when traces were received by backend, but at the same time there was no AppSec events sent (for example, if the client was using an outdated version of the agent). Also, there were difficulties in synchronization between traces and AppSec events on the backend side. Both problems happened because traces and AppSec events were sent by different communication channels. That is, the data was not sent up-to-date (asynchronously) or might not be sent at all due to some kind of communication issues.
To solve this problem, it was decided to rework AppSec events reporting in a way where both traces and AppSec events are transmitted through same communication channel and at the same time.

# Additional Notes

2021-12-13 11:51 UTC, bantonsson requested changes
I think the changes look good apart from using `setTagTop` instead of `setDataTop`. See comment.

2021-12-13 11:51 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +              traceSeg.setTagTop("_dd.appsec.json", json);
The whole point of `setDataTop("appsec", lazyJsonThingy)` is twofold:

1. Hide the ugly implementation detail that the information is currently sent as a special tag! This is not something that `AppSec` need to know, but it's a contract between the serialization of the trace, and the backend.
2. Make the JSON string creation lazy, i.e. happen at the point of writing the trace, which happens on another thread, and not here at the point of reporting, which is happening on the application thread.

2021-12-13 11:51 UTC, bantonsson commented on dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
> +    //1 * reportService.reportEvents([event], traceSegment)
Remove this?

2021-12-14 11:38 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +              traceSeg.setTagTop("_dd.appsec.json", json);
Done

2021-12-14 13:08 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +              traceSeg.setDataTop("appsec", wrapper);
Will the `toString()` method of the `AppSecEventWrapper` produce JSON? That is the contract in the doc for `setDataTop`

2021-12-14 16:39 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/AppSecEventWrapper.java
> +    this.json = ADAPTER.toJson(this);
This is no longer _lazy_. It creates the JSON during construction. Remove the `final` from the `json` field and set it in the `toString()` if it is empty.

2021-12-14 17:14 UTC, bantonsson approved these changes

2021-12-16 09:18 UTC, merged