[AppSec] Collect and report pre-defined HTTP request headers
DataDog/dd-trace-java pull request #3286
Opened 2021-12-21 14:43 UTC by ValentinZakharov

# What Does This Do
Implemented code to collect and report pre-defined HTTP request headers

# Motivation

# Additional Notes

2021-12-22 11:42 UTC, bantonsson requested changes

2021-12-22 11:42 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/HeadersCollector.java
> +  private final CaseInsensitiveMap<String> allowedHeaders = new CaseInsensitiveMap<>();
Why is there a difference in types between `headers` and allowed headers?

2021-12-22 11:42 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/HeadersCollector.java
> +    List<String> strings = headers.computeIfAbsent(name, h -> new ArrayList<>(1));
I genuinely dislike the `CaseInsensitiveMap` trying to magically hide the fact that it just stores the keys converted to lowercase. It has weird implications, like this `computeIfAbsent` converting `name` to lowercase twice. Once for `get` and once for `put`.

2021-12-22 11:42 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/HeadersCollector.java
> +    if (headersPassList.stream().anyMatch(name::equalsIgnoreCase)) {
I think that converting the `name` to lowercase and then doing a map lookup could be faster. Also if the types for `headers` and `allowedHeaders` were the same, they could point to the same list, and you would only need to do the check if the header wasn't found in the `headers` map.

2021-12-27 15:15 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/HeadersCollector.java
> +  private final CaseInsensitiveMap<String> allowedHeaders = new CaseInsensitiveMap<>();
`headers` it's all headers which used for analysis by WAF (i.e each record contains List of values)
`allowedHeaders` it's headers we are going to report to backend (only allowed headers) and they are represented as string.

2021-12-27 15:49 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/HeadersCollector.java
> +  private final CaseInsensitiveMap<String> allowedHeaders = new CaseInsensitiveMap<>();
Yes, but that doesn't explain why the `allowedHeaders` are eagerly concatenated into a string, when they for key `x` are exactly the same as `headers` for key `x`.

2021-12-28 10:57 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +                            if (size == 1) {
I would move this optimization into `Strings.join`, and change this whole bit to:

```
String v = Strings.join(",", value);
if (!v.isEmpty()) {
  traceSeg.setTagTop("http.request.headers." + name, v);
}
```

2021-12-28 22:33 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +                            if (size == 1) {
Done

2021-12-29 06:59 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/util/Strings.java
> +      return first.toString();
👍

2021-12-29 07:00 UTC, bantonsson approved these changes

2021-12-29 07:42 UTC, merged