[AppSec] Report metrics for web span only
DataDog/dd-trace-java pull request #3296
Opened 2021-12-29 15:21 UTC by ValentinZakharov

# What Does This Do
AppSec reports metrics/events for span with `web` type.  

# Motivation
Several customers reported that database services were showing up in their list of AppSec services (which is obviously wrong as we only support web services as of now).

# Additional Notes

2021-12-29 15:36 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +            traceSeg.setTagTop("_dd.runtime_family", "jvm");
Is there a SPEC for this? Can't this be handled in the backend? I mean AppSec is technically enabled even if there are no web requests processed. One of the downsides to this is that we can't see if AppSec has been enabled if the web framework is not yet supported.

2021-12-29 16:01 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +            traceSeg.setTagTop("_dd.runtime_family", "jvm");
Here is the [AppSec tracking requirements](https://datadoghq.atlassian.net/wiki/spaces/APS/pages/2137128985/Tracking+AppSec+libraries+usage+in+beta).
It seems, there is no way to see if AppSec enabled i case of not supported framework.

2021-12-29 16:13 UTC, bantonsson approved these changes

2021-12-29 16:13 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +            traceSeg.setTagTop("_dd.runtime_family", "jvm");
Ok, fine. But this still feels a bit weird.

2021-12-30 08:18 UTC, bantonsson requested changes

2021-12-30 08:18 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +            traceSeg.setTagTop("_dd.runtime_family", "jvm");
Woke up this morning with a feeling that this was wrong, and it is.

1. We should only get these callbacks for web requests, so you don't have to filter for the `spanType`.
2. You're setting the top tags based on the span type of the current span, which doesn't necessarily map 1:1.

I think it's fine to always set the top tags here, since we should only get callbacks for web requests. The problem with the other solution was that all local roots regardless of type got the tags.

2021-12-30 10:50 UTC, ValentinZakharov commented
You remark makes sense - I removed filter by spanType (tests are passed correctly)

2021-12-30 10:51 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +            traceSeg.setTagTop("_dd.runtime_family", "jvm");
You remark makes sense - I removed filter by spanType (tests are passed correctly)

2021-12-30 12:00 UTC, bantonsson approved these changes

2021-12-30 15:06 UTC, merged