Instrumentation JFR events
DataDog/dd-trace-java pull request #3355
Opened 2022-02-01 03:39 UTC by ygree

# What Does This Do

Adds JFR class transformation events to measure instrumentation.

# Motivation

This provides information about instrumentation time per class.

# Additional Notes

![image](https://user-images.githubusercontent.com/4147346/151909511-4c1ac06c-0a15-4ea6-8df6-c407366f7598.png)

2022-02-01 08:56 UTC, jbachorik commented on dd-java-agent/agent-tooling/src/main/java8/datadog/trace/agent/tooling/bytebuddy/ClassTransformationEvent.java
> +@Category({"Data Dog Tracer", "Class Transformation"})
```suggestion
@Category({"Datadog", "Tracer", "Class Transformation"})
```

We already have a bunch of events in `Datadog` category so it would be nice to have this one there as well.

2022-02-01 08:57 UTC, jbachorik commented on dd-java-agent/agent-tooling/src/main/java11/datadog/trace/agent/tooling/bytebuddy/DDJava9ClassFileTransformer.java
> +      event.setTransformed(result != null);
Would it make sense to track also the bytecode size? Before and after transformation?

2022-02-01 16:13 UTC, ygree commented on dd-java-agent/agent-tooling/src/main/java11/datadog/trace/agent/tooling/bytebuddy/DDJava9ClassFileTransformer.java
> +      event.setTransformed(result != null);
That's a good idea! Thanks!

2022-02-01 16:25 UTC, ygree commented on dd-java-agent/agent-tooling/src/main/java8/datadog/trace/agent/tooling/bytebuddy/ClassTransformationEvent.java
> +@Category({"Data Dog Tracer", "Class Transformation"})
Good point! Thanks!

2022-02-01 17:41 UTC, jbachorik commented on dd-java-agent/agent-tooling/src/main/java8/datadog/trace/agent/tooling/bytebuddy/ClassTransformationEvent.java
> +    classSizeDifference = classSizeAfterTransformation - classSizeBeforeTransformation;
You can wrap this in `if (shouldCommit()) { ...}` to avoid paying the cost if the event is eg. disabled in the settings.

2022-02-02 02:25 UTC, ygree commented on dd-java-agent/agent-tooling/src/main/java8/datadog/trace/agent/tooling/bytebuddy/ClassTransformationEvent.java
> +    classSizeDifference = classSizeAfterTransformation - classSizeBeforeTransformation;
Good point! Thanks!

2022-02-02 10:48 UTC, jbachorik commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentTooling.java
> +    } else if (Platform.isJavaVersionAtLeast(8)) {
Probably not something very common but it would be good to be on the safe side and check for `Platform.isJavaVersionAtLeast(8, 272, 0)` to make sure the JFR classes are available.

We could avoid raising the exception in that case.

2022-02-03 22:21 UTC, ygree commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentTooling.java
> +    } else if (Platform.isJavaVersionAtLeast(8)) {
Added. Thanks!

2022-02-08 00:26 UTC, devinsba approved these changes

2022-02-23 13:09 UTC, mcculls requested changes
Just want to check - is this PR just for benchmarking or is the plan to merge it into master at some point?

If the intent is to merge it into master then I'd like there to be a feature-flag that allows us to switch back to the previous transformers without JFR event collection. This would help us check relative performance of this feature and provide a way to workaround unforeseen issues in the field.

2022-02-23 16:50 UTC, ygree commented
> Just want to check - is this PR just for benchmarking or is the plan to merge it into master at some point?
> 
> If the intent is to merge it into master then I'd like there to be a feature-flag that allows us to switch back to the previous transformers without JFR event collection. This would help us check relative performance of this feature and provide a way to workaround unforeseen issues in the field.

Thanks, Stuart! I agree. The plan is to add a feature flag or even two: one for transformation and another for matchers (they are more expensive because of the number of matching events could be millions). I'll mark this PR as draft for now.

2022-02-23 18:40 UTC, jbachorik commented
> > Just want to check - is this PR just for benchmarking or is the plan to merge it into master at some point?
> > If the intent is to merge it into master then I'd like there to be a feature-flag that allows us to switch back to the previous transformers without JFR event collection. This would help us check relative performance of this feature and provide a way to workaround unforeseen issues in the field.
> 
> Thanks, Stuart! I agree. The plan is to add a feature flag or even two: one for transformation and another for matchers (they are more expensive because of the number of matching events could be millions). I'll mark this PR as draft for now.

Uff. Millions of events can turn out to be rather problematic as they will increase the size of the collected JFR recording significantly. That could affect our transfer and storage costs.

Would sampling of be suitable for matcher events? Something similar to what we do for exception in order to make sure we don't blow up the recording.

2022-02-24 17:45 UTC, ygree commented
> > > Just want to check - is this PR just for benchmarking or is the plan to merge it into master at some point?
> > > If the intent is to merge it into master then I'd like there to be a feature-flag that allows us to switch back to the previous transformers without JFR event collection. This would help us check relative performance of this feature and provide a way to workaround unforeseen issues in the field.
> > 
> > 
> > Thanks, Stuart! I agree. The plan is to add a feature flag or even two: one for transformation and another for matchers (they are more expensive because of the number of matching events could be millions). I'll mark this PR as draft for now.
> 
> Uff. Millions of events can turn out to be rather problematic as they will increase the size of the collected JFR recording significantly. That could affect our transfer and storage costs.
> 
> Would sampling of be suitable for matcher events? Something similar to what we do for exception in order to make sure we don't blow up the recording.

I don't think we will have instrumentation JFR events enabled by default, especially matching events that affect startup time drastically. At the moment we are using it to figure out how the startup can be optimized.

2022-05-10 20:19 UTC, ygree commented
Superseded by #3546

2022-05-10 20:19 UTC, closed without merging