Add Vertica, Apache Drill JDBC driver support
DataDog/dd-trace-java pull request #3410
Opened 2022-02-23 20:06 UTC by eric-ming2

2022-02-23 20:10 UTC, devinsba requested changes

2022-02-23 20:10 UTC, devinsba commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
> +      "com/vertica/jdbc/common/SPooledConnection.class", // Not sure if should include: implements javax.sql.PooledConnection
You are gonna want these to be `.` separated. Also seems like your intelliJ changed the tab size so you will want to fix that `./gradlew :dd-java-agent:instrumentation:jdbc:spotlessApply`

2022-02-23 20:17 UTC, devinsba commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
> +    "org/apache/drill/jdbc/DrillPreparedStatement",
Same here with dots

2022-02-23 20:17 UTC, eric-ming2 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
> +      "com/vertica/jdbc/common/SPooledConnection.class", // Not sure if should include: implements javax.sql.PooledConnection
Fixed, thank you!

2022-02-23 20:21 UTC, eric-ming2 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
> +    "org/apache/drill/jdbc/DrillPreparedStatement",
Fixed again, my bad for being careless.

2022-02-23 21:01 UTC, mcculls commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
> +    "com.vertica.jdbc.common.SPooledConnection", // Not sure if should include: implements
No need to include `PooledConnection` classes here, just the base connection class is enough

2022-02-23 21:02 UTC, mcculls commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
> +    "com.vertica.jdbc.kv.RoutableConnection",
This doesn't implement any interface we're interested in and can be removed

2022-02-23 21:12 UTC, mcculls commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
> +    "com.vertica.jdbc.VerticaPreparedStatement",
this is an interface, so doesn't need to be in this list (it represents Vertica's extension to the standard API)

2022-02-23 21:21 UTC, mcculls commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
> +    "com.vertica.jdbc.common.SPreparedStatement",
note to other reviewers - there is a `com.vertica.jdbc.common.SCallableStatement` class but it extends `com.vertica.jdbc.common.SPreparedStatement` and delegates its execute methods to the superclass, so we don't need to include it here

2022-02-23 21:37 UTC, mcculls commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
> +    "org.apache.drill.jdbc.DrillConnection",
this is another interface that extends `java.sql.Connection` - we just need to put its implementation here instead which is `org.apache.drill.jdbc.impl.DrillConnectionImpl`

2022-02-23 21:40 UTC, mcculls commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
> +    "org.apache.drill.jdbc.DrillPreparedStatement",
like with the connection, we should put `org.apache.drill.jdbc.impl.DrillPreparedStatementImpl` here instead of the extended interface

2022-02-23 21:42 UTC, mcculls requested changes
some minor cleanup needed, but once that's done it should be good to merge

2022-02-24 15:17 UTC, mcculls approved these changes
👍

2022-02-24 21:51 UTC, devinsba approved these changes

2022-02-24 22:41 UTC, merged