[WIP] Jb/tracing context
DataDog/dd-trace-java pull request #3414
Opened 2022-02-25 12:28 UTC by jbachorik

# What Does This Do

# Motivation

# Additional Notes

2022-03-17 16:43 UTC, devinsba reviewed
Just a couple things I noticed. Need to read through again

2022-03-17 16:43 UTC, devinsba commented on dd-java-agent/agent-profiling/profiling-context/profiling-context.gradle
> +  options.forkOptions.javaHome = file(System.env.JAVA_11_HOME)
You can replace these lines with `setJavaVersion(it, 11)`

see: https://github.com/DataDog/dd-trace-java/pull/3417

2022-03-17 16:53 UTC, devinsba commented on dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalEncoder.java
> + *       <td style="padding-left: 5px; padding-right: 5px;">4 bytes</td>
Couldn't this be a single byte unless you are planning on adding significantly more headers in the future? You could allow 50 5byte headers in a single byte. As it is you will be encoding 3 zeros at the begging (assuming big endian/network byte order) of every message

2022-03-17 16:55 UTC, devinsba commented on dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalEncoder.java
> + *       <td style="padding-left: 5px; padding-right: 5px;">4 bytes</td>
AH, I see. The javadoc doesn't match the PR description exactly

2022-03-17 17:37 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalEncoder.java
> + *       <td style="padding-left: 5px; padding-right: 5px;">4 bytes</td>
Ah, sorry. I missed one copy/paste. The PR description is updated.

2022-03-18 10:22 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
> +      IntervalBlobWriter.initialize(instance.asyncProfiler);
Shouldn't we have a Memory barrier then, or do constructors in Java have an implicit write memory barrier?

2022-03-18 10:28 UTC, luhenry commented on dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
> +      IntervalBlobWriter.initialize(instance.asyncProfiler);
And even if you do it in the constructor of `AuxiliaryAsyncProfiler`, you can have an implicit memory barrier which `AtomicReference.compareAndSet` does provide.

2022-03-18 10:35 UTC, bantonsson commented on dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
> +      IntervalBlobWriter.initialize(instance.asyncProfiler);
Either way, `this` is not escaping since it's the `asyncProfiler` that is the argument to the other method.

2022-03-18 10:42 UTC, bantonsson commented on dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
> +      IntervalBlobWriter.initialize(instance.asyncProfiler);
And just to be clear, this is the visibility guarantee wrt constructors.

> A thread that can only see a reference to an object after that object has been completely initialized is guaranteed to see the correctly initialized values for that object’s final fields.

2022-03-18 12:08 UTC, luhenry approved these changes

2022-03-18 12:08 UTC, luhenry commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
> +    tracingContextTracker.deactivateContext(true);
We could have the `deactiveContext` and `maybeDeactivateContext` rather than passing a magic true/false value.

2022-03-18 14:08 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
> +    tracingContextTracker.deactivateContext(true);
Done

2022-03-18 14:10 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/LongSequence.java
> +        ;
Perhaps. Gone.

2022-03-18 15:02 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/LongSequence.java
> +    if (released.get()) {
Good catch!
This code started with the assumption that all operations are done non-concurrently. Eg. there is always at most one thread operating on a particular instance at a time.
This assumption, however, changed when I added the tracing context expiration logic which may release the sequence resources while the sequence is being manipulated by some other thread.

This makes the current approach prone to non-benign races.
Let me update the implementation.

2022-04-08 11:58 UTC, bantonsson requested changes
Thanks for the great explanation in the PR and code comments. This looks good, but the extra unused `finished` field in `DDSpan` has to go.

Left some optimization comments/questions that are not important for getting this merged.

2022-04-08 16:20 UTC, jbachorik commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
> +  private final AtomicBoolean finished = new AtomicBoolean(false);
Gone

2022-04-08 16:43 UTC, jbachorik commented on dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/ProfilerTracingContextTracker.java
> +        data = Arrays.copyOf(data, buffer.limit());
Created a JIRA ticket to follow up - https://datadoghq.atlassian.net/browse/PROF-5307

2022-04-11 12:05 UTC, bantonsson approved these changes

2022-04-11 17:06 UTC, merged