Support long running spans
DataDog/dd-trace-java pull request #3452
Opened 2022-03-18 16:24 UTC by amarziali

# What Does This Do

Add support for long running spans. Allows incomplete spans to be reported to datadog and partial results to be displayed into the live view. 
As well, this PR enables collecting complete traces for spans lasting more than 15 minutes.

The feature is released behind a configuration flag and it's disabled by default.

# How does it work

Pending traces are scanned on a scheduled basis and if a long lasting span is found:
* A copy of this span (same span_id, parent_it, trace_id) is added to the buffer. The span is tagged as partial (metrics[_dd.partial_version] with an incrementing number)
* All finished spans also buffered on the same pending traces are flushed (similar to partial flush scenario)

# Motivation

Today, due to internal datadog architecture, spans lasting more than 15 minutes may result in incomplete tracing. Additionally to this, spans are sent only when all pending ones are closed. Hence, live view won't display those ones.

# Additional Notes

2022-03-18 18:04 UTC, devinsba requested changes
We need to address the `pendingTraces` map

2022-03-18 18:04 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +  private final ConcurrentLinkedDeque<DDSpan> unfinishedSpans = new ConcurrentLinkedDeque<>();
You can move this allocation into the constructor below

2022-03-18 18:55 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      span.setMetric(DDTags.DD_PARTIAL_VERSION, partialVersion);
+1

2022-03-18 20:31 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreSpan.java
> +  Long getPartialVersion();
I don't think I want partially pushed onto the span itself.  It isn't really a data model concept.  It is a transport concept.

2022-03-18 20:34 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  private final TraceKeepAlive traceKeepAlive;
I don't think we need another object for this.  I was thinking it would be handled inside of PendingTrace.

2022-03-18 20:35 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/TraceKeepAlive.java
> +public class TraceKeepAlive implements AgentTaskScheduler.Task<Boolean> {
As noted elsewhere, I don't think we need a separate class for this.  I think this would better be handled inside of PendingTrace.

2022-03-18 20:37 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  boolean isDisableSamplingMechanismValidation() {
Why is this being added?

2022-03-18 20:38 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
> +  public Long getPartialVersion() {
These shouldn't be part of the public span API.  I don't think should be on span at all.

2022-03-18 20:39 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +      final boolean incomplete = unsafeTags.containsKey(DDTags.DD_PARTIAL_VERSION);
We shouldn't be using a tag for partialness.  It isn't really a tag in the data model -- that's just a trick to fit into the existing protocol.

2022-03-18 20:40 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +  String getParentServiceName() {
Why are we adding these?  I don't think this is the right place for them.

2022-03-18 20:40 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      tracer.getTraceKeepAlive().onPendingTraceBegins(this);
This is mostly confirming that should just be part of PendingTrace.

2022-03-18 20:46 UTC, dougqh requested changes
I've commented on this PR, but I'd really suggest that the PR just be abandoned.

I think we need to back and talk about the protocol and how to make the changes more before jumping into code.

2022-03-23 07:50 UTC, amarziali commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +import static datadog.trace.api.ConfigDefaults.*;
Oh yes. I had to reorganize imports after a rebase. Now should be fixed thanks

2022-03-23 07:53 UTC, amarziali commented on dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
> +  public static final String LONG_RUNNING_TRACE_FLUSH_INTERVAL = "longrunning.flush.interval";
I stripped that prefix to align with what done on go tracer. There is a common convention between tracers on configuration generally speaking?

2022-03-23 07:55 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +  private final ConcurrentLinkedDeque<DDSpan> unfinishedSpans = new ConcurrentLinkedDeque<>();
should I move also already existing one `finishedSpans` so?

2022-03-23 07:56 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
> +  private long startTimeNano;
yes. just changed

2022-03-23 07:59 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  boolean isDisableSamplingMechanismValidation() {
Used here: https://github.com/DataDog/dd-trace-java/blob/7b5d30060e0d3bc2218bc230809440a831fd8522/dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java#L214

I limited to package visibility

2022-03-23 08:03 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +  private final TraceKeepAlive traceKeepAlive;
Do you prefer having PendingTrace handling  a scheduled job?

2022-03-23 08:05 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +  String getParentServiceName() {
Because this information is needed to construct a new SpanContext here: https://github.com/DataDog/dd-trace-java/blob/7b5d30060e0d3bc2218bc230809440a831fd8522/dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java#L201

I gave only package visibility. Maybe something can be simplified. Please advice

2022-03-23 08:06 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      span.setMetric(DDTags.DD_PARTIAL_VERSION, partialVersion);
Maybe putting in the metadata like `measured` or `top_level` could be a better option so?

2022-03-23 13:34 UTC, devinsba commented on dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
> +  public static final String LONG_RUNNING_TRACE_FLUSH_INTERVAL = "longrunning.flush.interval";
Yes, we try to align. The problem is that we support multiple products in our tracer so we try to consistently namespace our configs when they are specific to a product. We don't always do it though so it's probably fine but my preference is for namespacing

2022-03-23 13:36 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +  private final ConcurrentLinkedDeque<DDSpan> unfinishedSpans = new ConcurrentLinkedDeque<>();
No, that's a required feature. In this case we can avoid the creation of the Deque by only creating inside your if block

2022-03-31 07:50 UTC, amarziali commented on dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
> +  public static final String LONG_RUNNING_TRACE_FLUSH_INTERVAL = "longrunning.flush.interval";
I added the trace namespace as suggested. Thanks

2022-03-31 07:51 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +  private final ConcurrentLinkedDeque<DDSpan> unfinishedSpans = new ConcurrentLinkedDeque<>();
Changes are done. Also did another optimization not to populate this list if null (= feature not activated)

2022-03-31 08:04 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      tracer.getTraceKeepAlive().onPendingTraceBegins(this);
As far I can see, on PendingTrace I would have the possibility to emit keepalives when write is called (e.g. a span of the same trace is finished). But what in case nothing happens and I've just to keep alive an unfinished span? I don't see any other solution than using a scheduled thread. The advantage of externalizing is just use one thread for all the pending traces and separate roles

2023-04-03 08:37 UTC, closed without merging