Add Jedis 4.0 support
DataDog/dd-trace-java pull request #3471
Opened 2022-03-29 23:18 UTC by andrewmcnamara

This PR adds support for [Jedis 4](https://github.com/redis/jedis) as per issue #3467.

As per the discussion on the linked issue method we could not get tracing  in our project that was using Jedis 4. 
Originally the Jedis 3 instrumentation applied advice to the `sendCommand` method.
https://github.com/DataDog/dd-trace-java/blob/f5a2406a3132cbd800b73b7736be45b785c483ff/dd-java-agent/instrumentation/jedis-3.0/src/main/java/datadog/trace/instrumentation/jedis30/JedisInstrumentation.java#L42-L47

Since Jedis 4.0 the  method signature has changed  [see](https://github.com/redis/jedis/blob/83af8c19fd360f299eae7c54d7fc14f2a6cb3f6d/src/main/java/redis/clients/jedis/Protocol.java#L55)
```java
public static void sendCommand(final RedisOutputStream os, CommandArguments args) 
```

To add support I copied the  `jedis-3.0`  folder  and updated the `JedisInstrumentation` class to support the changes. 

As part of this change I also tried to address this comment.
> // FIXME: This instrumentation only incorporates sending the command, not processing the result.

By moving the tracing to  `executeCommand ` on `redis.clients.jedis.Connection`. This method looked like it would send the result and wait for Redis to complete.- which felt like it cover the entire `Redis` operation.

The tests cases copied from version 3 all  ran successfully, but am  unsure whether the tracing works deployed.

2022-04-04 13:17 UTC, devinsba requested changes
Thanks for the contribution. If you can update the gradle file we would be good to merge

2022-04-04 13:17 UTC, devinsba commented on dd-java-agent/instrumentation/jedis-4.0/jedis-4.0.gradle
> +  compileOnly group: 'redis.clients', name: 'jedis', version: '4.2.0'
Can you change this to 4.0.0?

2022-04-04 13:17 UTC, devinsba commented on dd-java-agent/instrumentation/jedis-4.0/jedis-4.0.gradle
> +  testImplementation project(':dd-java-agent:instrumentation:jedis-1.4')
Can you add all the Jedis implementations here?

2022-04-04 13:17 UTC, devinsba commented on dd-java-agent/instrumentation/jedis-4.0/src/main/java/datadog/trace/instrumentation/jedis40/JedisClientDecorator.java
> +    return null;
Since you were in this code recently can you maybe add a comment on how you think we might be able to get this and the instance information in the future? see: https://github.com/DataDog/dd-trace-java/issues/2249

2022-04-04 22:31 UTC, andrewmcnamara commented on dd-java-agent/instrumentation/jedis-4.0/jedis-4.0.gradle
> +  compileOnly group: 'redis.clients', name: 'jedis', version: '4.2.0'
Changed.

2022-04-04 22:32 UTC, andrewmcnamara commented on dd-java-agent/instrumentation/jedis-4.0/jedis-4.0.gradle
> +  testImplementation project(':dd-java-agent:instrumentation:jedis-1.4')
Have updated the Gradle file  let me know if that is correct.

2022-04-04 22:33 UTC, andrewmcnamara commented on dd-java-agent/instrumentation/jedis-4.0/src/main/java/datadog/trace/instrumentation/jedis40/JedisClientDecorator.java
> +    return null;
Comments added - I think it should be enough to help with linked issue

2022-04-04 22:33 UTC, andrewmcnamara commented
@devinsba Thanks for reviewing - hopefully I have addressed all change requests.

2022-04-05 13:28 UTC, devinsba commented on dd-java-agent/instrumentation/jedis-4.0/jedis-4.0.gradle
> +  testImplementation group: 'redis.clients', name: 'jedis', version: '4.2.0'
```suggestion
  testImplementation group: 'redis.clients', name: 'jedis', version: '4.0.0'
```

2022-04-05 13:30 UTC, devinsba commented on dd-java-agent/instrumentation/jedis-4.0/src/main/java/datadog/trace/instrumentation/jedis40/JedisClientDecorator.java
> +    return null;
Great thanks

2022-04-05 13:31 UTC, devinsba commented on dd-java-agent/instrumentation/jedis-4.0/jedis-4.0.gradle
> +  testImplementation group: 'redis.clients', name: 'jedis', version: '4.2.0'
I'll commit this so I can get it merged this morning. Thanks!

2022-04-05 14:58 UTC, merged