[WIP][Serverless] remove LambdaContext
DataDog/dd-trace-java pull request #3531
Opened 2022-04-29 19:41 UTC by maxday

# What Does This Do

Following this PR : https://github.com/DataDog/dd-trace-java/pull/3506 and https://github.com/DataDog/datadog-agent/pull/11825
LambdaHandler is not needed anymore which simplifies the code
# Motivation

# Additional Notes

2022-05-18 15:25 UTC, devinsba requested changes
Just the one constant that should be moved

2022-05-18 15:25 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> -        final String spanID = response.headers().get(DATADOG_SPAN_ID);
Is it not possible to have a parentSpanID now?

2022-05-19 23:31 UTC, maxday commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> -        final String spanID = response.headers().get(DATADOG_SPAN_ID);
now the spanID is generated by the tracer, not by the extension anymore

2022-05-20 14:59 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
So, this line says that this lambda will have a parent with span ID 0 (so it will be a root span), what about the case of one lambda calling another? Is the lambda layer doing some remapping outside the javaagent that we don't see here?

Maybe a class comment that outlines the flow would be helpful

2022-05-20 16:11 UTC, maxday commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
yeah, I'll add a comment.
Basically this span will be dropped by the extension since the extension is creating the top level invocation span on its own to avoid duplicating the logic of parsing the context in 6 different runtimes (this is our universal instrumentation project)
We just need this span for any subsequent created spans (custom spans or auto instrumented spans) so they will parented to this span and the trace will be consistent

2022-05-20 17:17 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
Would you mind posting the json too?

Also would it be possible for us to integration test this? Can we run the lambda layer as a docker container?

2022-05-20 17:24 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
I'm also not sure how the children end up with the correct parent, since the extension will have a span ID that the Java code won't know, unless the extension uses the span ID we communicate back in the `notifyEndInvocation` headers

2022-05-20 17:27 UTC, maxday commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
exact, the extension use the spanId from `notifyEndInvocation`
here is the full JSON
`{
    "orphaned": [],
    "trace": {
        "spans": {
            "2472584735297776176": {
                "metrics": {
                    "_sampling_priority_v1": 1.0,
                    "_dd.measured": 1.0,
                    "thread.id": 1.0
                },
                "resource_hash": "d1ca4edc1e7f181d",
                "end": 1651260911.850921,
                "name": "http.request",
                "service": "maxday-no-code-end",
                "start": 1651260911.438564,
                "org_id": 652564,
                "trace_id": "4720459294688652618",
                "host_groups": [
                    "env:none"
                ],
                "parent_id": "8599813794960346528",
                "meta": {
                    "http.host": "httpbin.org",
                    "http.path_group": "/get",
                    "http.url": "https://httpbin.org/get",
                    "thread.name": "main",
                    "http.status_code": "200",
                    "functionname": "maxday-demo-java-no-code-3-dev-helloend",
                    "service": "maxday-no-code-end",
                    "function_arn": "arn:aws:lambda:sa-east-1:xxx:function:maxday-demo-java-no-code-3-dev-helloend",
                    "peer.hostname": "httpbin.org",
                    "aws_account": "xxx",
                    "account_id": "xxx",
                    "memorysize": "2048",
                    "component": "http-url-connection",
                    "_dd.origin": "lambda",
                    "span.kind": "client",
                    "_dd.tracer_version": "0.90.0-SNAPSHOT~4b2127829a",
                    "http.method": "GET",
                    "language": "java",
                    "region": "sa-east-1",
                    "_dd.compute_stats": "1",
                    "dd_extension_version": "753",
                    "architecture": "x86_64",
                    "runtime": "java11"
                },
                "env": "none",
                "host_id": 0,
                "duration": 0.41235711,
                "resource": "GET /get",
                "children_ids": [],
                "type": "http",
                "span_id": "2472584735297776176"
            },
            "8599813794960346528": {
                "metrics": {
                    "_sampling_priority_v1": 2.0,
                    "_top_level": 1.0
                },
                "resource_hash": "48887d86a3537c3c",
                "end": 1651260912.240292,
                "name": "aws.lambda",
                "service": "maxday-no-code-end",
                "start": 1651260911.31607,
                "org_id": 652564,
                "trace_id": "4720459294688652618",
                "host_groups": [
                    "env:none"
                ],
                "parent_id": "6765293424654741647",
                "meta": {
                    "functionname": "maxday-demo-java-no-code-3-dev-helloend",
                    "service": "maxday-no-code-end",
                    "function_arn": "arn:aws:lambda:sa-east-1:xxx:function:maxday-demo-java-no-code-3-dev-helloend",
                    "region": "sa-east-1",
                    "_dd.compute_stats": "1",
                    "memorysize": "2048",
                    "dd_extension_version": "753",
                    "_dd.origin": "lambda",
                    "architecture": "x86_64",
                    "request_id": "2110c71c-7dc3-4e68-bf15-d6ee0c2e58e5",
                    "aws_account": "xxx",
                    "runtime": "java11",
                    "account_id": "xxx"
                },
                "env": "none",
                "host_id": 0,
                "duration": 0.924222509,
                "resource": "maxday-demo-java-no-code-3-dev-helloEnd",
                "children_ids": [
                    "3346775756877716047",
                    "2472584735297776176",
                    "1714385570878451487"
                ],
                "type": "serverless",
                "span_id": "8599813794960346528"
            },
            "1714385570878451487": {
                "metrics": {
                    "_sampling_priority_v1": 1.0,
                    "_dd.measured": 1.0,
                    "thread.id": 1.0
                },
                "resource_hash": "d1ca4edc1e7f181d",
                "end": 1651260912.237474,
                "name": "http.request",
                "service": "maxday-no-code-end",
                "start": 1651260911.851257,
                "org_id": 652564,
                "trace_id": "4720459294688652618",
                "host_groups": [
                    "env:none"
                ],
                "parent_id": "8599813794960346528",
                "meta": {
                    "http.host": "httpbin.org",
                    "http.path_group": "/get",
                    "http.url": "https://httpbin.org/get",
                    "thread.name": "main",
                    "http.status_code": "200",
                    "functionname": "maxday-demo-java-no-code-3-dev-helloend",
                    "service": "maxday-no-code-end",
                    "function_arn": "arn:aws:lambda:sa-east-1:xxx:function:maxday-demo-java-no-code-3-dev-helloend",
                    "peer.hostname": "httpbin.org",
                    "aws_account": "xxx",
                    "account_id": "xxx",
                    "memorysize": "2048",
                    "component": "http-url-connection",
                    "_dd.origin": "lambda",
                    "span.kind": "client",
                    "_dd.tracer_version": "0.90.0-SNAPSHOT~4b2127829a",
                    "http.method": "GET",
                    "language": "java",
                    "region": "sa-east-1",
                    "_dd.compute_stats": "1",
                    "dd_extension_version": "753",
                    "architecture": "x86_64",
                    "runtime": "java11"
                },
                "env": "none",
                "host_id": 0,
                "duration": 0.386217209,
                "resource": "GET /get",
                "children_ids": [],
                "type": "http",
                "span_id": "1714385570878451487"
            },
            "6765293424654741647": {
                "metrics": {
                    "_sampling_priority_v1": 2.0,
                    "_dd.measured": 1.0,
                    "thread.id": 1.0
                },
                "resource_hash": "8df58159005077b1",
                "end": 1651260912.253047,
                "name": "http.request",
                "service": "maxday-no-code-start",
                "start": 1651260911.291632,
                "org_id": 652564,
                "trace_id": "4720459294688652618",
                "host_groups": [
                    "env:none"
                ],
                "parent_id": "2583929690240414364",
                "meta": {
                    "http.host": "mbzo6fa3bd.execute-api.sa-east-1.amazonaws.com",
                    "http.path_group": "/dev/end",
                    "http.url": "https://mbzo6fa3bd.execute-api.sa-east-1.amazonaws.com/dev/end",
                    "thread.name": "main",
                    "http.status_code": "200",
                    "account_id": "xxx",
                    "service": "maxday-no-code-start",
                    "function_arn": "arn:aws:lambda:sa-east-1:xxx:function:maxday-demo-java-no-code-3-dev-hellostart",
                    "peer.hostname": "mbzo6fa3bd.execute-api.sa-east-1.amazonaws.com",
                    "aws_account": "xxx",
                    "functionname": "maxday-demo-java-no-code-3-dev-hellostart",
                    "component": "http-url-connection",
                    "memorysize": "2048",
                    "_dd.origin": "lambda",
                    "span.kind": "client",
                    "_dd.tracer_version": "0.90.0-SNAPS [...]

2022-05-20 17:29 UTC, maxday commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
yes we can test it with containers, this is what we've done with dd-trace-dotnet
would it be OK to do it a bit later in another PR?

2022-05-20 17:34 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
Yeah, that's fine. We would want one in `dd-smoke-tests` though.

Last question I think: what happens if a customer adds tags to the span (using opentracing for instance) that gets discarded? Do those tags also get lost?

2022-05-20 17:38 UTC, maxday commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
the span which gets discarded in the extension is the one that we create in `LambdaHandlerInstrumentation` so the customer can't really set tags on it.

2022-05-20 17:40 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
That will be the active span during the customers handler method, otherwise your urlconnection spans wouldn't be the child of it

2022-05-23 12:57 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
What I am saying here is: if the customer attempts to modify the active span during their handler code, adding tags for example, do those changes get lost? Or do they get copied into the extensions span?

2022-05-24 12:54 UTC, maxday commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
oh I see, sorry for the confusion. Indeed they would be lost. 
Only extra tags provided via environment variables DD_TAGS or DD_EXTRA_TAGS / datadog.yml config file would be kept.

2022-06-06 14:51 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +              DDId.from(traceID), DDId.ZERO, samplingPriority, DEFAULT, null, 0, null, null);
We will have to remember this as we gain more java users

2022-06-06 14:51 UTC, devinsba approved these changes

2022-06-07 15:29 UTC, merged