Matcher Cache Builder
DataDog/dd-trace-java pull request #3546
Opened 2022-05-10 20:15 UTC by ygree

# Matcher Cache Builder

Aims to speedup startup time by using a pre-built matcher cache.
It's comprised of two parts:
- Matcher Cache Builder CLI
- Matcher Cache agent param

## How to use

1. Build Matcher Cache

Run Agent jar with -mc for usage instruction:

```
$ java -jar dd-java-trace.jar -mc

Matcher Cache Builder CLI usage: -o output-data-file {-cp class-path} [-r csv-report-file]
```

`-o` (output file) It is a mandatory param for the output binary Matcher Cache Data file path. If such a file aready exists, it will be replaced.

`-r` (report file) It is an optional param for the Matcher Cache builder report file path.

`-cp` (classpath) It can point to a directory that contains class files, jars, fat-jars or jmods. `-cp` can be used more than once.

Matcher Cache Builder searches for all the classes in provided class paths (-cp), dd-trace-jave agent classes, and the current JDK classes (specified in the JAVA_HOME env var).
It tries to load each class and checks whether class is going to be instrumented or not and saves this information into the output data file. This output Matcher Cache Data file is passed into the agent.
In order to see which classes were found and where along with the matcher resolution use `-r` to generate a report file.

2. Use Matcher Cache Builder

In order to use a genreated matcher cache data file it needs to be passed as a java property to the java agent:

```
-Ddd.prebuilt.matcher.data.file=<path-to-generated-matcher-cache-data-file>
```

Check logs at the java agent startup to see whether the matcher cache was able to read cache data or not.

## Matcher Cache JFR events

When Matcher Cache is being used it emits next JFR events:

- `datadog.trace.agent.MatcherCacheMiss` for classes that where not found it the cache
- `datadog.trace.agent.MatcherCacheLoading` the time it took to load cache data

## Class Tranformation JFR events

When Agent loads classes it produces `datadog.trace.agent.ClassTransformation` events.

It has next properties:

- internal class name
- class size in bytes
- class difference after transformation
- a flag whether the class has been transformed or skipped
- duration

2022-05-10 20:15 UTC, ygree commented on .github/workflows/codeql-analysis.yml
> +      run: JAVA_HOME=$JAVA_HOME_8_X64 JAVA_8_HOME=$JAVA_HOME_8_X64 JAVA_11_HOME=$JAVA_HOME_11_X64 ./gradlew clean :dd-java-agent:shadowJar --build-cache --parallel --stacktrace --no-daemon --max-work
This is needed to compile `agent-builder/src/main/java8`. Otherwise it fails at the build check with:

```
Caused by: org.gradle.jvm.toolchain.internal.NoToolchainAvailableException: No compatible toolchains found for request filter: {languageVersion=8, vendor=any, implementation=vendor-specific} (auto-detect false, auto-download false)
```

https://github.com/DataDog/dd-trace-java/runs/6259971755?check_suite_focus=true

2022-05-10 20:16 UTC, ygree commented on dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java
> +    InstrumentationContextProvider contextProvider =
Moved this into the FieldBackedContextProvider.contextProvider static factory method to hide some internals about the constructor parameters that can be encapsulated.

2022-05-10 20:17 UTC, ygree commented on dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java
> +  static ElementMatcher<? super TypeDescription> typeMatcher(
This part extracted into the static method for Matcher Cache Builder

2022-05-11 09:14 UTC, mcculls commented
I notice this only runs the matcher against loaded classes - all the byte-buddy matchers are designed so they can run against bytecode, ie. the class resource, without having to load the class.

There are a number of benefits of running these ahead-of-time matchers against bytecode:
1. You can start with a simple search of resources, but then go on to support incremental generation as part of the build
2. You can get match results for classes which can't be loaded without the right environment
3. You can avoid a lot of complicated class-loading
4. You avoid triggering static initializers that might have side-effects on the system

How hard would it be to drive this by searching class resources rather than forcibly loading classes?

2022-05-11 09:22 UTC, mcculls commented on dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/SingleTypeMatcher.java
> +    return name != null && name.equals(target.getName());
Do you have a scenario when `getName` returned `null`? The byte-buddy API says it should return the empty string when there is no identifiable name, and a lot of the byte-buddy code assumes names are never `null` so if there is a case when it's `null` then that's something we should investigate and report back.

2022-05-12 00:40 UTC, ygree commented on dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/SingleTypeMatcher.java
> +    return name != null && name.equals(target.getName());
Good catch! I had an NPE there before I started using global ignores. Will remove this check. Thanks!

2022-05-12 00:47 UTC, mcculls commented on dd-java-agent/agent-matcher-cache/src/main/java/datadog/trace/agent/tooling/matchercache/MatcherCache.java
> +              + agentVersion);
minor: historically we've not been consistent in using tracer vs. agent in this codebase (because the Java tracer is a `javaagent`) but I think it would be better to use `tracerVersion` here to avoid people mixing this up with the Datadog agent version (the separate process that consumes traces and metrics to send through to the backend)

2022-05-12 01:02 UTC, ygree commented
> I notice this only runs the matcher against loaded classes - all the byte-buddy matchers are designed so they can run against bytecode, ie. the class resource, without having to load the class.
> 
> There are a number of benefits of running these ahead-of-time matchers against bytecode:
> 
>     1. You can start with a simple search of resources, but then go on to support incremental generation as part of the build
> 
>     2. You can get match results for classes which can't be loaded without the right environment
> 
>     3. You can avoid a lot of complicated class-loading
> 
>     4. You avoid triggering static initializers that might have side-effects on the system
> 
> 
> How hard would it be to drive this by searching class resources rather than forcibly loading classes?

Thanks for the suggestion, Stuart. I've reworked Matcher Cache Builder to avoid class loading.

2022-05-27 08:11 UTC, mcculls requested changes
Currently testing some large apps - will write up feedback once that's done

2023-05-05 16:26 UTC, ygree commented
Closing this as similar idea to persist matching result is implemented in #5026

2023-05-05 16:26 UTC, closed without merging