3143 add support for vertx web 4
DataDog/dd-trace-java pull request #3557
Opened 2022-05-16 10:34 UTC by LuboViluda

# What Does This Do
- providing support for Vert.x web 4
- Vert.x HttpServerResponseImpl class was replaced between versions 3 and 4. Reflect changes in instrumentation.
- Migrate other parts of code to Vert.x 4
- Migrate all Vert.x 3 tests to 4.

# Motivation
- provide instrumentation for Vert.x 4 (currently broken)

# Additional Notes / open questions
- some test fails currently: 
```
./gradlew :dd-java-agent:instrumentation:vertx-web-4.0:test
136 tests completed, 90 failed, 23 skipped
```
- What is a minimal test suite to get this merged? I couldn't really see from run of Vert.x vertx-3.4 tests what is the number of successful tests there as the final output doesn't provide this (the immediate step before the success message is showing around 130). But some constructs seem suspicious for Vert.x 3 test suite (fe. setting Vert.x clustering port for local test server - but maybe I'm lacking some internal Vert.x knowledge, why this is there)

2022-05-17 14:14 UTC, devinsba commented
Thanks @LuboViluda, I'm going to try to review this this week but unfortunately the vertx integrations are large so it may take a while

2022-05-17 14:34 UTC, devinsba requested changes
The version numbers will need to be addressed. Then just the one question

2022-05-17 14:34 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/HttpServerResponseEndHandlerInstrumentation.java
> +    super("vertx", "vertx-4.2");
The module name suggests you are targeting 4.0 so this version should match that

2022-05-17 14:34 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerInstrumentation.java
> +    super("vertx", "vertx-4.2");
Same comment here about the version number

2022-05-17 14:34 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteImplInstrumentation.java
> +    super("vertx", "vertx-4.2");
Same comment here about the version number

2022-05-17 14:34 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextImplInstrumentation.java
> +    super("vertx", "vertx-4.2");
Same comment here about the version number

2022-05-17 14:34 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
> +        .setConfig(new JsonObject().put(CONFIG_HTTP_SERVER_PORT, port))
Does vertx not support using 0 to get a random port number? We usually do that because we have had port conflict problems in CI in the past

2022-05-17 14:34 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-4.0/vertx-web-4.0.gradle
> +  main_java8CompileOnly group: 'io.vertx', name: 'vertx-web', version: '4.2.7'
Same comment here about the version number

2022-05-17 14:34 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-4.0/vertx-web-4.0.gradle
> +  testImplementation group: 'io.vertx', name: 'vertx-web-client', version: '4.2.7'
Same comment here about the version number

2022-05-20 15:58 UTC, LuboViluda commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/HttpServerResponseEndHandlerInstrumentation.java
> +    super("vertx", "vertx-4.2");
addressed

2022-05-20 16:00 UTC, LuboViluda commented on dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
> +        .setConfig(new JsonObject().put(CONFIG_HTTP_SERVER_PORT, port))
nice, I wasn't aware of this behavior with zero port. I added deploy to zero port + mechanism to propagate it to test. Unfortunately, it doesn't resolve failing test cases.

2022-05-20 17:28 UTC, devinsba requested changes
This will probably fix the tests

2022-05-20 17:28 UTC, devinsba commented on dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
> +import static server.VertxTestServer.CONFIG_HTTP_SERVER_PORT
```suggestion
import static datadog.trace.agent.test.base.HttpServerTest.ServerEndpoint.ERROR
import static datadog.trace.agent.test.base.HttpServerTest.ServerEndpoint.EXCEPTION
import static datadog.trace.agent.test.base.HttpServerTest.ServerEndpoint.LOGIN
import static datadog.trace.agent.test.base.HttpServerTest.ServerEndpoint.NOT_FOUND
import static datadog.trace.agent.test.base.HttpServerTest.ServerEndpoint.PATH_PARAM
import static datadog.trace.agent.test.base.HttpServerTest.ServerEndpoint.SUCCESS
import static server.VertxTestServer.CONFIG_HTTP_SERVER_PORT
```

2022-05-22 14:21 UTC, devinsba commented
You can see the failing tests here: https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/13590/workflows/64d950e9-c130-4d62-83b3-cecc8415eb39/jobs/298083/tests

Don't worry about the "instrumentation gateway" ones for now. The others like like they might just be a slight difference in how things were implemented

@ValentinZakharov can you see if there's an obvious reason that the instrumentation gateway tests failed?

2022-05-22 16:32 UTC, LuboViluda commented
> You can see the failing tests here: https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/13590/workflows/64d950e9-c130-4d62-83b3-cecc8415eb39/jobs/298083/tests
> 
> Don't worry about the "instrumentation gateway" ones for now. The others like like they might just be a slight difference in how things were implemented
> 
> @ValentinZakharov can you see if there's an obvious reason that the instrumentation gateway tests failed?

Thanks, double "/" in span resourceName is probably cause for a lot of failure, not sure if some toString/reporting Vert.x. method changed and broke this

```
assert span.resourceName.toString() == name
       |    |            |          |  |
       |    |            |          |  'GET /sub/success'
       |    |            |          false
       |    |            'GET /sub//success'
       |    GET /sub//success
```
from server.VertxSubrouterForkedTest

2022-05-24 13:41 UTC, LuboViluda commented
Hello [devinsba](https://github.com/devinsba),

I have committed change for correct path concatenation (deduplication of "//" to "/"). It fixed a nice number of tests. Fe. z_test_8_inst went from 32 failed tests to 4 failed tests (3 mentioning Gateway directly). Any idea how to fix Gateway related tests?

2022-05-24 15:22 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextImplInstrumentation.java
> +  }
The reason that the json body tests fail is that the signature of these two methods have changed, and they now take an `int` as argument. The code needs to be changed to this:

```
  @Override
  public void adviceTransformations(AdviceTransformation transformation) {
    transformation.applyAdvice(
        named("getBodyAsJson")
            .or(named("getBodyAsJsonArray"))
            .and(takesArguments(1).and(takesArgument(0, int.class))),
        packageName + ".RoutingContextJsonAdvice");
  }
```

2022-05-25 08:58 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextImplInstrumentation.java
> +  }
Sorry about the bad c'n'p, the code didn't compile. Here's a corrected one:

```
  @Override
  public void adviceTransformations(AdviceTransformation transformation) {
    transformation.applyAdvice(
        named("getBodyAsJson")
            .or(named("getBodyAsJsonArray"))
            .and(takesArguments(1))
            .and(takesArgument(0, int.class)),
        packageName + ".RoutingContextJsonAdvice");
  }
```

Also, you should probably run the formatting, or else the build will fail on that as well:

```
./gradlew formatCode
```

2022-05-25 12:30 UTC, LuboViluda commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextImplInstrumentation.java
> +  }
thanks! 3 more tests are fixed.

The weird thing about the last failing test is that it's not failed for all versions (I assume different pipeline steps are using a different version of java with the same test suite). Any suggestion for the last one?

2022-05-25 12:56 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextImplInstrumentation.java
> +  }
Hey as far as I can see it is failing on all the `inst` pipelines from `8` up to and including `15` which is the highest that will be tested (see `TODO Java 17:` comment in `vertx-web-4.0.gradle`).

I'll take a quick look at what has changed wrt the sub routers.

2022-05-25 12:59 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-web-4.0/vertx-web-4.0.gradle
> +  maxJavaVersionForTests = JavaVersion.VERSION_15
Is this true, or does this version work on Java 17?

2022-05-25 13:01 UTC, bantonsson commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerWrapperAdvice.java
> +    if (!handler.getClass().getName().startsWith(RouterImpl.class.getName())) {
This lambda no longer lives in the `RouterImpl` class but in the `RouteImpl` class. The statement can be changed to `if (!handler.getClass().getName().startsWith(RouteImpl.class.getName()))`, and include the class as well 😉

2022-05-31 08:47 UTC, LuboViluda commented on dd-java-agent/instrumentation/vertx-web-4.0/vertx-web-4.0.gradle
> +  maxJavaVersionForTests = JavaVersion.VERSION_15
seems Java 17 is supported by Vertx web 4.2 and above

https://vertx.io/blog/whats-new-in-vert-x-4-2/#java-17

2022-05-31 09:09 UTC, LuboViluda commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextImplInstrumentation.java
> +  }
thanks! I was confused by green Java 7 tests, it makes sense now

2022-05-31 11:45 UTC, LuboViluda commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerWrapperAdvice.java
> +    if (!handler.getClass().getName().startsWith(RouterImpl.class.getName())) {
Thanks!

2022-05-31 12:29 UTC, LuboViluda commented
@bantonsson @devinsba 
tests are passing now, thanks for all the suggestions. I fixed the static analysis check as well (was failing on usage String.replaceAll). 

Do you have any suggestions for failing the `system-tests` and `muzzle` build step?

2022-06-07 12:25 UTC, LuboViluda commented
> You can ignore the system-tests but we do need to fix muzzle. What the failure seems to be telling us is that one of the instrumentation classes works for more versions than the range `[4.0.0,5)`
> 
> ```
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.4.2 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.8.5 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.9.13 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.9.0 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.5.0 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.7.0 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.7.1 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.5.4 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.4.0 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.6.0 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.6.3 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> 
> > Task :dd-java-agent:instrumentation:vertx-web-4.0:muzzle-AssertFail-io.vertx-vertx-web-3.8.0 FAILED
> MUZZLE PASSED HttpServerResponseEndHandlerInstrumentation BUT FAILURE WAS EXPECTED
> ```
> 
> We usually fix this by adding a method to the advice class that depends on something that was added in the lowest version, see: https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/jetty-9/src/main/java/datadog/trace/instrumentation/jetty9/JettyServerInstrumentation.java#L147

Thanks for the suggestion @devinsba. I have already bound instrumentation on the class which was added in Vert.x 4 (similar as Vertx 3 instrumentation is doing it) in  [VertxVersionMatcher](https://github.com/DataDog/dd-trace-java/pull/3557/files#diff-3fd84a527cdefa49ba4b1e80d20767b2ba9e22c87d4d33c6064a694a6c43a6f6R11 ). The class should be in [Vertx 4](https://github.com/eclipse-vertx/vert.x/tree/4.1/src/main/java/io/vertx/core/http/impl), but not in the [Vertx 3](https://github.com/eclipse-vertx/vert.x/tree/3.9/src/main/java/io/vertx/core/http/impl). I will take another look, at if I ported changes correctly and what possibly could go wrong (maybe the class exist on other path in Vert.x 3.x)

2022-06-08 14:18 UTC, devinsba commented
I have a fix for muzzle if you can allow me push access to the branch: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

2022-06-08 15:13 UTC, mcculls commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/VertxVersionMatcher.java
> +public class VertxVersionMatcher {
@devinsba now that #3589 has been merged this class should be updated along the same lines as https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/VertxVersionMatcher.java

2022-06-08 15:14 UTC, mcculls commented on dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteImplInstrumentation.java
> +  }
@devinsba now that https://github.com/DataDog/dd-trace-java/pull/3589 has been merged this class should be updated along the same lines as https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/RouteImplInstrumentation.java#L24

2022-06-08 17:46 UTC, LuboViluda commented
> I have a fix for muzzle if you can allow me push access to the branch: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

It's seems it's on by default.

![image](https://user-images.githubusercontent.com/9551795/172683211-70d98ff2-e188-467f-907c-ee0e90373f6e.png)

2022-06-09 13:21 UTC, devinsba approved these changes
LGTM. Thanks!

2022-06-14 15:47 UTC, merged