Telemetry; support for reporting dependencies
DataDog/dd-trace-java pull request #3559
Opened 2022-05-17 10:17 UTC by cataphract

# What Does This Do

Sends telemetry data to the agent. Right now, only host information and dependencies are reported.
Dependencies are collected by installing a transformer that collects URLs from unique protection domains. The telemetry thread wakes up every 10 seconds to try and determine the name, version and possibly hash for the dependency associated with the URL.

2022-05-18 14:15 UTC, devinsba reviewed
Can you add in the code and instructions for how you generated the binary files used in the tests

2022-05-18 15:14 UTC, devinsba commented
Ah, can you at least include the spring-boot-app.jar source. If not instead of adding the source can you at least add a doc in that directory for how and why you generated the files the way you did? If we don't have that written down the tests become nearly impossible to change for anyone except you

2022-05-24 11:39 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/dependency/LocationsCollectingTransformer.java
> +        uri = location.toURI();
This will actually both create a `String` from the `location` which is a `URL`, and then parse that `String`. Maybe it can be done on the side?

2022-05-24 11:39 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/dependency/LocationsCollectingTransformer.java
> +        uri = getJbossVfsPath(location);
This also feels _costly_. Can it be done in the helper `Thread`?

2022-05-24 11:39 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/Platform.java
> +  static final class JmvRuntime {
`JvmRuntime` would be even better

2022-05-24 11:39 UTC, bantonsson commented on telemetry/src/test/groovy/datadog/telemetry/UnameTest.groovy
> +  void 'can obtain the data via libc'() {
Can't we check the values against the output of the `uname` command?

2022-05-24 11:40 UTC, bantonsson commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/dependency/Dependency.java
> +    while (entry.hasMoreElements()) {
I know it happens on the background thread, but it is still iterating through jar files that can potentially have a large number of entries.

2022-05-27 13:38 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
> +    // TODO: Telemetry should be moved out of appsec
Most of the telemetry is in a module apart; the exception being the dependency collection which in the appsec (it's not yet clear whether dep collection is meant to be part of appsec), but it's now loaded in the appsec classloader and therefore enabled only when appsec is enabled. Do you think this is an agreeable (interim) state of affairs?

2022-05-27 13:53 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/dependency/LocationsCollectingTransformer.java
> +        uri = location.toURI();
I'm moving it to the other thread and storing just the URL.

2022-05-27 13:53 UTC, cataphract commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/dependency/LocationsCollectingTransformer.java
> +        uri = getJbossVfsPath(location);
idem

2022-06-08 11:59 UTC, bantonsson requested changes
Mostly minor nitpicks, but the `hash` computation and memory allocation around it needs further discussion.

2022-06-08 11:59 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/ConfigCollector.java
> +    public static final ConfigCollector INSTANCE = new ConfigCollector();
Why is the `Holder` class and `INSTANCE` field `public`? Shouldn't they only be accessed from `get()`? Then they can both be `private`, and in all other places as well.

2022-06-08 11:59 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/ConfigCollector.java
> +    public static final ConfigCollector INSTANCE = new ConfigCollector();
I'm not really a fan of these _singletons_, but I guess it's a necessity since other things like the `Config` is a singleton, and that is accessed very early.

2022-06-08 11:59 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
> +    TELEMETRY("dd-agent-telemetry"),
The `agent` in this is confusing, since `agent` is used for the Datadog Agent, and not the Java Tracer. I think that `dd-telemetry` is enough.

2022-06-08 11:59 UTC, bantonsson commented on telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
> +            .os(System.getProperty("os.name"))
Why is this not part of the `HostInfo`?

2022-06-19 21:18 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +  private static boolean telemetryEnabled = true;
Thanks, Fixed default value.

2022-06-19 21:18 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +import static datadog.trace.api.ConfigDefaults.*;
Done

2022-06-19 21:18 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +import static datadog.trace.api.config.GeneralConfig.*;
Done

2022-06-19 21:18 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
> +    TELEMETRY("dd-agent-telemetry"),
Name changed to `dd-telemetry` as suggested

2022-06-19 21:20 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
> +            .os(System.getProperty("os.name"))
Fixed

2022-06-19 21:21 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
> +            .kernelVersion(Uname.UTS_NAME.version())
Impproved

2022-06-19 21:23 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
> +    log.info("Adding APP_STARTED telemetry event");
Yes, you are correct. Fixed logging across entire module.

2022-06-19 21:31 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
> +      // No reliable version calculate hash and use any version
If artifact name/version can't be guessed, then we calculate the `hash` of the jar file and report it. On the backend side, the `Dependency Recognition Service` will pull info from Maven repository based on hash to get the name and version of the dependency.

2022-06-19 21:35 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
> +      byte[] buf = new byte[8192];
Fixed.

2022-07-11 11:06 UTC, bantonsson commented on telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
> +      // No reliable version calculate hash and use any version
I'm still not sure how many hits we will  get here in the end, but I don't think that it can hurt since we probably won't do this that often.

2022-07-11 11:19 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/ConfigCollector.java
> +    public static final ConfigCollector INSTANCE = new ConfigCollector();
Still don't see why the `Holder` class needs to be `public`

2022-07-11 11:20 UTC, bantonsson approved these changes

2022-07-11 11:25 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/Platform.java
> +  static final class JmvRuntime {
Fixed

2022-07-11 11:27 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
> +      // No reliable version calculate hash and use any version
I'm planning to run telemetry on our internal services to collect to get some data about how many of the dependencies will need a hash calculation

2022-07-11 11:28 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/ConfigCollector.java
> +    public static final ConfigCollector INSTANCE = new ConfigCollector();
Fixed

2022-07-13 10:51 UTC, merged