Add agent-crashreporting to upload crash uploader
DataDog/dd-trace-java pull request #3594
Opened 2022-06-15 22:01 UTC by luhenry

# What Does This Do

# Motivation

# Additional Notes

2022-06-16 14:44 UTC, luhenry commented
cc @iglendd WIP for uploading crash file with `-XX:OnError`

2022-07-07 09:36 UTC, ValentinZakharov commented
I'm curious, why you are reading some options directly from `configProvider` rather than default way using the `config` ?

2022-07-07 11:47 UTC, jbachorik requested changes

2022-07-07 11:47 UTC, jbachorik commented on dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
> +  static final String V4_ATTACHMENT_NAME = "main";
These constant don't seem to be used anywhere in the PR changes. Are they still requied?

2022-07-07 11:47 UTC, jbachorik commented on dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
> +  static final String REQUEST_TYPE = "logs";
These all fields seem to be used solely from `CrashUploader` class. Can they be made `prviate`?

2022-07-07 11:47 UTC, jbachorik commented on dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
> +    this.configProvider = configProvider;
I wonder - can the config be accessed using `ConfigProvider` only? It seems to be a bit of overkill using two different ways to access the same data in one method.

2022-07-07 11:47 UTC, jbachorik commented on dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
> +    tags = String.join(",", tagsToList(tagsMap));
Perhaps the intermediary list can be avoided by using the filtered `tagsMap` stream and collecting the elements via `Collectors.joining(",")`

2022-07-07 11:47 UTC, jbachorik commented on dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
> +  }
See my previous comment - this may become:
```suggestion
  private String tagsToString(final Map<String, String> tags) {
    return tags.entrySet().stream()
        .filter(e -> e.getValue() != null && !e.getValue().isEmpty())
        .map(e -> e.getKey() + ":" + e.getValue())
        .collect(Collectors.joining(",");
  }
```

2022-07-07 11:47 UTC, jbachorik commented on dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
> +          .value("5e5b1180-2a0b-41a6-bed2-bc341d19f853");
😬

2022-07-07 11:47 UTC, jbachorik commented on dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
> +      // runtime_id
Do you want to keep this commented out?

2022-07-07 11:47 UTC, jbachorik commented on dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/CrashUploaderTest.java
> +  public void testHappyPath() {}
Could you add some simple test cases here?

2022-07-07 12:12 UTC, jbachorik commented on dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
> +    this.configProvider = configProvider;
Ok. Makes sense. Not ideal but that's what we have now :(

2022-07-08 08:00 UTC, ValentinZakharov commented on dd-java-agent/agent-crashtracking/agent-crashtracking.gradle
> +minimumInstructionCoverage = 0.0
Don't forget to increase coverage, when will add tests.

2022-07-21 10:03 UTC, jbachorik commented on internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
> +public class ConfigProvider {
This seems to be unnecessary

2022-07-21 10:03 UTC, jbachorik approved these changes
Please, make `ConfigProvider` final again.
Otherwise, LGTM!

2022-07-21 14:31 UTC, merged

2022-08-03 20:27 UTC, devinsba commented on utils/process-utils/process-utils.gradle
> +}
I just noticed, `:utils:process-utils` never got added to `settings.gradle`, is that intentional?

2022-08-03 20:45 UTC, mcculls commented on utils/process-utils/process-utils.gradle
> +}
it was added [here](https://github.com/DataDog/dd-trace-java/pull/3594/files#diff-7f825392aa37acd1cee0c2e7b9bb7366ad6eac64f3e6cdd816e156bcb69d30deR79) and is in the latest `settings.xml`: https://github.com/DataDog/dd-trace-java/blob/master/settings.gradle#L79

2022-08-03 20:46 UTC, devinsba commented on utils/process-utils/process-utils.gradle
> +}
Whelp, I didn't notice my rebase failed :(