Piotr wolski/always propagate pathway context
DataDog/dd-trace-java pull request #3638
Opened 2022-07-05 16:58 UTC by piochelepiotr

# What Does This Do

# Motivation

# Additional Notes

2022-07-07 16:32 UTC, piochelepiotr commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +  private String group;
Good point. Right now, yes, but it's safer to put protect these variables with the lock.
That means I should also mark them as `volatile`, is that correct?

Also, I would prefer to put these parameters to `startSpan`, but I haven't found a clean way to do it.

2022-07-07 19:49 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +  private String group;
volatile would still allow racy interactions between the fields.  If they should be set atomically, you have two options.  synchronized/Lock on read and write.  Or create an immutable object to hold all the fields, then construct an instance of that object and place in a volatile field.

Since this is done rarely, I think I'd just go with synchronization.

2022-07-11 12:16 UTC, piochelepiotr commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +  private String group;
Sorry about my ignorance, but shouldn't the lock be enough? 
I re-used the lock that the object already had.

2022-07-11 19:18 UTC, hokitam commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedPathwayContext.java
> +public class ExtractedPathwayContext implements AgentSpan.Context.Extracted {
I don't feel strongly about this either way! I just wasn't quite sure what the intended usage was for the Extracted interface, but agree that we'll want to be careful about crashes.

2022-07-11 21:00 UTC, randomanderson requested changes
Overall a valiant effort for someone not familiar with the Java tracer. I have some inline comments.

Aside from code, I have some other concerns:
- **The new extract/inject assumes base64 encoding**. How does this work in mixed environments with Go and Java? Unless I'm missing something, I think it breaks. I think you either have to encode the protocol into the context with a marker or use a different header.
- **Checkpoints are only created when a root span is created**. This is a departure from the previous behavior. If a user creates a span, then reads from kafka, no checkpoint is created

2022-07-12 02:38 UTC, hokitam commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +  public void setQueueTags(String type, String group, String topic) {
I'm still learning about rabbitmq, but is "consumer group" a concept that is specific to kafka? from this stackoverflow answer (https://stackoverflow.com/questions/48956267/rabbitmq-multiple-instances-reading-from-the-same-topic)

also wondering whether this might be the case for other non-kafka queues. if so, do we want to be more flexible about tags, and have a method to set key-value pairs instead?

2022-07-14 23:04 UTC, hokitam commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
> +  public final TagContext withPathwayContext(PathwayContext pathwayContext) {
fixed!

2022-07-18 21:23 UTC, hokitam commented
Looked into Piotr's suggestion, and updated the PR to call setCheckpoint directly in the decorators, right after propagate().extract() is called. This allows us to turn on support for each types of service individually. With this change instrumentation looks to be working for kafka, grpc, and rabbitmq. Laplie, can you PTAL and see if you think this approach makes sense?

Meanwhile we'll work on your other suggestions on base64 encoding

2022-07-19 17:04 UTC, piochelepiotr commented on dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
> -          span.mergePathwayContext(pathwayContext);
We discussed offline, fan-in is not supported for now, this fan-in was always on a span containing no data stream context, so it wasn't really a fan-in.

2022-07-19 21:28 UTC, hokitam commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    return spanContext;
Updated the PR, such that we brought back extractPathwayContext. Marking this as resolved, thanks!

2022-07-19 21:28 UTC, hokitam commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +  public void setQueueTags(String type, String group, String topic) {
removed setQueueTags in latest implementation, marking as resolved.

2022-07-19 21:29 UTC, hokitam commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +    }
updated the PR's behavior to retain separate injectPathwayContext and extractPathwayContext call, so this code is obsolete. Marking as resolved. thanks!

2022-07-21 17:42 UTC, randomanderson approved these changes
I had one nit about `tags` being null but otherwise, I think this is good to go

2022-07-21 17:42 UTC, randomanderson commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +      }
Is there a valid case where `tags` is `null`? I think it should be an empty list if there are no tags with `null` being invalid.

```suggestion
      edgeTags.addAll(tags);
```

2022-07-21 18:16 UTC, hokitam commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +  private String group;
resolving this discussion as we no longer have these fields

2022-07-21 23:11 UTC, hokitam commented
`z_test_17_inst` (flaky) passed on a rerun, so all checks are successful. Merging.

2022-07-21 23:11 UTC, merged