Util to get stacktrace for reported vulnerabilities
DataDog/dd-trace-java pull request #3647
Opened 2022-07-11 14:09 UTC by jandro996

# What Does This Do

Util to do partial walks through the stack excluding elements that belong to DataDog trace project. This PR has default implementation that works with all JDKs.

# Motivation

This utility is necessary for IAST, when we detect vulnerabilities we need vulnerability class and line that usually match the first one that is out of dd-trace-java project

# Additional Notes

**First version** with default implementation. We plan to develop future implementations that improve performance for JDK9+([StackWalker](https://docs.oracle.com/javase/9/docs/api/java/lang/StackWalker.html))  and JDK8 with HotSpot [(JavaLangAccess)](https://github.com/openjdk/jdk/blob/jdk8-b120/jdk/src/share/classes/sun/misc/JavaLangAccess.java)

2022-07-12 12:48 UTC, smola requested changes

2022-07-13 11:41 UTC, manuel-alvarez-alvarez commented on internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackWalker.java
> +  protected Stream<StackTraceElement> doGetStack() {
Maybe you can drop a comment explaining that this method can be overriden by subclasses (for instance an implementation using JDK9 stack walker)

2022-07-13 11:46 UTC, manuel-alvarez-alvarez commented on internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/StackWalkerTest.java
> +            stackTraceElement -> stackTraceElement.toString().startsWith("com.datadog.appsec.")));
Since the stack does not contain any `com.datadog.appsec.` classes ... this test does not provide any value. Maybe you can create a mock class in that package, same way as it's done with `Foo`.

2022-07-13 11:51 UTC, manuel-alvarez-alvarez commented on internal-api/internal-api-8/src/test/java/com/foo/Foo.java
> +package com.foo;
If bytebuddy is included as a test dependency you can create the classes on the fly giving you more flexibitily for the tests (for instance allowing you to choose the package)

2022-07-14 04:36 UTC, anderruiz commented on internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackWalker.java
> +          .collect(Collectors.toCollection(HashSet::new));
I would prefer to create a predicate instead of an Set that then is transformed to an Stream to create a predicate (for each stack line)

2022-07-14 04:38 UTC, anderruiz commented on internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackWalker.java
> +  protected Stream<StackTraceElement> doGetStack() {
I would even say that we should not implement this method here and do it in another class (I know why you did it)

2022-07-14 04:40 UTC, anderruiz commented on internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/StackWalkerFactory.java
> +        .orElse(new DefaultStackWalker());
At this point we know DefaultStackWalker will return true, so, or we do not include in the Stream or we remove .orElse

2022-07-14 04:43 UTC, anderruiz commented on internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/StackWalkerTest.java
> +  private static Supplier<Stream<StackTraceElement>> getSupplier(final String clazzName)
What is this method doing?

2022-07-14 04:45 UTC, anderruiz commented on internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackWalker.java
> +          .collect(Collectors.toCollection(HashSet::new));
```suggestion
          protected static Predicate<String> filteredPackages = (cn)->!cn.startsWith("datadog.trace.")&&!cn.startsWith("com.datadog.appsec.)
```

2022-07-14 04:47 UTC, anderruiz commented on internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackTraceGenerator.java
> +    return doGetStack().filter(e -> isNotDDTraceClass(e.getClassName()));
No, our classes were always excluded

2022-07-14 07:26 UTC, manuel-alvarez-alvarez commented on internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/StackWalkerTest.java
> +  private static Supplier<Stream<StackTraceElement>> getSupplier(final String clazzName)
It dynamically generates mock classes in custom packages to validate stack trace filtering. Another possible and maybe cleaner option would be to separate the testing logic to build the stack from the one to filter it (this way we can create mocks of the full stack giving us more fine grained control)

2022-07-15 06:50 UTC, smola approved these changes

2022-07-15 07:18 UTC, manuel-alvarez-alvarez approved these changes

2022-07-26 12:52 UTC, smola approved these changes

2022-07-27 14:11 UTC, devinsba reviewed
I think we can avoid `new Throwable()` in most places by using `Thread.currentThread()` to get the stacktrace instead

2022-07-27 14:11 UTC, devinsba commented on gradle.properties
> +org.gradle.java.installations.fromEnv=JAVA_HOME,JAVA_8_HOME,JAVA_11_HOME
This change shouldn't be necessary. `JAVA_HOME` and `JAVA_8_HOME` should be equivalent

2022-07-27 14:11 UTC, devinsba commented on internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackWalker.java
> +    return consumer.apply(Arrays.stream(new Throwable().getStackTrace()));
This would avoid allocation of a throwable object unnecessarily 
```suggestion
    return consumer.apply(Arrays.stream(Thread.currentThread().getStackTrace()));
```

2022-07-28 09:05 UTC, jandro996 commented
> 

We changed it in `DefaultStackWalker` but `HotSpotStackWalker` needs `Throwable`  to use `sun.misc.JavaLangAccess` api

2022-07-28 09:06 UTC, jandro996 commented
> I think we can avoid `new Throwable()` in most places by using `Thread.currentThread()` to get the stacktrace instead

We changed it in `DefaultStackWalker` but `HotSpotStackWalker` needs `Throwable`  to use `sun.misc.JavaLangAccess` api

2022-07-28 12:13 UTC, jandro996 commented on gradle.properties
> +org.gradle.java.installations.fromEnv=JAVA_HOME,JAVA_8_HOME,JAVA_11_HOME
Yes it seems redundant...  

We need a way to make this config work https://github.com/DataDog/dd-trace-java/blob/e28c1be6b194910664a8064d04f8faf5c9973e7c/internal-api/internal-api-8/internal-api-8.gradle#L17-L21

**CodeQL build** and **Lib injection test** try to build dd-java-agent.jar

https://github.com/DataDog/dd-trace-java/blob/63cc87143a0e3f6d0c0d3ea3b40facf1e3526eda/.github/workflows/codeql-analysis.yml#L38-L39

https://github.com/DataDog/dd-trace-java/blob/63cc87143a0e3f6d0c0d3ea3b40facf1e3526eda/.github/workflows/test-lib-injection.yaml#L44-L45

and our configuration breaks it with this error

```
Where:
Script '/home/runner/work/dd-trace-java/dd-trace-java/gradle/java_no_deps.gradle' line: 265

What went wrong:
A problem occurred evaluating project ':internal-api:internal-api-8'.
No compatible toolchains found for request filter: {languageVersion=8, vendor=any, implementation=vendor-specific} (auto-detect false, auto-download false)
```

At this moment we found 2 possible approaches:

- ~~Edit  `gradle.properties` to add JAVA_HOME allowing valid toolchains search~~

- Edit `codeql-analysis.yml` and `test-lib-injection.yaml` to define `JAVA_8_HOME`

2022-07-29 14:26 UTC, anderruiz approved these changes

2022-08-02 07:47 UTC, smola commented on .github/workflows/codeql-analysis.yml
> +      - name: Checkout repository
Can you avoid changing formatting here, just changing the relevant value?

2022-08-02 09:18 UTC, jandro996 commented on .github/workflows/codeql-analysis.yml
> +      - name: Checkout repository
This change is the result of apply spotless automatic code formatting

2022-08-09 14:57 UTC, bantonsson approved these changes
I think the performance tables has `Deep` and `Limit` headings mixed up, but apart from that 👍🏻

2022-08-10 07:10 UTC, merged