Jsantos/invalid hash
DataDog/dd-trace-java pull request #3649
Opened 2022-07-11 17:23 UTC by DDJavierSantos

Insecure Hashing instrumentation and configuration

2022-07-12 12:50 UTC, smola commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +package datadog.trace.instrumentation.insecurehash;
I think we might want to add this to a `jdk` module? Something like `jdk.insecurehash` (both at Gradle module level and Java package level).

2022-07-12 12:50 UTC, smola commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +  //@Override
Please, remove any commented code from the final PR.

2022-07-12 12:52 UTC, smola commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/MessageDigestAdvice.java
> +    if (Config.get().getInsecureHashingAlgorithms().contains(algorithm)){
We need to define the API to call our vulnerability detection logic from aspects. I bet it won't be in `Config`. I guess we'll have something like `IastEvents.hashAlgorithmFound(algorithm)`.

cc @manuel-alvarez-alvarez

2022-07-12 12:54 UTC, smola commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  static final Set<String> DEFAULT_IAST_INSECURE_HASHING_ALGORITHMS = new HashSet<>(Arrays.asList("MD2","RSA-MD4","md4","MD5","SHA")) ;
I think it should be `"SHA-1"` here. Also, what happens with uppercase/lowercase variants?

2022-07-12 15:49 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/MessageDigestAdvice.java
> +    if (Config.get().getInsecureHashingAlgorithms().contains(algorithm)){
But since it will eventually be configurable, it will involve config, right? the code that I added to the Config function?

2022-07-12 15:50 UTC, DDJavierSantos commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  static final Set<String> DEFAULT_IAST_INSECURE_HASHING_ALGORITHMS = new HashSet<>(Arrays.asList("MD2","RSA-MD4","md4","MD5","SHA")) ;
this are the ids in java. There are aliases as well. I will add them. Also, we should probably uppercase the argument so we don't need to care about uppercase.

2022-07-13 13:06 UTC, smola commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/MessageDigestAdvice.java
> +    if (Config.get().getInsecureHashingAlgorithms().contains(algorithm)){
Amending my previous comment: yes, the list of algorithms might involve config, but we'll want to decouple the instrumentation from the detection logic. So this detection and reporting will eventually be in the IAST module, not embedded into each instrumentation module.

2022-07-13 14:49 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +package datadog.trace.instrumentation.insecurehash;
I think it might be better to treat the JDK as a library and group all instrumentation targeting JDK classes in a single gradle module (this one can have different submodules for each JDK version or flavour(

2022-07-13 14:51 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +  protected boolean defaultEnabled() {
Isn't this already implied by extending `Instrumenter.AppSecIast`?

2022-07-13 15:15 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/MessageDigestAdvice.java
> +    if (Config.get().getInsecureHashingAlgorithms().contains(algorithm)){
I agree with pretty much everything Santiago said already, doing the separation between instrumentation and IAST logic will be beneficial in the long run.

2022-07-14 04:52 UTC, anderruiz commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +package datadog.trace.instrumentation.insecurehash;
I agree with both. Keep in mind that most of the instrumentation will end up in that module anyway

2022-07-14 04:55 UTC, anderruiz commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +    super("insecurehash");
```suggestion
    super("weakhash");
```

2022-07-14 04:56 UTC, anderruiz commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +        InsecureHashInstrumentation.class.getName() + "$MessageDigestAdvice");
```suggestion
        WeakHashInstrumentation.class.getName() + "$MessageDigestAdvice");
```

2022-07-14 04:58 UTC, anderruiz commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +
Could we use ClassNameTrie or something similar not to have the list here?

2022-07-14 04:58 UTC, anderruiz commented on dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
> +      "appsec.iast.insecure_hashing_algorigthms";
```suggestion
      "appsec.iast.insecure_hashing_algorithms";
```

2022-07-14 05:01 UTC, anderruiz commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +      if (Config.get().getInsecureHashingAlgorithms().contains(algorithm)) {
Shouldn't we cache Config?

2022-07-14 05:03 UTC, anderruiz commented on settings.gradle
> +include ':dd-java-agent:instrumentation:insecurehash'
```suggestion
include ':dd-java-agent:instrumentation:weakhash'
```

2022-07-14 05:58 UTC, anderruiz commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +      if (Config.get().getInsecureHashingAlgorithms().contains(algorithm)) {
There are additional filtering features that we should include here

2022-07-15 10:54 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/insecurehash/src/main/java/datadog/trace/instrumentation/insecurehash/InsecureHashInstrumentation.java
> +package datadog.trace.instrumentation.insecurehash;
finally it has been agreed to create a instrumentation module named java-security

2022-07-21 12:35 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/java-security/java-security.gradle
> +  testImplementation group: 'org.bouncycastle', name: 'bcprov-jdk18on', version: '1.71'
You are using `Bouncy Castle Provider` for jdk 1.8+, but some of our CircleCI tests are running on jdk 1.7 and as the result `bouncycastle` tests are failing. May be it make sense to use older version - `bcprov-jdk15on`, or prevent to run this test in java7.

2022-07-21 12:40 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakHashInstrumentation.java
> +  }
I'm sorry, I don't get what was the reason of overriding `isEnabled()` if we call base method?

2022-07-26 13:27 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/java-security/java-security.gradle
> +  testImplementation group: 'org.bouncycastle', name: 'bcprov-jdk18on', version: '1.71'
Done

2022-07-26 13:27 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakHashInstrumentation.java
> +  }
Done

2022-08-23 07:01 UTC, jbachorik commented
This is looking funny - the PR is showing like you are going to re-apply all 100+ commits which are already in master.
Can you, please, recheck and make sure only the real changes are to be reviewed?

2022-08-23 14:14 UTC, smola commented on dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakHashInstrumentation.java
> +      if (Config.get().getWeakHashingAlgorithms().contains(algorithm.toUpperCase())) {
Please, just call the callback here directly, without checking anything else. That way we keep the logic in a single place, and we don't need to check for the algorithm twice.

2022-08-24 07:03 UTC, team-sourcecodeintegration commented on dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakHashInstrumentation.java
> +      if (Config.get().getWeakHashingAlgorithms().contains(algorithm.toUpperCase())) {
Done

2022-08-24 09:21 UTC, bantonsson approved these changes

2022-08-25 13:59 UTC, smola requested changes

2022-08-25 13:59 UTC, smola commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
> +              .findFirst()
You need to do `.findFirst().get()` within the `walk` call. The stream is not valid once it leaves the scope of `walk`.

2022-08-26 08:03 UTC, smola approved these changes

2022-08-26 10:02 UTC, merged