Added exception catches for the OkHTTPClient header vulnerability
DataDog/dd-trace-java pull request #3682
Opened 2022-07-28 18:54 UTC by nayeem-kamal

# What Does This Do
The exceptions added prevent the header secrets from being printed when non-printable characters cause IllegalArgument Exceptions.
# Motivation

# Additional Notes

2022-07-28 19:03 UTC, devinsba commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/OkHttpUtils.java
> +    } catch (IllegalArgumentException e) {
Undo this one, no use of header or addHeader

2022-07-28 19:03 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
> +    } catch (IllegalArgumentException e) {
Undo this one, no use of header or addHeader

2022-07-28 19:07 UTC, devinsba commented on communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
> +      } catch (IllegalArgumentException e) {
Undo this one, no use of header or addHeader

2022-07-28 19:14 UTC, devinsba commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +      log.warn("IllegalArgumentException at OkHttpUtils.class");
Remove log

2022-07-28 19:33 UTC, devinsba commented on communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
>        Map<String, ?> config = (Map<String, ?>) info.get("config");
We can undo all changes to this file

2022-07-28 19:33 UTC, devinsba commented on communication/src/main/java/datadog/communication/fleet/FleetServiceImpl.java
> +      headers = Collections.singletonMap(CONFIG_PRODUCT_HEADER, product.name());
We can undo all changes to this file

2022-07-28 19:33 UTC, devinsba commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
> +      throw new IllegalArgumentException();
We can remove this one

2022-07-28 19:33 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/common/metrics/OkHttpSink.java
>    private void handleFailure(okhttp3.Response response) throws IOException {
We can undo all changes to this file

2022-07-28 19:33 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
>  }
We can undo all changes to this file

2022-07-28 19:33 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDIntakeApi.java
> +    } catch (IllegalArgumentException e) {
We can remove this one

2022-07-28 19:33 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDIntakeApi.java
We can undo all changes to this file

2022-07-28 21:09 UTC, ygree requested changes
I suggest extracting this logic into utility methods to keep it separate and avoid large try-catch blocks

2022-07-28 21:09 UTC, ygree commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
> +        requestBuilder.addHeader(HEADER_DD_API_KEY, apiKey);
We could possibly extract safe adding header logic into the utility static methods, in order to avoid large try-catch blocks. E.g.

```java
//...
return safeAddHeader(response
        .request()
        .newBuilder(),
    "Proxy-Authorization", credential)
    .build();
}
                    
private static Request.Builder safeAddHeader(Request.Builder b, String name, String value) {
  // TODO                                                                                   
  return b;                                                                                 
}                                                                                           
```

2022-07-28 21:09 UTC, ygree commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
> +        requestBuilder.addHeader(HEADER_DD_API_KEY, apiKey);
There could be a few utility methods for setting/adding individual header or a list of headers. It would allow to keep this logic separate and avoid wrapping large parts of code with a try-catch block. Also it would provide access to useful context such as invalid header key that could be used in the error message.

2022-07-29 08:10 UTC, ValentinZakharov commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +                  throw new IllegalArgumentException(
What was the original exception message? I'd rather to re-throw exception with sanitised message, instead of provide a custom once 🤔 

Something like this:
```
} catch (IllegalArgumentException e) {
    String msg = e.getMessage().replace(credential, "<redacted>");
    throw new IllegalStateException(msg);
}
```

2022-07-29 08:27 UTC, ValentinZakharov commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +                  throw new IllegalArgumentException(
Or even some common approach for all cases:
```
} catch (IllegalArgumentException e) {
  throw sanitiseException(e, credential);
}
...
private Exception sanitiseException(Exception e, String... values) {
  String msg = e.getMessage();
  for (String value : values) {
    msg = msg.replaceAll(value, "<redacted>");
  }
  return e.getClass().getConstructor(String.class).newInstance(msg);
}

2022-07-29 14:54 UTC, nayeem-kamal commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +                  throw new IllegalArgumentException(
> What was the original exception message? I'd rather to re-throw exception with sanitised message, instead of provide a custom once 🤔
> 
> Something like this:
> 
> ```
> } catch (IllegalArgumentException e) {
>     String msg = e.getMessage().replace(credential, "<redacted>");
>     throw new IllegalStateException(msg);
> }
> ```

Based on the original issue (https://github.com/square/okhttp/issues/6738) , it looks like the  original message being printed/logged is what we are trying to prevent as the message can contain secrets that are in the headers:
```java.lang.IllegalArgumentException: Unexpected char 0x0a at 20 in Authorization value: very-secret-password\n```

2022-07-29 15:11 UTC, devinsba commented
I'm on board with the changes @ygree suggested. It changes the structure more but I like that it gives us the ability to report the header in the new exception

2022-07-29 16:07 UTC, ygree commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
> +        requestBuilder.addHeader(HEADER_DD_API_KEY, apiKey);
Or it could even be an adapter class that mimics Request.Builder's interface, delegates to Request.Builder and does some extra work to make it safe.

2022-08-01 15:45 UTC, ygree requested changes

2022-08-01 15:45 UTC, ygree commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +                return new SafeRequestBuilder.Builder(response.request())
I'd limit SafeRequest to Request.Builder instead of Request and pass `response.request.newBuilder()` as a parameter.

2022-08-01 15:45 UTC, ygree commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +  /*
I think SafeRequestBuilder Java Doc is enough and this comment can be removed.

2022-08-01 15:45 UTC, ygree commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +      safeAddHeader(builder, DD_API_KEY, apiKey);
The safeAddHeader method belongs to SafeRequestBuilder and already implemented as `SafeRequestBuilder.addHeader`. This could reused here:

```java
new SafeRequestBuilder(builder).addHeader(DD_API_KEY, apiKey).getRequestBuilder()
```

2022-08-01 15:45 UTC, ygree commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
> +    // SafeRequestBuilder is used here because of a vulnerability in okhttp3
I think this comment is unnecessary because it's already explained in SafeRequestBuilder Java Doc.

2022-08-01 15:45 UTC, ygree commented on dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
> +    try {
This try-catch seems to be unnecessary. Just wrap Request.Builder into SafeRequestBuilder and unwrap when it's passed into HTTP_CLIENT.newCall. This would keep the change scope to minimum here.

2022-08-01 15:45 UTC, ygree commented on telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
> +    try {
Looks like this try-catch is not needed anymore as this logic is already handled in SafeRequestBuilder.addHeader

2022-08-01 18:30 UTC, ygree approved these changes
LGTM

2022-08-01 20:37 UTC, devinsba approved these changes

2022-08-01 20:37 UTC, devinsba commented on communication/src/main/java/datadog/communication/http/SafeRequestBuilder.java
> +  public static class Builder {
You probably don't need the additional layer of a second class here. There aren't any methods in the outer class so moving all the methods out will create one less class file

2022-08-02 13:23 UTC, ValentinZakharov approved these changes

2022-08-02 13:23 UTC, ValentinZakharov commented
Perfect solution! 👍

2022-08-02 13:27 UTC, devinsba approved these changes

2022-08-02 13:27 UTC, devinsba commented on communication/src/main/java/datadog/communication/http/OkHttpUtils.java
> +      builder = new SafeRequestBuilder(builder).addHeader(DD_API_KEY, apiKey).getBuilder();
Maybe instead of allocating a new object here there should be a static `addHeader` method such as:
```
builder = SafeRequestBuilder.addHeader(builder, DD_API_KEY, apiKey);
```
Since the builder already exists it feels wasteful to create another object to check a single header

2022-08-02 18:12 UTC, merged