Alejandro.gonzalez/overhead control engine v0
DataDog/dd-trace-java pull request #3694
Opened 2022-08-02 11:43 UTC by jandro996

# What Does This Do

Implement Overhead Control Engine (OCE) for IAST operations

# Motivation

Low overhead is a mandatory requirement for a software that is running in production. The main constraint is that having to introduce many hooks for taint tracking keeping a low overhead is a challenging task.

The OCE is an element that by design ensures that the overhead does not go over a maximum limit. It will measure operations being executed in a request and it will deactivate detection (and therefore reduce the overhead to nearly 0) if a certain threshold is reached.

# Additional Notes

First approach set threshold to **2 concurrent analysed request** and **2 vulnerabilities per analysed request**

2022-08-02 19:59 UTC, dougqh commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastRequestContext.java
> +    vulnerabilities = new ConcurrentLinkedQueue<>();
We're not allowed to have any unbounded data structures.

2022-08-02 20:01 UTC, dougqh commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastRequestContext.java
> +    vulnerabilities = new ConcurrentLinkedQueue<>();
You are probably also better off with a a synchronized list than a concurrent linked queue for performance reasons.  The list needs to be thread safe, but if it is primarily accessed from a single thread a synchronized ArrayList will be better.

2022-08-02 20:33 UTC, dougqh commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastRequestContext.java
> +    final RequestContext reqCtx = span.getRequestContext();
Yes, this makes sense.  Long term, I'd like to flip this so that every span has an owning request context, but this is fine for now.

2022-08-02 20:34 UTC, dougqh commented on dd-java-agent/iast/src/main/java/com/datadog/iast/oce/OverheadController.java
> +  protected boolean requestAnalyzed = false;
This needs to be thread safe.

2022-08-02 20:36 UTC, dougqh commented on dd-java-agent/iast/src/main/java/com/datadog/iast/oce/OverheadController.java
> +  public static Quota hasQuota(final LongRunningOperation operation, final AgentSpan span) {
This method has an odd name.  It sounds like it would return a boolean but its unconditionally constructing a Quota.

2022-08-02 20:37 UTC, dougqh commented on dd-java-agent/iast/src/main/java/com/datadog/iast/oce/OverheadController.java
> +    return new Quota() {
How many operations do we expect?  I don't want a lot of spurious object allocation.

2022-08-02 20:38 UTC, dougqh commented
I'm seeing a number of thread safety and overhead issues in these pull requests.  I think it would be good to discuss the threading requirements of objects in the tracer.

2022-08-03 12:01 UTC, jandro996 commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastRequestContext.java
> +    vulnerabilities = new ConcurrentLinkedQueue<>();
> We're not allowed to have any unbounded data structures. In practice, we don't check bound everything, but we need to understand how big this collection can be.

Thanks for the advice! I think no one in the IAST Java team was aware of this 

This implementation came from another branch PR https://github.com/DataDog/dd-trace-java/pull/3673. I see that there is an open discussion about this issue https://github.com/DataDog/dd-trace-java/pull/3673#discussion_r930940869

@smola, I've added a link to this conversation in you PR

2022-08-03 12:14 UTC, jandro996 commented on dd-java-agent/iast/src/main/java/com/datadog/iast/oce/OverheadController.java
> +    return new Quota() {
We spect one per request... as you say this is not well designed, we are changing it considering your advice

2022-08-03 15:44 UTC, smola commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastRequestContext.java
> +    vulnerabilities = new ConcurrentLinkedQueue<>();
@dougqh Sure. There's two key pieces that I omitted from https://github.com/DataDog/dd-trace-java/pull/3673, but will come up in the following PRs:

* Limit the vulnerabilities reported per request. While we haven't decided all the details about caps, we'll likely start with something like 2 or 3 vulnerabilities per request. Depending on how comfortable we're with performance overhead, we'll increase it, but it's likely to always remain low (e.g. less than 10 or 100).
* We are adding deduplication of vulnerabilities, so we'll hold at most one vulnerability that is considered a duplicate (e.g. same vulnerability type, in the same class, and same line). So it will probably make sense to change the structure here to accommodate that.

We're also considering limiting the maximum number of requests that we analyze concurrently. In that case, we might afford to do something like having a fixed pool of contexts with initialized structures (e.g. plain arrays).

2022-09-06 10:51 UTC, manuel-alvarez-alvarez requested changes

2022-09-06 10:51 UTC, manuel-alvarez-alvarez commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
>      if (!config.getIastWeakCipherAlgorithms().contains(algorithmId)) {
Conceptually shouldn't this be executed after the overhead controller?

2022-09-06 10:51 UTC, manuel-alvarez-alvarez commented on dd-java-agent/iast/src/main/java/com/datadog/iast/overhead/OverheadContext.java
> +    if (availableAfter < 0) {
There's a race condition here if `delta > 1`, I don't think it's that important but ...

2022-09-06 10:51 UTC, manuel-alvarez-alvarez commented on dd-java-agent/iast/src/main/java/com/datadog/iast/overhead/OverheadController.java
> +    }
Maybe we should do:

```suggestion
    if (availableRequests.getAndUpdate(value -> value <= 0 ? 0 : value - 1) <= 0) {
      return false;
    }
```

2022-09-06 10:51 UTC, manuel-alvarez-alvarez commented on dd-java-agent/iast/src/main/java/com/datadog/iast/overhead/OverheadContext.java
> +    }
Will this work?

```suggestion
    final int available = availableOperations.getAndUpdate(value -> value < delta ? value : value - delta);
    if (available < delta) {
      return false;
    }
```

2022-09-06 10:52 UTC, manuel-alvarez-alvarez commented on dd-java-agent/iast/src/test/groovy/com/datadog/iast/RequestEndedHandlerTest.groovy
> +    0 * _
Nice one! I will copy this for my PRs moving forward :smile:

2022-09-07 09:17 UTC, smola commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
>      if (!config.getIastWeakCipherAlgorithms().contains(algorithmId)) {
I think we shouldn't consume quota for non-weak algorithms? I could check `hasQuota`, but that would require also getting the active span, increasing the overhead for the happy path of non-weak algorithms...

2022-09-07 09:39 UTC, smola commented on dd-java-agent/iast/src/main/java/com/datadog/iast/overhead/OverheadController.java
> +    }
I have applied similar logic to all operations now. Performance is similar in the absence of concurrency. I'm sure we'll revisit this again once we do more benchmarks and profiling including concurrency.

2022-09-07 14:26 UTC, manuel-alvarez-alvarez commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
>      if (!config.getIastWeakCipherAlgorithms().contains(algorithmId)) {
To my mind the reasoning regarding the quota in terms of vulnerabilities is the following:

Is there quota to check for vulnerability X?
* Yes: Check for the vulnerability and report it if found
* NO: Continue

In this particular case checking  the vulnerability is  much faster than the quota system, but others might not be. For instance, in a SQL injection you will surely first check for the quota and then continue.

Imagine we have an analyzer system, will you keep the quota check before or after calling the analyzer to check for the weak algorith?

2022-09-07 14:35 UTC, manuel-alvarez-alvarez approved these changes

2022-09-15 09:55 UTC, smola commented
@dougqh Is there any remaining thread safety concern for the latest code?

2022-09-23 07:09 UTC, merged