ygree/graphql-java
DataDog/dd-trace-java pull request #3703
Opened 2022-08-05 22:03 UTC by ygree

# What Does This Do

GraphQL-Java instrumentation

# Motivation

# Additional Notes

- [ ] add error handling

2022-08-24 22:49 UTC, ygree commented on dd-java-agent/instrumentation/graphql-java-14.0/src/main/java8/datadog/trace/instrumentation/graphqljava/GraphQLQuerySanitizer.java
> +  private static final AstTransformer astTransformer = new AstTransformer();
Ops, excuse my Scala habit for not using all capitals for static finals :) Fixed now.

2022-08-25 09:38 UTC, bantonsson requested changes

2022-08-25 09:38 UTC, bantonsson commented on dd-java-agent/instrumentation/graphql-java-14.0/graphql-java-14.0.gradle
> +    versions = "[14.0,19.0)"
So stopping muzzle at `19.0` does not seem right, so I had to dig into this. There are _weirdly_ versioned artifacts using dates, starting from `2018-...` so the muzzle range should be `'[14.0,2018)'`. You also would need to do some fail matching, so the whole muzzle block would be:
```
muzzle {
  pass {
    group = "com.graphql-java"
    module = 'graphql-java'
    versions = '[14.0,2018)' // exclude dates as version numbers
    // earlier versions are missing some classes and will require separate instrumentation
  }
  fail {
    group = "com.graphql-java"
    module = 'graphql-java'
    versions = '[1.2,14.0)'
  }
}
```

2022-08-25 09:38 UTC, bantonsson commented on dd-java-agent/instrumentation/graphql-java-14.0/graphql-java-14.0.gradle
> +  testImplementation group: 'com.graphql-java', name: 'graphql-java', version: '18.1'
Why not use `14.0` since that is the lowest version that will work according to the muzzle match?

2022-08-25 09:38 UTC, bantonsson commented on dd-java-agent/instrumentation/graphql-java-14.0/graphql-java-14.0.gradle
> +  latestDepTestImplementation group: 'com.graphql-java', name: 'graphql-java', version: '+'
In the same vein of weird version numbers, this does not test what you think it does, since it pulls in the highest version number ever that just happens to be `230521-nf-execution`. To get the latest but not anything weird, change `version` to a range like this `'[19+,2018)'`. That pulls in `19.1`, which passes muzzle but fails the `latestDepTest` since the error message seems to have changed.

A simple way to check what is actually used is to run the `dependencies` task like this:
```
./gradlew :dd-java-agent:instrumentation:graphql-java-14.0:dependencies --configuration latestDepTestRuntimeClasspath
```

2022-08-25 18:37 UTC, ygree commented on dd-java-agent/instrumentation/graphql-java-14.0/graphql-java-14.0.gradle
> +    versions = "[14.0,19.0)"
Good point! I'll fix it accordingly. Thanks for digging into this!

2022-08-25 18:53 UTC, ygree commented on dd-java-agent/instrumentation/graphql-java-14.0/graphql-java-14.0.gradle
> +  latestDepTestImplementation group: 'com.graphql-java', name: 'graphql-java', version: '+'
Good point! I'll fix it. Thanks for explanation!

2022-08-26 06:50 UTC, bantonsson approved these changes

2022-09-02 21:16 UTC, merged