:construction: :construction_worker: :building_construction: Initial version with CSI support
DataDog/dd-trace-java pull request #3706
Opened 2022-08-09 15:16 UTC by manuel-alvarez-alvarez

# What Does This Do
This PR introduces the basics to do Call Site Instrumentation with the tracer. CSI is achived via a new gralde plugin **call-site-instrumentation** that is able to read advice classes with the form:
```
@CallSite
public class SampleCallSite {

  @CallSite.Before(
      "java.security.MessageDigest java.security.MessageDigest.getInstance(java.lang.String)")
  public static void beforeMessageDigestGetInstance(@Advice.Argument(0) final String algorithm) {
    // do something with the algorithm
  }
}
```
and generate the required Java code in order to perform the actual instrumentation.

# Motivation
Instrumentations related to IAST often affect core parts of the JDK (String, StringBuilder...) where using callee instrumentation (by default in ByteBuddy) is not good enough regarding performance requirements. Call site instrumentation focus on the calls to the instrumented methods enabling the use of inclusion/exclusion lists to fine tune where to instrument.

# Additional Notes

2022-08-10 11:03 UTC, jandro996 approved these changes

2022-08-12 07:44 UTC, anderruiz commented on buildSrc/src/main/java/datadog/trace/plugin/csi/impl/AsmSpecificationBuilder.java
> +package datadog.trace.plugin.csi.impl;
This class does the parsing of the callbacks to search for @CallSite annotations to find the instrumentation spots

2022-08-17 14:29 UTC, ValentinZakharov commented on buildSrc/src/main/java/datadog/trace/plugin/csi/AdviceGenerator.java
> +    }
Such uncertainty scares a bit, we are not sure how exactly caller will be using the list (just add? may be get? remove?)

2022-08-22 08:16 UTC, manuel-alvarez-alvarez commented on buildSrc/src/main/java/datadog/trace/plugin/csi/impl/AsmSpecificationBuilder.java
> +package datadog.trace.plugin.csi.impl;
This PR has been divided in two, one for the instrumenter and another for the gradle plugin, this one now relates to just the instrumenter.

2022-08-22 08:16 UTC, manuel-alvarez-alvarez commented on buildSrc/src/main/java/datadog/trace/plugin/csi/AdviceGenerator.java
> +    }
This PR has been divided in two, one for the instrumenter and another for the gradle plugin, this one now relates to just the instrumenter.

2022-08-31 12:39 UTC, smola approved these changes

2022-09-05 12:03 UTC, anderruiz approved these changes

2022-09-06 07:16 UTC, bantonsson requested changes
Great PR!

There is only one thing that I think needs fixing in some way before merging.

I was a bit confused by the benchmarks, and it feels very counter intuitive that there should be any performance difference between `callSite` and `callee` in this case, so I had to poke at them a bit, and the response differs. The `callSite` one gets back `Hello! [Transformed]` and the `callee` one gets back `Hello! [Transformed] [Transformed]`. So we're not comparing the same things.

2022-09-06 09:20 UTC, manuel-alvarez-alvarez commented
> Great PR!
> 
> There is only one thing that I think needs fixing in some way before merging.
> 
> I was a bit confused by the benchmarks, and it feels very counter intuitive that there should be any performance difference between `callSite` and `callee` in this case, so I had to poke at them a bit, and the response differs. The `callSite` one gets back `Hello! [Transformed]` and the `callee` one gets back `Hello! [Transformed] [Transformed]`. So we're not comparing the same things.

@bantonsson, first of all thanks for the feedback :smiley:, much appreciated!

My idea with the benchmark is to validate that doing call site instrumentation is feasible in terms of startup time as long as there's a proper exclusion list.

In this particular case I wanted to showcase the instrumentation of `javax.servlet.http.HttpServlet#getParameter` as it's something we need for IAST. It's true that when using callee, due to wrappers/facades/... you end up being executed a few times in the stack of a request (that's why we got the double `[Transformed]` response). I've changed to instrument only the real implementation of the interface (in this particular case it's the apache connector).

Let me know if I should do something else about it.

2022-09-06 09:21 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/Advices.java
> +     * advices to parse it.
Ops! my bad I don't know what I was ~~parsing~~ thinking when I wrote it, fixed!

2022-09-06 09:23 UTC, bantonsson approved these changes

2022-09-06 09:23 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteInstrumenter.java
> +public abstract class CallSiteInstrumenter extends Instrumenter.Default
Exactly, couldn't have explained it better. Our idea is to provide a `CallSiteInstrumenter` that can be used by any other product if so desired.

2022-09-06 10:37 UTC, DDJavierSantos approved these changes

2022-09-06 11:42 UTC, merged