Add support for multiple configurations per product
DataDog/dd-trace-java pull request #3739
Opened 2022-08-23 03:04 UTC by shatzi

# What Does This Do

Add support for multiple configurations to be applied per product for ConfigurationPoller.
Listeners now accept configKey (string) to indicate which config to apply or remove (indicated by null configuration)

# Motivation

Live debugger can receive multiple configurations.

# Additional Notes

2022-08-23 13:10 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
> +  }
This is not used

2022-08-23 13:51 UTC, shatzi commented on remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
> +  }
Good catch, removed.

2022-08-23 14:15 UTC, cataphract requested changes
This is missing tests with the now supported multiple configurations.

2022-08-23 14:15 UTC, cataphract commented on remote-config/src/test/groovy/datadog/remoteconfig/ConfigurationPollerSpecification.groovy
> +  void 'deserializer can return null, indicate this config should be un-applied'() {
This changes the semantics. Returning null from the deserializer can be done when the configuration cannot be deserialized (has some unexpected format). I don't think that in that case the configuration should be "unapplied" (pulled). It would IMO make more sense to keep the old configuration.

2022-08-23 21:31 UTC, jpbempel approved these changes

2022-08-24 13:52 UTC, cataphract approved these changes

2022-08-24 14:03 UTC, merged