Implement weak cipher detection functionality
DataDog/dd-trace-java pull request #3760
Opened 2022-08-26 12:15 UTC by DDJavierSantos

# What Does This Do
Instrument the javax.crypto.Cipher class so we can detect and report the use of weak cipher algorightms

# Motivation
This will allow us to detect and report vulnerabilities in crypto code when weak cipher algorithms are used in customer code. 

# Additional Notes
In order for the functionality to be complete, we need the backend to filter and display the vulnerability information we add to the span.

2022-08-26 12:56 UTC, bantonsson approved these changes

2022-08-26 14:50 UTC, smola requested changes

2022-08-26 14:50 UTC, smola commented on dd-java-agent/instrumentation/java-security/src/test/groovy/test/UnavailableHashAlgorithmTest.groovy
> +  def "test instrumentation"() {
@DDJavierSantos Can you move these different test cases to a single suite (e.g. `WeakCipherInstrumentationTest`)?

2022-08-29 07:43 UTC, smola approved these changes

2022-08-31 09:38 UTC, merged