Remote config improvements
DataDog/dd-trace-java pull request #3832
Opened 2022-09-13 14:26 UTC by cataphract

# What Does This Do

Implements specs RCTE1 (signature verification), RCTE2 (report non-protocol errors during configuration) and RCTE3 (report "capabilities").

Additionally (2nd commit): if the remote config cannot be discovered at startup, keep trying to discover at intervals between 5 and 120 seconds. This allows remote config to work if the agent is not immediately available on startup.

2022-09-15 08:39 UTC, jpbempel requested changes
I think we can reuse some dependencies to avoid reimplementing some parts

2022-09-15 08:39 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
> +  public void accept(Configuration configuration) {
please remove the comment above

2022-09-15 08:39 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
> +
Sounds weird to refer to ASM specific capabilities in this part of the code.

2022-09-15 08:39 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/HexUtils.java
> +  public static byte[] fromHexString(String input) {
Maybe consider this implementation: https://stackoverflow.com/a/140861

2022-09-15 08:39 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/HexUtils.java
> +  }
Please don't use Exception for that, and test against the limit of the array!

2022-09-15 08:39 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/HexUtils.java
> +  public static byte[] fromHexString(String input) {
also your crypto lib used provides already some utils: https://github.com/cryptography-cafe/curve25519-elisabeth/blob/597bf78f175b0c00a72af7413ba1817554ea6cee/src/test/java/cafe/cryptography/curve25519/Utils.java

2022-09-15 08:39 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/JsonCanonicalizer.java
> +public class JsonCanonicalizer {
is it an original implementation?
I think there are some implementation available as dependency like
https://github.com/erdtman/java-json-canonicalization
https://github.com/cyberphone/json-canonicalization

2022-09-15 08:39 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/tuf/RemoteConfigRequest.java
> +
same here, not sure we want to have specifc product capability constants here.

2022-09-15 09:10 UTC, cataphract commented on remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
> +
These are global constants defined in the protocol, so I think that makes sense that the constants be defined in the `remoteconfig` module. However, perhaps it would make more sense to have a way for the clients of the poller to turn on the capabilities, rather than having this logic here.

2022-09-15 09:33 UTC, cataphract commented on remote-config/src/main/java/datadog/remoteconfig/HexUtils.java
> +  public static byte[] fromHexString(String input) {
The implementation is specialized to only accept 128 or 256-bit data and pads with zeros on the leftmost bytes to ensure that the output has those exact sizes. I'll add a comment to that effect.

2022-09-15 09:41 UTC, cataphract commented on remote-config/src/main/java/datadog/remoteconfig/JsonCanonicalizer.java
> +public class JsonCanonicalizer {
It is an original implementation, yes.

None of these seem to follow the [spec that's mentioned in the RFC](https://wiki.laptop.org/go/Canonical_JSON). In particular, the spec indicates that the only characters that should be escaped are `"` and `\`, while both libraries (which seem to share code between themselves) escape other characters. There are other differences; for instance both allow floating point numbers.

2022-09-15 09:48 UTC, cataphract commented on remote-config/src/main/java/datadog/remoteconfig/tuf/RemoteConfigRequest.java
> +
See above. The capability definitions are part of the protocol.

2022-09-16 07:31 UTC, jpbempel approved these changes

2022-09-16 07:31 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/HexUtils.java
> +      input = new String(new char[diff]).replace('\0', '0') + input;
Could also use ` Arrays.fill()`

2022-09-16 07:31 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/HexUtils.java
>    private static int getDec(int index) {
Can use `Character.digit(x, 16)`

2022-09-19 10:35 UTC, cataphract commented on remote-config/src/main/java/datadog/remoteconfig/HexUtils.java
> +      input = new String(new char[diff]).replace('\0', '0') + input;
Done. I've used `Array.fill` and `System.arrayCopy` to avoid creating new strings.

2022-09-19 10:35 UTC, cataphract commented on remote-config/src/main/java/datadog/remoteconfig/HexUtils.java
>    private static int getDec(int index) {
I think I prefer to used the current method because it's more efficient and doesn't accept code points outside ASCII as digits.

2022-09-21 09:55 UTC, bantonsson commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
> +  // the exception will be reported in the next request to the conf service
I can't really see where or what would report the exception message. How does this machinery work? Are there any negative tests?

2022-09-23 11:32 UTC, cataphract commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
> +  // the exception will be reported in the next request to the conf service
The tests are in `ConfigurationPollerSpecification`. See `reports error applying configuration` and `reports error during deserialization`.

2022-09-23 12:11 UTC, bantonsson commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
> +  // the exception will be reported in the next request to the conf service
Ah, now I see. They are put in `collectedCfgErrors` and added to the state.

2022-09-30 13:48 UTC, ValentinZakharov approved these changes

2022-09-30 19:46 UTC, merged