Added Health metrics for spans and traces
DataDog/dd-trace-java pull request #3856
Opened 2022-09-19 18:19 UTC by nayeem-kamal

# What Does This Do
### Added the following health metrics:
Count of traces
- **Created  trace.pending.created**

Count of spans
- **Created - span.pending.created**  
- Sampled - tracing.context.size  (already existed) 

Count of continuations
- **Finished - span.continuations.finished**  
- **Canceled - span.continuations.canceled**

# Motivation

# Additional Notes
### Updated List of metrics
Count of traces
- Created - _trace.pending.created_
- Sampled Here - _queue.enqueued.traces/queue.dropped.traces - SAMPLER_KEEP tag_  
- w/ Errors - _queue.dropped.traces/api.errors.total_  
- Sent - _flush.traces.total_  

Count of spans
- Created - _span.pending.created_  
- Sampled - _tracing.context.size_   

Count of continuations
- Finished - _span.continuations.finished_  
- Canceled - _span.continuations.canceled_

2022-09-19 22:51 UTC, ygree requested changes

2022-09-19 22:51 UTC, ygree commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +    healthMetrics.onCreateSpan();
Would be great to have tests verifying that expected counters increased at certain events

2022-09-19 22:51 UTC, ygree commented on dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
> -    // api.errors???
Looks like this comment was cut by mistake

2022-09-20 11:52 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      this.healthMetrics = new HealthMetrics(statsDClient);
Maybe I'm missing something, but I can't see that this `HealthMetrics` or the other new one below is _started_, so I'm not sure when the metrics would be sent anywhere.

2022-12-14 17:04 UTC, closed without merging