Added HealthMetrics and tests for the HealthMetrics and PendingTrace classes
DataDog/dd-trace-java pull request #3883
Opened 2022-09-23 15:09 UTC by nayeem-kamal

# What Does This Do
- Created a new branch/PR because rebasing the old one caused it to show 280+ files changed.
### Added the following health metrics:
Count of traces
- **Created  trace.pending.created**

Count of spans
- **Created - span.pending.created**  
- Sampled - tracing.context.size  (already existed) 

Count of continuations
- **Finished - span.continuations.finished**  
- **Canceled - span.continuations.canceled**

# Motivation

# Additional Notes
### Updated List of metrics
Count of traces
- Created - _trace.pending.created_
- Sampled Here - _queue.enqueued.traces/queue.dropped.traces - SAMPLER_KEEP tag_  
- w/ Errors - _queue.dropped.traces/api.errors.total_  
- Sent - _flush.traces.total_  

Count of spans
- Created - _span.pending.created_  
- Sampled - _tracing.context.size_   

Count of continuations
- Finished - _span.continuations.finished_  
- Canceled - _span.continuations.canceled_

2022-12-09 09:36 UTC, bantonsson requested changes
Looks good apart from multiple instances sending different counts of the same metrics.

2022-12-09 09:36 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      this.healthMetrics = new HealthMetrics(statsDClient);
Having multiple instances of the `HealthMetrics` will lead to different counts for the same metrics being sent. There needs to be one instance created that is used in all places.

2022-12-13 21:08 UTC, nayeem-kamal commented on dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
> +      this.healthMetrics = new HealthMetrics(statsDClient);
Thanks, I moved the instantiation of HealthMetrics into the CoreTracer class so that a common instance can be used by all instances of the PendingTrace class.

2022-12-14 14:18 UTC, nayeem-kamal commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +            : new HealthMetrics(StatsDClient.NO_OP);
I agree. I think this would be useful.

2022-12-14 14:18 UTC, nayeem-kamal commented on dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
> +    this.healthMetrics = new HealthMetrics(statsDClient);
Ah, missed this one thanks!

2022-12-14 15:49 UTC, bantonsson approved these changes

2022-12-14 16:57 UTC, merged