Jsantos/weak hash csi
DataDog/dd-trace-java pull request #3903
Opened 2022-09-27 12:25 UTC by DDJavierSantos

# What Does This Do
Change weak hash and weak cipher instrumentation so we use the call site interface instead of the target instrumentation. 

# Motivation
This is needed so we can instrument the use of SHA-1 hash algorithm since it is used by the jar verifier and we need to ignore the jar verifier.

# Additional Notes

This PR depends on five unmerged PRs, so it will be rebased a number of times before it is ready for merge

2022-10-10 11:43 UTC, manuel-alvarez-alvarez requested changes

2022-10-10 11:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/iast-instrumenter/iast-instrumenter.gradle
> +apply plugin: 'call-site-instrumentation'
Is it needed here?

2022-10-10 11:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/iast-instrumenter/src/main/java/datadog/trace/instrumentation/iastinstrumenter/IastInstrumenter.java
> +    return true;
```suggestion
    return Config.get().isIastEnabled();
```

2022-10-10 11:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakCipherInstrumentationCallSite.java
> +package datadog.trace.instrumentation.java.security;
You can use `@CallSite.Before` skipping the return parameter and making the instrumentation faster

2022-10-10 11:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakHashInstrumentationCallSite.java
> +package datadog.trace.instrumentation.java.security;
Same as WeakCipher with before instrumentation

2022-10-10 11:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/java-security/src/test/java/test/foo/TestJavaCalls.java
> +package test.foo;
I always use `TestSuite` for this object, perhaps we could use better names to prevent methods growing in these classes (for instance, `TestSecuritySuite`). And I normally put them under the package `foo.bar` I think we should agree in package and naming.

2022-10-10 11:43 UTC, manuel-alvarez-alvarez commented on internal-api/src/test/groovy/datadog/trace/api/iast/InstrumentationBridgeTest.groovy
> +  def "bridge calls don't leak exceptions for onParameterName and onParameterValue on null parameters"() {
This doesn't belong here right?

2022-10-10 11:43 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java
> +  public static void onParameterName(final String parameterName) {
Same as below, this is for another PR right?

2022-10-10 11:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/java-security/src/test/java/test/foo/TestJavaCalls.java
> +    return Cipher.getInstance(algo);
Something that I do in these kind of test suites is to consume the parameters of the stack and the result, like the following:

```java
  public static String toString(final StringBuilder builder) {
    LOGGER.debug("Before string builder toString {}", builder);
    final String result = builder.toString();
    LOGGER.debug("After string builder toString {}", result);
    return result;
  }
```

The reasoning here is that, if the instrumenter screws the stack, when the call site is the last instruction of the method then the issue might not be detected.

2022-10-11 07:31 UTC, manuel-alvarez-alvarez reviewed
The filtering of the stack should be changed:
```java
    StackTraceElement stackTraceElement =
        stackWalker.walk(
            stack ->
                stack
                    .filter(s -> !s.getClassName().equals("java.security.MessageDigest"))
                    .findFirst()
                    .get());
```

Ideally we should could use a trie based solution for all vulnerabilities:

```java
StackTraceElement stackTraceElement =
        stackWalker.walk(IastModuleImpl::findValidPackageForVulnerability);
```

```java
  private static StackTraceElement findValidPackageForVulnerability(
      Stream<StackTraceElement> stream) {
    final StackTraceElement[] first = new StackTraceElement[1];
    return stream
        .filter(
            stack -> {
              if (first[0] == null) {
                first[0] = stack;
              }
              return IastExclusionTrie.apply(stack.getClassName()) != 1;
            })
        .findFirst()
        .orElse(first[0]);
  }
```

2022-10-13 10:06 UTC, manuel-alvarez-alvarez approved these changes

2022-10-17 07:22 UTC, smola approved these changes

2022-10-20 07:48 UTC, smola requested changes
I think we need to remove the previous exception for we had globally:

https://github.com/DataDog/dd-trace-java/blob/0d6702eda5c05925f4040083a36e6a8d384b5847/dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie#L43-L44

2022-10-20 12:33 UTC, bantonsson commented on dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
> +# Wildcard lines end with '.' or '$' and match any sub-packages/nested-classes
This comment is out of date.

2022-10-20 12:33 UTC, bantonsson commented on dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
> +
Double newline

2022-10-20 12:33 UTC, bantonsson commented on dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
> +
Double newline. I wish that there was a better formatter for `spock/gradle`.

2022-10-26 09:04 UTC, manuel-alvarez-alvarez commented on dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
> +    command.addAll([
This is actually a duplicate from previous line

2022-10-26 14:46 UTC, jandro996 approved these changes

2022-10-28 09:39 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintObjectsLogTest.groovy.orig
> +package com.datadog.iast.taint
@DDJavierSantos  Can we remove this file? It seems an old test, and not being used (`.orig`).

2022-11-03 07:56 UTC, smola commented on dd-java-agent/instrumentation/iast-instrumenter/src/main/java/datadog/trace/instrumentation/iastinstrumenter/IastInstrumenter.java
> +    return Config.get().isIastEnabled();
That `isEnabled` is gone.
There could be possibly more than one instrumenter related to IAST. But all call site instrumentations for IAST will use this single `IastInstrumenter`. This is currently all we introduce, and we expect most of our instrumentation to land here.

2022-11-09 13:13 UTC, bantonsson commented on dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
> +# Wildcard lines end with '.' or '$' and match any sub-packages/nested-classes
This comment is still out of date and **wrong**. Wildcard lines to not end with `'.'` or `'$'`.

2022-11-09 13:18 UTC, bantonsson approved these changes

2022-11-09 15:16 UTC, merged