Jsantos/string trim instrumentation
DataDog/dd-trace-java pull request #3951
Opened 2022-10-04 13:19 UTC by DDJavierSantos

# What Does This Do
Instrument the String.trim() function so we can track tainted objects for iast vulnerability detection

# Motivation
This is part of an effort to instrument all of the String and StringBuilder calls that will require taint object tracking instrumentation.

# Additional Notes
This depends on a lot of non reviewed PRs so I am marking it as draft for now until we can rebase it after the other PRs are merged.

2022-10-04 13:46 UTC, manuel-alvarez-alvarez commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
> +    if (!canBeTainted(self)) {
Being `result` a subset of `self` we might want to skip this test (unless something is terribly broken it should be ok)

2022-10-05 11:04 UTC, smola commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
> +    if (self.equals(result)) {
Use reference comparison `==`, not equals here. This kind of short-circuit is only valid if input and result are _the same object_, not equal objects.

2022-10-05 11:04 UTC, smola commented on dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
> +    final Range[] rangesSelf = getRanges(taintedObjects, self);
This utility method seems pointless? `taintedSelf.getRanges()` skips one call and one check, to end up with the same result.

2022-10-05 12:45 UTC, jandro996 commented on dd-java-agent/iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +    for (int rangeIndex = ranges.length - 1; rangeIndex > 0; rangeIndex--) {
I think this should be 

for (int rangeIndex = ranges.length - 1; **rangeIndex >= 0**; rangeIndex--) 

otherwise you can  miss one range to be skipped and method returns an array with a null range


offset = 0;
length = 4;

Range.start = 4
Range.length = 3

this will be the case for "012345678".substring(0,4)

2022-10-05 13:17 UTC, jandro996 commented on dd-java-agent/iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +    for (int rangeIndex = 0; rangeIndex < ranges.length; rangeIndex++) {
'for' loop can be replaced with enhanced 'for'

````java
for (final Range rangeSelf : ranges) {
      if (rangeSelf.getStart() + rangeSelf.getLength() <= offset) {
        skippedRanges++;
      } else {
        break;
      }
    }
````

2022-10-05 13:17 UTC, jandro996 commented on dd-java-agent/iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +    for (int rangeIndex = 0; rangeIndex < ranges.length; rangeIndex++) {
'for' loop can be replaced with enhanced 'for'

````java
for (final Range rangeSelf : ranges) {
      int newStart = rangeSelf.getStart() - offset;
      int newLength = rangeSelf.getLength();
      final int newEnd = newStart + newLength;
      if (newStart < 0) {
        newLength = newLength + newStart;
        newStart = 0;
      }
      if (newEnd > length) {
        newLength = length - newStart;
      }
      if (newLength > 0) {
        newRanges[newRangeIndex] = createIfDifferent(rangeSelf, newStart, newLength);
        newRangeIndex++;
      }
    }
````

2022-10-06 08:26 UTC, jandro996 commented on dd-java-agent/iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +    }
Maybe we can extract this to a private method 

`getSkippedRanges(offset, length, ranges);`

:)

2022-12-15 10:19 UTC, jandro996 requested changes
All the old sources, propagation and sinks PRs must be rebased and refactored due to https://github.com/DataDog/dd-trace-java/pull/4300

2022-12-16 09:23 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +  static int calculateSubstringSkippedRanges(int offset, int length, @Nonnull Range[] ranges) {
Have a look to this comment 

https://github.com/DataDog/dd-trace-java/pull/3915#discussion_r1025361092

@manuel-alvarez-alvarez  suggest me how to improve this code

2022-12-16 09:30 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +    if (self.equals(result)) {
I think that we must check if it is the same instance instead of the value

2022-12-16 09:32 UTC, jandro996 approved these changes

2022-12-21 16:39 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +  static int calculateSubstringSkippedRanges(int offset, int length, @Nonnull Range[] ranges) {
I have written the implementation, it would be like this:

2022-12-21 16:46 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +    if (self.equals(result)) {
Done

2022-12-22 10:29 UTC, smola requested changes

2022-12-22 10:29 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +    // checks
Remove this comment, it seems just noise.

2022-12-22 10:29 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +  public void onStringTrim(@Nullable final String self, @Nullable final String result) {
`self` can never be `null` here.

2022-12-22 10:29 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +  public static Range[] forSubstring(int offset, int length, @Nonnull Range[] ranges) {
I guess this will need a rebase. I believe this method is now in master?

2023-01-04 16:54 UTC, smola approved these changes

2023-01-04 16:55 UTC, merged