String taint tracking - join methods
DataDog/dd-trace-java pull request #3985
Opened 2022-10-07 11:39 UTC by jandro996

# What Does This Do
Adds all the instrumentation needed to perform taint tacking in join operations for String objects

# Motivation
IAST requires to track all modifications that happen to strings in the code, this PR implements the join operations for String class

# Additional Notes
The instrumentation for the join method with the iterable param is based on the premise of iterating only once since these iterators may not be immutable.

2022-10-19 11:50 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java
> +    return null;
We have to do the join here rather than returning `null`

2022-11-18 10:31 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
> +    InstrumentationBridge.onStringJoin(
Why the extra `toArray` method call?

2022-11-18 10:33 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/jmh/java/com/datadog/iast/propagation/AbstractBenchmark.java
> +      iastContext = iasContext;
Does this even compile?

2022-11-18 10:39 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastModuleImpl.java
> +    Range[] delimiterRanges = getRanges(getTainted(taintedObjects, delimiter));
There is something I've built that can extract ranges from arrays and lists, it will allow you to iterate easily and give you the count of ranges

https://github.com/DataDog/dd-trace-java/blob/malvarez/command-injection/dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastModuleImpl.java#L278

2022-11-24 09:23 UTC, jandro996 commented on dd-java-agent/agent-iast/src/jmh/java/com/datadog/iast/propagation/AbstractBenchmark.java
> +      iastContext = iasContext;
yes, but we discover a typo error 😄 

I will change the pram name from iasContext to iastContext that is the correct one

2022-11-24 09:57 UTC, jandro996 commented on dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
> +    InstrumentationBridge.onStringJoin(
Some weeks ago I had a conversation with @anderruiz and @smola about this topic and we decided to assume the toArray overhead to keep it simple in this first iteration.

2022-12-22 09:10 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +   * Iterates over the element ranges and delimiter ranges (if is necessary) to update them and calc
```suggestion
   * Iterates over the element and delimiter ranges (if necessary) to update them and calculate
```

2022-12-22 09:48 UTC, smola requested changes

2022-12-22 09:48 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    when:
Let's separate blocks.

2022-12-22 09:48 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    delimiter              | elements                                                                                    | expected
I would add cases with an empty string as delimiter.

2022-12-22 09:48 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    delimiter              | elements                                                                                    | expected
Also, what happens with `null` delimiter?

2022-12-22 11:42 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +      Integer pos,
Why the boxing?

2022-12-22 11:44 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +      pos += element.length();
It's weird to have it inside the `canBeTainted` if block, if at some point we choose to make strings of a single character length to be not tainteable this code will fail.

2022-12-22 11:48 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +      CharSequence element,
This code does not handle the case where element is null:

```java
String.join(" ", "Hello " , null, " World!"); // Hello  null  World!
```

2022-12-22 13:02 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +      pos += element.length();
Changed and added test for 
`String.join(" ", "Hello " , null, " a", "b", "c"); // Hello  null  a b c where Hello and b are tainted`

2022-12-23 12:30 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +    pos += element == null ? 4 : element.length();
You can reuse the method on top of this one:

```java
  private static int getToStringLength(@Nullable final String s) {
    return s == null ? NULL_STR_LENGTH : s.length();
  }
```

2022-12-23 12:33 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +        newRanges.add(new Range(range.getStart() + pos, range.getLength(), range.getSource()));
```java
newRanges.add(range.shift(pos));
```

2022-12-23 12:34 UTC, manuel-alvarez-alvarez approved these changes

2022-12-23 14:14 UTC, smola approved these changes

2022-12-23 14:51 UTC, merged