String taint tracking - repeat method
DataDog/dd-trace-java pull request #3997
Opened 2022-10-10 11:30 UTC by jandro996

# What Does This Do
Adds all the instrumentation needed to perform taint tacking in repeat operation for String objects

# Motivation
IAST requires to track all modifications that happen to strings in the code, this PR implements the repeat operation for String class

# Additional Notes
The  String repeat method is available since JAVA 11

2022-10-10 12:32 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastModuleImpl.java
> +    if (!canBeTainted(self) || !canBeTainted(result) || self == result) {
You can replace `self == result` by 'count <= 1'

2023-01-09 12:43 UTC, smola requested changes

2023-01-09 12:43 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +    final Range[] selfRanges = getRanges(taintedObjects.get(self));
Is `getRanges` guaranteed to return not-null?

2023-01-09 12:43 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    then:
Space out blocks in tests, please.

2023-01-09 14:13 UTC, jandro996 commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    then:
🤦

2023-01-09 14:16 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +    final Range[] selfRanges = getRanges(taintedObjects.get(self));
Yes!

```
private static Range[] getRanges(final TaintedObject taintedObject) {
    return taintedObject == null ? Ranges.EMPTY : taintedObject.getRanges();
  }
```
and

```
public TaintedObject(
      final @Nonnull Object obj,
      final @Nonnull Range[] ranges,
      final @Nullable ReferenceQueue<Object> queue) {
    super(obj, queue);
    this.positiveHashCode = System.identityHashCode(obj) & POSITIVE_MASK;
    this.ranges = ranges;
  }
```

2023-01-09 16:37 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    "i̇̀i̇̀==>fff<==f123b"                | "ÌÌFF==>FF1<==23B"        | "lt"   | 14         | 12           | [[6, 3]]
@jandro996 Please, reformat this.

2023-01-10 17:04 UTC, smola approved these changes

2023-01-11 08:33 UTC, merged