Jsantos/exclusion list
DataDog/dd-trace-java pull request #3998
Opened 2022-10-10 12:07 UTC by DDJavierSantos

# What Does This Do

# Motivation

# Additional Notes

2022-11-25 09:34 UTC, mcculls commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnores.java
> +    Integer allowCode = GlobalIgnoresCache.getAllowCode(name);
Hi - any reason this is being done for all ignores, and not just IAST ones?

This is a very hot-path during startup and I'd like to make sure we don't accidentally regress some recent improvements.

I'd also be interested in your original requirements, as there might be a better way to approach this.

2022-11-25 11:20 UTC, mcculls requested changes
I'm concerned about making a change that affects a very hot-path for all instrumentations when only a very specific instrumentation needs this behaviour. I believe there's a better way to approach this and would prefer to look into that before this is approved.

2022-11-25 11:22 UTC, mcculls commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresCache.java
> +  private static long cache = 0;
class-loading (and therefore matching) is not single-threaded, so you can't rely on a single static

2022-11-25 11:27 UTC, mcculls commented on dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
> + io.micrometer.*
this change looks odd - there's no number for `io.micrometer.*` any more and two different numbers for the same 'smoke-test' package (also test packages shouldn't really be in there TBH, instead a different package should be chosen for this particular smoke-test code that doesn't start with `datadog.`)

2023-01-03 11:10 UTC, closed without merging

2023-01-03 11:10 UTC, DDJavierSantos commented
Performance is a problem with this approach