Glopes/string constr format
DataDog/dd-trace-java pull request #4001
Opened 2022-10-10 14:23 UTC by cataphract

# What Does This Do

Implements taint tracking for String constructors and `String.format`.

2022-10-10 14:55 UTC, manuel-alvarez-alvarez commented on internal-api/src/test/groovy/datadog/trace/api/iast/InstrumentationBridgeTest.groovy
> +  private final static BRIDGE_METHODS = [
Nice!

2022-10-11 15:50 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastModuleImpl.java
> +    List<Integer> patternPositions = new ArrayList<>();
Maybe we can avoid the allocation of a new List using a matcher.groupCount approach :)

2022-10-11 15:50 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastModuleImpl.java
> +    List<Object> newArgs = new ArrayList<>(Arrays.asList(args));
I think we could avoid the List allocation here using the args length and iterating over the `toFmt.getRanges()` with a counter to calc a newArgs  array size

2022-12-15 10:21 UTC, jandro996 commented
All the old sources, propagation and sinks PRs must be rebased and refactored due to https://github.com/DataDog/dd-trace-java/pull/4300

2022-12-15 10:21 UTC, jandro996 requested changes
All the old sources, propagation and sinks PRs must be rebased and refactored due to https://github.com/DataDog/dd-trace-java/pull/4300

2023-10-16 09:53 UTC, closed without merging