Update generated IAST json with new RFC for ranges
DataDog/dd-trace-java pull request #4006
Opened 2022-10-10 17:18 UTC by manuel-alvarez-alvarez

# What Does This Do
Update the JSON of the vulnerabilities to support the new evidence format according to the RFC

# Motivation

# Additional Notes
[IAST Tainted Range Offsets RFC](https://docs.google.com/document/d/1UVXCCVzoXFpJm2yXKeWQUQ4swhbQFEASHRkHGHehgTw)

2022-10-11 13:54 UTC, jandro996 approved these changes

2022-10-20 07:42 UTC, smola requested changes

2022-10-20 07:42 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/EvidenceAdapter.java
> +    writer.name("value");
This needs an update to the latest version of the spec, but otherwise the PR looks good.

2022-10-24 08:49 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/EvidenceAdapter.java
> +    writer.name("value");
Updated :smile:

2022-11-03 07:51 UTC, smola requested changes

2022-11-03 07:51 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/EvidenceEncodingTest.groovy
> +    'Hello World' | [range(0, 5, source(0))]                         | '{"valueParts": [{"value": "Hello", "source": 0}, " World"]}'
In the latest version of the RFC (`valueParts`), all elements in the array are objects. Non-tainted parts have no `source` field.

2022-11-03 10:45 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/EvidenceEncodingTest.groovy
> +    'Hello World' | [range(0, 5, source(0))]                         | '{"valueParts": [{"value": "Hello", "source": 0}, " World"]}'
Thanks for the input, don't know why I missed it. It's changed now (I'll go over the json schema as well)

2022-11-04 10:49 UTC, smola approved these changes

2022-11-04 11:33 UTC, merged