system-tests and CI Visibility integration
DataDog/dd-trace-java pull request #4102
Opened 2022-10-26 15:31 UTC by robertomonteromiguel

# What Does This Do
Integration system-tests and CI Visibility. Pipeline configuration to send data to CI Visibility

# Motivation
Observe the system-tests executions over main branch

# Additional Notes

2022-10-26 15:33 UTC, richardstartin commented
We have a lot of forked processes in our smoke tests, will this integrate with them? I have a branch which can profile them but it's a bit artisanal.

2022-10-26 16:07 UTC, bantonsson requested changes
Fix this please https://app.circleci.com/jobs/github/DataDog/dd-trace-java/416545?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

2022-10-26 16:07 UTC, bantonsson commented on .circleci/config.yml
> +            export DD_APP_KEY=$DD_CI_APP_KEY
Please remove any global `DD_*` keys from circleci since it's failing all our cleanup checks in the tests.

2022-10-27 08:22 UTC, robertomonteromiguel commented on .circleci/config.yml
> +            export DD_APP_KEY=$DD_CI_APP_KEY
Renamed. Now:

SYSTEM_TESTS_CI_API_KEY
SYSTEM_TESTS_CI_APP_KEY

2022-11-03 14:40 UTC, bantonsson approved these changes
Please squash the commits before merging to `master`

2022-11-04 06:58 UTC, merged