WAF lazy loading
DataDog/dd-trace-java pull request #4115
Opened 2022-10-28 10:17 UTC by ValentinZakharov

# What Does This Do
WAF loads lazily to reduce startup time (third attempt with fix for tests)

# Motivation

# Additional Notes

2022-10-31 07:35 UTC, smola approved these changes

2022-11-03 18:15 UTC, smola requested changes
With this PR, PowerWAF does not seem to run when AppSec has been activated remotely. Holding off until this is verified/fixed.

2022-11-04 09:41 UTC, cataphract approved these changes

2022-11-04 11:19 UTC, smola approved these changes

2022-11-04 12:41 UTC, smola commented
Tested with prod, LGTM.

2022-11-04 13:23 UTC, merged