Added configuration flags for IAST weak hash and IAST weak cipher con…
DataDog/dd-trace-java pull request #4167
Opened 2022-11-07 08:51 UTC by DDJavierSantos

…figuration. Defaulted to true.

# What Does This Do
Add configuration flags for IAST weak cipher and IAST weak hash. 

# Motivation
To allow independent configuration of IAST detection by vulnerability type.

# Additional Notes
The features are defaulted to true, so if IAST is enabled, they are enabled.

2022-11-07 10:14 UTC, smola commented on dd-java-agent/instrumentation/java-security/src/test/groovy/test/DisabledWeakCipherForkedTest.groovy
> +    injectSysConfig("iast.weak-cipher.detection.enabled", "false")
Maybe just `dd.iast.weak-cipher.enabled`?
cc @anderruiz

2022-11-11 13:56 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/java-security/src/test/groovy/test/DisabledWeakCipherForkedTest.groovy
> +    injectSysConfig("iast.weak-cipher.detection.enabled", "false")
false is testing that we disable the flag, there are another test where we test it enabled

2022-12-15 10:25 UTC, jandro996 requested changes

2022-12-15 10:25 UTC, jandro996 commented on dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakCipherInstrumentationCallSite.java
>  package datadog.trace.instrumentation.java.security;
All the old sources, propagation and sinks PRs must be rebased and refactored due to https://github.com/DataDog/dd-trace-java/pull/4300

2022-12-15 11:11 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakCipherInstrumentationCallSite.java
>  package datadog.trace.instrumentation.java.security;
Done

2022-12-15 12:02 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/java-security/src/test/groovy/test/DisabledWeakCipherForkedTest.groovy
> +    injectSysConfig("iast.weak-cipher.detection.enabled", "false")
I have changed the flag name to dd.iast.weak-cipher.enabled

2022-12-15 13:43 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  private final boolean iastWeakCipherEnabled;
I assume that these variables can be removed now?

2022-12-22 16:21 UTC, DDJavierSantos commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  private final boolean iastWeakCipherEnabled;
We are interested in the flags being reported in Config.toString(). We think it can help us troubleshoot in the future. I have added this variables to the output produced by Config.toString().

2022-12-27 14:33 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  private final boolean iastWeakCipherEnabled;
I understand that, but going forward we would need some more generic mechanism than adding config flags by hand here for every iast integration, and also, you don't need to add them here since they are only used when printing the config. Another thing is that they would still be printed as _enabled_ even though `iast` itself is not _enabled_.

2023-01-05 15:53 UTC, bantonsson approved these changes

2023-01-06 19:44 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  private final boolean iastWeakCipherEnabled;
Yeah, I really think Config should be more declarative & self-describing.  If we ever do truly overhaul Config, then I'd definitely like it to be able to print out the flags, values, and even defaults without requiring code changes every time.

I'm thinking something akin to how it is done inside the JVM, but alas, not today.

2023-01-20 09:20 UTC, smola commented on dd-trace-api/src/main/java/datadog/trace/api/config/IastConfig.java
> +  public static final String IAST_WEAK_CIPHER_ENABLED = "iast.weak-cipher.enabled";
What about the other supported vulnerabilities?

2023-02-08 16:02 UTC, jandro996 reviewed
As @smola said [here](https://github.com/DataDog/dd-trace-java/pull/4167/files#r1082271362) we are not covering  SQL_INJECTION, COMMAND_INJECTION, PATH_TRAVERSAL and LDAP_INJECTION:

- Modify each callsite implementation and tests
- Set default values in ConfigDefaults.java

Maybe it would be better to implement each sink in a different PR

2023-11-17 13:52 UTC, closed without merging