[testing]Lib injection and system-tests integration
DataDog/dd-trace-java pull request #4194
Opened 2022-11-09 10:47 UTC by robertomonteromiguel

# What Does This Do

Remove lib injection scripts and move them to system-tests repository. When a branch is built we will clone system-tests repository and launch the lib injeciton tests

# Motivation

Create system-tests ecosystem centralized on system-tests repository
# Additional Notes

2022-11-24 14:25 UTC, robertomonteromiguel commented on .github/workflows/lib-injection.yaml
> +          ref: 'robertomonteromiguel/lib_injection_integration'
I will remove this:

When my system-tests branch is merged to main branch
Just before merging this PR

2022-11-24 14:26 UTC, robertomonteromiguel commented on .github/workflows/lib-injection.yaml
> +  injection-tests-java:
I decided not to remove this file...but another option is moving these jobs to system-tests pipeline (circleci)
what do you think?

2022-11-30 17:41 UTC, smola reviewed
I added @DataDog/apm-java and @devinsba (who touched this recently).

2022-11-30 17:41 UTC, smola commented on .github/workflows/lib-injection.yaml
> +  injection-tests-java:
This could be named just `lib-injection-tests:`? `-java` is redundant in this repository.

2022-11-30 18:14 UTC, devinsba commented on lib-injection/src/main/docker/Dockerfile
> -FROM busybox
I don't really agree with this file being moved to the system-tests repo. If this is to move to a central place it should be specific to lib injection

The docker image described here is one of our release artifacts not just part of the tests

2022-12-01 12:53 UTC, robertomonteromiguel commented on lib-injection/src/main/docker/Dockerfile
> -FROM busybox
Yes, from the pythom they said me the same. I will change it, and I will ask a new review after that

2022-12-02 16:17 UTC, devinsba requested changes

2022-12-02 16:17 UTC, devinsba commented on .github/workflows/lib-injection.yaml
> +        platforms: "linux/amd64,linux/arm64/v8"
Please change this to: `steps.buildx.outputs.platforms` out previous script supported every platform that was available

2022-12-12 09:26 UTC, robertomonteromiguel commented on .github/workflows/lib-injection.yaml
> +        platforms: "linux/amd64,linux/arm64/v8"
I tried to run as you suggested, but there is a problem building images for all platforms:

`/usr/bin/docker buildx build --iidfile /tmp/docker-build-push-qOp1xt/iidfile --platform linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/amd64/v4,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6 --tag ghcr.io/datadog/dd-trace-java/dd-lib-java-init:abb27066c999fc1636f0a9cb8bb41f1a13f0967b --metadata-file /tmp/docker-build-push-qOp1xt/metadata-file --push ./lib-injection`

#5 [linux/mips64 internal] load metadata for docker.io/library/busybox:latest
#5 ERROR: no match for platform in manifest sha256:3b3128d9df6bbbcc92e2358e596c9fbd722a437a62bafbc51607970e9e3b8869: not found

2022-12-13 09:18 UTC, robertomonteromiguel commented on .github/workflows/lib-injection.yaml
> +        if [ $(echo ${GITHUB_HEAD_REF-${GITHUB_REF#refs/heads/}} | tr / -) == 'robertomonteromiguel-lib_injection_system_tests_integration' ]; then
Change to master after merge

2022-12-14 11:58 UTC, robertomonteromiguel commented on .github/workflows/lib-injection.yaml
> +        platforms: "linux/amd64,linux/arm64/v8"
Finally talking with @pawelchcki we decided to work only with amd64 and arm64... are you agree @devinsba ?

2022-12-14 15:52 UTC, devinsba commented on .github/workflows/lib-injection.yaml
> +        platforms: "linux/amd64,linux/arm64/v8"
I'm not sure what changed then. Our releases since this feature released have been created for the 10 architectures you can see here: https://hub.docker.com/repository/registry-1.docker.io/datadog/dd-lib-java-init/tags?page=1&ordering=last_updated

If we are to change this we will need to check with a PM. I can't make that decision

2022-12-14 19:54 UTC, robertomonteromiguel commented on .github/workflows/lib-injection.yaml
> +        platforms: "linux/amd64,linux/arm64/v8"
Ok. I have changed. I  added a new step, because "steps.buildx.outputs.platforms" returns too many platforms.

2022-12-14 21:16 UTC, devinsba approved these changes

2022-12-22 09:20 UTC, merged