[WIP] Split DDId into DDSpanId and DDTraceId
DataDog/dd-trace-java pull request #4211
Opened 2022-11-11 08:55 UTC by bantonsson

# What Does This Do

Splits `DDId` into `DDSpanId` and `DDTraceId`

# Motivation

In preparation for 128 bit trace ids and other changes

# Additional Notes

2022-11-11 09:21 UTC, richardstartin commented
Do you think the span id could just be a `long`?

2022-11-11 09:27 UTC, bantonsson commented
I don't think so, since we want to cache various representations for header injection in the propagators.

2022-11-11 11:23 UTC, richardstartin commented
> I don't think so, since we want to cache various representations for header injection in the propagators.

Can we discuss this offline? What if a span never propagates, or only propagates once? It made sense when the ID types were shared because it's always a win for trace ids, but this incurs cost in the interior nodes of the span tree for the sake of caching a value at the leaves which may never be reused.

2022-11-11 11:32 UTC, richardstartin requested changes
I want to discuss the relative merits of `DDSpanId` vs `long` before this is merged, I'll approve if consensus forms in favour of `DDSpanId`.

2022-11-11 11:50 UTC, bantonsson commented
Completely agree that the `DDSpanId` can be changed into a `long` with some helper functions and caches if needed.

2022-11-14 14:24 UTC, richardstartin commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Location.java
> +  public long getSpanId() {
this looks suspicious because it can NPE, why not just leave it as zero in the constructor and use it as a sentinel value? Since 0 is an invalid value for a span id, this doesn't have any downsides, it just replaces null checks with zero checks with the benefit of not blowing up if you miss one.

2022-11-14 14:33 UTC, bantonsson commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Location.java
> +  public long getSpanId() {
The only downside of using `0` is that you would need to write your own `JsonAdapter<Location>` which I would rather not. This method is only used from tests, but I'll make sure that it doesn't throw NPE.

2022-11-14 14:34 UTC, bantonsson commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Location.java
> +  public long getSpanId() {
Great catch BTW.

2022-11-14 15:33 UTC, richardstartin approved these changes
Approving to remove my request for changes, I have scrutinised some but not all of the changes: get an approval from someone else before merging.

2022-11-14 15:53 UTC, bantonsson commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Location.java
> +    this.spanId = spanId == 0 ? null : spanId;
@smola Did I interpret the tests correctly and we don't want to serialize out a `spanId` if there isn't one?

2022-11-14 16:54 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/XRayHttpCodec.java
> +              .append(DDSpanId.toHexStringPadded(context.getSpanId()));
The X-Ray spec is very strict about this being padded to 16 chars - I assume that the chance of `DDSpanId.toHexStringPadded` changing its target width is very low to zero?

2022-11-14 17:01 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceStructureWriter.java
> +        if (!(rootSpanId == span.getSpanId())) {
simplify to `!=` ?

2022-11-14 17:04 UTC, PerfectSlayer approved these changes
In most place, `DDId.ZERO` was replaced by `0` (the long value) when used for Span ID.
I feel we lost the meaning of this special value. Can we add this constant somewhere and document its expected behavior and implication? Thanks 🙏 
Otherwise, looks good to me but better have more reviews

2022-11-14 17:16 UTC, mcculls approved these changes
LGTM, just a couple of minor comments

2022-11-15 07:28 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/XRayHttpCodec.java
> +              .append(DDSpanId.toHexStringPadded(context.getSpanId()));
Yes, padding to 16 chars is the only reasonable thing for span ids AFAICS, and is documented on the method.

2022-11-15 07:28 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceStructureWriter.java
> +        if (!(rootSpanId == span.getSpanId())) {
Yes

2022-11-15 07:30 UTC, bantonsson commented on dd-trace-api/src/main/java/datadog/trace/api/DDSpanId.java
> +    // TODO:ban cache here?
For future reference. I'll add a GitHub issue and link to it.

2022-11-15 07:38 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceStructureWriter.java
> -      if (rootSpanId != null) {
Yes, it's only for debug logging, but I'll add that back.

2022-11-15 07:41 UTC, bantonsson commented on dd-trace-api/src/main/java/datadog/trace/api/IdGenerationStrategy.java
> +    return null;
done

2022-11-15 09:26 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Location.java
> +    this.spanId = spanId == 0 ? null : spanId;
@bantonsson We assumed there would always be a span ID, but yes, if there really isn't, then we shouldn't serialize the `spanId` field.

cc @manuel-alvarez-alvarez I guess that we'll need to make this optional too?
https://github.com/DataDog/experimental/blob/cc82f08a8429feb40e68c7a8eaacd2d72af3f0f5/teams/asm/vulnerability_schema/vulnerability_schema.json#L84-L86

2022-11-15 09:30 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Location.java
> +    this.spanId = spanId == 0 ? null : spanId;
Yes, that's how it's done in the tests, but in the real life scenarios there will always be a span linked to a location.

2022-11-15 10:02 UTC, merged