Remove prefixes for value reference in expressions
DataDog/dd-trace-java pull request #4378
Opened 2022-12-05 13:26 UTC by jpbempel

# What Does This Do
Value references are now without prefix except field access with `this` or synthetic variable (`@duration`).
Json representation have then changed to use `ref` and `getmember` operator.
The `ValueReferenceResolver` have evolved to have 2 methods instead of
matching those operators: `lookup` and `getmember`

# Motivation
More user-friendly way to express var/field accesses

# Additional Notes

2022-12-06 21:15 UTC, shatzi requested changes
I think there is a bug regarding the resolving references. maybe I'm wrong

2022-12-06 21:15 UTC, shatzi commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
> +        Field declaredField = clazz.getDeclaredField(name); // no parent fields!
also this doesn't support interfaces right?

2022-12-06 21:15 UTC, shatzi commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
>            convertIfRequired(varType, expectedType, insnList);
not sure if convertIfRequired should be called on every tryRetrieveLocalVar but only at the end of expressions.

2022-12-07 07:19 UTC, jpbempel commented
> I think there is a bug regarding the resolving references. maybe I'm wrong

yeah nice catches! need to revisit and add more tests 😞

2022-12-07 18:26 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
> +        Field declaredField = clazz.getDeclaredField(name); // no parent fields!
we don't support calling method, so interfaces too by consequence

2022-12-07 18:32 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
>            convertIfRequired(varType, expectedType, insnList);
true

2022-12-07 18:32 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ValueRefExpressionTest.java
> +    ExTester instance = new ExTester(null, "\"hello\"");
refactoring leftover

2022-12-19 17:34 UTC, shatzi commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
> +      if (arguments != null && !arguments.isEmpty()) {
do we cap arguments/local/field length when creating a CaptureContext?

2022-12-19 17:38 UTC, shatzi commented on dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java
> +            case "parsedExpr":
what did we decided to use at the end? "expr" + "ParsedExpr" or we are changing everything to "dsl" and "json"?

2022-12-19 17:47 UTC, shatzi commented on dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/RefResolverHelper.java
> +    while (clazz != null) {
are we using this trick for CaptureContent.addFields()? 
ans also for ReflectiveFieldResolver?

2022-12-19 17:50 UTC, shatzi commented on dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/Tester.java
> +class Tester {
I find the name confusing.
When I read it the first time I thought it was some kind of a Test, and ExTester was even more confusing.

Suggest HelperObject, or ObjectWithRefAndValue

2022-12-19 18:29 UTC, shatzi commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
> +        Field declaredField = clazz.getDeclaredField(name); // no parent fields!
We might need to rethink the compile logic here.
The UI is adding the ability to create metric from any node in the captured tree.
That mean, there is an expection that we resolve interface/baseClass to the acutal 
object class.

Should we have two different logic pathes:
First, find the field from compiled type. if fails...
Second, use ReflectiveFieldResolver at run-time and report error if failed

Maybe a different PR?

2022-12-19 18:32 UTC, shatzi commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
> +  private static class ResolverResult {
I like the idea of creating a new insnList for every Ref and append it to with getMember.

Two notes:
1. When it come to do getIndex we would need to merge two lists togther.
2. Each GetMemebr add NULL check and jump. it would be nice if the ResolverResult would have "NullJump" label that all getMembers can jump to and skip the enitre chain.

2022-12-19 18:34 UTC, shatzi approved these changes
Great progress. LGTM. There are few points we should address in following PRs. mostly the gap in how we handle interface and base classes in both Script Eval and Compiled expression.

2022-12-20 08:54 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
> +        return target;
it's a safety net, but the error was already took into account in `lookup` method

2022-12-20 08:57 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
> +      Object field = fields.get(name);
not here, at serialization time

2022-12-20 08:57 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
> +      if (arguments != null && !arguments.isEmpty()) {
no

2022-12-20 08:59 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java
> +            case "parsedExpr":
not decided. and seems the vote are split half-half :(

2022-12-20 09:35 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/RefResolverHelper.java
> +    while (clazz != null) {
we are not capturing parent fields of class of instance method.

2022-12-20 09:37 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/Tester.java
> +class Tester {
done

2022-12-20 09:43 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
> +        Field declaredField = clazz.getDeclaredField(name); // no parent fields!
clearly a different PR, we had the problem before changing the syntax.

2022-12-20 09:46 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
> +        Field declaredField = clazz.getDeclaredField(name); // no parent fields!
Obviously there are some known limitation with the compile approach.
But usually it involves invoking methods, with the all the issues you are pulling with that approach...

2022-12-21 11:45 UTC, merged

2022-12-21 17:53 UTC, shatzi commented on dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java
> +            case "parsedExpr":
I think you can then be the vote-breaker - and make the decision. it is a good timing as Cimi is update the UI parser.

2022-12-21 17:56 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java
> +            case "parsedExpr":
Already did, we keep dsl/json, and updated the PR accordingly