Add support for tainting cookies
DataDog/dd-trace-java pull request #4419
Opened 2022-12-13 14:43 UTC by jandro996

# What Does This Do

Add support for tainting cookies

# Motivation

# Additional Notes

2022-12-14 11:15 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Tainteds.java
> +  public static boolean canBeTaintedNullSafe(@Nullable final CharSequence s) {
Check `canBeTainted` it's now null safe by default

2022-12-14 11:22 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
> +  void onCookie(String comment, String domain, String value, String name, String path);
The ordering of the parameters wakes up my TOC :smile:, I'll rather do `name`, `value`, and the rest in no particular order.

2022-12-14 12:57 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Tainteds.java
> +  public static boolean canBeTaintedNullSafe(@Nullable final CharSequence s) {
done

2022-12-14 12:57 UTC, jandro996 commented on internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
> +  void onCookie(String comment, String domain, String value, String name, String path);
done

2022-12-14 12:58 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
> +          comment, new Source(SourceType.REQUEST_COOKIE, "http.request.cookie.comment", comment));
Fixed for the "all string attributes tainted" approach

2022-12-15 10:33 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +            module.onCookie(
This might introduce a lot of pressure on the tainted objects map, we could taint methods on the Cookie class itself but it might introduce false positives with custom created objects.

What do you think @smola @anderruiz ?

2022-12-15 10:33 UTC, manuel-alvarez-alvarez approved these changes

2022-12-15 11:09 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/SourceType.java
> +  public static final byte REQUEST_COOKIE_NAME = 5;
@jandro996  Please, also add these to the JSON schema spec.

2022-12-15 11:11 UTC, smola commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +            module.onCookie(
I think we could taint `Cookie` instances themselves. Then instrument `Cookie` methods and taint their outputs only if the cookie object itself is tainted?

2022-12-15 11:33 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/SourceType.java
> +  public static final byte REQUEST_COOKIE_NAME = 5;
I made this PR yesterday to add it 👍  
https://github.com/DataDog/experimental/pull/1692

2022-12-16 11:59 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
> +          comment, new Source(SourceType.REQUEST_COOKIE, "http.request.cookie.comment", comment));
Agreed.

2022-12-16 14:30 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
> +            .with(
I guess you didn't want to commit this

2022-12-16 14:54 UTC, jandro996 commented on dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
> +            .with(
😨

2022-12-19 09:45 UTC, jandro996 commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +            module.onCookie(
Done, as @smola have  suggested

2022-12-19 14:22 UTC, smola requested changes

2022-12-19 14:22 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
> +    final IastRequestContext ctx = IastRequestContext.get();
Return early if `cookies == null`.

2022-12-19 14:22 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
> +    final IastRequestContext ctx = IastRequestContext.get();
Return early if result cannot be tainted.

2022-12-20 10:20 UTC, smola approved these changes

2022-12-20 10:48 UTC, merged