AgentCLI command to debug detected dependencies
DataDog/dd-trace-java pull request #4458
Opened 2022-12-20 11:05 UTC by anderruiz

# What Does This Do

New command line tool to scan dependencies in a jar/war file or in a folder

# Motivation

Provide a tool that gathers more information that what it is stored in the backend to be able to debug weird scenarios

2022-12-20 11:15 UTC, smola requested changes

2022-12-20 11:15 UTC, smola commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
> +                  log.debug("Entry:" + e.getName() + " ignored in file:" + file.getAbsolutePath());
```suggestion
                  log.debug("Entry: {} ignored in file: {}",  e.getName() , file.getAbsolutePath());
```

2022-12-20 11:15 UTC, smola commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
> +                    log.debug("Adding new jar:" + temp.getAbsolutePath());
```suggestion
                    log.debug("Adding new jar: {}", temp.getAbsolutePath());
```

2022-12-20 11:15 UTC, smola commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
> +                        "Jar entry found in file:" + file.getName() + " entry:" + e.getName());
```suggestion
                        "Jar entry found in file: {} entry: {}", file.getName(), e.getName());
```

2022-12-20 11:15 UTC, smola commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentJar.java
> +          case "scandependencies":
```suggestion
          case "scanDependencies":
```

To maintain consistency with case style of other commands.

2022-12-20 11:15 UTC, smola commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentJar.java
> +    System.out.println("  scandependencies file/path ...");
```suggestion
    System.out.println("  scanDependencies <path> ...");
```

2022-12-20 11:15 UTC, smola commented on telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
> +    log.debug("No maven dependency added {}.{} jar name {} hash {}");
There are placeholders here, but no arguments?

2022-12-20 13:56 UTC, ValentinZakharov approved these changes

2022-12-20 13:59 UTC, ValentinZakharov commented
Does it make sense turn debug messages for log file, turn into stdout? 🤔 
I'm doubt somebody will use tracer as CLI with enabled debug mode.

2022-12-20 14:31 UTC, dougqh commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
> +                    throw new RuntimeException(ex);
Why are we propagating a RuntimeException?
What are we doing in the event that delete fails?  It doesn't throw an Exception; it returns a boolean.

2022-12-20 19:36 UTC, anderruiz commented on telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
> +    log.debug("No maven dependency added {}.{} jar name {} hash {}");
Done

2022-12-20 19:41 UTC, anderruiz commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
> +                    throw new RuntimeException(ex);
Changes done

2022-12-20 19:42 UTC, anderruiz commented
> Does it make sense turn debug messages for log file, turn into stdout? 🤔 I'm doubt somebody will use tracer as CLI with enabled debug mode.

Part of the normal execution will go to trace so it makes sense to use the same approach

2022-12-21 09:42 UTC, smola approved these changes

2023-01-02 08:23 UTC, merged