Jsantos/disable sending dependencies
DataDog/dd-trace-java pull request #4497
Opened 2023-01-04 11:31 UTC by DDJavierSantos

# What Does This Do

Separating Dependencies from Telemetry Events, by disabling the DependencyService using a configuration flag.

# Motivation

We’d like to have a flag to enable/disable the sending of dependency because it could possibly contain sensitive customer information. This would change the app-started event to no longer contain the dependencies list.
Requirements:
Remove dependencies field from app-started
Only send dependencies-loaded event when DD_TELEMETRY_DEPENDENCY_SERVICE_ENABLED flag is enabled
DD_TELEMETRY_DEPENDENCY_SERVICE_ENABLED is enabled by default

# Additional Notes

2023-01-04 11:48 UTC, smola requested changes

2023-01-04 11:48 UTC, smola commented on dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
> +  public static final String TELEMETRY_DEPENDENCY_SERVICE_ENABLED =
per the spec, the name of the environment variable should be `DD_TELEMETRY_SEND_DEPENDENCIES`.

```suggestion
  public static final String TELEMETRY_SEND_DEPENDENCIES = "telemetry.send.dependencies";
```

2023-01-04 11:48 UTC, smola commented on telemetry/src/test/groovy/datadog/telemetry/DisabledDependencyServiceTest.groovy
> +class DisabledDependencyServiceTest  extends DDSpecification{
```suggestion
class DisabledDependencyServiceTest extends DDSpecification {
```

2023-01-04 13:33 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
> +      }
I'd rather keep DependencyServiceImplementation as much separated from tracer as possible.
I mean, we can check `Config.get().isTelemetryDependencyServiceEnabled();` here in `TelemetrySystem.createDependencyService()` and if it's disabled, then the method will return `null`.

2023-01-04 14:38 UTC, ValentinZakharov approved these changes

2023-01-04 14:44 UTC, devinsba commented
Maybe it would be good to give the customer the freedom to configure a set of artifact group IDs that they don't want to send? I agree that a flag to turn it off completely is good but a more fine grained approach might do enough to ease fears

2023-01-04 14:46 UTC, devinsba commented on telemetry/src/test/groovy/datadog/telemetry/DisabledDependencyServiceTest.groovy
> +    injectSysConfig("dd.telemetry.send.dependencies", "false")
Maybe `dd.telemetry.dependency-collection.enabled` would be better aligned with other feature enable/disable configs

2023-01-05 09:02 UTC, DDJavierSantos commented on dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
> +  public static final String TELEMETRY_DEPENDENCY_SERVICE_ENABLED =
done

2023-01-05 09:02 UTC, DDJavierSantos commented on telemetry/src/test/groovy/datadog/telemetry/DisabledDependencyServiceTest.groovy
> +class DisabledDependencyServiceTest  extends DDSpecification{
done

2023-01-05 09:34 UTC, smola commented
> @devinsba Maybe it would be good to give the customer the freedom to configure a set of artifact group IDs that they don't want to send? I agree that a flag to turn it off completely is good but a more fine grained approach might do enough to ease fears

Good point. I'll bring this up with the telemetry team.

2023-01-05 10:46 UTC, DDJavierSantos commented on telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
> +      }
done

2023-01-06 00:12 UTC, mcculls commented on telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
> +    if (Config.get().isTelemetryDependencyServiceEnabled()) {
```suggestion
    if (null != dependencyService) {
```

This avoids checking the same flag twice and also avoids a NPE when the tracer jar is used to send sample traces:
```
$ java -jar dd-java-agent/build/libs/dd-java-agent-1.4.0-SNAPSHOT.jar sampleTrace
[dd.trace 2023-01-06 00:11:29:212 +0000] [main] INFO com.datadog.appsec.AppSecSystem - AppSec is ENABLED_INACTIVE with powerwaf(libddwaf: 1.5.1) no rules loaded
[dd.trace 2023-01-06 00:11:29:239 +0000] [dd-telemetry] ERROR datadog.telemetry.TelemetryRunnable - Uncaught exception in dd-telemetry
java.lang.NullPointerException
	at datadog.telemetry.dependency.DependencyPeriodicAction.doIteration(DependencyPeriodicAction.java:17)
	at datadog.telemetry.TelemetryRunnable.run(TelemetryRunnable.java:54)
	at java.lang.Thread.run(Thread.java:750)
[dd.trace 2023-01-06 00:11:29:652 +0000] [dd-task-scheduler] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {...}
... completed 6 traces
```

2023-01-13 09:31 UTC, DDJavierSantos commented on telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
> +    if (Config.get().isTelemetryDependencyServiceEnabled()) {
Done

2023-01-16 11:56 UTC, mcculls approved these changes

2023-01-17 14:28 UTC, smola commented on telemetry/src/test/groovy/datadog/telemetry/DisabledDependencyServiceTest.groovy
> +    injectSysConfig("dd.telemetry.send.dependencies", "false")
Wait a sec. This setting comes from a spec that will be the same across languages. So I would rather not diverged from it.

cc @DDJavierSantos

2023-01-19 08:30 UTC, bantonsson commented on telemetry/src/test/groovy/datadog/telemetry/DisabledDependencyServiceTest.groovy
> +    injectSysConfig("dd.telemetry.send.dependencies", "false")
@smola I can't find anything resembling that setting when searching through our documents. Naming is hard, and it would be good if external facing user configuration followed some convention going forward.

2023-01-27 07:47 UTC, smola commented on telemetry/src/test/groovy/datadog/telemetry/DisabledDependencyServiceTest.groovy
> +    injectSysConfig("dd.telemetry.send.dependencies", "false")
The spec was updated to use `DD_TELEMETRY_DEPENDENCY_COLLECTION_ENABLED`.
@DDJavierSantos We're good to update the PR to `DD_TELEMETRY_DEPENDENCY_COLLECTION_ENABLED` / `dd.telemetry.dependency-collection.enabled`.

2023-01-27 07:49 UTC, smola approved these changes

2023-01-27 09:28 UTC, merged