Implementation of Telemetry API Exception reporting
DataDog/dd-trace-java pull request #4521
Opened 2023-01-10 19:42 UTC by DDJavierSantos

# What Does This Do
Implements Exception reporting using the Telemetry API

# Motivation
To collect reports about exceptions in client's installations. This will be used for troubleshooting.

# Additional Notes

2023-01-18 11:57 UTC, mcculls commented
FYI, if you have a new bootstrap class which is referenced during startup and you see this kind of error from the Graal smoke tests:
```
No instances of SomeClass are allowed in the image heap as this class should be initialized at image runtime
```
then there are 2 options - one is to use `!Platform.isNativeImageBuilder()` to guard code we never expect to run during native image. That is useful to eliminate large chunks of code which are inapplicable to native-image, but won't work if the class is still being touched from startup code (in other words it depends how the class is being used).  

The other option is to add it to the list of build-time classes in https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java#L64 - ideally we want to list as few classes as possible there (especially since you then need to list any classes they depend on, etc...) so this should be a last resort. Excluding the feature via `!Platform.isNativeImageBuilder()` is preferred.

2023-01-19 15:32 UTC, smola requested changes

2023-01-19 16:46 UTC, DDJavierSantos commented on telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
> +      // TODO: update jnr_ffi and jnr_unixsocket to version that supports aarch64
Done

2023-01-19 16:53 UTC, DDJavierSantos commented on telemetry/src/main/java/datadog/telemetry/api/LogTelemetry.java
> +  public void setApiVersion(ApiVersion apiVersion) {
Removed

2023-01-20 08:03 UTC, smola requested changes

2023-01-20 08:03 UTC, smola commented on internal-api/src/test/groovy/datadog/trace/api/LogCollectorTest.groovy
> +  def 'Log Collector Test'() {
Can you add tests for de-duplication?

2023-01-20 08:03 UTC, smola commented on internal-api/src/test/groovy/datadog/trace/api/LogCollectorTest.groovy
> +    messageList.size() == LogCollector.MAX_ENTRIES + 1
Why `MAX_ENTRIES + 1` and not `MAX_ENTRIES`?

2023-01-20 11:38 UTC, DDJavierSantos commented on internal-api/src/main/java/datadog/trace/api/telemetry/LogCollector.java
> +    } else if (isDDCode && null != format) {
Done

2023-01-20 11:40 UTC, DDJavierSantos commented on internal-api/src/test/groovy/datadog/trace/api/LogCollectorTest.groovy
> +  def 'Log Collector Test'() {
there is one in TelemetryLogTest:

2023-01-20 11:41 UTC, DDJavierSantos commented on internal-api/src/test/groovy/datadog/trace/api/LogCollectorTest.groovy
> +    messageList.size() == LogCollector.MAX_ENTRIES + 1
Because when we overflow we add an entry with a warning about the overflow:

2023-01-20 11:43 UTC, DDJavierSantos commented on internal-api/src/main/java/datadog/trace/api/telemetry/LogCollector.java
> +      overflowedEntryCount++;
Lets change this to a telemetry entry once Manu's PR is merged. I would leave it like this for now.

2023-01-20 11:44 UTC, DDJavierSantos commented on telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
> +  private final BlockingQueue<TelemetryLogEntry> logEntries = new LinkedBlockingQueue<>();
I have added a recommended capacity. I will check other options.

2023-01-27 18:22 UTC, dougqh commented
I've only skimmed this, but it seems like a reasonable minimally invasive approach.

But as pointed out in conversation, I think there is challenge with cases that use guarded logging today.
By which I mean...
`if ( logger.isDebugEnabled() ) {
   logger.debug("myMessage {} {}", foo.getX(), foo.doExpensiveThing());
}`

I'll admit I've never been a huge fan of that idiom because it seems like we shouldn't be doing "doExpensiveThing".

My far more invasive way of solving this is to introduce a helper or event object that does the expensive work.

logger.debug("myMessage {} {}", foo, (foo) -> return new Object[] { foo.getX(), foo.doExpensiveThing() });

The idea here is use a non-capturing lambda that is only called when needed, but the passing of foo and the lambda are cheap.


Although, that's just my idea for something that kind of fits into standard logging.  I have a crazy notion of having some helper event class that handles the details.

The end call would be something like...
`logger.on(MY_EVENT, foo)`

But I feel creating those Event objects likely requires too much ceremony.

2023-02-01 15:00 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/telemetry/LogCollector.java
> +  public synchronized void addLogEntry(
Using `synchronized` for this method that can consume some time due to stack modifications, have you give it a thought about using thread safe data structures like:

-  `int overflowedEntryCount`  :arrow_right: `AtomicInteger overflowedEntryCount`
- `LinkedHashSet<TelemetryLogEntry> logEntries`  :arrow_right: `Set<TelemetryLogEntry> logEntries = ConcurrentHashMap.newKeySet();`

2023-02-01 15:00 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/telemetry/LogCollector.java
> +    if (logEntries.size() >= MAX_ENTRIES) {
It worries me a bit that there is no notion of priority between log entries, `ERROR` ones should always take priority so we don't lose them in a very verbose scenario.

2023-02-01 15:00 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  private final boolean telemetryEnabled;
Why the extra field if already present at `InstrumenterConfig`?

2023-02-01 15:00 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/telemetry/LogCollector.java
> +  public static final int MAX_ENTRIES = 10000;
Looks weird to me having a collector with room for 10.000 entries that will be capped by the telemetry service which only has room for 1.024 (`private final BlockingQueue<TelemetryLogEntry> logEntries = new LinkedBlockingQueue<>(1024);`)

2023-02-09 11:23 UTC, iunanua commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLogger.java
> +            || (level == LogLevel.DEBUG && LogCollector.get().isDebugEnabled())) {
What about `LogLevel.INFO`? in Node we are treating them as `DEBUG` for telemetry purposes

2023-02-13 18:58 UTC, jpbempel requested changes

2023-02-13 18:58 UTC, jpbempel commented on internal-api/src/main/java/datadog/trace/api/telemetry/LogCollector.java
> +  public synchronized void addLogEntry(
+1

2023-02-13 18:58 UTC, jpbempel commented on internal-api/src/main/java/datadog/trace/api/telemetry/TelemetryLogEntry.java
> +  private String stack_trace;
nit: `stackTrace`

2023-02-13 18:58 UTC, jpbempel commented on internal-api/src/main/java/datadog/trace/api/telemetry/TelemetryLogEntry.java
> +  private transient Integer hashCode = null;
maybe use the primitive `int` instead and consider 0 as no hash coached.
could also use a extra boolean `isCached` if you are afraid to stumble upon a calculated hash that is zero, consumed less memory than a boxed integer

2023-02-13 18:58 UTC, jpbempel commented on internal-api/src/main/java/datadog/trace/api/telemetry/TelemetryMarker.java
> +  private static String SEP = ", ";
can mark them `final`

2023-02-13 18:58 UTC, jpbempel commented on internal-api/src/main/java/datadog/trace/api/telemetry/TelemetryMarker.java
> +        Iterator var2 = this.referenceList.iterator();
use `Iterator<Marker> var2` this will avoid casting below

also use the for each:

```
for (Marker ref : referenceList) {
  if (ref.contains(other)) {
    return true;
  }
}

2023-02-13 18:58 UTC, jpbempel commented on internal-api/src/main/java/datadog/trace/api/telemetry/TelemetryMarker.java
> +  private List<Marker> referenceList = new CopyOnWriteArrayList();
blocker: why using a list for that instead of a HashSet?
order is important?

2023-02-13 18:58 UTC, jpbempel commented on telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
> +  private static final Config config = Config.get();
sounds useless, `get` method just returns the singleton instance

2023-02-13 18:58 UTC, jpbempel commented on telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
> +      BlockingQueue<T> srcQueue, List<T> defaultList, Integer maxItems) {
can we just use the primitive `int` for `maxItems`?

2023-02-13 18:58 UTC, jpbempel commented on internal-api/src/main/java/datadog/trace/api/telemetry/TelemetryMarker.java
> +      Iterator<Marker> it = this.iterator();
why not referencing directly referenceList and using a for each?

2023-03-31 09:34 UTC, smola commented
Let's try to move this forward. Other than the commands that are still not resolved (and should) and the pending rebase:
* Drop `dd.instrumentation.telemetry.debug` and its associated logic. I think the subset we should start with is: either has an exception attached, or it has a SEND_TELEMETRY marker.
* `dd.instrumentation.telemetry.log-collection.enabled` -> `dd.telemetry.log-collection.enabled`

2023-10-25 09:29 UTC, smola commented
Superseded by https://github.com/DataDog/dd-trace-java/pull/6057

2023-10-25 09:29 UTC, closed without merging