Implementation of IAST telemetry
DataDog/dd-trace-java pull request #4560
Opened 2023-01-18 08:30 UTC by manuel-alvarez-alvarez

# What Does This Do
This PR makes use of the telemetry API to send metrics for IAST

# Motivation

# Additional Notes

2023-01-18 08:45 UTC, smola commented on buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/AsmSpecificationBuilder.java
> +import static datadog.trace.plugin.csi.util.CallSiteConstants.*;
I think this goes against our guidelines: https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#intellij-idea

2023-01-18 08:45 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/taint/TaintedObjectsWithTelemetry.java
> +public abstract class TaintedObjectsWithTelemetry {
As much as separation of concerns here is nice, we might want to eventually add this to `TaintedObjects` for performance. But we can defer that until it's measured and profiled.

2023-01-18 08:45 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/taint/TaintedObjectsWithTelemetry.java
> +        REQUEST_TAINTED.add(delegate.getEstimatedSize());
Good point that we only bump estimated size if not in flat mode.

2023-01-18 09:08 UTC, manuel-alvarez-alvarez commented on buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/AsmSpecificationBuilder.java
> +import static datadog.trace.plugin.csi.util.CallSiteConstants.*;
Yes, I changed that, don't know why this configuration got removed from my IntelliJ

2023-01-18 09:10 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/taint/TaintedObjectsWithTelemetry.java
> +public abstract class TaintedObjectsWithTelemetry {
We could also extend instead of compose, but I don't think that taint operations will be so massive that it really makes a huge difference. But like you said, we have to measure and then make a decision.

2023-01-18 09:12 UTC, manuel-alvarez-alvarez commented on internal-api/build.gradle
> +  implementation deps.jctools
I am a bit unsure if it's OK to add this dependency to the `internal-api` module

2023-02-08 14:55 UTC, smola approved these changes

2023-02-09 14:25 UTC, jandro996 approved these changes

2023-02-16 12:58 UTC, smola requested changes

2023-02-16 12:58 UTC, smola commented on dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
> +  public static final String TELEMETRY_DEBUG_ENABLED = "instrumentation.telemetry.debug.enabled";
@manuel-alvarez-alvarez We probably need to rename this for:
* Dropping the `instrumentation.` part of the prefix.
* Possibly making something more specific, since there are side discussions for a debug flag for logs with pretty different purpose.

2023-02-16 14:22 UTC, manuel-alvarez-alvarez commented on dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
> +  public static final String TELEMETRY_DEBUG_ENABLED = "instrumentation.telemetry.debug.enabled";
Yes, I've removed the variable for the time being, we can come back to it in the future if needed.

2023-02-22 11:22 UTC, smola approved these changes

2023-02-22 16:25 UTC, merged