Add tainting support to spring json request body
DataDog/dd-trace-java pull request #4595
Opened 2023-01-25 08:29 UTC by jandro996

# What Does This Do
Add tainting support to:
- JsonFactory create parser methods
- JsonParser methods that returns Strings 
- InputStream
- request body InputStrem and Reader

# Motivation
- Support Spring request body propagation (json)

# Additional Notes
This is a first iteration that aims to get a full propagation from request body source

2023-01-30 16:29 UTC, smola requested changes

2023-01-30 16:29 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
> +  public void taintParam1IfParam2IsTainted(@Nullable Object param1, @Nullable Object param2) {
Something like `taintIfInputIsTainted` might be more intuitive.

2023-01-30 16:29 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
> +    TaintedObject tainted = taintedObjects.get(toEval);
I think we want slightly different logic here, at least for the case where the output is a `String`: if the input is fully tainted (single range, that range is a special "fully tainted" range), then the output string should be tainted with `[Range(0, str.length(), ...]` (`str.length()` rather than `MAX_INTEGER`.

2023-02-03 10:42 UTC, smola requested changes

2023-02-03 10:42 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
> +  void 'taintParam1IfParam2IsTainted without span (#param1, #param2)'(final Object param1, final Object param2) {
Please, update the function names here.

2023-02-03 10:42 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
> +      }else{
```suggestion
      } else{
```

2023-02-03 10:42 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
> +      if(param1 instanceof String){
```suggestion
      if (param1 instanceof String) {
```

etc, please, apply the formatter.

2023-02-03 10:42 UTC, smola commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
> +     * *
```suggestion
```

2023-02-06 10:19 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +    return new Range[] {new Range(0, Integer.MAX_VALUE, source)};
Can it be problematic using `Integer.MAX_VALUE` from the point of view of the backend (they will have to know that `2147483647` means that the full value is tainted)?

2023-02-06 10:25 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
> +  void 'taintIfInputIsTainted null or empty (#param1, #param2)'(final Object param1, final Object param2) {
Using the syntax is problematic for `spock`, I think it's better if we don't declare the parameters to prevent issues (I did introduce this flaky syntax sorry :cry:)

2023-02-06 10:32 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/JsonFactoryCallSite.java
> +public class JsonFactoryCallSite {
Since we are already instrumenting inside the `JsonParser` I'll rather use traditional instrumentation instead of call site for this one. 

I think we are also missing `com.fasterxml.jackson.core.JsonFactory.createParser(java.io.Reader)`

2023-02-06 10:38 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
> +    public String[] getClassesToBeForced() {
Check helperClassNames():
```java
    public String[] helperClassNames() {
      return new String[0];
    }
```

We are not using java beans syntax, so perhaps a better name will be `public String preloadClassNames()`

2023-02-06 10:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
> +        forceClassLoad();
I don't think this is the right place to do it, maybe:

```java
@Override
    public final void instrument(TransformerBuilder transformerBuilder) {
      super.instrument(transformerBuilder);
      if (isEnabled()) {
        forceClassLoad();
      } 
    }
```

2023-02-06 11:37 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +    return new Range[] {new Range(0, Integer.MAX_VALUE, source)};
Range offsets never reach the backend, so as long as our internal handling is correct, there's no problem for them.

2023-02-06 11:40 UTC, smola approved these changes
Ok from me, provided that Manu's comments are addressed.

2023-02-06 11:46 UTC, jandro996 commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
> +        forceClassLoad();
`public void instrument(TransformerBuilder transformerBuilder)` is declared as final in the Default Instrumenter.  A few weeks ago we asked in slack about an issue that we found trying to instrument PushbackInputStream and @mcculls  suggested us to force the class load. Stuart, are you okay with making this change?

2023-02-06 12:27 UTC, jandro996 commented on dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/JsonFactoryCallSite.java
> +public class JsonFactoryCallSite {
Ok! We will implement it in the next iteration

2023-02-06 15:20 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +    return new Range[] {new Range(0, Integer.MAX_VALUE, source)};
Actually I think it will break our `EvidenceAdapter`, can you add a test at `EvidenceEncodingTest`

2023-02-06 15:25 UTC, manuel-alvarez-alvarez approved these changes

2023-02-06 16:07 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
> +    return new Range[] {new Range(0, Integer.MAX_VALUE, source)};
As @manuel-alvarez-alvarez said this PR breaks the `EvidenceAdapter`, I've modified it and added a new test case

2023-02-07 10:14 UTC, mcculls commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
> +        forceClassLoad();
yes, it's fine to make it non-final

2023-02-07 10:58 UTC, merged