Removing some statements that log sensitive information
DataDog/dd-trace-java pull request #4619
Opened 2023-01-30 12:53 UTC by DDJavierSantos

# What Does This Do
debug, error and warn logging statements that report both a resource and an exception have been changed so they don't get sent over the wire by the telemetry code. Instead of reporting the full exception with trace they now only report the exception message.

# Motivation
Exception reports filed by DDLogger will be sent to our servers using the telemetry API. If the message contains both an exception report and the name of a resource this could leak sensitive information that would be sent through the internet. Reporting only the exception message results in the telemetry API not sending this messages to our servers.

# Additional Notes
This changes are related to the new telemetry functionality implemented by https://github.com/DataDog/dd-trace-java/pull/4521

2023-01-30 13:40 UTC, smola requested changes

2023-01-30 13:40 UTC, smola commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/blocking/BlockingActionHelper.java
> +      log.warn("Error reading template file {} Exception: {}", f, e.getMessage());
Exceptions are treated especially, and we generally don't need to add them to the placeholders. I don't think this like (or any like this one) would need any change?

2023-01-30 16:35 UTC, smola commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +      log.debug("Initializing JMX system access provider for {}", classLoader.toString());
I think we can replace this:
```
    if (log.isDebugEnabled()) {
      log.debug("Initializing JMX system access provider for {}", classLoader.toString());
    }
```

with:

```
log.debug("Initializing JMX system access provider for {}", classLoader);
```

since the `toString()` will be triggered by the logging fornmattibgm and the `isDebugEnabled` call was presumably added to avoid that.

2023-01-30 16:35 UTC, smola commented on dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
> +        log.warn("Failed to initialize profiling agent! {}", e.getMessage());
@richardstartin I guess we might want to log just one or the other? (using the `isDebugEnabled` helper)

2023-01-30 16:35 UTC, smola commented on dd-smoke-tests/jboss-modules/src/main/java/datadog/smoketest/jbossmodules/common/ServiceSupport.java
> +      log.warn("Problem starting {}" + this, e);
```suggestion
      log.warn("Problem starting {}", this, e);
```

2023-01-30 16:35 UTC, smola commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +      log.warn("Problem loading TraceInterceptor for classLoader: {}", classLoader.toString(), e);
Do we need the `toString()` here?

2023-01-30 18:57 UTC, DDJavierSantos commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/blocking/BlockingActionHelper.java
> +      log.warn("Error reading template file {} Exception: {}", f, e.getMessage());
I have removed those

2023-02-01 15:04 UTC, DDJavierSantos commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +      log.debug("Initializing JMX system access provider for {}", classLoader.toString());
done

2023-02-02 09:49 UTC, smola approved these changes

2023-02-02 11:12 UTC, jpbempel approved these changes

2023-08-09 21:37 UTC, richardstartin approved these changes

2023-08-10 07:14 UTC, bantonsson commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
> +      log.error("Cannot write classfile for class: {} Exception: ", classFilePath, t.getMessage());
Is this missing a placeholder?

2023-08-10 15:22 UTC, merged

2023-08-10 15:51 UTC, DDJavierSantos commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
> +      log.error("Cannot write classfile for class: {} Exception: ", classFilePath, t.getMessage());
removed

2023-08-11 20:41 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
> +      log.error("Cannot write classfile for class: {} Exception: ", classFilePath, t.getMessage());
Sorry late to the party, but here you have changed the behavior of our log here, I want the full exception and not just the message.
Other places with exception are not changed like here.
Please revert this.