Split check job out of the critical path
DataDog/dd-trace-java pull request #4654
Opened 2023-02-03 17:35 UTC by smola

# What Does This Do
Split check job out of the critical path

# Motivation
So we don't delay starting tests, but if check fails, we still cancel the whole workflow.

# Additional Notes

2023-02-03 17:36 UTC, richardstartin requested changes
If I've got a formatting error, I want to know straight away

2023-02-03 18:46 UTC, richardstartin approved these changes

2023-02-08 08:15 UTC, bantonsson approved these changes

2023-02-08 08:15 UTC, bantonsson commented on .circleci/cancel_workflow.sh
> +echo "Canceliing workflow ${CIRCLE_WORKFLOW_ID}"
Cancel*ii*ng

2023-02-08 08:30 UTC, bantonsson commented on .circleci/config.yml
> +  spotless:
Is there a particular reason that the `spotless` job doesn't use `.circleci/cancel_workflow.sh` the same way as `check`?

2023-02-08 11:54 UTC, smola commented on .circleci/config.yml
> +  spotless:
While `check` runs concurrently to all test jobs, all downstream jobs depend on both `build` and `spotless`, so a spotless failure already prevents every job from running, except `build`. I thought it wouldn't be as relevant in that case, but I have no strong opinion on that.

2023-02-08 12:00 UTC, bantonsson commented on .circleci/config.yml
> +  spotless:
No strong opinion either. It was only that the number of dependency lines was getting a bit cluttered. Another option would be to have `build` and `spotless` combine into `ok to test` and all tests depend on that.

2023-02-08 14:32 UTC, smola commented on .circleci/config.yml
> +  spotless:
Sounds good, I think we'll survive to the extra 3 seconds of the fan-in job :wink: 
Here's an example: https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/21488/workflows/4bf34acd-8ff0-48bb-9b7b-e116bb49fd6b

2023-02-08 17:16 UTC, merged