Improve graphql sanitizer to only sanitize value types that are neces…
DataDog/dd-trace-java pull request #4662
Opened 2023-02-05 04:39 UTC by theJC

…sary/could contain sensitive info

# What Does This Do

Fixes https://github.com/DataDog/dd-trace-java/issues/4661

# Motivation

Currently the GraphQL sanitization implementation changes too much/wipes out useful information that would not be considered sensitive/needing sanitization, such as variable references and use of Enums.

# Additional Notes

2023-03-08 17:21 UTC, ygree commented on dd-java-agent/instrumentation/graphql-java-14.0/src/main/java/datadog/trace/instrumentation/graphqljava/GraphQLQuerySanitizer.java
> +  public TraversalControl visitIntValue(IntValue node, TraverserContext<Node> context) {
Would be nice to have these cases also covered in the tests.

2023-03-08 17:38 UTC, ygree commented on dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
> +    def query = 'query findBookById($id: ID) {\n' +
Good to have this test case for named parameters. I think that it will work with current implementation the same way though preserving the named parameters as is in the sanitized queries.

2023-03-08 17:41 UTC, ygree commented on dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
> +      '  bookById(id: "") {\n' +
Now sanitized values will be replaced with defaults which makes them indistinguishable from the real values. Is it possible to use `?` for all sanitized values to make this more explicit?

2023-03-08 17:45 UTC, ygree requested changes
Thanks for your contribution. Could you provide an example where current implementation is overzealous? Would be great to have it as a test case. From current changes I only see that `?` is now `""`.

2023-03-08 18:02 UTC, theJC commented on dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
> +      '  bookById(id: "") {\n' +
I dont see why not.

I like your suggestion, its a blend of what I'm try to improve and what was being done before - best of both worlds.  I'll give it a whirl, thanks for the 👀 and suggestion!

2023-03-08 18:53 UTC, theJC commented on dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
> +      '  bookById(id: "") {\n' +
One thing that this updated method of sanitization does for the reader is they already have an idea of what type the constant is, versus if we replace the values with a Enum ?, then they have to go reference something else to refresh/review what type it is.

2023-03-08 19:14 UTC, theJC commented on dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
> +      '  bookById(id: "") {\n' +
Based on this feedback, how about using different enum values that provide hints to the customer as to which type.  I've pushed an update showing an example of this.

2023-03-12 05:57 UTC, theJC commented on dd-java-agent/instrumentation/graphql-java-14.0/src/main/java/datadog/trace/instrumentation/graphqljava/GraphQLQuerySanitizer.java
> +  public TraversalControl visitIntValue(IntValue node, TraverserContext<Node> context) {
Updated, created a separate test class that just tests sanitization by itself and hit all the cases.

2023-03-12 05:59 UTC, theJC commented
Added an additional test case that showed the variable references being sanitized which doesn't seem like it was necessary and lost information that could be useful.

2023-03-13 04:04 UTC, theJC commented on dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
> +      '  bookById(id: "") {\n' +
@ygree -- Whats your take on my proposal to preserve some type fingerprint on the nodes that are sanitized?  

If we can get alignment on that front, I think everything else mentioned/discussed in this MR has been addressed.

2023-03-21 18:53 UTC, ygree approved these changes

2023-03-21 18:54 UTC, merged