Jax-rs instrumentation for IAST
DataDog/dd-trace-java pull request #4670
Opened 2023-02-06 15:02 UTC by DDJavierSantos

# What Does This Do
IAST instrumentation for jax-rs web services implementations.

# Motivation
We need to support Jersey web services applications in IAST. They need specific instrumentations since they don't use ServletRequest

# Additional Notes

2023-02-09 16:22 UTC, cataphract commented on dd-java-agent/instrumentation/jersey-2-appsec/src/main/java/datadog/trace/instrumentation/jersey2/ParamConverterInstrumentation.java
> +    return implementsInterface(named("javax.ws.rs.ext.ParamConverter"));
See if you can instrument a single jersey specific class rather doing expensive hierarchy checks and instrumenting many classes (like it's done in MessageBodyReaderInstrumentation).

2023-02-21 10:16 UTC, smola requested changes

2023-02-21 10:16 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderInstrumentation.java
> +public class AbstractStringReaderInstrumentation extends Instrumenter.Tracing
```suggestion
public class AbstractStringReaderInstrumentation extends Instrumenter.Iast
```

So that they are activated only with IAST.

2023-02-23 15:36 UTC, cataphract commented on dd-java-agent/instrumentation/glassfish/build.gradle
> +  testImplementation group: 'org.glassfish.jersey.core', name: 'jersey-common', version: '3.0.0'
Not sure what these two extra dependencies are doing here, since nothing else changes in the module.

2023-02-23 15:36 UTC, cataphract commented on dd-java-agent/instrumentation/jersey-3-appsec/build.gradle
> +  testImplementation group: 'org.glassfish.jersey.core', name: 'jersey-common', version: '3.0.0'
This module has no tests, so this is definitely not doing anything. Bit perhaps it would make sense to merge the existing jersey-3-appsec and the new jersey module, since they both target jersey 3

2023-02-23 15:36 UTC, cataphract commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderAdvice.java
> +        System.out.println("Module is null");
Are we supposed to be printing stuff directly to stout?

2023-02-23 15:36 UTC, cataphract commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderInstrumentation.java
> +    super("AbstractStringReaderAdvice Jersey 2");
This should be a shortish name without spaces, since it is used to disable/enable modules via configuration

2023-03-13 13:39 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/glassfish/build.gradle
> +  testImplementation group: 'org.glassfish.jersey.core', name: 'jersey-common', version: '3.0.0'
removed

2023-03-13 13:39 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey-3-appsec/build.gradle
> +  testImplementation group: 'org.glassfish.jersey.core', name: 'jersey-common', version: '3.0.0'
removed

2023-03-13 13:40 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderAdvice.java
> +        System.out.println("Module is null");
removed

2023-03-13 13:40 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderInstrumentation.java
> +    super("AbstractStringReaderAdvice Jersey 2");
Name changed to jersey (name of the module)

2023-03-14 10:28 UTC, smola requested changes

2023-03-14 10:28 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderInstrumentation.java
> +        named("fromString").and(isPublic()), packageName + ".AbstractStringReaderAdvice");
Please, add explicit matchers for argument number and argument types.

2023-03-14 10:28 UTC, smola commented on dd-java-agent/instrumentation/jersey/build.gradle
> +  testImplementation group: 'org.glassfish.jersey.core', name: 'jersey-common', version: '3.0.0'
Is this for jersey-3 only? I'd name the module as `jersey-3` if that's the case.

2023-03-14 10:28 UTC, smola commented on dd-smoke-tests/jersey-2/src/test/groovy/datadog/smoketest/Jersey2SmokeTest.groovy
> +    //command.add("-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000")
Please, remove debugging leftovers.

2023-03-14 10:28 UTC, smola commented on dd-smoke-tests/jersey-2/src/test/groovy/datadog/smoketest/Jersey2SmokeTest.groovy
> +  def "Test path parameter in Jersey"() {
```suggestion
  def "Test path parameter"() {
```

The suite name already provides the `in Jersey` context.

2023-03-21 14:38 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey/build.gradle
> +  testImplementation group: 'org.glassfish.jersey.core', name: 'jersey-common', version: '3.0.0'
This is for both, but I can only test with one

2023-03-21 14:40 UTC, DDJavierSantos commented on dd-smoke-tests/jersey-2/src/test/groovy/datadog/smoketest/Jersey2SmokeTest.groovy
> +    //command.add("-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000")
Done

2023-03-21 14:40 UTC, DDJavierSantos commented on dd-smoke-tests/jersey-2/src/test/groovy/datadog/smoketest/Jersey2SmokeTest.groovy
> +  def "Test path parameter in Jersey"() {
Done

2023-03-22 08:55 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderInstrumentation.java
> +        named("fromString").and(isPublic()), packageName + ".AbstractStringReaderAdvice");
See `takesArguments`, which can get the types of arguments.

2023-03-22 09:36 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderInstrumentation.java
> +        named("fromString").and(isPublic()), packageName + ".AbstractStringReaderAdvice");
done

2023-03-22 09:48 UTC, smola commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
> +    accessLogValue = (server as TomcatServer).accessLogValue
Same, was this actually needed?

2023-03-22 09:50 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderAdvice.java
> +          module.onUnexpectedException("afterGetParameter threw", e);
```suggestion
          module.onUnexpectedException("AbstractStringReaderAdvice.exit threw", e);
```

2023-03-22 09:50 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/HttpHeadersInstrumentation.java
> +  public static class $InstrumenterAdvice {
I don't think you need to add a `$` to your class name. `$` is just the generated name for inner classes.

2023-03-22 09:50 UTC, DDJavierSantos commented on dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/WithHttpServer.groovy
> +    server = server()
There is a problem with the instrumentation in tests. This fix was provided by Manu so we would not get errors when running the unit tests.

2023-03-22 09:51 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
> +    accessLogValue = (server as TomcatServer).accessLogValue
yes, for the same reason as previous.

2023-03-22 09:52 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/HttpHeadersInstrumentation.java
> +  public static class $InstrumenterAdvice {
I didn't notice this. Copy/paste error. Fixing...

2023-03-22 09:53 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/HttpHeadersInstrumentation.java
> +          module.onUnexpectedException("afterGetParameter threw", e);
Same here, `afterGetParameter` does not seem appropriate here.

2023-03-22 10:49 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/HttpHeadersInstrumentation.java
> +          module.onUnexpectedException("afterGetParameter threw", e);
done

2023-03-22 11:49 UTC, smola approved these changes

2023-03-23 09:08 UTC, merged