Jackson 1 instrumentation
DataDog/dd-trace-java pull request #4783
Opened 2023-02-23 07:21 UTC by DDJavierSantos

# What Does This Do

Instrument the older versions of the jackson library.

# Motivation
org.codehaus.jackson is used by Jersey 2 to deserialize json objects. We need to instrument the parser calls so we can achieve propagation in IAST.

# Additional Notes
This PR includes and depends on https://github.com/DataDog/dd-trace-java/pull/4670. Once the dependency is merged, this one will be rebased and the number of files will be smaller.

2023-02-24 09:50 UTC, smola requested changes

2023-02-24 09:50 UTC, smola commented on dd-java-agent/instrumentation/glassfish/build.gradle
> +  testImplementation group: 'jakarta.ws.rs', name: 'jakarta.ws.rs-api', version: '3.0.0'
I don't think this is related to this PR?

2023-02-24 09:50 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderAdvice.java
> +        System.out.println("Module is null");
No stdout printing.

2023-02-24 09:50 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderInstrumentation.java
> +public class AbstractStringReaderInstrumentation extends Instrumenter.Tracing
```suggestion
public class AbstractStringReaderInstrumentation extends Instrumenter.Iast
```

2023-03-23 16:52 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/glassfish/build.gradle
> +  testImplementation group: 'jakarta.ws.rs', name: 'jakarta.ws.rs-api', version: '3.0.0'
removed

2023-03-23 16:53 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderInstrumentation.java
> +public class AbstractStringReaderInstrumentation extends Instrumenter.Tracing
fixed

2023-03-23 16:54 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderAdvice.java
> +        System.out.println("Module is null");
fixed

2023-03-24 10:58 UTC, smola requested changes

2023-03-24 10:58 UTC, smola commented on dd-java-agent/instrumentation/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/JsonFactoryCallSite.java
> +        module.onUnexpectedException("afterCreate threw", e);
```suggestion
        module.onUnexpectedException("JsonFactoryCallSite.afterCreate threw", e);
```

2023-03-24 10:58 UTC, smola commented on dd-java-agent/instrumentation/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/JsonFactoryCallSite.java
> +        module.onUnexpectedException("afterCreate threw", e);
```suggestion
        module.onUnexpectedException("JsonFactoryCallSite.afterCreate threw", e);
```

2023-03-24 10:58 UTC, smola commented on dd-java-agent/instrumentation/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/JsonParserInstrumentation.java
> +    super("jsonParser");
```suggestion
    super("jackson", "jackson-1");
```

2023-03-29 09:45 UTC, smola requested changes

2023-03-29 09:45 UTC, smola commented on dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
> +0 org.codehaus.jackson.*
Given that we moved to target instrumentation, we can probably remove this?

2023-03-29 09:45 UTC, smola commented on dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/InputStreamInstrumentation.java
> +        isConstructor().and(takesArgument(0, InputStream.class)),
Do we need to instrument private constructors here?

2023-03-29 09:45 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/ReaderInterceptorExecutor.java
> +        System.out.println("Module is null");
Please, no println. You can remove the `else` altogether.

2023-03-29 13:03 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
> +0 org.codehaus.jackson.*
Done

2023-03-29 16:14 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/InputStreamInstrumentation.java
> +        isConstructor().and(takesArgument(0, InputStream.class)),
We need to instrument some protected ones

2023-04-03 07:59 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
> +  public void onGetInputStream(@Nullable InputStream inputStream) {
```
public static ServletInputStream afterGetInputStream(
      @CallSite.This final ServletRequest self,
      @CallSite.Return final ServletInputStream inputStream) {
    final PropagationModule module = InstrumentationBridge.PROPAGATION;
    if (module != null) {
      try {
        module.taint(SourceTypes.REQUEST_BODY, inputStream);
      } catch (final Throwable e) {
        module.onUnexpectedException("afterGetInputStream threw", e);
      }
    }
    return inputStream;
  }
```

might be better as it takes care of the `Taintable` interface

2023-04-18 16:56 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
> +  public void onGetInputStream(@Nullable InputStream inputStream) {
applied

2023-04-19 13:13 UTC, smola requested changes

2023-04-19 13:13 UTC, smola commented on dd-java-agent/instrumentation/jackson-core/jackson-core-1/build.gradle
> +  testRuntimeOnly(project(':dd-java-agent:instrumentation:iast-instrumenter'))
Dependency probably not needed if there's no call site in the package.

2023-04-19 13:13 UTC, smola commented on dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/Json1ParserInstrumentation.java
> +    @Advice.OnMethodExit
Same here.

2023-04-19 13:13 UTC, smola commented on dd-java-agent/instrumentation/jackson-core/src/test/java/foo/bar/Json2FactoryTestSuite.java
> +  public Json2FactoryTestSuite() {
As above, not needed without callsites.

2023-04-19 13:13 UTC, smola commented on dd-java-agent/instrumentation/jackson-core/src/test/java/foo/bar/Json2ParserTestSuite.java
> +public class Json2ParserTestSuite {
Same here.

2023-04-19 13:13 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/ReaderInterceptorExecutor.java
> +    super("jersey ReaderInterceptorExecutor");
Please, use a name more in line with the other instrumenters here.

2023-04-19 13:13 UTC, smola commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/ReaderInterceptorExecutor.java
> +    @Advice.OnMethodExit
Let's use suppress.

2023-04-20 14:58 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/jackson-core-1/build.gradle
> +  testRuntimeOnly(project(':dd-java-agent:instrumentation:iast-instrumenter'))
changed

2023-04-20 14:58 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/Json1FactoryInstrumentation.java
> +    @Advice.OnMethodExit
applied

2023-04-20 14:58 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/Json1ParserInstrumentation.java
> +    return declaresMethod(namedOneOf("getCurrentName", "getText", "nextTextValue"))
applied

2023-04-20 14:58 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/test/groovy/Json1FactoryInstrumentationTest.groovy
> +    1 * propagationModule.taintIfInputIsTainted(_ as JsonParser, content)
applied

2023-04-20 14:58 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/src/test/groovy/Json2FactoryInstrumentationTest.groovy
> -@CompileDynamic
reinstated the annotation

2023-04-20 14:59 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/src/test/java/foo/bar/Json2ParserTestSuite.java
> +public class Json2ParserTestSuite {
removed

2023-04-20 14:59 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/ReaderInterceptorExecutor.java
> +    @Advice.OnMethodExit
applied

2023-04-20 14:59 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/test/groovy/Json1FactoryInstrumentationTest.groovy
> +    1 * propagationModule.taintIfInputIsTainted(_ as JsonParser, is)
applied

2023-04-20 15:00 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/test/java/foo/bar/codehaus/Json1FactoryTestSuite.java
> +  public Json1FactoryTestSuite() {
removed

2023-04-20 15:00 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/Json2FactoryInstrumentation.java
> +    @Advice.OnMethodExit
applied

2023-04-20 15:00 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/src/test/groovy/Json2FactoryInstrumentationTest.groovy
> +  def 'test createParser(String)'() {
done

2023-04-20 15:01 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/Json1ParserInstrumentation.java
> +    @Advice.OnMethodExit
applied

2023-04-24 09:20 UTC, smola reviewed
Looks good to me. Just one comment about iast-instrumenter dependency.

2023-04-24 09:20 UTC, smola commented on dd-java-agent/instrumentation/jackson-core/build.gradle
> -apply plugin: 'call-site-instrumentation'
Below:

```
testRuntimeOnly(project(':dd-java-agent:instrumentation:iast-instrumenter'))
```

I think that shouldn't be needed anymore?

2023-04-24 12:14 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jackson-core/build.gradle
> -apply plugin: 'call-site-instrumentation'
removed

2023-04-24 15:39 UTC, smola approved these changes

2023-04-25 09:23 UTC, merged