Add missing URLAsResourceNameRule functionality to TagInterceptor
DataDog/dd-trace-java pull request #4798
Opened 2023-02-25 17:20 UTC by devinsba

# What Does This Do

# Motivation

# Additional Notes

2023-03-02 14:28 UTC, devinsba commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/HttpResourceDecorator.java
> -  private static final DDCache<Pair<CharSequence, CharSequence>, CharSequence>
@ygree Can you check this? I had to move the code you just added

2023-03-03 17:02 UTC, ygree commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +              HttpResourceNames.compute(value.toString(), normalized.getLeft()),
I'd suggest to move calls to `HttpResourceNames` should be inside `HttpPathNormalizers` (or maybe another abstraction), since they are always used together? Or maybe even pass a span to set the resource name. This way, it will combine three calls normalization, cache and setting the resource name. When all combined it will allow to reduce allocations that are needed now to return both the result and priority. It will also move normalization + caching + resource setting in one place.

2023-03-03 17:05 UTC, ygree commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +            && ruleFlags.isEnabled(STATUS_404)
Why do we need two rules STATUS_404 & STATUS_404_DECORATOR if it only makes sense when both are enabled. Wouldn't enough to have just one rule for that?

2023-03-03 17:09 UTC, ygree commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +        span.setResourceName(NOT_FOUND_RESOURCE_NAME, ResourceNamePriorities.HTTP_404);
Wouldn't it replace the routing path if the existing endpoint return 404 explicitly? Or this case will be handled by the priority?

2023-03-03 17:11 UTC, ygree commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/HttpResourceDecorator.java
> -  private static final DDCache<Pair<CharSequence, CharSequence>, CharSequence>
Thanks for the heads up, @devinsba! Moving out this logic makes sense to me. So, now we will only have one cache for both client and server resources. Probably that's fine.

2023-03-03 17:13 UTC, ygree requested changes
I'd suggest to also move out cache logic and probably resource setting logic into one abstraction to avoid extra allocations and remove logic duplication since normalization + caching + resource setting are always used together.

2023-03-03 17:15 UTC, ygree commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/HttpResourceDecorator.java
> -  private static final DDCache<Pair<CharSequence, CharSequence>, CharSequence>
> # What Does This Do
> # Motivation
> # Additional Notes

Would be nice to have a few sentences about this change motivation for easier navigation.

2023-03-03 17:15 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +            && ruleFlags.isEnabled(STATUS_404)
This is how the rule was implemented before. So I brought back all the settings so we don't run into any more issues with customers updating from a couple years ago

https://github.com/DataDog/dd-trace-java/blob/7cf97e4f3c9ba935e51398ad61e15a4e4891ed1d/dd-trace-core/src/main/java/datadog/trace/core/processor/rule/URLAsResourceNameRule.java#L27

2023-03-03 17:17 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +        span.setResourceName(NOT_FOUND_RESOURCE_NAME, ResourceNamePriorities.HTTP_404);
The route priority is higher, so it would not change

2023-03-06 15:00 UTC, devinsba commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/HttpResourceDecorator.java
> -  private static final DDCache<Pair<CharSequence, CharSequence>, CharSequence>
To address your first comment, there are still 2 caches. I just moved them both to the same place

2023-03-08 16:49 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +              HttpResourceNames.compute(value.toString(), normalized.getLeft()),
I've moved everything into `HttpResourceNames` except for the code needed by `TagInterceptor` since it doesn't have access to internal-api

2023-03-08 20:34 UTC, ygree commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +      if (HTTP_METHOD.equals(tag)) {
Could these two calls `computeForServer` and `setResourceName` be replaced with `setForServer`. It would open the opportunity to avoid a Pair allocation altogether.

2023-03-08 20:37 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +      if (HTTP_METHOD.equals(tag)) {
`internal-api` doesn't have access to `DDSpanContext` and there isn't a way to get back to `AgentSpan` from `DDSpanContext`

2023-03-08 20:49 UTC, ygree commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +      if (HTTP_METHOD.equals(tag)) {
I see. Thanks for clarification.

2023-03-08 20:49 UTC, ygree approved these changes
LGTM

2023-03-09 13:06 UTC, merged