Add USM instrumentation
DataDog/dd-trace-java pull request #4813
Opened 2023-02-28 14:45 UTC by Yumasi

# What Does This Do

This PR adds a new instrumentation, `sun-sslsocketimpl`, that captures HTTPS traffic in Java applications that use `SSLSocketImpl` under the hood, and sends it to `system-probe` via a custom `ioctl`. This part of USM's HTTPS monitoring support.

Few things to note:
- This is meant to be attached to Java process by `system-probe` (which uses `jattach` under the hood), which requires a different way to get the `javaagent` args, hence the addition to `agentmain`.
- The instrumentation does not produce traces, but instead does an `ioctl` using `jna`. The dependency to `jna` is the reason `UsmMessage` and `UsmExtractor` implementations are in separate packages.
- Due to it only making an `ioctl` call as a side-effect, the included instrumentation test focuses on the "instrumentation part" i.e the advices, to make sure it does the expected calls to the implementation that makes the actual `ioctl` call.
- There is an included string `split` function included in `internal-api` (meant to be used for argument parsing but did not due to not being able to depend on `internal-api` in `bootstrap`). I left here in case you want it, but it can be removed or made into a separate PR if needed.

# Motivation

# Additional Notes

2023-03-01 12:36 UTC, amarziali commented on dd-java-agent/instrumentation/sun-sslsocketimpl/src/main/java/datadog/trace/instrumentation/sslsocketimpl/SslSocketImplInstrumentation.java
> +    return "sun.security.ssl.SSLSocketImpl";
I do not know if you're only focusing on the sun reference implementation. If you want to have a broader range of ssl socket (some libraries may use its own instead of the sun reference impl) you may intercept type hierarchy of  `javax.net.ssl.SSLSocket`. The method close is anyway available since defined on the class Socket

2023-03-01 12:38 UTC, amarziali commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
> +import java.util.Vector;
Is there any particular need to use Vector (which is reentrant) instead of a classic ArrayList?

2023-03-01 12:41 UTC, amarziali commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
> +  public static Vector<String> strSplit(String str, char sep) {
String has already a  method called `split` who can do a similar job. Can it be used instead rewriting such logic?

2023-03-02 07:48 UTC, Yumasi commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
> +  public static Vector<String> strSplit(String str, char sep) {
Not here sadly. Usage of `split` is forbidden in bootstrap because it uses regular expressions under the hood, and that's too costly.

2023-03-02 08:20 UTC, amarziali commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
> +  public static Vector<String> strSplit(String str, char sep) {
oh thanks I learn something

2023-03-02 08:30 UTC, Yumasi commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
> +import java.util.Vector;
No, fixed it.

2023-03-02 09:25 UTC, mcculls commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/UsmExtractorImpl.java
> +package datadog.trace.agent.tooling;
could you move the USM specific classes to a `usm` sub-package? ie. `datadog.trace.agent.tooling.usm`

2023-03-02 09:30 UTC, mcculls commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
> +      Vector<String> args = strSplit(agentArgs, ' ');
IMHO after looking at this code it would be better to have a `parseAsSystemProperties` method which accepts a string - that method would walk over the string and call `System.setProperty` as it found key/value pairs, which would avoid the need to create a temporary collection.

2023-03-02 09:32 UTC, mcculls commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
> +      // isolated CL
could you remove unrelated formatting changes?

2023-03-02 09:36 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/util/Strings.java
> +  public static String[] split(String str, char sep) {
Can you remove this (now unused) method - on reflection we shouldn't encourage use of `split` in general because it can create a lot of intermediate objects, which this method also does. (A better approach is to walk over the string and perform whatever action you want on substrings as you parse them.)

2023-03-02 15:55 UTC, Yumasi commented on dd-java-agent/instrumentation/sun-sslsocketimpl/src/main/java/datadog/trace/instrumentation/sslsocketimpl/SslSocketImplInstrumentation.java
> +    return "sun.security.ssl.SSLSocketImpl";
We haven't found a way to get the plain buffers from the interface for the read and write methods. If it is possible in a way we haven't thought of that would be great though, as we want to cover as many implementations as possible. Do you think that would be possible via `javax.net.ssl.SSLSocket`?
Otherwise, instrumenting `javax.net.ssl.SSLSocket` just for the `close` method won't make much of a difference.

2023-03-02 17:17 UTC, Yumasi commented on dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
> +      Vector<String> args = strSplit(agentArgs, ' ');
Good idea, I changed this in [a6bfba2](https://github.com/DataDog/dd-trace-java/pull/4813/commits/a6bfba277fbd2ac14c6e36f60818593854f1b5bd), WDYT?

2023-03-13 08:55 UTC, Yumasi commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/UsmExtractorImpl.java
> +package datadog.trace.agent.tooling;
Done in d238376aedb176f42032fcca72a3e92e5cc5ab21

2023-03-27 09:07 UTC, val06 requested changes
added my comments

2023-03-27 09:07 UTC, val06 commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/usm/UsmExtractorImpl.java
> +// TODO: maybe move to a separate module: "agent-usm" (similar to agent-iast, agent-debugger, etc...
remove the todo comment, as it is done by introducing a separate pkg under agent-tooling :)

2023-03-27 09:07 UTC, val06 commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/usm/UsmMessageImpl.java
> +      byte[] dstIPBuffer = connection.getDstIP().getAddress();
[possible](https://datadoghq.atlassian.net/browse/USMO-299?atlOrigin=eyJpIjoiOTIyM2EyZDRhOGQyNGM5OThiZWJjNmJlYmY5NzczMDMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ) `NullPointerException`

2023-03-27 09:07 UTC, val06 commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/usm/UsmMessageImpl.java
> +              + connection.getDstIP().toString()
also here possible NullPointerException

2023-04-05 10:19 UTC, Yumasi commented on dd-java-agent/instrumentation/sun-sslsocketimpl/src/main/java/datadog/trace/instrumentation/sslsocketimpl/SslSocketImplInstrumentation.java
> +    return "sun.security.ssl.SSLSocketImpl";
Fixed in latest version

2023-04-05 10:28 UTC, mcculls commented on dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
> +    UsmExtractorImpl.registerAsSupplier();
suggestion: only do this if `cfg.isUsmEnabled()` is `true` to avoid loading classes that won't be used by default

2023-04-05 10:32 UTC, mcculls commented on internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy
> +  def "test split"() {
This looks like a stale test that can be removed?

2023-04-05 10:36 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/UsmConnection.java
> +package datadog.trace.bootstrap.instrumentation.api;
usually we put bootstrap related instrumentation types under `dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation` - is there a reason this has to be in `internal-api`? (you'll be able to see types from `agent-bootstrap` in your advice because they get added to the bootstrap class-path at runtime)

2023-04-05 10:39 UTC, mcculls commented on dd-java-agent/instrumentation/sslsocket/src/main/java/datadog/trace/instrumentation/sslsocket/SslSocketStreamsInstrumentation.java
> +    super("sslsocket-streams", "sslsocket-streams", "sslsocket-streams");
these are all the same string, so can just be `super("sslsocket-streams")`

2023-04-05 10:40 UTC, mcculls commented on dd-java-agent/instrumentation/sslsocket/src/main/java/datadog/trace/instrumentation/sslsocket/SslSocketInstrumentation.java
> +    super("sslsocket", "sslsocket", "sslsocket");
same here, can simplify this to `super("sslsocket")`

2023-04-05 10:40 UTC, mcculls commented on dd-java-agent/instrumentation/sslsocket/src/main/java/datadog/trace/instrumentation/sslsocket/SslSocketStreamsInstrumentation.java
> +  private static final Logger log = LoggerFactory.getLogger(SslSocketStreamsInstrumentation.class);
remove unused logger

2023-04-05 10:45 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/UsmConnection.java
> +package datadog.trace.bootstrap.instrumentation.api;
Also this should not be at the `datadog.trace.bootstrap.instrumentation.api` level which is for generic internal API, but ideally in a USM specific sub-package like `datadog.trace.bootstrap.instrumentation.usm`

2023-04-05 10:47 UTC, mcculls requested changes
Needs a bit more cleanup before this can be merged - see comments about using USM specific package for new types and preferring `agent-bootstrap` over `internal-api` for bootstrap related instrumentation types

2023-04-05 10:49 UTC, mcculls commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +      // TODO: @Val
remove empty TODO (or add a bit more detail to explain why this is a TODO)

2023-04-05 11:04 UTC, Yumasi commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/UsmConnection.java
> +package datadog.trace.bootstrap.instrumentation.api;
No particular reason, no. I moved them to a `usm` package in the path you provided.

2023-04-05 11:07 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
> +  // to initialize
there's a few places like this where the formatting of comments which aren't related to the PR has changed - could you revert these whitespace-only comment changes, thanks

2023-04-05 11:22 UTC, mcculls approved these changes
Once the unrelated formatting changes have been cleaned up this should be OK to merge

2023-04-05 16:18 UTC, merged

2023-04-09 15:01 UTC, nikita-tkachenko-datadog commented
This breaks logic introduced in https://github.com/DataDog/dd-trace-java/pull/4888