Andrew.munn/uri opaque
DataDog/dd-trace-java pull request #4820
Opened 2023-03-01 07:06 UTC by am312

if telemetry.convert-opaque-uri.enabled is set, opaque URLs will be converted to hierarchal by prepending the missing '/'.  This work-around addresses malformed Windows URLs which can cause errors like:

`datadog.telemetry.dependency.DependencyResolver - Failed to determine dependency for uri file:C:/lib.jar. java.lang.IllegalArgumentException: URI is not hierarchical
`

2023-03-01 08:55 UTC, mcculls commented on dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
> +      "telemetry.convert-opaque-uri.enabled";
I'm not sure this warrants its own feature-flag, given that we know the opaque case leads to an exception.

BTW, have you considered an alternative fix to the `DependencyResolver` - when it tries to turn the URI into a file it could fall back to using the path for opaque URLs?

2023-03-01 08:58 UTC, mcculls commented on telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
> +                "Opaque URI '{}' changed to hierarchical URI '{}'", oldUri, uri.toASCIIString());
We know opaque code locations exist, so I'm not sure a warning is useful here - if the user doesn't have control over the code location URI then this warning wouldn't be very helpful and could lead to false-alerts

2023-03-01 08:59 UTC, mcculls commented on telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
> +                "Opaque URI '{}' changed to hierarchical URI '{}'", oldUri, uri.toASCIIString());
(IMHO a lot of the warnings in the telemetry service/resolver should really be debug)

2023-03-01 15:47 UTC, am312 commented on telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
> +                "Opaque URI '{}' changed to hierarchical URI '{}'", oldUri, uri.toASCIIString());
Good idea, will change to debug.

2023-03-01 15:49 UTC, am312 commented on dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
> +      "telemetry.convert-opaque-uri.enabled";
My concern with going without a flag was that if the path was relative and everything was working fine, prepending an unneeded "/" to make URIs hierarchical might break something for the user.   The anticipated usage is just selectively when there is a problem and the behavior should not roll out as a new default for users where everything is working ok right now.

In DependencyResolver I could just catch any `IllegalArgumentException` containing `URI is not hierarchical` in its message and then convert+retry the `new File` op again using the updated URI.  If that also does not work then rethrow the original exception.  Sound ok using that default behavior without a flag around it?

2023-03-01 16:44 UTC, am312 commented on dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
> +      "telemetry.convert-opaque-uri.enabled";
Actually I think the flag should stay because if "fixing" it for everybody causes some previously ignored opaque URL to suddenly start working it could override a dep and change the behavior in some unexpected, unanticipated way.

2023-03-01 17:18 UTC, mcculls commented on dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
> +      "telemetry.convert-opaque-uri.enabled";
I don't think that's a valid case though - not handling opaque file URLs properly and causing an exception is a bug, it's not something that we need a flag for. If an opaque file URL can be mapped to a file by using its path then I see that as improving the resolver logic. That's why I think the fix really should be in the resolver when it tries to convert the URL to a file.

2023-03-01 17:21 UTC, mcculls requested changes
Can you remove the flag and also move this fix to `DependencyResolver` - ie. when it tries to convert the URI to a file, handle opaque URIs by using the path. If that resolves to a file then we know that conversion is ok. (You can either check the URI is opaque upfront or use a try...catch with the path conversion as a fallback for any situation where the whole URI doesn't map to a file.)

2023-03-02 23:14 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
> +                "Opaque URI '{}' changed to hierarchical URI '{}'", oldUri, uri.toASCIIString());
I like this approach, but may be we can just get path from uri instead of manipulating with the string directly in the resolver?
Something like this:
```
static List<Dependency> extractDependenciesFromURI(URI uri) {
    ...
    File f;
    if ("file".equals(uri.getScheme())) {
        if (uri.isOpaque()) {
            f = new File(uri.getPath());
        } else {
            f = new File(uri);
        }
    }
    dependencies = extractDependenciesFromJar(f);
    ...
}
```

2023-03-02 23:25 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
> +                "Opaque URI '{}' changed to hierarchical URI '{}'", oldUri, uri.toASCIIString());
BTW, according to [rfc8089](https://datatracker.ietf.org/doc/html/rfc8089#appendix-F) the windows local file representation like `file:c:/path/to/file` is valid. So that looks like a bug in the `File`, which brings me to idea that we should not touch `uri`.

2023-03-02 23:27 UTC, ValentinZakharov commented
I like this approach, but may be we can just get path from uri instead of manipulating with the string directly in the resolver?
Something like this:
```
static List<Dependency> extractDependenciesFromURI(URI uri) {
    ...
    File f;
    if ("file".equals(uri.getScheme())) {
        if (uri.isOpaque()) {
            f = new File(uri.getPath());
        } else {
            f = new File(uri);
        }
    }
    dependencies = extractDependenciesFromJar(f);
    ...
}
```

Also, according to [rfc8089](https://datatracker.ietf.org/doc/html/rfc8089#appendix-F) the windows local file representation like file:c:/path/to/file is valid. So that looks like a bug in the File, which brings me to idea that we should not touch uri.

2023-03-03 05:36 UTC, am312 commented
if `uri.isOpaque() == true` then `uri.getPath() == null`

but we could do this which I agree is better than manipulating the string: 

```
if (uri.isOpaque()) {
    f = new File(uri.getSchemeSpecificPart());
}...
```

2023-03-06 14:21 UTC, mcculls approved these changes

2023-03-06 17:47 UTC, am312 commented
The updated version works but it's tricky to add really meaningful tests for Windows files when we don't build on Windows.

2023-03-06 17:48 UTC, merged