Implement DBM-APM feature for JDBC instrumentation
DataDog/dd-trace-java pull request #4847
Opened 2023-03-04 02:08 UTC by jmeunier28

# What Does This Do

# Motivation

# Additional Notes

2023-03-04 03:15 UTC, alexandre-normand commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +          span.setTag(DBM_TRACE_INJECTED, true);
To match other tracers and [the spec](https://docs.google.com/document/d/1hlp3CuIRE-os2zYgc0wYOS8kPtCKqlrGL7aepbHHDaU/edit?pli=1#heading=h.v3ga4zojhwao), this tagging should move to the block below (when we're doing _full_ injection). That said, in hindsight, I wish we had just injected a `_dd.dbm_propagation_mode:<mode>` instead because it would have helped debugging in some cases.

2023-03-06 13:37 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +          span.setTag(DBM_TRACE_INJECTED, true);
ah duh, thanks

2023-03-06 14:51 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +          span.setTag(DBM_TRACE_INJECTED, true);
> That said, in hindsight, I wish we had just injected a _dd.dbm_propagation_mode:<mode> instead because it would have helped debugging in some cases.

Do you want me to set an additional tag on the span so we have the mode?

2023-03-06 17:35 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/jmh/java/datadog.trace.instrumentation.jdbc/SQLCommenterBenchmark.java
> +    commenter.augmentSQLStatement(SQL_STMT, TAGS);
```
Benchmark                                Mode  Cnt     Score    Error  Units
SQLCommenterBenchmark.encodeComment      avgt   25  5124.687 ± 43.768  ns/op
SQLCommenterBenchmark.encodeTraceParent  avgt   25  1123.568 ± 37.793  ns/op
```

I think the comment encoding can be improved. I still have some intermediate `String` creation that I should get rid of

2023-03-07 15:56 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +  public static String toComment(final SortedMap<String, Object> tags) {
```
Benchmark                                Mode  Cnt     Score    Error  Units
SQLCommenterBenchmark.encodeComment      avgt   25   974.606 ± 46.508  ns/op
SQLCommenterBenchmark.encodeTraceParent  avgt   25  1123.753 ± 56.404  ns/op
```

2023-03-09 19:12 UTC, dougqh commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBQueryInfo.java
> +      return CACHED_PREPARED_STATEMENTS.computeIfAbsent(
This introducing a capturing lambda which we want to avoid for performance reasons.  If "k" is the sql statement, then it would be better to use "k".  (Although, probably with a different name.)

2023-03-09 19:13 UTC, dougqh commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBQueryInfo.java
> +    this.sql = SQLNormalizer.normalize(sql, stripSQLComment);
Does this mean we start with the comment and then strip it out again?  My preference would be to only provide the original sql to DBQueryInfo if at all possible.

2023-03-09 19:22 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractConnectionInstrumentation.java
> +      if (DECORATE.injectSQLComment()) {
I'm on the fence on whether we need to optimize this.  I worry about having a lot of allocation on a potential hot path, but maybe preparation is infrequent enough that this is okay.

We can add a cache later if need be, but hopefully, we won't have to do so.  Often prepared statements are put into a cache at higher level.

2023-03-09 19:28 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
> +    dbService = dbInfo.getType();
Is that the service that you want here?  That's really a peer.service and not the service of the Java process.
I suspect that you might really want the service of the local root span instead.

2023-03-09 19:29 UTC, jmeunier28 commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBQueryInfo.java
> +    this.sql = SQLNormalizer.normalize(sql, stripSQLComment);
Yeah that makes sense, the reason why I have this here is because for prepared statements I can't see any way to mutate the sql on connection (bc now that `PreparedStatement` object's sql text will contain the comments), but avoid adding the comments to the `DBQueryInfo` when that statement is executed, so I strip the comments on normalization.

We don't have to do that for  regular `Statement`s though, we can just keep a copy of the sql text in memory & pass that to the `DBQueryInfo` object we create

2023-03-09 19:31 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
> +  public DBInfo parseDBInfoFromConnection(final Connection connection) {
Just breaking out a helper method it appears...  Fine by me.
Does it need to be public?  Should it be static?

2023-03-09 19:31 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractConnectionInstrumentation.java
> +        DBQueryInfo info = DBQueryInfo.ofPreparedStatement(sql, DECORATE.injectSQLComment());
ah okay, yeah that might work

2023-03-09 19:32 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommentInjectorAdaptor.java
> +public class SQLCommentInjectorAdaptor implements AgentPropagation.Setter<SQLCommenter.Builder> {
At least conceptually, it makes sense to me that SQLCommentInjector is connected to propagation.  Although, we should double check with @bantonsson who was working on injection and propagation recently.

2023-03-09 19:34 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +public class SQLCommenter {
As mentioned elsewhere, I'm debating whether or not we should optimize this some more.

Typically, I'm not a fan of builders because they result in needless allocation that impacts response time latency.
I'd probably prefer this to just be a set of static utility functions.

2023-03-09 19:35 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +  private static final DDCache<SortedMap<String, Object>, String> CACHED_SQL_COMMENTS =
Ah, I see there's a cache here -- that I was looking for above.

2023-03-09 19:35 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +  private static final DDCache<SortedMap<String, Object>, String> CACHED_SQL_COMMENTS =
Why SortedMap?  That seems a bit unnecessary.

2023-03-09 19:36 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    StringBuilder sb = new StringBuilder();
It would be good to provide a better default length for this StringBuilder.  We should be able to make a reasonable approximation based on the number of tag entries.

2023-03-09 19:40 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    return new String(buffer.array(), 0, buffer.position(), StandardCharsets.UTF_8);
Why are we converting back and forth from UTF8 here?  Why not just stay in UTF16?

2023-03-09 19:43 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    SortedMap<String, Object> sortedMap = new TreeMap<>();
Why SortedMap / TreeMap?
Or more pointedly, why are we constructing a map?
Couldn't we just build the comment eagerly a wrapper around a StringBuilder?

2023-03-09 19:47 UTC, dougqh requested changes
Overall, I think looks pretty good.

I'm concerned about the need to strip comments.  That for me is a must fix.

I'm undecided about the various performance related concerns.
I somewhat willing to ignore them as long as this feature remains off by default.
However if this ever turned on by default, we'll have to revisit it.

2023-03-09 19:48 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    return new String(buffer.array(), 0, buffer.position(), StandardCharsets.UTF_8);
oh that was an oversight by me :face-palm:. sorry, i changed this code a bunch of times

2023-03-09 19:51 UTC, jmeunier28 commented
> I'm concerned about the need to strip comments. That for me is a must fix.

yes this makes sense to me, ill try to implement your suggestion for this. Stripping comments in normalization certainly isn't ideal.

> I'm undecided about the various performance related concerns.

definitely willing to spend more time on performance related concerns, the things you mentioned should be easy fixes.

2023-03-10 14:58 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    SortedMap<String, Object> sortedMap = new TreeMap<>();
yes for sure, i can do that

2023-03-10 16:42 UTC, alexandre-normand commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
> +    dbService = dbInfo.getType();
We include both although, admittedly, we're definitely getting more value from the parent service (the DD_SERVICE and service name of the Java process). The db service usages is likely going to fade away as more work to migrate towards `peer.service` is implemented in all parts of the stack/product but the reality right now is that the front-end still shows database services and we've got front-end integration that shows database hosts for those (and that relies on this db service to be propagated).

2023-03-15 16:48 UTC, jmeunier28 commented
Hm I am not sure what could be causing the muzzle check to fail here:
```
Caused by: java.lang.RuntimeException: Instrumentation failed Muzzle validation
	at datadog.trace.agent.tooling.muzzle.MuzzleVersionScanPlugin.assertInstrumentationMuzzled(MuzzleVersionScanPlugin.java:68)
	... 30 more
```

2023-03-16 12:35 UTC, jmeunier28 commented
hm I the last test that is failing is getting a SockeckTimeout, but it's a test unrelated to my change

```shell
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:239)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
	....
	...
	at datadog.trace.agent.test.base.HttpServerTest.test success with #count requests(HttpServerTest.groovy:455)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 26 more
```

2023-03-21 11:18 UTC, bantonsson reviewed
Mostly performance comments. The only thing that I find confusing is the `SQL_COMMENT` propagation style and what the code is trying to accomplish with it. I think there should be some cleaner way implement it.

2023-03-21 11:18 UTC, bantonsson commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/SqlCommentInjector.java
> +      if (context.lockSamplingPriority()) {
This is a very roundabout way to get hold of the sampling priority. The `lockSamplingPriority` method shouldn't be used and the comment says `this is now effectively a no-op - there is no locking`.
You should just read the sampling priority where you need it, like this.
```
int samplingPriority = span.samplingPriority();
if (samplingPriority != PrioritySampling.UNSET) {
  // do whatever needs to be done
}
```

2023-03-21 11:18 UTC, bantonsson commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    buffer.put("/*".getBytes(StandardCharsets.UTF_8));
These constant short strings could be constant `Utf8ByteStrings` so that the same utf8 bytes can be reused. This will allocate new arrays of size 2 for every call here.

2023-03-21 11:18 UTC, bantonsson commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +        sb.append(URLEncoder.encode(key, UTF8));
Since the keys are controlled constants, then they could already be URL encoded once during initialization.

2023-03-21 11:18 UTC, bantonsson commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    final String comment =
Since the `comment` is never used as a string, but the bytes are consumed directly, then it would be more performant to build up the bytes directly instead.

2023-03-21 14:35 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +  protected static String encodeTraceParent(long traceID, long spanID, long sampled) {
ah good to know 👍

2023-03-21 14:36 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +            propagate().inject(span, carrier, SETTER, TracePropagationStyle.SQL_COMMENT);
I was just trying to force a sampling decision, because the sampling priority was always null before

2023-03-21 14:37 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +        sb.append(URLEncoder.encode(key, UTF8));
ah yeah, good call 👍

2023-03-21 19:01 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +            propagate().inject(span, carrier, SETTER, TracePropagationStyle.SQL_COMMENT);
ah I see i can just use the `TRACE_PARENT` propagator instead, that wasn't there when I originally started working on this so that's why I created a new injector so i could set the sampling priority properly

2023-03-22 16:48 UTC, jmeunier28 commented
OK @bantonsson I think I covered everything here 10f25f95e177e6569b1dbbf66acba49520c70286

I did have one question about setting the service [right here ](https://github.com/DataDog/dd-trace-java/pull/4847/files#diff-2d9c6d46bfc5e23443a77d1e4f7a36426c78021d3ba1f5c4d0dc4805b4400cc9R81-R89), which I was not sure about & so left a `TODO`. 

I did confirm that the changes work, by checking that we are seeing samples with the services set properly in my test app here:
![Screen Shot 2023-03-22 at 12 47 29 PM](https://user-images.githubusercontent.com/14317240/226977893-d0830416-337e-403d-b1c7-477f1f570fa0.png)

Traces are being found & properly linked in our test application

![Screen Shot 2023-03-22 at 12 46 59 PM](https://user-images.githubusercontent.com/14317240/226977854-9cc1501f-a3cc-45f9-8b72-35cbea5689eb.png)

2023-03-24 09:01 UTC, bantonsson reviewed
This is coming together nicely. There is still some cleanup that needs to be done in the `SQLCommenter`.

2023-03-24 14:27 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    final byte[] sqlStmtBytes = this.sql.getBytes(StandardCharsets.UTF_8);
true, this code was shuffled around a few times. I'll re-implement it using a string input

2023-03-24 14:29 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +          SQLCommenter carrier =
yes, will fix 👍

2023-03-24 14:35 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +      sb.deleteCharAt(sb.length() - 1);
yeah i was trying to make it less complicated, since i don't know which one will be the last non-empty value ahead of time

2023-03-24 15:11 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    if (sb.length() == 0) {
> Or maybe the code should assume that it should inject a comment, and only have a boolean for the trace context part?

yes, this is what I did. Checking the mode again, seemed excessive  since we do this in the advice already

2023-03-24 15:55 UTC, bantonsson commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +          && hasMatchingSubstring(sql, i, PARENT_SERVICE)) {
This is just `sql.startsWith(PARENT_SERVICE, i)`

2023-03-24 15:55 UTC, bantonsson commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +      sb.deleteCharAt(sb.length() - 1);
You know which is the first one, and it doesn't need a comma in front of it, but all the other ones do.

2023-03-24 15:55 UTC, bantonsson commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    sb.insert(0, OPEN_COMMENT);
This is costly, and you can insert the `/*` before calling `toComment(...)` and check if length is `2` instead of `0`.

2023-03-27 09:26 UTC, bantonsson commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    first = append(sb, DATABASE_SERVICE, dbService, first);
Instead of doing this I would do:
```
int emptySize = sb.length();
append(sb, PARENT_SERVICE, parentService, false);
append(sb, DATABASE_SERVICE, dbService, sb.length() > emptySize);
...
```

2023-03-27 14:13 UTC, dougqh approved these changes

2023-03-27 15:09 UTC, merged