Telemetry API v1 updated to the latest version
DataDog/dd-trace-java pull request #4872
Opened 2023-03-08 01:23 UTC by ValentinZakharov

# What Does This Do
Implemented latest changes according to specification for Telemetry API v1

# Motivation
Requires for metrics over telemetry

# Additional Notes

2023-03-08 09:40 UTC, smola requested changes
Looks good overall, I miss test cases, and an overall description in the PR of what we updated. This is only an update for Telemetry API v1, and not really v2, correct?

2023-03-08 09:40 UTC, smola commented on telemetry/src/main/java/datadog/telemetry/TelemetryService.java
> +import datadog.telemetry.api.*;
See https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#intellij-idea to avoid this.

2023-03-08 09:40 UTC, smola commented on telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
> +  private static final int MAX_ELEMENTS_PER_REQUEST = 100;
Is this exact limit from the spec, or an arbitrary one on our side?

2023-03-08 09:52 UTC, manuel-alvarez-alvarez commented on telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
> +              .collect(Collectors.groupingBy(DistributionSeries::getNamespace))
I think we can group the series and provide a single `Distributions` with mixed namespaces in `DistributionSeries` I'm not sure if this was possible in V1 (the same applies to the metrics).

2023-03-08 09:52 UTC, manuel-alvarez-alvarez commented on telemetry/src/main/java/datadog/telemetry/api/Metric.java
> +  private String namespace;
Nice!, I'm not 100% sure but I think this field was not present in the spec when I did the change :disappointed_relieved:

2023-03-10 13:42 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/TelemetryService.java
> +import datadog.telemetry.api.*;
Thanks, fixed

2023-03-10 13:43 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
> +  private static final int MAX_ELEMENTS_PER_REQUEST = 100;
There is no number of entries limit in spec, the value is from our side.

2023-03-10 13:43 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
> +              .collect(Collectors.groupingBy(DistributionSeries::getNamespace))
Thanks, done

2023-03-10 13:45 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/api/Metric.java
> +  private String namespace;
It wasn't before. The spec is still evolving, we might see another small improvements in future.

2023-03-10 13:49 UTC, smola approved these changes

2023-03-13 18:38 UTC, merged