Allow using Java agent arguments to provide config properties
DataDog/dd-trace-java pull request #4888
Opened 2023-03-10 18:10 UTC by nikita-tkachenko-datadog

# What Does This Do
Adds support for using Java agent arguments to provide configuration properties for the tracer, e.g.:
```
-javaagent:$HOME/.m2/repository/com/datadoghq/dd-java-agent/1.10.0/dd-java-agent-1.10.0.jar=\
dd.service=service-name,\
dd.civisibility.enabled=true
```

# Motivation
A client has the following ways of providing configuration properties to the tracer:
* system properties
* environment variables
* property file (the location of the file has to be specified using one of the previous two ways)

In certain scenarios none of the methods above can be used: for instance, when using the tracer to instrument Gradle Daemon, it is not possible to pass system properties as Gradle [filters them](https://discuss.gradle.org/t/how-to-actually-affect-daemon-args/39053). And when using Gradle test kit to run daemon instrumentation tests, it is not possible to set environment variables, since the test kit does not provide corresponding API.

# Additional Notes
* Agent arguments have lower priority than system properties or environment variables
* Agent arguments have higher priority than property files (as a file might be reused by different traced processes) and captured environment config values (as agent args are something that the client specifies explicitly)
* Arg name and value are separated with `=`, name-value pairs are separated with `,`. For simplicity quoting is not supported
* Arg names should be the same as system property names (i.e. lower-case, separated with `.`, `dd.` prefix)

2023-03-13 09:04 UTC, mcculls commented
Had a thought the other day - another approach would be to parse the `agentArgs` string and push the key value pairs into `System.properties`. That would avoid having to add a new config source, which would reduce the impact on the rest of the codebase, and since `System.properties` are specific to the process it wouldn't leak out into the environment.

2023-03-13 10:00 UTC, nikita-tkachenko-datadog commented
> another approach would be to parse the `agentArgs` string and push the key value pairs into `System.properties`

Agree, that sounds like a less intrusive approach. Changed the code accordingly.

2023-03-13 10:55 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/bootstrap/config/provider/AgentArgsParser.java
> +  public static Map<String, String> parseAgentArgs(String agentArgs) {
Across the tracer in different places we are doing the same parsing of string to key-value list and each time it's almost the same implementation. Might be nice to implement later a common one somewhere in `datadog.trace.util`

2023-03-13 18:56 UTC, nikita-tkachenko-datadog commented on internal-api/src/main/java/datadog/trace/bootstrap/config/provider/AgentArgsParser.java
> +  public static Map<String, String> parseAgentArgs(String agentArgs) {
@ValentinZakharov, I have moved the parsing logic to `datadog.trace.util.Strings#parseCommaSeparatedKeyValueList`.
I could update the places that you're referring to to use the common method, if you point them out (provided this PR is a proper place to do so)

2023-03-13 21:09 UTC, mcculls commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +    injectAgentArgsConfig(agentArgs);
If you check `agentArgs` is non-null and non-empty here then you can avoid the reflective call when there are no agent args (which is the common case)

2023-03-13 22:28 UTC, nikita-tkachenko-datadog commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +    injectAgentArgsConfig(agentArgs);
Fixed

2023-03-14 12:07 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/util/Strings.java
> +      Scanner scanner = new Scanner(keyValueList);
I think `java.util.Scanner` is overkill for this utility - it pulls in a lot of classes and uses regex under the covers.

All we really need here is repeated use of `indexOf` to find each comma in turn to break the string into chunks.

2023-03-14 12:14 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/util/Strings.java
> +      Scanner scanner = new Scanner(keyValueList);
Also how does this relate to similar parsing logic in `ConfigConverter` ? Should we maybe make that class and its static helpers public, so that code can be re-used rather than create a similar duplicate method here?

2023-03-14 14:32 UTC, nikita-tkachenko-datadog commented on internal-api/src/main/java/datadog/trace/util/Strings.java
> +      Scanner scanner = new Scanner(keyValueList);
I missed the code in `ConfigConverter`. It surely looks more robust and optimal than the naive parser I implemented (not to mentioned code duplication).
I made the class/method public and update the args parser to use it

2023-03-16 15:41 UTC, devinsba approved these changes
Looks reasonable to me

2023-03-16 17:02 UTC, ygree commented on internal-api/src/main/java/datadog/trace/util/Strings.java
> +  public static String systemPropertyNameToEnvironmentVariableName(final String setting) {
Such a method already exist (see `toEnvVar`) also would be nice to remove duplication from existing `propertyNameToEnvironmentVariableName`

2023-03-16 17:04 UTC, ygree commented on internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/ConfigConverterTest.groovy
> +    def result = ConfigConverter.parseMap(mapString, "test", separator as char)
I think it would be better to have a separate test for a custom separator instead.

2023-03-16 17:04 UTC, ygree commented on internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
> +    loadMap(map, trimmed, settingName, ':');
Maybe introduce another loadMap that uses the `:` separator by default to avoid passing it as a literal here and in ConfigProvider?

2023-03-16 17:05 UTC, ygree requested changes
Looks good. I got a couple of suggestions.

2023-03-16 19:26 UTC, nikita-tkachenko-datadog commented on internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
> +    loadMap(map, trimmed, settingName, ':');
done

2023-03-16 19:26 UTC, nikita-tkachenko-datadog commented on internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/ConfigConverterTest.groovy
> +    def result = ConfigConverter.parseMap(mapString, "test", separator as char)
done

2023-03-16 19:27 UTC, nikita-tkachenko-datadog commented on internal-api/src/main/java/datadog/trace/util/Strings.java
> +  public static String systemPropertyNameToEnvironmentVariableName(final String setting) {
removed the new method, removed duplication from `propertyNameToEnvironmentVariableName`

2023-03-16 19:28 UTC, nikita-tkachenko-datadog commented on internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
> +public final class ConfigConverter {
Good catch, there is actually no need to change visibility

2023-03-20 15:29 UTC, ygree commented on internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/ConfigConverterTest.groovy
> +    def result = ConfigConverter.parseMap(mapString, "test", separator as char)
Thanks!

2023-03-21 10:45 UTC, merged