Adding RequestContext slot for CI Visibility
DataDog/dd-trace-java pull request #4900
Opened 2023-03-14 14:38 UTC by devinsba

# What Does This Do

# Motivation

I plan to build on top of #4894 and add the `TestContext` using this

# Additional Notes

2023-03-16 17:31 UTC, ygree commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    private Map<RequestContextSlot, Object> requestContextData;
Maybe avoid using Map and just have three variables for existing slots? It would help lower number of allocations.

2023-03-16 17:31 UTC, ygree requested changes
LGTM. Only a small suggestion.

2023-03-16 22:25 UTC, devinsba commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    private Map<RequestContextSlot, Object> requestContextData;
Done

2023-03-21 16:14 UTC, ygree approved these changes
LGTM! Thanks!

2023-03-21 23:46 UTC, merged