IAST: support webflux
DataDog/dd-trace-java pull request #4942
Opened 2023-03-22 10:08 UTC by cataphract

2023-03-24 11:29 UTC, smola requested changes

2023-03-24 11:29 UTC, smola commented on dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/TaintHttpHeadersGetFirstAdvice.java
> +    module.onHeaderName(lc);
Is this header name comming from the request or application code? Note that we should not taint strings coming from user code.

2023-03-24 11:29 UTC, smola commented on dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/TaintHttpHeadersToSingleValueMapAdvice.java
> +      module.onHeaderName(lc);
Same here. And even if it somes from the request, once you've transformed it with toLowerCase, you wouldn't be tainting the right instance anymore?

2023-03-31 10:13 UTC, cataphract commented on dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/RequestHeaderMapResolveAdvice.java
> +        module.onHeaderName(lc);
yes, the tainting of the transformed key makes no sense, I've fixed it.

re: the second point, this advice is precisely for when the user injects a full map (or multimap) of headers, so I think it makes sense to taint it all. If he was interested in only one or two headers, he'd likely inject only those specific ones into string variables.

2023-03-31 10:15 UTC, cataphract commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
> +    final TaintedObjects taintedObjects = getTaintedObjects();
The current version now checks first if the object is taintable:

```
  @Override
  public boolean isTainted(@Nullable Object obj) {
    if (obj instanceof Taintable) {
      return ((Taintable) obj).$DD$isTainted();
    }

    // ...
  }
```

This is done in https://github.com/DataDog/dd-trace-java/pull/4996/files

2023-03-31 10:17 UTC, cataphract commented on dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/TaintHttpHeadersToSingleValueMapAdvice.java
> +      module.onHeaderName(lc);
You're right. Fixed.

2023-03-31 10:17 UTC, cataphract commented on dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/TaintHttpHeadersGetFirstAdvice.java
> +    module.onHeaderName(lc);
Fixed

2023-04-03 10:14 UTC, smola commented on dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/HandleMatchAdvice.java
> +      @Advice.Argument(2) ServerWebExchange xchg, @ActiveRequestContext RequestContext reqCtx) {
Can `xchg` possibly be null? If there's the slightest chance of it, I will check it first and do early return. But I guess it would not be the case for onExit...

2023-04-03 10:14 UTC, smola approved these changes

2023-04-12 18:26 UTC, merged