[USM] USMO-259 - Support Async Frameworks for USM
DataDog/dd-trace-java pull request #4992
Opened 2023-03-29 18:24 UTC by val06

# What Does This Do

Added SSLEngine and SocketChannel instrumentations as `ForTypedHierarchy` instrumentations
   - We hook write/read/close of any class that extends the `SocketChannel` (`SocketChannelImpl` for sun module)
   - We hook wrap and unwrap of any class that extends the `SSLEngine` class (SSLEngineImpl for sun module)

# Motivation

Support asynchronous https frameworks. Mostly used by the server side, e.g: jetty, spring via Restlet, but also some asynchronous clients like `java.net.http.HttpClient` 

# Additional Notes

   - Need to refactor the USMMessage classes hierarchy, BaseUSMMessage can't contain connection anymore, since we don't have such information inside the SSLEngine instrumentation 
     - Implemented a Visitor pattern to encode each entity (connection, peer, payload) into a given **pre-allocated direct** ByteBuffer (to avoid extra allocations and it must be direct as we pass it to the ioctl)
     - Removed the UsmMessage interface and all related implementations including the MessageFactory, now the only reference to jna exists in the ExtractorImpl and can be easily substituted later by our own tiny library to drop the heavy jna dependency

2023-05-11 08:26 UTC, Yumasi requested changes
A few small comments, but otherwise LGTM ! Also, don't forget to apply spotless to fix the formatting before merging.

2023-05-11 08:26 UTC, Yumasi commented on dd-java-agent/instrumentation/sslengine/src/main/java/datadog/trace/instrumentation/sslengine/SslEngineInstrumentation.java
> +        System.out.println("[wrap] no source buffers");
Avoid using `println` for logging, use a logger instead.

2023-05-16 07:59 UTC, val06 commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/usm/Connection.java
changed to use `/* */` for function/object documentation
and using `//` for in-function comments

2023-07-03 14:16 UTC, Yumasi approved these changes

2023-07-05 13:59 UTC, dougqh commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/usm/Connection.java
> +    log.debug("encoding connection:");
debug logging should probably be guarded with isDebugEnabled.
Probably also better to take advantage of interpolation than it is use concatenation.

We also just need to be careful about network in general.  Have you done any performance testing of this instrumentation?

2023-07-05 14:01 UTC, dougqh commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/usm/MessageEncoder.java
> +  public enum MessageType {
Java enums and especially enum switches are really bloated.  It might be better to just use ints.

2023-07-05 14:04 UTC, dougqh commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/usm/UsmExtractorImpl.java
> +    log.debug("ioctl result: " + String.format("%08x", res.intValue()));
If a recall correctly, this pattern behaves differently depending on the Locale.  You probably want to specify Locale here.

2023-07-05 14:18 UTC, dougqh commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/usm/Extractor.java
> +      if (SUPPLIER == null) {
I see this is being set by outside.

This could be implemented more efficiently.  You can use double checked locking or an Atomic to make this more efficient.

2023-07-05 14:21 UTC, dougqh commented on dd-java-agent/instrumentation/sslengine/src/main/java/datadog/trace/instrumentation/sslengine/SocketChannelImplInstrumentation.java
> +      Connection connection =
How often is onMessage called?

I'm worry about creating a Connection and Peer on each call.  I'd either pass the address objects directly or find a way to reuse the Connection object.

Do you have any benchmarks that illustrate the overhead?

2023-07-05 14:23 UTC, dougqh commented on dd-java-agent/instrumentation/sslengine/src/main/java/datadog/trace/instrumentation/sslengine/SslEngineInstrumentation.java
> +        Peer peer = new Peer(thiz.getPeerHost(), thiz.getPeerPort());
Probably don't want to creating extract objects on every wrap call.

2023-07-05 14:37 UTC, val06 commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/usm/Connection.java
> +    log.debug("encoding connection:");
switched to parameterized overload of debug 
(according to [this](https://www.slf4j.org/faq.html#logging_performance) should be fast enough, as long as the parameters are simple types and don't require heavy computation

2023-07-05 14:41 UTC, val06 commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/usm/Extractor.java
> +      if (SUPPLIER == null) {
this was copied from WeakMaps [implementation](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java), and introduced when implemented the first instrumentation (sslsocket), according to @mcculls advice

2023-07-05 14:51 UTC, val06 commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/usm/UsmExtractorImpl.java
> +    log.debug("ioctl result: " + String.format("%08x", res.intValue()));
this log.debug prints the pointer in a format of 8 digits with a `0x` prefix. Why would locale impact the print of the hex digits?

2023-07-10 08:56 UTC, val06 commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/usm/UsmExtractorImpl.java
> +    log.debug("ioctl result: " + String.format("%08x", res.intValue()));
we still didn't do the performance tests, planning to do them in USM load-test cluster before dog-fooding on staging.

2023-07-10 08:57 UTC, val06 commented on dd-java-agent/instrumentation/sslengine/src/main/java/datadog/trace/instrumentation/sslengine/SocketChannelImplInstrumentation.java
> +      Connection connection =
i didn't want to make pre-mature optimizations, we will do benchmarks in our load-test cluster to determine if those needed

2024-09-20 13:53 UTC, bm1549 commented
Hi @val06 👋 
We noticed that your pull request has been inactive for a while. In order to keep the project clean and organized, we’re going to close it for now.
Feel free to reopen it at any time when you’re ready to continue working on it.

2024-09-20 13:53 UTC, closed without merging