[WIP] Spark instrumentation
DataDog/dd-trace-java pull request #4997
Opened 2023-03-30 16:02 UTC by paul-laffon-dd

# What Does This Do

# Motivation

# Additional Notes

2023-04-04 13:17 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +  String serviceName = "apache-spark";
Constants should typically be _final_.  Although, I doubt it is a good idea for us to set serviceName, so this constant is probably not needed.

2023-04-04 13:20 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +  HashMap<Integer, AgentSpan> jobSpans = new HashMap<>();
These collections should also be final - unless you need to create a new collection.
You're also going to have to cap the size of the collections to avoid unbounded memory consumption.

We also don't want to holding references to spans because that can cause memory consumption problems.  I'll have to study what the code is doing to see if there's a better approach.

2023-04-04 13:21 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +  SparkAggregatedTaskMetrics applicationMetrics = new SparkAggregatedTaskMetrics();
Again, all of these could probably be final.

2023-04-04 13:24 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    jobSpan.finish(jobEnd.time() * 1000);
The collections might be okay, but only if you are cleaning them up on finished and capping their size.

2023-04-04 13:26 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    Optional<Long> completionTime =
Optional creates needlessly allocation.  I'd prefer a simple.

2023-04-04 13:32 UTC, dougqh requested changes
I haven't reviewed this closely yet, but there are several issues that I can already see need to be addressed...

First, in terms of Java style...
1 - The member variables aren't private - not idiomatic for Java
2 - Many member variables that should be final are not final

Second, memory management - the tracer is pretty strictly prohibited from having unbounded collections like those in this listener.

The first step towards fixing this is to remove elements from the map as those jobs & tasks finish.
The second step towards this to check that the map isn't over capacity as insertion.

Third, it is clear what the thread safety rules are the listener, so this code may not be safe.  Please indicate the thread safety behavior of the Spark listener with a comment in the code.

2023-04-04 13:33 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +  public void onApplicationStart(SparkListenerApplicationStart applicationStart) {
Are the listener methods always called in the same thread?  If not, then this code isn't thread safe.

2023-04-04 15:21 UTC, paul-laffon-dd reviewed
Thanks for the review! I am not used to write java, I tried to adapt the style related to your comments

For the memory management, I added a check that we are not above a certain size and removing the spans on the end event

For the thread-safety, all the callbacks are called from the same thread on the driver, so we should be safe on that (added a comment about it in the code)

2023-04-04 15:21 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +  public void onApplicationStart(SparkListenerApplicationStart applicationStart) {
Yes, they are all called from the same thread https://www.mail-archive.com/user@spark.apache.org/msg48812.html

2023-04-04 15:21 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +      jobStart
Changed it to a loop

2023-04-04 15:21 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    jobSpan.finish(jobEnd.time() * 1000);
Added a cap on their size and removing the spans when getting those from the maps

2023-04-04 15:21 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    Optional<Long> completionTime =
Changed it to a simple if

2023-04-04 15:21 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +  HashMap<Integer, AgentSpan> jobSpans = new HashMap<>();
Added final to those collections and capping the size

2023-04-06 01:27 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    if (jobSpans.size() > MAX_COLLECTION_SIZE) {
Good

2023-04-06 01:29 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    if (!stageToJob.containsKey(stageId)) {
containsKey followed by get is redundant unless you store nulls into the map.
You can just do stageToJob.get(stageId).  The only caveat is that you'll get back an Integer rather than int and then need to check against null.

2023-04-06 01:32 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    AgentSpan stageSpan =
Seeing withStartTimestamp made me realize that we probably want to exclude these spans from tracking by profiling, since these spans aren't actually represent work within this JVM.

I'll make a note to think about that.  It doesn't need to be a blocker for this initial prototype.

2023-04-06 01:34 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    for (Tuple2<String, String> conf : sparkConf.getAll()) {
We actually don't to capture all values from config into a span.
That risks accidentally exposing sensitive information.

We need to build an inclusion list of config to include.  We don't want to just include everything unconditionally.
It would also be fine to have the list be configurable.

2023-04-06 01:37 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    tracer.flush();
You shouldn't explicitly flush the tracer that's bad for performance.
Also, tracer.flush doesn't provide the semantics that you probably want.  As currently implemented, it is really only good for testing.

2023-04-06 01:38 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +      applicationSpan.setTag(DDTags.ERROR_TYPE, "Spark Application Failed");
Is there a better message available on the applicationEnd object?

2023-04-06 01:39 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +      for (final Map.Entry<Object, Object> entry : jobStart.properties().entrySet()) {
As with the config info, this needs to an inclusion list of know safe properties -- otherwise, there's a risk of leaking sensitive information.

2023-04-06 01:43 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    return stageId * 100000 + attemptId;
Since you are dealing with two ints, you might as well just use a long if you want a composite key.  Then you'll have no risk of accidental key collision.

It will also be more efficient to use shift operations / powers of 2 than multiplication.

2023-04-06 01:45 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
> +  private Long executorDeserializeTime = 0L;
I don't love that we have to box all these, but so be it.

2023-04-06 01:48 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
> +  public void setSpanMetrics(AgentSpan span, String prefix) {
Why the prefix?  This code is going to create a lot of Strings unnecessarily.

2023-04-06 01:52 UTC, dougqh requested changes
One critical issue that I missed in the first review...

The loops that copy data from spark onto the span from config, etc are a data exposure risk.  Those need to changed to using an inclusion list of properties that are known to not contain sensitive data.

The metrics code also looks quite inefficient in terms of allocation.  Especially with the use of box Long-s rather than long-s.  

Also, rebuilding the same metric names repeatedly is going to lead to unnecessary allocation, but I won't insist on fixing that right now.

2023-04-06 11:40 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +      applicationSpan.setTag(DDTags.ERROR_TYPE, "Spark Application Failed");
There is no error message in `SparkListenerApplicationEnd`, but we can provide the error message of the last job that failed

2023-04-06 11:40 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    for (Tuple2<String, String> conf : sparkConf.getAll()) {
Add the [SparkConfAllowList](https://github.com/DataDog/dd-trace-java/pull/4997/commits/e2f7ff62737cdad5d96c463950f5cda18312700b#diff-2e7513091cc3dc2274001eb2632efc645f996cfa87062427f4782981022d5759R12) to only capture a safe subset of the config. Is it what you meant by have the list be configurable ?

2023-04-06 11:40 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
> +  public void setSpanMetrics(AgentSpan span, String prefix) {
We are reporting those metrics at the stage / job / application level. When aggregating the values, if there is no filter on a specific operation, it will lead to double counting. The goal of the prefix (application|job|stage) is to avoid this double counting

I agree this is creating a lot of string, but I would think this is acceptable for now as there is not that many stage/job (less than 100) per application

2023-04-06 11:40 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    if (!stageToJob.containsKey(stageId)) {
Changed it to [here](https://github.com/DataDog/dd-trace-java/pull/4997/commits/e2f7ff62737cdad5d96c463950f5cda18312700b#diff-fdd413dca7c2a8c2c89e56c070d7062bf96975789772f7a16aebdae140edbc10L152-R165)

```java
Integer jobId = stageToJob.get(stageId);
if (jobId == null) {
  return;
}
```

2023-04-06 11:40 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    tracer.flush();
Removed the `flush()`. The idea was that the JVM will be shut down by spark pretty quickly after the `onApplicationEnd()` event is received and this was to make sure that the spans are sent to datadog

Would you know if there is a way to ensure that ?

2023-04-06 11:40 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/InjectedSparkListener.java
> +    return stageId * 100000 + attemptId;
Changed it to [here](https://github.com/DataDog/dd-trace-java/pull/4997/commits/e2f7ff62737cdad5d96c463950f5cda18312700b#diff-fdd413dca7c2a8c2c89e56c070d7062bf96975789772f7a16aebdae140edbc10L319-L321)

```java
private long stageSpanKey(int stageId, int attemptId) {
  return ((long) stageId << 32) + attemptId;
}
```

2023-04-06 11:40 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
> +  private Long executorDeserializeTime = 0L;
You are right, plain `long` are enough since they cannot be null, changed everything from `Long` to `long`

2023-04-13 01:34 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +    applicationSpan =
What is an application in Spark terms? 
Can multiple applications be running at once?

2023-04-13 01:37 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +    for (Tuple2<String, String> conf : sparkConf.getAll()) {
I suppose with allow list this is fine.  It could still be more efficient, but I imagine app starts are relatively rare.

2023-04-13 01:39 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +        if (SparkConfAllowList.canCaptureParameter(entry.getKey().toString())) {
Wouldn't it better to have two different allow lists?  I imagine the parameters are different for app vs a job.  Are they not?

2023-04-13 01:41 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +    if (!jobSpans.containsKey(jobEnd.jobId())) {
You don't need the containsKey guard.  You can just do a remove and test the result against null.
That's generally a better overall practice because it avoids rare race conditions when using maps synchronized across threads.  It also happens to be a bit more efficient.

2023-04-13 01:45 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
> +  public void setSpanMetrics(AgentSpan span, String prefix) {
Okay, presuming the cardinality is low, it should be okay.  In many places, we have to deal with 50000 ops/sec, so even a little inefficiency is deadly.

2023-04-13 01:47 UTC, dougqh requested changes
I think pretty much all uses of containsKey are unnecessary.  You can just do a get or remove then check the return value.

That's a good habit to get into because it will race condition problems when dealing with synchronized maps.  Plus it is a tad bit more efficient.

2023-04-13 12:04 UTC, mcculls commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +            .and(isDeclaredBy(named("org.apache.spark.SparkContext"))),
Since we're instrumenting a known type, `org.apache.spark.SparkContext`, you don't need `isDeclaredBy` here

2023-04-13 12:13 UTC, mcculls commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +        applicationSpan.setTag("config." + conf._1.replace(".", "_"), conf._2);
this is another place we could use a small cache to reduce string creation

2023-04-13 12:14 UTC, mcculls commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +    stageInfo.rddInfos().foreach(rdd -> span.setTag("rdd." + rdd.name(), rdd.toString()));
this is another place we could use a small cache to reduce string creation

2023-04-13 12:26 UTC, mcculls commented
Agree with the comments from @dougqh about avoiding `containsKey` and going straight to the `get` or `remove` method.

Likewise patterns like this:
```
    if (!stageMetrics.containsKey(stageSpanKey)) {
      stageMetrics.put(stageSpanKey, new SparkAggregatedTaskMetrics());
    }
    stageMetrics.get(stageSpanKey).addTaskMetrics(taskEnd);
```
can be simplified in Java 8 to:
```
    stageMetrics.computeIfAbsent(stageSpanKey, SparkAggregatedTaskMetrics::new).addTaskMetrics(taskEnd)
```

2023-04-13 13:23 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +    for (Tuple2<String, String> conf : sparkConf.getAll()) {
application starts is a pretty heavy process in spark that generally takes multiple seconds

2023-04-13 13:23 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +            .and(isDeclaredBy(named("org.apache.spark.SparkContext"))),
Removed it in this commit https://github.com/DataDog/dd-trace-java/pull/4997/commits/17a8ccf7b7f32b92916195801a0aaeb4f2ccb6ce

2023-04-13 15:40 UTC, paul-laffon-dd commented
I removed all usage of `containsKey` to directly use remove/get instead. 

About the caching to limit creation of duplicate strings, I would think that they might not be worthwhile since there is not that many stages per spark application (generally less than 100 for applications running for tens of minutes)

2023-04-19 16:43 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +    applicationSpan =
What is the lifetime of an application span?
If the application last indefinitely, then it probably shouldn't have a span.

2023-04-19 16:47 UTC, dougqh commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
> +  public void setSpanMetrics(AgentSpan span, String prefix) {
Okay, that seems reasonable for Spark.

2023-04-19 16:51 UTC, dougqh approved these changes
The code around applicationSpan isn't obviously correct to me.

I think having a trace encompass the whole application might be the wrong choice, but it really depends on the lifetime of the application object.

Just based on the names, I think it would probably be better to have a trace per job -- not a trace per application.

2023-04-20 10:20 UTC, paul-laffon-dd commented
The application is started when the spark driver is spin up and ends when the driver is shut down. 

Spark applications are launched with a [spark-submit](https://spark.apache.org/docs/latest/submitting-applications.html#launching-applications-with-spark-submit) command to produce an output and the application lifecycle is tied to this command

```sh
./bin/spark-submit \
  --class org.apache.spark.examples.SparkPi \
  --master local[8] \
  /path/to/examples.jar \
  100
```

The application metrics are the most useful since they provide an overall picture of what happened during the entire program. Looking into Spark jobs is mainly useful for troubleshooting when the application has failed or performed poorly

2023-04-20 18:03 UTC, paul-laffon-dd commented
Excluding the spark instrumentation from semeru jdk since hadoop, on which spark in depending is not behaving well on it, https://issues.apache.org/jira/browse/HADOOP-18174

2023-04-24 07:32 UTC, merged