vertx-redis: implement v1 naming and surface remote connection info
DataDog/dd-trace-java pull request #5041
Opened 2023-04-07 14:04 UTC by amarziali

# What Does This Do

Implements opt-in v1 naming convestions:
* operation: redis.command
* service: DD_SERVICE

Surface remote host connection tags:
* peer.hostname
* peer.port

# Motivation

# Additional Notes

2023-04-27 18:37 UTC, ygree commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisAPIImplSendAdvice.java
> +        if (!future.isComplete()) {
NIce!

2023-04-27 18:44 UTC, ygree commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/ConnectionAsyncResultWrapper.java
> +              contextStore.put(redisInstance, connection);
Here we associate one connection with a Redis client instance. Could there be more than one active connections for the same Redis client instance?

2023-04-27 18:50 UTC, ygree commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +      if (connection instanceof Redis) {
This two if checks are read as that the connection object associated with RedisAPIImpl can be either Redis or RedisConnection which is a bit confusing. If it's never the case and the object associated with RedisAPIImpl is always Redis then moving the next if-check inside of the first if-check scope would be less confusing.

2023-04-27 18:54 UTC, ygree commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +      if (connection instanceof Redis) {
The same applies to [RedisSendAdvice.java](https://github.com/DataDog/dd-trace-java/pull/5041/files#diff-8981ca5bfd751f6700ee29de7d46bce2444dd47b3cc34333da14bb796adb7b2b)

2023-04-27 18:55 UTC, ygree requested changes
Looks good! Just got a couple of questions

2023-05-02 08:56 UTC, amarziali commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisAPIImplSendAdvice.java
> +        if (!future.isComplete()) {
Thanks

2023-05-02 08:56 UTC, amarziali commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
> +      if (connection instanceof Redis) {
Finally I found another approach so this is now unnecessary

2023-05-02 08:58 UTC, amarziali commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/ConnectionAsyncResultWrapper.java
> +              contextStore.put(redisInstance, connection);
Yes completely. You are right. I completely changed the approach in order to have something only depending to the connection (without relating to other objects) 
Now it looks to my eyes way better

2023-05-03 16:36 UTC, ygree commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisConnectAdvice.java
> +      return activateSpan(span, true);
I'm not sure why do we need this advice? RedisAPICallAdvice should already activate the command span scope.

2023-05-03 16:37 UTC, ygree approved these changes
Nice fix! The only thing I'm not sure is still needed is RedisConnectAdvice

2023-05-04 14:15 UTC, amarziali commented on dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisConnectAdvice.java
> +      return activateSpan(span, true);
Actually when used in pooled mode `Redis#send` is calling itself `connect` in a lambda. Without activating in this way I do not have the span in the other advices. The solution I found is to activate here

2023-05-09 08:01 UTC, merged