Add support for SSRF vulnerabilities
DataDog/dd-trace-java pull request #5051
Opened 2023-04-12 09:53 UTC by manuel-alvarez-alvarez

# What Does This Do

# Motivation

# Additional Notes

2023-04-12 09:55 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URLCallSite.java
> +          module.taintIfAnyInputIsTainted(result, args);
I think it makes sense to build a different module aka `UrlModule` to deal with the propagation in URLs

2023-04-21 11:48 UTC, smola commented on dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
> +                              "/home/malvarez/go/src/github.com/DataDog/dd-trace-java/build/instrumented"));
I guess this is why this is still in draft :wink:

2023-04-21 16:18 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
> +                              "/home/malvarez/go/src/github.com/DataDog/dd-trace-java/build/instrumented"));
Yep, actually it's ready now :smile:

2023-04-24 09:38 UTC, smola requested changes

2023-04-24 09:38 UTC, smola commented on dd-java-agent/instrumentation/commons-httpclient-2/src/main/java/datadog/trace/instrumentation/commonshttpclient/IastCommonsHttpClientInstrumentation.java
> +public class IastCommonsHttpClientInstrumentation extends Instrumenter.Tracing
```suggestion
public class IastCommonsHttpClientInstrumentation extends Instrumenter.Iast
```

2023-04-24 09:47 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/commons-httpclient-2/src/main/java/datadog/trace/instrumentation/commonshttpclient/IastCommonsHttpClientInstrumentation.java
> +public class IastCommonsHttpClientInstrumentation extends Instrumenter.Tracing
Fixed, thanks!

2023-04-24 09:48 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URICallSite.java
> +  @CallSite.After("java.lang.String java.net.URI.toString()")
The class has the annotation:

```java
@IastAdvice.Propagation(PropagationTypes.URI)
@CallSite(spi = IastAdvice.class)
public class URICallSite {
   ...
}
```

Method annotations take precedence over the type annotation so you can override the telemetry annotation.

2023-04-24 17:53 UTC, smola approved these changes

2023-04-26 14:24 UTC, merged