Add flag DD_TELEMETRY_METRICS_ENABLED disabled by default
DataDog/dd-trace-java pull request #5073
Opened 2023-04-17 13:10 UTC by manuel-alvarez-alvarez

# What Does This Do
Adds a new flag to disable telemetry metrics by default.

# Motivation
Disables the telemetry payloads until the telemetry-intake is ready.

# Additional Notes

2023-07-20 07:37 UTC, PerfectSlayer requested changes

2023-07-20 07:37 UTC, PerfectSlayer commented on internal-api/src/main/java/datadog/trace/api/MetricCollector.java
> +    }
It feels like it would be better to create a noop collector if metrics are disabled rather than checking the config state for each call.

2023-07-20 07:37 UTC, PerfectSlayer commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +        configProvider.getBoolean(TELEMETRY_METRICS_ENABLED, DEFAULT_TELEMETRY_METRICS_ENABLED);
Does it take care if the whole telemetry thing is enabled?

2023-09-18 14:00 UTC, closed without merging

2023-09-18 14:52 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/MetricCollector.java
> +    }
Hello! sorry for the late reply to the feedback :cry: , I should have closed this PR long ago as the requirement regarding telemetry is not here anymore.

Thanks for the feedback!