Report internal errors/exceptions via telemetry
DataDog/dd-trace-java pull request #5075
Opened 2023-04-17 14:47 UTC by ValentinZakharov

# What Does This Do
Implements exception reporting using the Telemetry API. Implements a marker that can be used to send debug lines to the telemetry API if the marker is used as a parameter in the debug call.

# Motivation
To collect reports about exceptions in client's installations. This will make support cycles easier and ensure we know about potentially silent issues in libraries.

# Additional Notes
New configuration:

DD_TELEMETRY_LOG_COLLECTION_ENABLED (environment variable) or dd.instrumentation.telemetry.log-collection.enabled (system property): This boolean flag (true, false) enables log collection by telemetry for log lines with level ERROR and WARN. It is disabled by default.
Additional conditions for log lines to be sent to telemetry:

The line contains an exception, e.g. logger.error("there was an exception", throwable).
The line doesn't contain an exception but the Logger was called with the marker DDLogger.SEND_TELEMETRY, e.g. logger.error(DDLogger.SEND_TELEMETRY, "message sent to telemetry").
Log lines are de-duplicated during the telemetry heartbeat interval (default: 1 minute).
There is a limit in the number of log lines collected during a telemetry heartbeat interval, currently set to 1024 so we stay bounded. If we hit the limit, any extra lines are dropped silently.

2023-04-18 07:37 UTC, smola reviewed
Looks good, but change the default to `false` until we battle test this.

2023-04-18 07:37 UTC, smola commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  static final boolean DEFAULT_TELEMETRY_LOG_COLLECTION_ENABLED = true;
Disable by default at the moment.

2023-04-26 08:51 UTC, smola commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
> +      return new DDTelemetryLogger(getHelperFactory(), name);
If `DD_TELEMETRY_LOG_COLLECTION_ENABLED` is not true, we probably want to just use `DDLogger` here? It would be pointless to get any overhead in that case.

2023-04-28 20:53 UTC, ygree commented on telemetry/src/test/groovy/datadog/telemetry/log/LogPayloadSerializationTest.groovy
> +    System.out.println(request.body())
Some debugging leftovers?

2023-04-28 21:05 UTC, ygree commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDTelemetryLogger.java
> +        // or tokens
A minor suggestion for a possibly better wording: Sending debug level messages as-is because they are expected not to have any sensitive information

2023-04-28 21:09 UTC, ygree commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDTelemetryLogger.java
> +        // we are only send static (compile time) log messages, plus redacted stack traces.
It's minor but I find this comment a bit misleading. Correct me if I'm wrong I just don't see that we really scrub anything here, but rather using a format string instead of the original log message.

2023-04-28 22:02 UTC, ygree commented on telemetry/src/test/groovy/datadog/telemetry/log/ExceptionHelper.groovy
> +    (-1 != stackLine.indexOf('/') ? stackLine.indexOf('/') : stackLine.indexOf(" at ") + 3)
I'd save the result of `stackLine.indexOf('/')` to avoid calling it twice

2023-04-28 22:03 UTC, ygree commented on telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
> +    //0 * requestBuilder._
A leftover comment?

2023-04-28 22:05 UTC, ygree commented on telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
> +  private static final String[] packageList = {"datadog.", "com.datadog.", "java.", "javax."};
Should be an uppercase snail style

2023-04-28 22:07 UTC, ygree commented on telemetry/src/test/groovy/datadog/telemetry/log/ExceptionHelper.groovy
> +    return callSpec.startsWith("java.")
Getting these values from LogPeriodicAction.packageList or moving them here will help to avoid duplicity

2023-04-28 22:12 UTC, ygree commented on telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
> +          new LogMessage().message(rawLogMsg.message).tracerTime(rawLogMsg.timestamp);
I'd rather pass everything as LogMessage construct parameters. Or do we need to mutate them at some point?

2023-04-28 22:15 UTC, ygree commented on telemetry/src/main/java/datadog/telemetry/api/LogMessage.java
> +    return "LogMessage{"
It looks nicer. There wasn't any need to use StringBuffer here as all parts are statically defined, so the compiler will do this job.

2023-04-28 22:16 UTC, ygree commented on telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
> +    if (dependencyService != null) {
Java style vs C style :-)

2023-04-28 22:33 UTC, ygree commented on internal-api/src/main/java/datadog/trace/api/LogCollector.java
> +  public boolean isEnabled() {
I don't think the `enabled` flag belongs to this class. It's never used within this class and accessing it will force LogCollector initialization, just for this check.

2023-04-28 22:55 UTC, ygree commented on internal-api/src/main/java/datadog/trace/api/LogCollector.java
> +    if (!rawLogMessages.isEmpty()) {
Alternatively, you could use two separate rawLogMessages and swapping them on the drain call. This way you can avoid multiple remove calls (cleaning the entire map is likely to be cheaper) and  multiple List elements allocations (pre-allocating the result list at once knowing the size of the rawLogMessages map at the moment when it's swapped and there won't be any insertions after the swap operation because now all new writes will got to the other rawLogMessages map).

2023-04-28 22:56 UTC, ygree requested changes
I have a few suggestions for this change.

2023-05-05 16:32 UTC, ValentinZakharov commented on telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
> +          new LogMessage().message(rawLogMsg.message).tracerTime(rawLogMsg.timestamp);
LogMessage is kind of autogenerated pojo, like all api telemetry structures. I agree, it make sense to rewrite them all, in future.

2023-05-05 16:43 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/LogCollector.java
> +  public boolean isEnabled() {
Yeah, I agree, the solution looks crappy. The enable flag here is for "bridge" purpose (between different modules). The log collector located in `internal-api`. We are reading value from `agent-logging` and writing value from `telemetry`. Initially I was checking is it's enabled in current class, but later, performance-wise, I moved it to logger.

2023-05-05 16:46 UTC, ValentinZakharov commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDTelemetryLogger.java
> +        // we are only send static (compile time) log messages, plus redacted stack traces.
That's correct. To avoid processing string and do a "real" scrubbing, we just use format string which already looks like scrubbed string, because has no values.

2023-05-09 16:58 UTC, smola approved these changes

2023-05-09 17:01 UTC, smola requested changes

2023-05-09 17:01 UTC, smola commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
> +    if (Platform.isNativeImageBuilder() && !telemetryLogCollectionEnabled) {
```suggestion
    if (Platform.isNativeImageBuilder() || !telemetryLogCollectionEnabled) {
```

2023-06-01 10:36 UTC, smola commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
> +    value = System.getProperty("DD_TELEMETRY_LOG_COLLECTION_ENABLED");
Ouch. Indeed.

2023-10-25 09:29 UTC, smola commented
Superseded by https://github.com/DataDog/dd-trace-java/pull/6057

2023-10-25 09:29 UTC, closed without merging