Add IAST instrumentation for nimbusds' jose-jwt and auth0's java-jwt
DataDog/dd-trace-java pull request #5076
Opened 2023-04-17 15:01 UTC by DDJavierSantos

# What Does This Do

Instruments the auth0's java-jwt and nimbusds's jose-jwt parsers to taint JWT tokens as sources for vulnerability detection.

# Motivation

We need to cover vulnerabilities created by JWTs (Java web token) and Jose is the most popular library for dealing with JWT in java.

# Additional Notes

2023-04-18 07:23 UTC, smola commented on dd-java-agent/instrumentation/jose-jwt/build.gradle
> +apply plugin: 'org.unbroken-dome.test-sets'
Please, rebase from latest master. This will not work with Gradle 8.1. It was recently changed here: https://github.com/DataDog/dd-trace-java/pull/5064

2023-04-18 07:24 UTC, smola commented on dd-java-agent/instrumentation/jose-jwt/build.gradle
> +csi {
It sees no call sites are defined, so this is not needed.

2023-04-18 07:24 UTC, smola commented on dd-java-agent/instrumentation/jose-jwt/build.gradle
> +testSets {
See the PR linked above for the new format for this.

2023-04-18 07:26 UTC, smola commented on dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
> +    return "com.auth0.jwt.impl.JWTParser";
I guess this is auth0's java-jwt, not nimbus jose-jwt?

2023-04-18 07:26 UTC, smola commented on dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
> +  public static class InstrumenterAdvice {
```suggestion
  public static class ParsePayloadAdvice {
```

2023-04-18 07:26 UTC, smola commented on dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
> +    @Advice.OnMethodEnter
```suggestion
    @Advice.OnMethodEnter(suppress=Throwable.class)
```

2023-04-18 07:27 UTC, smola commented on dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
> +        try {
You can remove the try/catch given the `suppress` parameter to the annotation above.

2023-04-18 07:28 UTC, smola commented on dd-java-agent/instrumentation/jose-jwt/src/test/groovy/JWTParserInstrumentationTest.groovy
> +    TestSuite.parse(payload)
I think you don't need that separate `TestSuite` class given that no call site instrumentation is being used.

2023-04-18 07:29 UTC, smola commented on dd-smoke-tests/spring-security/src/main/java/com/example/jwt/MainController.java
> +
Please, avoid these multiple consecutive newlines (not just in this file).

2023-04-18 07:31 UTC, smola commented on dd-smoke-tests/spring-security/src/test/groovy/datadog/smoketest/SpringSecurityJwtTest.groovy
> +  //curl --oauth2-bearer "<token>" http://localhost:8080/token
Remove these left overs. Or if it's meant as documentation, add a brief explanation in a `/** */` block for the test or `//` within the test, so that it doesn't get lost in a refactor.

2023-04-18 07:31 UTC, smola commented on dd-smoke-tests/spring-security/src/test/groovy/datadog/smoketest/SpringSecurityJwtTest.groovy
> +  private static String builClassPath(){
```suggestion
  private static String buildClassPath(){
```

2023-04-18 09:08 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
> +    return "com.auth0.jwt.impl.JWTParser";
auth0 is used by maven 1, nimbus for maven 2

2023-04-19 08:37 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/build.gradle
> +apply plugin: 'org.unbroken-dome.test-sets'
applied

2023-04-19 08:38 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/build.gradle
> +testSets {
applied

2023-04-19 08:38 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
> +  public static class InstrumenterAdvice {
This is a nested class, JWTParserInstrumentation$InstrumenterAdvice. I am not sure why the name needs changing.

2023-04-19 08:38 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
> +        try {
done

2023-04-19 08:39 UTC, DDJavierSantos commented on dd-smoke-tests/spring-security/src/main/java/com/example/jwt/MainController.java
> +
done

2023-04-19 08:39 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/build.gradle
> +csi {
done

2023-04-19 08:41 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
> +    return "com.auth0.jwt.impl.JWTParser";
I have changed the labels of the instrumenters to differentiate: "jwt", "jose-jwt" and "jwt", "auth0"

2023-04-19 08:42 UTC, DDJavierSantos commented on dd-smoke-tests/spring-security/src/test/groovy/datadog/smoketest/SpringSecurityJwtTest.groovy
> +  //curl --oauth2-bearer "<token>" http://localhost:8080/token
done

2023-04-19 08:42 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
> +    @Advice.OnMethodEnter
done

2023-04-19 08:43 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/src/test/groovy/JWTParserInstrumentationTest.groovy
> +    TestSuite.parse(payload)
done

2023-04-24 17:49 UTC, smola requested changes

2023-04-24 17:49 UTC, smola commented on dd-java-agent/instrumentation/jose-jwt/build.gradle
> +  testRuntimeOnly(project(':dd-java-agent:instrumentation:iast-instrumenter'))
This shouldn't be needed anymore?

2023-04-25 10:57 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/jose-jwt/build.gradle
> +  testRuntimeOnly(project(':dd-java-agent:instrumentation:iast-instrumenter'))
removed

2023-04-26 07:37 UTC, smola approved these changes

2023-04-26 09:03 UTC, merged