Spark instrumentation for databricks
DataDog/dd-trace-java pull request #5118
Opened 2023-04-26 08:58 UTC by paul-laffon-dd

# What Does This Do

Databricks is using Spark in a slightly different way than other cluster managers, with a model of one cluster = one spark application, whereas one cluster can have multiple Spark applications on YARN or Kubernetes. 

The spark driver, and consequently the Spark application, are long running and bound to the cluster with spark jobs (not applications) submitted to it. In this case, we make spark jobs the local root spans.

# Motivation

Adapting the spark instrumentation for databricks

2023-04-26 16:28 UTC, raphaelgavache approved these changes
lgtm for the new databrick tags, I double checked them in our UI

2023-05-02 13:19 UTC, PerfectSlayer requested changes

2023-05-02 13:29 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +    }
It can definitely be written using `split` / `lastIndexOf` instead. I wrote it using a regexp at first since it felt easier to implement/read

Right now the regexp is compiled only once, if it has not been used yet (with the if null condition)

2023-05-02 14:37 UTC, PerfectSlayer approved these changes

2023-05-03 06:52 UTC, PerfectSlayer commented
`String.split()` is forbidden from `gradle/forbiddenApiFilters/main.txt` as it internally uses regex.
But, `split()` implementation has a fast-path for non-regex delimiter.
So you can use the `@SuppressForbidden` annotation with a such comment to get the check pass.

2023-05-03 12:22 UTC, merged