Jsantos/insecure cookie vertx
DataDog/dd-trace-java pull request #5209
Opened 2023-05-16 08:53 UTC by DDJavierSantos

# What Does This Do
Instruments Vertx's SeverResponse in order to detect insecure cookies.

# Motivation
Insecure cookie detection needs to cover the main frameworks.

# Additional Notes

2023-05-25 11:32 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServertResponseInstrumentation.java
> +      System.out.println("!!!");
If you want to quickly debug this methods you can set `inline = false` in the advice and then you can actually debug inside (the instrumenter will inject a call to this method instead of it's bytecode)

2023-05-25 11:40 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServertResponseInstrumentation.java
> +public class HttpServertResponseInstrumentation extends Instrumenter.Iast
HttpServer**t**ResponseInstrumentation

2023-05-25 11:48 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServertResponseInstrumentation.java
> +          module.onCookieHeader(value.toString());
Shouldn't we use the `InstrumentationBridge.onHeader()`?

2023-05-25 11:52 UTC, manuel-alvarez-alvarez commented on dd-smoke-tests/vertx-3.4/.idea/gradle.xml
All this files shouldn't be added to git, there's no `.gitignore` for it?

2023-06-01 10:52 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServertResponseInstrumentation.java
> +      System.out.println("!!!");
Thanks, I'll keep it in mind, and remove this statement

2023-06-01 10:53 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServertResponseInstrumentation.java
> +public class HttpServertResponseInstrumentation extends Instrumenter.Iast
fixed

2023-06-01 10:54 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServertResponseInstrumentation.java
> +            .or(takesArguments(String.class, String.class)),
There are two override funtions, one takes the CharSequence and the other one takes the Strings. We need to instrument both.

2023-06-01 11:28 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServertResponseInstrumentation.java
> +          module.onCookieHeader(value.toString());
Moved to instrumentation bridge

2023-06-06 14:07 UTC, smola commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java
> +    super("vertx", "vertx-3.4", "Http");
```suggestion
    super("vertx", "vertx-3.4");
```

I guess we can just keep this like this atm.

2023-06-06 14:08 UTC, smola requested changes

2023-06-06 14:08 UTC, smola commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java
> +            .or(takesArguments(String.class, Iterable.class)),
I think this `.or` needs to be inside the previous `.and`, so that it's no "named or takesArguments"

2023-06-06 14:18 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java
> +    super("vertx", "vertx-3.4", "Http");
applied

2023-06-06 14:18 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java
> +            .or(takesArguments(String.class, Iterable.class)),
applied

2023-06-07 07:42 UTC, smola requested changes

2023-06-07 07:42 UTC, smola commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java
> +      for (Object value : values) {
Let's check if  `values` is null.

2023-06-07 10:33 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java
> +      for (Object value : values) {
fixed

2023-06-07 10:33 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java
> +        if (value instanceof CharSequence && null != value) {
fixed

2023-06-07 12:32 UTC, smola approved these changes

2023-06-07 12:44 UTC, merged