Add dynamic config support for log injection
DataDog/dd-trace-java pull request #5221
Opened 2023-05-16 22:24 UTC by randomanderson

# What Does This Do

Supports dynamic config with log injection. There are 2 main changes:

**1. Instrumentation enable/disable is no longer controlled by the log injection flag**
For "reasons", log injection was special-cased to also control instrumentation enable/disable. In order to support dynamic config, the instrumentations need to be enabled. We already have a separate mechanism for disabling instrumentations

**2. "Event Instrumentation"s are wrapped in config checks**
These are the parts of the instrumentations where the `AgentContext` is store in an `InstrumentationContext`. With this PR, the instrumentation is skipped if log injection is not enabled (or `TraceConfig` is null meaning a NOOP span)

**2. MDC operations are wrapped in config checks**
These are parts of the instrumentations that might not occur during a span (the LogAppender writing an event). With these instrumentations, the PR checks if a context was stored (meaning log injection was enabled when the log message was created) or if log injection is enabled at the tracer level.

# Testing

This needs to be added at the log injection smoke test level. Currently there is no api for dynamic config, so it can't be tested

2023-06-21 07:47 UTC, bantonsson requested changes
Looks good, but I would like some `null` check guards unless I missed something.

2023-06-21 07:47 UTC, bantonsson commented on dd-java-agent/instrumentation/log4j-2.7/src/main/java/datadog/trace/instrumentation/log4j27/SpanDecoratingContextDataInjector.java
> +    if (!AgentTracer.traceConfig(activeSpan()).isLogsInjectionEnabled()) {
You already have `activeSpan()` in `span`.

2023-06-21 07:47 UTC, bantonsson commented on dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
> +    def conditions = new PollingConditions(timeout: 30, initialDelay: 0, delay: 0.5, factor: 1)
Yup, a thousand seconds seems a bit excessive.

2023-06-21 07:47 UTC, bantonsson commented on dd-java-agent/instrumentation/jboss-logmanager/src/main/java/datadog/trace/instrumentation/jbosslogmanager/ExtLogRecordInstrumentation.java
> +      if (context == null && !AgentTracer.traceConfig().isLogsInjectionEnabled()) {
Can't the `context` be `null` but `isLogsInjectionEnabled()` be `true` so we would possibly get a `NullPointerException` at `context.getTraceId()` and `context.getSpanId()` below?

2023-06-21 07:47 UTC, bantonsson commented on dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/LoggingEventInstrumentation.java
> +      if (context == null && !AgentTracer.traceConfig().isLogsInjectionEnabled()) {
Same thing with the `null` checks of `context` below (even though it was missing for `traceId` before).

2023-06-21 07:47 UTC, bantonsson commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
> +      add(CorrelationIdentifier.getSpanIdKey(), CorrelationIdentifier.getSpanId());
It feels a bit wasteful to go via `CorrelationIdentifier.getTraceId() -> GlobalTracer.get().getTraceId() -> getTraceId(activeSpan())` when we already have the `traceId` and `spanId`. Can't we add methods to the tracer to get the `String` from a `traceId` and a `spanId`?

2023-06-21 10:05 UTC, mcculls commented
Heads-up that I'm adding the rest of the dynamic-config plumbing in https://github.com/DataDog/dd-trace-java/pull/5437 - once that's merged you'll be able to simplify this PR to just the pieces that act on the dynamic-config

2023-06-21 20:56 UTC, randomanderson commented on dd-java-agent/instrumentation/jboss-logmanager/src/main/java/datadog/trace/instrumentation/jbosslogmanager/ExtLogRecordInstrumentation.java
> +      if (context == null && !AgentTracer.traceConfig().isLogsInjectionEnabled()) {
Good catch. I think this was a ctrl+x error.

2023-06-22 09:26 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +
Could you record this in `Config.toString()` now that it's been removed from `InstrumenterConfig`?

2023-06-22 09:29 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    private boolean logsInjectionEnabled;
This can be removed, since we get the `logsInjectionEnabled` setting from the config not the builder.

2023-06-22 09:30 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +    }
This builder method can also be removed

2023-06-22 09:32 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
> +      final boolean logsInjectionEnabled) {
this parameter can be removed now

2023-06-22 09:35 UTC, mcculls commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
> +      if (traceId.toHighOrderLong() != 0 && InstrumenterConfig.get().isLogs128bTraceIdEnabled()) {
Should we check `InstrumenterConfig.get().isLogs128bTraceIdEnabled()` first since it's more likely to be optimized away at runtime? (given it's all static finals)

2023-06-22 09:41 UTC, bantonsson approved these changes

2023-06-22 09:56 UTC, mcculls commented on dd-smoke-tests/log-injection/build.gradle
> +  implementation project(path: ':dd-trace-ot', configuration: 'shadow')
I wasn't able to see where `dd-trace-ot` is required in the tests - is this extra dependency still needed?

2023-06-22 09:58 UTC, mcculls approved these changes
LGTM - just some minor cleanup to do before merging

2023-06-23 08:34 UTC, mcculls commented on dd-smoke-tests/log-injection/build.gradle
> +  implementation project(path: ':dd-trace-ot', configuration: 'shadow')
Understood, thanks for the explanation

2023-06-26 20:53 UTC, merged