[Spark] Separate the error stack trace from the error message
DataDog/dd-trace-java pull request #5256
Opened 2023-05-24 13:53 UTC by paul-laffon-dd

# What Does This Do

Before this PR, the full error message from spark (which also contained the stack trace) was added to the `span.setErrorMessage`. Changing that to separate the message from the stack trace in the span so it can be better represented in the UI

Another change is to only send task errors that `countTowardsTaskFailures` as the ones that don't count as a failure tend to be very noisy (`FetchFailed`, `Resubmitted`, ...)

2023-05-24 19:05 UTC, raphaelgavache approved these changes
very nice

2023-05-25 11:54 UTC, PerfectSlayer requested changes
Hi Paul,
Does those changes should come with the related tests too?

2023-05-25 11:54 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +  private String getErrorMessageWithoutStackTrace(String errorMessage) {
`errorMessage` can be `null`

2023-05-26 12:35 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +  private String getErrorMessageWithoutStackTrace(String errorMessage) {
Added a safe guard in case `errorMessage` is null

2023-05-26 12:36 UTC, paul-laffon-dd commented
Added a test to check the shape of the error type / message / stacktrace

2023-05-28 12:20 UTC, PerfectSlayer commented
> Added a test to check the shape of the error type / message / stacktrace

That’s better, thanks!
But the new test case seem to fail in CI:

```
assert span.operationName.toString() == name
       |    |             |          |  |
       |    'spark.job'   'spark.job'|  'spark.application'
       |                             false
       DDSpan [ t_id=7, s_id=8, p_id=6 ] 
```

2023-05-31 11:41 UTC, paul-laffon-dd commented
> But the new test case seem to fail in CI:

Yes, I fixed the test in the new version

2023-05-31 15:02 UTC, bantonsson approved these changes

2023-05-31 15:07 UTC, merged