[Spark] Handle spark on YARN application end in a special way
DataDog/dd-trace-java pull request #5267
Opened 2023-05-25 12:15 UTC by paul-laffon-dd

# What Does This Do

Instrument the spark [yarn.ApplicationMaster.finish()](https://github.com/apache/spark/blob/master/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/ApplicationMaster.scala#L378) function in order to
- catch the exit code and message of the application
- make sure the tracer has enough time to send its trace to the datadog agent

### Capturing exit code

An application can fail during spark computations (when performing operations on the data) or in the user code (like trying to select a column that does not exists)

Failures during spark computations are caught by the SparkListener, but not the errors in the user code so instrumenting the finish function allows to also capture those

### Tracer being shut down

In the case the sparkContext is not closed explicitly by the user (using `spark.close()`), the spark context is shutdown automatically during a shutdown hook. However this hook is triggered just before the thread is interrupted, which might not leave enough time for the tracer to send its traces, leading to the logs below

```
23/05/17 13:11:23 INFO ApplicationMaster: Final app status: SUCCEEDED, exitCode: 0
23/05/17 13:11:23 INFO SparkContext: Invoking stop() from shutdown hook
[dd.trace 2023-05-17 13:11:23:205 +0000] [dd-trace-processor] DEBUG datadog.trace.agent.common.writer.TraceProcessingWorker - Datadog trace processor exited. Publishing traces stopped
[dd.trace 2023-05-17 13:11:23:212 +0000] [spark-listener-group-shared] DEBUG datadog.trace.agent.common.writer.RemoteWriter - Trace written after shutdown.. Counted but dropping trace
```

In this case a simple work around is to wait a bit before completing the shutdown, to let enough time to send its trace

2023-05-25 14:04 UTC, raphaelgavache commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +        DatadogSparkListener.listener.finishApplication(System.currentTimeMillis(), exitCode, msg);
Is YarnFinishAdvice run by a separate thread then the SparkListener? If so finishApplication needs to be thread safe

2023-05-25 14:14 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +        DatadogSparkListener.listener.finishApplication(System.currentTimeMillis(), exitCode, msg);
Yes, it will run in the main thread of the application while the sparkListener will run on another thread so this method has to be thread safe

2023-05-25 16:25 UTC, PerfectSlayer requested changes

2023-05-25 16:25 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +      }
I don’t think this will do what you expect:

* We do already flush the traces in the shutdown hook
* You don’t know if your hook will run after or before the tracer one. So it might be already dead when you call `sleep`.

Moreover, please avoid using `thread.sleep()`. It should be added to _forbidden API_ by the way.

2023-05-26 08:44 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +      }
I removed the sleep since as you said it was not needed. 

The issue with the dropped trace was because the `onApplicationEnd` could be triggered after the processor was exited, with the log `Datadog trace processor exited. Publishing traces stopped`. 

By manually triggering the event before the `finish` function, we can already be sure that the trace is written before the tracer is exited

2023-05-26 20:21 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +      }
> I removed the sleep since as you said it was not needed.

I did not say it was not needed, rather than it might not do what you expect.
Hence, it implies we would like to have some tests to back the feature you introduce.
It would ensure it works properly and we can maintain it in the future.

2023-05-26 21:04 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +        DatadogSparkListener.listener.finishApplication(System.currentTimeMillis(), exitCode, msg);
All methods are now synchronized that could lead to performance issue.
What is the thing you are protecting against in the first place?
If only `finishApplication()` can be called from another thread, it might worth it to handle the thread safety at this level only, like using volatile or atomic boolean for `applicationEnded`. `AgentSpan` instance should be fine.

2023-05-30 09:45 UTC, raphaelgavache approved these changes

2023-05-30 13:21 UTC, bantonsson commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +        DatadogSparkListener.listener.finishApplication(System.currentTimeMillis(), exitCode, msg);
The _biased_ locking (which I think you are alluding to) have been removed from newer versions of the JDK, since the maintenance overhead outweighed the performance gains. That being said, from what I gather, these `synchronized` blocks are not in a performance critical path, so I think it should be fine for the case of simplicity.

2023-05-30 14:37 UTC, bantonsson commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
> +      }
I agree with @PerfectSlayer that it would be good to at least have one test. I know that orchestrating a spark test with yarn is out of the question, but a test that checks that the method gets instrumented and the tags added could be possible anyway. I quickly looked at the `ApplicationMaster` and I think it would be possible, even if it's a horrible hack, to _force_ use it without having it orchestrate the whole spark application. Basically just create a `SparkSession` and then create a `ApplicationMaster` and call `finish(...)` on it. The spark/yarn conf supplied to it would need to be faked to make sure it doesn't try to do anything.

2023-05-31 09:23 UTC, bantonsson approved these changes

2023-05-31 09:29 UTC, merged