Include search body in Elaticsearch spans
DataDog/dd-trace-java pull request #5273
Opened 2023-05-26 13:24 UTC by AhmadMasry

# What Does This Do
It adds the search request body and parameters to the span like what it did in python ddtrace

2023-05-30 12:17 UTC, AhmadMasry commented
Only system tests are not working now

2023-06-13 09:25 UTC, AhmadMS1988 commented
Hi @smola
Did anyone have the chance to review my work, or it can be included in the agent or not?
thank you for your efforts

2023-06-13 09:26 UTC, AhmadMasry commented
Hi @smola
Did anyone have the chance to review my work, or it can be included in the agent or not?
thank you for your efforts

2023-06-13 09:50 UTC, mcculls commented
Hi @AhmadMasry -  we've just been discussing about adding a new `Config` flag to control this new feature, in case other users prefer not to collect these additional details (we may decide to merge this first and then add the feature-flag)

2023-06-13 11:27 UTC, AhmadMasry commented
Thanks a lot @mcculls 
If you have any documentation or example on how to add the flag, please mention it to me, and I can help in the implementation.
Best regards

2023-06-16 00:43 UTC, am312 requested changes

2023-06-16 00:43 UTC, am312 commented on dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchRestClientDecorator.java
> +    StringBuffer bodyStringBuffer = new StringBuffer();
Could we be using StringBuilder here to avoid StringBuffer's syncronization overhead?

2023-06-16 00:43 UTC, am312 commented on dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchRestClientDecorator.java
> +      StringBuffer queryParametersStringBuffer = new StringBuffer();
and also StringBuilder here?

2023-06-16 11:37 UTC, AhmadMasry commented on dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchRestClientDecorator.java
> +    StringBuffer bodyStringBuffer = new StringBuffer();
Done

2023-06-16 11:37 UTC, AhmadMasry commented on dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchRestClientDecorator.java
> +      StringBuffer queryParametersStringBuffer = new StringBuffer();
Done

2023-06-16 12:21 UTC, am312 approved these changes

2023-06-16 16:22 UTC, merged