[Spark] Compute available executor time per stage
DataDog/dd-trace-java pull request #5310
Opened 2023-06-02 08:58 UTC by paul-laffon-dd

# What Does This Do

Compute available executor time per stage

2023-06-08 09:27 UTC, raphaelgavache commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +      long executorRunTime = taskEnd.taskMetrics().executorRunTime();
this doesn't take in account resultSerializationTime and executorDeserialize time

2023-06-08 09:28 UTC, raphaelgavache approved these changes

2023-06-09 10:32 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
> +      long executorRunTime = taskEnd.taskMetrics().executorRunTime();
You are right, it does not take the `resultSerializationTime` and `executorDeserialize`. But since the total task duration is also including those, I think we should take them into account

Added a new commit to use the `executorRunTime + resultSerializationTime + executorDeserialize` to compute the allocation

2023-06-12 14:57 UTC, bantonsson requested changes

2023-06-12 14:57 UTC, bantonsson commented on utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy
> +    //assert System.getenv().findAll { it.key.startsWith("DD_") }.isEmpty()
This should not be commented out, and the same goes for the three other instances below.

2023-06-12 17:39 UTC, paul-laffon-dd commented on utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy
> +    //assert System.getenv().findAll { it.key.startsWith("DD_") }.isEmpty()
Yes, my bad, I didn't realize that I pushed that 🤦 I removed it

2023-06-13 05:05 UTC, bantonsson approved these changes

2023-06-13 12:54 UTC, merged