WIP: Implement remote settings fetching for CI Visibility
DataDog/dd-trace-java pull request #5412
Opened 2023-06-15 18:24 UTC by nikita-tkachenko-datadog

# What Does This Do

# Motivation

# Additional Notes

2023-06-26 16:03 UTC, nikita-tkachenko-datadog commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  public Boolean getCiVisibilityCodeCoverageEnabled() {
In parent process this flag is supposed to be enabled by default (unless the client explicitly disables it), and in children processes it's disabled by default (unless the parent process explicitly informs the child to enable it).
I agree that it is somewhat confusing.
My line of thinking was that having two different flags would be even more confusing

2023-06-26 16:21 UTC, nikita-tkachenko-datadog commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +  public Boolean getCiVisibilityCodeCoverageEnabled() {
This is something I forgot to rollback, good catch! I though I'd need the code to behave differently based on whether the flag is specified or omitted, but in the end I could do with just specifying the default value.
Rolled back this change.

2023-06-28 11:34 UTC, bantonsson commented on dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/JvmInfo.java
> +  public static final JvmInfo CURRENT_JVM =
It feels like this is the same thing as the data in `datadog.trace.api.Platform`

2023-06-28 11:36 UTC, bantonsson commented on dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ModuleExecutionSettingsFactory.java
> +        .runtimeVendor(jvmInfo.getVendor())
Why is this code not using the `datadog.telemetry.HostInfo`?

2023-06-28 12:38 UTC, nikita-tkachenko-datadog commented on dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ModuleExecutionSettingsFactory.java
> +        .runtimeVendor(jvmInfo.getVendor())
Similarly to `Platform`, I missed this class.
And just like with the platform, there's a gotcha: I need the values to fully correspond to the tags that are applied to the test spans (the tags are set in `datadog.trace.civisibility.decorator.TestDecoratorImpl`).
The distinction in this case is in the OS name, which is always taken from the system property for the test spans - in `HostInfo` it is calculated slightly differently.
I could add a new field to the host info (something like `osNameProperty`, I suppose), not sure if this would be better than what I have now.
What do you think?

2023-06-28 12:43 UTC, nikita-tkachenko-datadog commented
It would be ideal of course to just use `Platform` and `HostInfo` as the sources for test span tags, the problem here is all the historical data that already exists in the backend: a history of executions is stored for each test case, and the tags in question are part of the composite test case "ID", so changing the logic that populates the tags will break the history for existing customers :(

2023-06-28 13:25 UTC, bantonsson commented on dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/JvmInfo.java
> +  public static final JvmInfo CURRENT_JVM =
As far as I know, the string in `java.vendor` and `java.vm.vendor` are identical (at least on the handful of JVMs that I just tested with). I hear what you are saying, and maybe consolidating things are not worth it since you don't try to parse out the version components or anything.

2023-06-28 13:47 UTC, nikita-tkachenko-datadog commented on dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ModuleExecutionSettingsFactory.java
> +        .runtimeVendor(jvmInfo.getVendor())
That's a good point, making the dependency more obvious is a good idea. Added the comment.

2023-06-29 09:38 UTC, bantonsson requested changes

2023-06-29 09:38 UTC, bantonsson commented on internal-api/internal-api-9/src/main/java/datadog/trace/util/JDK9ExecutableSupplier.java
> +      log.debug("Cannot get PID through JVM API", e);
This is not the PID.

2023-06-29 09:38 UTC, bantonsson commented on internal-api/src/main/java/datadog/trace/util/ProcessUtils.java
> +  public static String getCurrentExecutablePath() {
Please document/test the different _suprising_ behaviors, not to mention that the `JDK9ExecutableSupplier` will return `null` and not throw an exception. This `null` value would be propagated to the code using this, resulting in a `null` pointer.

2023-06-29 10:08 UTC, nikita-tkachenko-datadog commented on internal-api/internal-api-9/src/main/java/datadog/trace/util/JDK9ExecutableSupplier.java
> +      log.debug("Cannot get PID through JVM API", e);
My bad, poorly done copy-paste.

2023-06-29 10:12 UTC, nikita-tkachenko-datadog commented on internal-api/src/main/java/datadog/trace/util/ProcessUtils.java
> +  public static String getCurrentExecutablePath() {
Updated `JDK9ExecutableSupplier` to throw exception, and documented the fallback strategy which is to return home folder instead of the path.
Now the method will only return `null` if `java.home` System property is not available (which is possible in theory, but I don't think there's a JVM that does not set it).

2023-06-30 07:42 UTC, bantonsson approved these changes

2023-06-30 08:58 UTC, merged