alejandro.gonzalez/test
DataDog/dd-trace-java pull request #5459
Opened 2023-06-23 11:41 UTC by jandro996

# What Does This Do

# Motivation

# Additional Notes

2023-06-26 08:45 UTC, jandro996 commented on dd-java-agent/instrumentation/javax-xml/src/test/groovy/datadog/trace/instrumentation/javax/xml/XPathInstrumentationTest.groovy
> +class XPathInstrumentationTest extends AgentTestRunner {
working in more tests

2023-06-26 09:40 UTC, smola requested changes

2023-06-26 09:40 UTC, smola commented on dd-java-agent/instrumentation/javax-xml/build.gradle
> +  setJavaVersion(it, 8)
Is this really needed? I would say it's the default now.

2023-06-26 09:47 UTC, jandro996 commented on dd-java-agent/instrumentation/javax-xml/src/test/groovy/datadog/trace/instrumentation/javax/xml/XPathInstrumentationTest.groovy
> +class XPathInstrumentationTest extends AgentTestRunner {
done

2023-06-27 03:52 UTC, anderruiz commented on dd-java-agent/instrumentation/javax-xml/src/main/java/datadog/trace/instrumentation/javax/xml/XPathInstrumentation.java
> +    super("java-xml");
java-xpath may be a better name?

2023-06-27 03:56 UTC, anderruiz commented on dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
> +0 com.sun.org.apache.xpath.internal.jaxp.XPathImpl
Why do we need the classes? aren't we using CSI?

2023-06-27 06:05 UTC, jandro996 commented on dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
> +0 com.sun.org.apache.xpath.internal.jaxp.XPathImpl
No, we are using traditional instrumentation

2023-06-27 08:53 UTC, jandro996 commented on dd-java-agent/instrumentation/javax-xml/src/main/java/datadog/trace/instrumentation/javax/xml/XPathInstrumentation.java
> +      if (module != null && !self.getClass().getName().equals("org.apache.xpath.jaxp.XPathImpl")) {
I'm not really confortable with this `!self.getClass().getName().equals("org.apache.xpath.jaxp.XPathImpl")`
This check is needed because `org.apache.xpath.jaxp.XPathImpl` calls internally `com.sun.org.apache.xpath.internal.jaxp.XPathImpl` calling twice module onExpression method

Any suggestions? split it in two Instrumenters?

2023-06-27 11:28 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
> +0 com.sun.org.apache.xpath.internal.jaxp.XPathImpl
I'm not 100% sure if we should use bytebuddy advices here, but if we do it then we must edit our own trie `iast_exclusion.trie` to prevent us from reporting vulnerabilities in `com.sun.org.apache.xpath.internal.jaxp.XPathImpl` or  `org.apache.xpath.jaxp.XPathImpl`

2023-06-27 11:39 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/javax-xml/src/test/groovy/datadog/trace/instrumentation/javax/xml/XPathInstrumentationTest.groovy
> +  private static final String XML_STRING = '<?xml version="1.0" encoding="UTF-8"?>\n' +
You can use [groovy multiline strings](https://groovy-lang.org/syntax.html#_triple_double_quoted_string) for clarity

2023-06-27 11:42 UTC, manuel-alvarez-alvarez commented on dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
> +  public static final String XML_STRING =
Probably better to use an injected resource in the classpath:

```java
@Value("classpath:resource.txt")
private Resource resource;
```

2023-06-27 11:57 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/javax-xml/src/test/groovy/datadog/trace/instrumentation/javax/xml/XPathInstrumentationTest.groovy
> +  void 'evaluate expression calls module onExpression method'() {
You are not testing the exceptional case with `org.apache.xpath.jaxp.XPathImpl`, can you add the dependency to the testing scope and parameterize the test using a `javax.xml.xpath.XPathFactory`?

2023-06-28 08:24 UTC, jandro996 commented on dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
> +0 com.sun.org.apache.xpath.internal.jaxp.XPathImpl
I've changed the approach to CSI, as both of you commented seems to fit better

2023-06-28 08:24 UTC, jandro996 commented on dd-java-agent/instrumentation/javax-xml/src/main/java/datadog/trace/instrumentation/javax/xml/XPathInstrumentation.java
> +      if (module != null && !self.getClass().getName().equals("org.apache.xpath.jaxp.XPathImpl")) {
Not necessary with the CSI approach

2023-06-28 08:24 UTC, jandro996 commented on dd-java-agent/instrumentation/javax-xml/src/test/groovy/datadog/trace/instrumentation/javax/xml/XPathInstrumentationTest.groovy
> +  private static final String XML_STRING = '<?xml version="1.0" encoding="UTF-8"?>\n' +
done

2023-06-28 08:25 UTC, jandro996 commented on dd-java-agent/instrumentation/javax-xml/src/test/groovy/datadog/trace/instrumentation/javax/xml/XPathInstrumentationTest.groovy
> +  void 'evaluate expression calls module onExpression method'() {
done

2023-06-28 12:14 UTC, jandro996 commented on dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
> +  public static final String XML_STRING =
done

2023-06-30 07:37 UTC, smola approved these changes
Looks good to me. Please, check system-tests before merging.

2023-07-03 05:38 UTC, merged