IAST - HSTS missing header vulnerability detection
DataDog/dd-trace-java pull request #5520
Opened 2023-07-04 08:24 UTC by DDJavierSantos

# What Does This Do
Detect and report HSTS header missing vulnerabilities
# Motivation
To cover all of the header vulnerabilities
# Additional Notes

2023-07-04 08:34 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +          System.out.println("!!! Exception " + e);
No println.

2023-07-04 08:34 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +      if (!iastRequestContext.getHstsHeaderIsSet()) {
Let's move this logic to a separate method or class.

2023-07-04 08:34 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +    System.out.println("!!! requestEndedHandler");
No println.

2023-07-04 08:34 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +          ctx.setHstsContentTypeIsHtml();
```suggestion
          ctx.setContentTypeIsHtml();
```

2023-07-04 08:34 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +    if (CONTENT_TYPE_HEADER.equalsIgnoreCase(name)) {
Use `if else`, since only one header can match.

2023-07-04 08:34 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +          ctx.setHstsXForwardedProtoIsHtttps();
```suggestion
          ctx.setXForwardedProtoIsHtttps();
```

2023-07-04 12:49 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +    System.out.println("!!! requestEndedHandler");
removed

2023-07-04 12:49 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +      if (!iastRequestContext.getHstsHeaderIsSet()) {
done

2023-07-04 12:55 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +    if (CONTENT_TYPE_HEADER.equalsIgnoreCase(name)) {
done

2023-07-04 12:58 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +          ctx.setHstsXForwardedProtoIsHtttps();
done

2023-07-04 16:30 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +  static void checkForHstsMissingVulnerability(
I don't think this is the place for checking vulnerabilities, instead we could provide something to let our modules listen to the end request event and do the check in the `HttpResponseHeaderModuleImpl`

2023-07-04 16:31 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +        // do nothing
Don't do that please, at least log it as `debug`/`warn` so we can troubleshoot if something goes wrong.

2023-07-04 16:35 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +      if ("text/html".equalsIgnoreCase(value) || "application/xhtml+xml".equalsIgnoreCase(value)) {
Did you discuss using the appsec `Address<Map<String, List<String>>> RESPONSE_HEADERS_NO_COOKIES`?, I'm pretty sure that we might lose some headers (specially if they are set by the frameworks themselves)

2023-07-04 16:58 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +  static void checkForHstsMissingVulnerability(
That sounds reasonable, but let's keep it simple. For example, I don't think this needs to go to `internal-api` or `InstrumentationBridge` and it should stay within `agent-iast` module boundaries.

2023-07-04 16:59 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +  static void checkForHstsMissingVulnerability(
Yep, I was thinking about something living inside our `IastSystem`

2023-07-07 07:38 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +  static void checkForHstsMissingVulnerability(
Moved this code to HttpResponseHeaderModuleImpl

2023-07-07 07:38 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +        // do nothing
exception logged now

2023-07-07 07:39 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +      if ("text/html".equalsIgnoreCase(value) || "application/xhtml+xml".equalsIgnoreCase(value)) {
After some conversation we think the current design is simpler and will keep it

2023-07-10 14:44 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +    if (HSTS_HEADER.equalsIgnoreCase(name) && !isMaxAgeZero(value)) {
I think `max-age` is mandatory? This only checks that it's positive when it's present?

2023-07-10 14:44 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +      HttpResponseHeaderModuleImpl.checkForHstsMissingVulnerability(
We could probably just call this `checkForHeaderVulnerabilities`, since we need to add at least one more here.

2023-07-11 11:52 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +    if (HSTS_HEADER.equalsIgnoreCase(name) && !isMaxAgeZero(value)) {
Yes, it is mandatory:

2023-07-11 14:13 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-jmxfetch/integrations-core
Be careful with this or you might break the build :cry:

2023-07-11 15:57 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +    if (HSTS_HEADER.equalsIgnoreCase(name) && !isMaxAgeZero(value)) {
But we don't need to validate the header, only detect if it is there, so after some conversation with Santi we are keeping this implementation.

2023-07-11 15:57 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +      HttpResponseHeaderModuleImpl.checkForHstsMissingVulnerability(
Done

2023-07-11 16:11 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastRequestContext.java
> +    this.contentTypeIsHtml = false;
I have changed it so we store the content type string now

2023-07-13 15:34 UTC, smola requested changes

2023-07-13 15:34 UTC, smola commented on dd-java-agent/agent-jmxfetch/integrations-core
Please, see https://github.com/DataDog/dd-trace-java/pull/5522#issue-1787790804

You can prevent this in the future setting this:
```
git config --local submodule.recurse true
```

To fix it in this PR: `git checkout -f origin/master -- dd-java-agent/agent-jmxfetch/integrations-core`

2023-07-13 15:34 UTC, smola commented on dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
> +    response.addHeader("X-Forwarded-Proto", "https");
I'd swear `X-Forwarded-Proto` needs to be set by the caller in the request, not by the app in the response.

2023-07-14 08:09 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +  public static void checkForHeaderVulnerabilities(
You don't need a static method with all the dependencies, you can create an instance one like:

```java
@Override
public void onRequestEnded(final IastRequestContext iastRequestContext, final AgentSpan span) {
   ...
}
```

And call it in the `RequestEndedHandler` via the bridge as usual:

```java
try {
  HttpResponseHeaderModule module = InstrumentationBridge.RESPONSE_HEADER_MODULE;
  if (module != null) {
    module.onRequestEnded(iastRequestContext, (AgentSpan) igSpanInfo);
  }
} catch (Throwable e) {
   LOGGER.error("Failed to handle request ended in headers module", e);
}
```

2023-07-31 11:02 UTC, DDJavierSantos commented on dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
> +    response.addHeader("X-Forwarded-Proto", "https");
Design changed, please check

2023-07-31 11:02 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +  public static void checkForHeaderVulnerabilities(
Design changed, please check

2023-07-31 11:05 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +            iastRequestContext, igSpanInfo, overheadController, reporter);
The `HttpResponseHeaderModule` already has the overhead controller and reported dependencies injected, no need to pass them around.

2023-07-31 11:21 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
> +    HttpResponseHeaderModule mod = InstrumentationBridge.RESPONSE_HEADER_MODULE;
This approach introduces IAST related logic into the tracing advice that doesn't feel right, maybe an API where the request start callbacks can specify headers that they are interested in?

2023-07-31 12:02 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/iast/sink/HttpResponseHeaderModule.java
> +  void onXForwardedProtoHeaderValue(String value);
Can we try to find a different place for this?, the original idea of the module is to deal with response headers.

2023-08-03 11:16 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
> +    HttpResponseHeaderModule mod = InstrumentationBridge.RESPONSE_HEADER_MODULE;
design changed, please check

2023-08-03 11:16 UTC, DDJavierSantos commented on internal-api/src/main/java/datadog/trace/api/iast/sink/HttpResponseHeaderModule.java
> +  void onXForwardedProtoHeaderValue(String value);
design changed, please check

2023-08-07 09:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +      System.out.println(
This should be removed

2023-08-07 09:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +  private final Reporter reporter;
I think this is not needed

2023-08-07 09:44 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestHeaderHandler.java
> +  private static final String X_FORWARDED_PROTO_HEADER = "X-Forwarded-Proto";
Maybe not for this PR, but since we already have a lot of places where we have header names, maybe a headers class that groups all the logic makes sense

2023-08-07 09:45 UTC, manuel-alvarez-alvarez commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +      new Throwable().printStackTrace();
This should be gone

2023-08-07 09:48 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +    final IastRequestContext iastRequestContext = (IastRequestContext) iastRequestContextObject;
Doesn't this make more sense to have a `HstsHeaderModule`, we forced small modules for insecure cookies et all to be able to switch them on/off so it looks weird to me to embed this one inside the response headers module.

2023-08-07 14:25 UTC, DDJavierSantos commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
> +      System.out.println(
removed

2023-08-07 14:26 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
> +  private final Reporter reporter;
removed

2023-08-07 14:26 UTC, DDJavierSantos commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +      new Throwable().printStackTrace();
removed

2023-08-07 14:26 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +    final IastRequestContext iastRequestContext = (IastRequestContext) iastRequestContextObject;
I have added a module named HstsMissingHeaderModule

2023-08-07 18:27 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/build.gradle
> +  excludedClassesBranchCoverage = [
I think we should not ignore coverage for those classes, can you try to test all branches?

2023-08-07 18:29 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java
> +        if (httpStatus == HttpURLConnection.HTTP_MOVED_PERM
This will throw a NPE if there is no status due to unboxing, if the status code is null we should consider as a reportable status code

2023-08-07 18:39 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +    if (value.toLowerCase().contains("max-age=-1")) {
Why only `0` and `-1`? Maybe we can cover all cases with a regexp (like `max-age`, `max-age=`, `max-age=-2`):

```java
  private static final Pattern MAX_AGE = Pattern.compile("max-age=(\\d+)", Pattern.CASE_INSENSITIVE);

  private static boolean isValidMaxAge(@Nullable final String value) {
    if (value == null) {
     return false;
    }
    final Matcher matcher = MAX_AGE.matcher(value);
    if (!matcher.find()) {
      return false;
    }
    return Integer.parseInt(matcher.group(1)) > 0;
  }

```

And probably it will be a better approach to move this code to the HSTS module rather than here.

2023-08-07 18:39 UTC, manuel-alvarez-alvarez approved these changes

2023-08-08 11:07 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java
> +        if (httpStatus == HttpURLConnection.HTTP_MOVED_PERM
fixed

2023-08-08 11:07 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/build.gradle
> +  excludedClassesBranchCoverage = [
fixed

2023-08-08 11:08 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
> +    if (value.toLowerCase().contains("max-age=-1")) {
I'd rather have a simple comparison rather than a regex for performance reasons. I have moved the function to the Hsts module.

2023-08-08 15:58 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java
> +    if (value.toLowerCase().contains("max-age=0")) {
Fair enough if you don't want to use regexps but don't duplicate the `toLowerCase`, we are still missing cases like `max-age=012345` (not sure if we will ever find it though)

2023-08-08 15:58 UTC, manuel-alvarez-alvarez approved these changes

2023-08-09 09:25 UTC, smola requested changes
One small change, then good to go.

2023-08-09 09:25 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java
> +        LOGGER.error("Exception while checking for hsts vulnerability", e);
```suggestion
        LOGGER.debug("Exception while checking for missing HSTS headers vulnerability", e);
```

Changed to debug. If this turns out to happen too often, we don't want to spam the logs.

2023-08-09 09:25 UTC, smola approved these changes
Applied the change myself.

2023-08-09 09:28 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java
> +    if (value.toLowerCase().contains("max-age=0")) {
Well, max-age=012345 is still not zero so the function will work as intended. About the duplication of toLowerCase, it is fixed now.

2023-08-09 15:56 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java
> +        LOGGER.error("Exception while checking for hsts vulnerability", e);
applied

2023-08-09 18:06 UTC, merged