Add initial version of tracer benchmarks
DataDog/dd-trace-java pull request #5604
Opened 2023-07-19 17:43 UTC by manuel-alvarez-alvarez

# What Does This Do

# Motivation

# Additional Notes

2023-07-31 07:17 UTC, smola requested changes
Good job!
The PR commenter should have one or more collapsibles to avoid too long comments by default.

2023-07-31 09:24 UTC, manuel-alvarez-alvarez commented on .gitlab/benchmarks.yml
> +    - git clone --depth 1 --branch malvarez/dd-trace-java https://github.com/DataDog/benchmarking-platform.git /platform && cd /platform
Branch name will be adapted when the [benchmarking-platform](https://github.com/DataDog/benchmarking-platform.git) PR is merged

2023-07-31 10:20 UTC, manuel-alvarez-alvarez commented
> Good job! The PR commenter should have one or more collapsibles to avoid too long comments by default.

Done, now it has collapsibles :wink:

2023-07-31 11:29 UTC, smola commented on .gitlab/benchmarks.yml
> +    - git clone --branch malvarez/dd-trace-java https://github.com/DataDog/benchmarking-platform.git /platform && cd /platform
Reminder:  Change this to the final branch.

2023-07-31 11:29 UTC, smola commented on benchmark/load/petclinic/benchmark.json
> +    "iast_FULL": {
Can we add a `iast_inactive` variant? With `-Ddd.iast.enabled=inactive`? (assuming it does work)

2023-07-31 11:29 UTC, smola commented on benchmark/utils/update-java-version.sh
> +#!/usr/bin/env bash
Nitpick:
```
#!/usr/bin/env bash
set -eu
```

These are not needed (and can be confusing) if the file is meant to be sourced. In particular, `set -eu` in a sourced file could interfere with options set by the main script.

2023-07-31 11:49 UTC, manuel-alvarez-alvarez commented on benchmark/load/petclinic/benchmark.json
> +    "iast_FULL": {
Yep done, it seems to work fine according to the logs: `"iast_enabled":"ENABLED_INACTIVE"`

2023-08-01 07:27 UTC, manuel-alvarez-alvarez commented on benchmark/utils/update-java-version.sh
> +#!/usr/bin/env bash
Changed, thanks for the input!

2023-08-01 08:07 UTC, smola approved these changes

2023-08-01 08:07 UTC, smola commented on benchmark/benchmarks.sh
> +readonly SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
```suggestion
readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
```

Just in case there is a space in the parent path.

2023-08-01 10:10 UTC, manuel-alvarez-alvarez commented on benchmark/benchmarks.sh
> +readonly SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
Thanks! fixed :smile:

2023-08-01 14:06 UTC, bantonsson commented
Just out of curiosity. How long does the benchmark runs take? I see the automatic comments showing up hours after the commit.

2023-08-01 14:44 UTC, manuel-alvarez-alvarez commented
> Just out of curiosity. How long does the benchmark runs take? I see the automatic comments showing up hours after the commit.

The whole run of the benchmark stage takes around 51 minutes (it's accessible from the gitlab benchmark CI check), but it's true that the comments are taking a bit too long to appear (I'll dig into it)

2023-08-02 07:35 UTC, smola commented on benchmark/Dockerfile
> +FROM openjdk:17-slim as petclinic
Note that this image is deprecated. `eclipse-temurin:11-jre-focal` is the new thing.

2023-08-02 08:40 UTC, manuel-alvarez-alvarez commented on benchmark/Dockerfile
> +FROM openjdk:17-slim as petclinic
Thanks for the hint!, I've migrated the jdk images

2023-08-04 08:58 UTC, merged