[DSM] Context Propagation for SQS
DataDog/dd-trace-java pull request #5637
Opened 2023-07-25 14:54 UTC by shethhriday29

# What Does This Do

# Motivation

# Additional Notes

2023-07-27 19:11 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/build.gradle
> +  compileOnly group: 'software.amazon.awssdk', name: 'sns', version: '2.2.0'
could you remove all these whitespace-only changes, thanks :)

I believe the only changes left would then be in the SQS module

2023-07-28 09:33 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/build.gradle
> +  }
these changes should no longer be necessary now the code has moved to the SQS module?

2023-07-28 09:33 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/build.gradle
> +  compileOnly group: 'software.amazon.awssdk', name: 'sns', version: '2.2.0'
these changes should no longer be necessary now the code has moved to the SQS module?

2023-07-28 10:05 UTC, PerfectSlayer requested changes
Hi, I left a bunch of comments about questions and minor changes but it feels like the feature need some refactoring about context propagation. If you think you will need help with it, feel free to ping me.

Moreover, did you expect to change `integration-core`?

2023-07-28 10:05 UTC, PerfectSlayer commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/URIUtils.java
> +      path = path.replaceAll("^/|/$", "");
Is this only to remove leading or last `/`?
If yes, please consider `substring()` for performance rather than regexp (moreover, you can merge it with the next `substring` too)

2023-07-28 15:04 UTC, PerfectSlayer commented
I checked at the new test file and I think it would be better if we don't duplicate the whole test suite:

1. There is already a DSM flag (`isDataStreamEnabled()`)
2. Simply create two new nested classes in `dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy` in which you will override `isDataStreamsEnabled()` to `true`:
    * `SqsClientV0DataStreamsTest`, a copy of `SqsClientV0Test`
    * `SqsClientClientV1DataStreamsForkedTest`, a copy of `SqsClientV1ForkedTest`
 3. You tests changes can be guarded by testing the datastream activation flag (like `injectSysConfig("dd.data.streams.enabled", "true")`)
 4. You can disable JMS tests when the DataStreams flag is missing using framework annotations like `@Requires` ([doc](https://spockframework.org/spock/docs/2.3/all_in_one.html#_requires)) or `@IgnoreIf`

Avoid duplication should make the whole test suite easier to maintain even if it will get slightly more complex by introducing some DataStreams guards. I hope it answers your questions about dealing with tests.

2023-07-31 10:50 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/build.gradle
> +  implementation project(path: ':dd-java-agent:agent-bootstrap')
you shouldn't need to declare this as a dependency

2023-07-31 10:57 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsExecutionAttribute.java
> +public class AwsExecutionAttribute {
Looking over the codebase I found a better way to share this attribute - there's a similar issue in the undertow instrumentation and the solution there is to use the `InstanceStore` which uses `ClassValue` to share instances across instrumentations that can see the same shared type.

To use this approach move this back into `TracingExecutionInterceptor.java` and replace:
```
  public static final ExecutionAttribute<AgentSpan> SPAN_ATTRIBUTE =
      new ExecutionAttribute<>("DatadogSpan");
```
with:
```
  public static final ExecutionAttribute<AgentSpan> SPAN_ATTRIBUTE =
      InstanceStore.of(ExecutionAttribute.class).putIfAbsent(
          "DatadogSpan", new ExecutionAttribute<>("DatadogSpan"));
```

You can then use the same approach in the other interceptor:
```
  public static final ExecutionAttribute<AgentSpan> SPAN_ATTRIBUTE =
      InstanceStore.of(ExecutionAttribute.class).putIfAbsent(
          "DatadogSpan", new ExecutionAttribute<>("DatadogSpan"));
```
which will then share the same `ExecutionAttribute` across both interceptors, even when they are in different instrumentations.

2023-07-31 10:58 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsClientInstrumentation.java
> +        "software.amazon.awssdk.services.sqs.model.SendMessageBatchResponse", "java.lang.String");
you don't need to declare this here because your instrumentation doesn't use this context-store

2023-07-31 11:03 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsInterceptor.java
> +    if (Config.get().isDataStreamsEnabled()) {
I would move this check into `AwsSqsBuilderAdvice` and only add the interceptor when `isDataStreamsEnabled` is `true` - that way you'd avoid incurring the cost of the interceptor when data-streams is not enabled.

2023-07-31 18:33 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AbstractAwsClientInstrumentation.java
> +      packageName + ".AwsExecutionAttribute",
`AwsExecutionAttribute` can now be removed from here

2023-07-31 18:34 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsExecutionAttribute.java
> +public class AwsExecutionAttribute {
`AwsExecutionAttribute` can now be removed

2023-07-31 18:34 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/AbstractSqsClientInstrumentation.java
> +      packageName + ".SqsInterceptor", "datadog.trace.instrumentation.aws.v2.AwsExecutionAttribute",
`AwsExecutionAttribute` can now be removed from here

2023-07-31 19:05 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
> +          "DatadogSpan", new ExecutionAttribute<>("DatadogSpan"));
since AWSv2 is checking uniqueness in the constructor you'll need to change this to:
```
      InstanceStore.of(ExecutionAttribute.class).putIfAbsent(
          "DatadogSpan", () -> new ExecutionAttribute<>("DatadogSpan"));
```
in both places.

2023-08-01 10:45 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AbstractAwsClientInstrumentation.java
> +      packageName + ".AwsSdkClientDecorator", packageName + ".TracingExecutionInterceptor",
remove this stray comma

2023-08-01 10:47 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
> +import spock.lang.Requires
`Requires` and `IgnoreIf` are no longer used and should be removed (this will fix one of the failing checks)

2023-08-02 16:16 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/build.gradle
> +  compileOnly project(':dd-java-agent:instrumentation:aws-java-sdk-2.2')
is this still needed?

2023-08-02 16:17 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/AbstractSqsClientInstrumentation.java
> +public abstract class AbstractSqsClientInstrumentation extends Instrumenter.Tracing {
AFAICT this class is only used in one place, so we could just flatten this into `SqsClientInstrumentation`

2023-08-04 06:18 UTC, PerfectSlayer reviewed
Most comments are about performance but my main concern is about creating an empty TagContext everything DSM is enabled.

2023-08-04 06:18 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
> -
Why remove this part? It is included and duplicated in all child classes?

2023-08-04 06:18 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
> +
What about using `@IgnoreIf({ isDataStreamsEnabled() })` instead? It will make things clearer for the test engine.

2023-08-04 06:18 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
> +    }
Same comment about `@IgnoreIf({ isDataStreamsEnabled() })`

2023-08-04 06:18 UTC, PerfectSlayer commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DataStreamContextExtractor.java
> +      extracted = new TagContext();
I think you should avoid returning an empty `TagContext` when no pathway context is extracted.
I am not sure about the consequence but I am not sure all calls to `extract()` ensure the extracted context is valid.

By the way, what was the use case in the first place (where you have DSM context without any extracted header)?

2023-08-04 13:27 UTC, shethhriday29 commented on dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsClientInstrumentation.java
> +      if (Config.get().isDataStreamsEnabled()) {
will confirm with Piotr

2023-08-04 14:32 UTC, PerfectSlayer approved these changes
Thanks for talking into account my comments!

Please squash all your commits into one when you merge 🙏

2023-08-04 19:29 UTC, merged