Netty: block on response
DataDog/dd-trace-java pull request #5650
Opened 2023-07-27 12:45 UTC by cataphract

2023-08-07 10:57 UTC, smola requested changes

2023-08-07 10:57 UTC, smola commented on dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/MaybeBlockResponseHandler.java
> +    final ChannelTraceContext channelTraceContext =
Early short-circuit if AppSec is disabled?

2023-08-07 10:57 UTC, smola commented on dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/MaybeBlockResponseHandler.java
> +    Channel channel = ctx.channel();
Same here, short-circuit for AppSec disabled?

2023-08-16 17:20 UTC, cataphract commented on dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/MaybeBlockResponseHandler.java
> +    final ChannelTraceContext channelTraceContext =
I added an early check for `requestContext.getData(RequestContextSlot.APPSEC) == null`. Checking `ActiveSubsystems.APPSEC_ACTIVE` is not really appropriate because the boolean could have been flipped in the middle of the request. Unfortunately, this still leaves a few operations in the beginning.

2023-08-18 09:53 UTC, smola commented on dd-java-agent/instrumentation/netty-3.8/src/test/groovy/datadog/trace/instrumentation/netty38/Netty38ServerTest.groovy
> +    false
Why would this be `false` now?

2023-08-21 10:11 UTC, smola approved these changes

2023-08-24 13:33 UTC, merged