Upgrade to ddprof 0.69.0
DataDog/dd-trace-java pull request #5676
Opened 2023-08-03 16:03 UTC by richardstartin

# What Does This Do

Bug fix for a crash when determining the execution state of non-Java threads

# Motivation

# Additional Notes

2023-08-03 20:02 UTC, mcculls approved these changes

2023-08-04 07:35 UTC, jbachorik requested changes
I think this need to be 0.70.0
There was a superfluous 0.69.0 release due to switch to open-source repo train but the version containing the fix is 0.70.0 (https://github.com/DataDog/java-profiler/releases/tag/v_0.70.0)

2023-08-04 07:36 UTC, jbachorik commented on gradle/dependencies.gradle
> +    ddprof        : "0.69.0",
```suggestion
    ddprof        : "0.70.0",
```

2023-08-04 09:20 UTC, jbachorik approved these changes

2023-08-04 10:34 UTC, merged