[DSM] - Better KStreams support
DataDog/dd-trace-java pull request #5697
Opened 2023-08-08 19:07 UTC by kr-igor

# What Does This Do
This PR fixes context propagation for DSM in the case of KStreams.

# Motivation
KStreams is currently supported by DSM only partially. Users can see topics and produce / consume operations, however, the context propagation is broken. The reason is that a single message may be passing multiple instances of the processor application and the context is inject to headers only on produce.

Moreover, must of the customers express interests only in topics they actually create, not system topics. DSM filters out data related to KStreams internal topics while serving requests. 

This PR adds instrumentation for TopologyBuilder, allowing to build a StreamingContext. DSM checkpoints will be set differently, depending on the StreamingContex. This allows us to fully rely on Kafka headers for context propagation. 

Topology without the change:

Topology with the change:
<img width="562" alt="Screenshot 2023-08-08 at 2 03 34 PM" src="https://github.com/DataDog/dd-trace-java/assets/21974069/efbcd23b-cc39-4ec1-919b-81de65ed7e7b">

# Additional Notes

2023-10-30 12:49 UTC, PerfectSlayer requested changes
There are several issues with:
* Context injection not using the propagation API,
* Instrumentations might need to be refactored for common code reuse and proper min version requirements,
* CI tests are failing,
* sub-module change must be reverted.

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-java-agent/agent-jmxfetch/integrations-core
> +Subproject commit 9adcfbec547a9e5aa39cf3bd9235a84ff1772ebd
Can you revert this change?

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
> +              PathwayContext pathwayContext = span.context().getPathwayContext();
Why don't you use the `propage().injectPathwayContext()` instead?

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-streams-0.11/build.gradle
> +  compileOnly group: 'org.apache.kafka', name: 'kafka-streams', version: '1.0.0'
You can't change the minimal version required.
It will break the support contract of the instrumentation.

What are you trying to acchieve with this change?

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
> +            pathwayContext.injectBinary(record, SR_GETTER_SETTER);
Same question about propagation API?

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
> +            pathwayContext.injectBinary(record, PR_GETTER_SETTER);
Same question about propagation API?

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/ProcessorRecordContextVisitor.java
> +        AgentPropagation.BinarySetter<ProcessorRecordContext> {
I would create a dedicated class. 
You don't expect a `ProcessorRecordContextVisitor` to be a `BinarySetter`

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/StampedRecordContextVisitor.java
> +        AgentPropagation.BinarySetter<StampedRecord> {
Same remark about creating a dedicated class.

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/StreamingContextUpdater.java
> +    StreamingContext.registerTopics(topology.sourceTopics(), topology.sinkTopics(), internalTopics);
Can you refactor the instrumentation to create a proper common module to `kafka-clients` and `kafka-streams`?

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +  public <C> void injectBinary(C carrier, BinarySetter<C> setter) {
Isn't the role of `datadog.trace.core.datastreams.DataStreamContextInjector`?

2023-10-30 12:49 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/InternalTopologyBuilderInstrumentation.java
> +    return "org.apache.kafka.streams.processor.internals.InternalTopologyBuilder";
You might need to start a dedicated instrumentation module for this instrumentation.

2023-10-30 20:49 UTC, kr-igor commented on dd-java-agent/agent-jmxfetch/integrations-core
> +Subproject commit 9adcfbec547a9e5aa39cf3bd9235a84ff1772ebd
Will do, thanks for noticing!

2023-10-30 20:55 UTC, kr-igor commented on dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
> +              PathwayContext pathwayContext = span.context().getPathwayContext();
`injectPathwayContext` will additionally set a DSM checkpoint (which is not really obvious judging by the function name). In this case we just need to carry the context forward, without setting the checkpoint.

2023-10-30 21:01 UTC, kr-igor commented on dd-java-agent/instrumentation/kafka-streams-0.11/build.gradle
> +  compileOnly group: 'org.apache.kafka', name: 'kafka-streams', version: '1.0.0'
I though the compile time dependency should not affect the instrumentation itself. I updated this version to reference `InternalTopologyBuilder` which was added in 1.0. 

I will roll this back and extract the topology processor to a separate instrumentation common for both clients.

2023-10-30 21:01 UTC, kr-igor commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/ProcessorRecordContextVisitor.java
> +        AgentPropagation.BinarySetter<ProcessorRecordContext> {
Makes sense, thank you.

2023-10-30 21:01 UTC, kr-igor commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/StreamingContextUpdater.java
> +    StreamingContext.registerTopics(topology.sourceTopics(), topology.sinkTopics(), internalTopics);
Yes, will do

2023-11-08 22:44 UTC, kr-igor commented
Addressed all of the comments above. Failing checks are not related to this PR. @PerfectSlayer please, re-review.

2023-11-15 14:35 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-streams-1.0/build.gradle
> +  //
Can the commented code be removed?

2023-11-15 19:28 UTC, kr-igor commented on dd-java-agent/instrumentation/kafka-streams-1.0/build.gradle
> +  //
Sure, removed it.

2023-11-29 15:58 UTC, PerfectSlayer approved these changes
Thanks for all the changes.
It looks good to me but I saw the release grew in size. Any particular reason from this PR?

2023-11-29 15:58 UTC, PerfectSlayer commented on dd-java-agent/build.gradle
> +    def megs = (project.rootProject.hasProperty("agentIncludeCwsTls") && agentIncludeCwsTls) ? 29 : 28
Is this going to be a problem @bantonsson ?

2023-11-29 16:05 UTC, kr-igor commented
> Thanks for all the changes. It looks good to me but I saw the release grew in size. Any particular reason from this PR?

I merged the changes in from `master` and this test started to fail. I didn't add much with my PR, so I presume this is the straw that broke the camel's back... I can try to lower the limit a bit, adding a few KB, not a MB if that's better.

2023-11-29 16:24 UTC, PerfectSlayer commented
> I didn't add much with my PR, so I presume this is the straw that broke the camel's back... 

That is what I thought too but I didn't see the other PRs failing (where most of them should also add some KB too).
I will reach out the team to be sure we are okay 😉

2023-11-29 18:05 UTC, kr-igor commented
I will be merging this PR in, since the same size-related change was just merged in https://github.com/DataDog/dd-trace-java/pull/6274

2023-11-29 18:07 UTC, merged