Reduce log level for WAF timeouts
DataDog/dd-trace-java pull request #5733
Opened 2023-08-16 18:32 UTC by cataphract

2023-08-16 19:31 UTC, ValentinZakharov approved these changes

2023-08-17 08:04 UTC, smola requested changes

2023-08-17 08:04 UTC, smola commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
> +        log.info("Timeout calling the WAF", tpe);
```suggestion
        log.debug("Timeout calling the WAF", tpe);
```

@cataphract Let's reduce timeouts to debug level, since they might be spammy in some cases and will be better handled by metrics.

2023-08-24 14:58 UTC, smola approved these changes

2023-08-28 12:30 UTC, merged