Stacktrace leak protection
DataDog/dd-trace-java pull request #5740
Opened 2023-08-19 21:47 UTC by ValentinZakharov

# What Does This Do
Added mechanism, to detect and suppress Stecktrace leaks (enabled by default).
Implemented error handler instrumentation in Tomcat 7+ to catch exceptions before they could be populated to client.
To make it works - the IAST should be enabled `-Ddd.isat.enabled=true`
Suppression can be disabled with the option `-Ddd.iast.stacktrace-leak.suppress=false`

# Motivation
This is an Innovation week project.

# Additional Notes

2023-08-21 16:00 UTC, cataphract requested changes

2023-08-21 16:45 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/StacktraceLeakModuleImpl.java
> +          new Vulnerability(VulnerabilityType.STACKTRACE_LEAK, null, new Evidence(serviceName)));
The evidence is actually shown in the UI. Having the service name there might not be very useful, we could include some information like:

- Actual exception type
- Exception message
- Stack (or just a fragment)

2023-08-25 09:50 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/tomcat-appsec-7/build.gradle
> +  compileOnly group: 'org.apache.tomcat.embed', name: 'tomcat-embed-core', version: '9.0.39'
Thanks. Fixed!

2023-08-25 09:51 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/tomcat-appsec-7/src/main/java/datadog/trace/instrumentation/tomcat7/ErrorReportValueInstrumentation.java
> +      "java.lang.IllegalStateException",
Removed unnecessary classes

2023-08-25 09:51 UTC, ValentinZakharov commented on dd-smoke-tests/appsec/spring-mvc/.gitignore
> +.gradle
Removed, thanks

2023-08-25 09:51 UTC, ValentinZakharov commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/StacktraceLeakModuleImpl.java
> +          new Vulnerability(VulnerabilityType.STACKTRACE_LEAK, null, new Evidence(serviceName)));
I've reworked module as discussed.

2023-08-28 08:23 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/tomcat-appsec-7/src/main/java/datadog/trace/instrumentation/tomcat7/ErrorReportValueAdvice.java
> +          module.onStacktraceLeak(
There's a way to obtain the class and method names for an advice using `@Advice.Origin("#t #m") String typeAndMethodName` (in case this advice is used in other places, but I think it's OK for now ).

2023-10-16 10:02 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/tomcat-appsec-7/src/main/java/datadog/trace/instrumentation/tomcat7/ErrorReportValueAdvice.java
> +          module.onStacktraceLeak(
Done

2023-10-19 13:39 UTC, smola approved these changes

2023-11-02 15:15 UTC, cataphract approved these changes

2023-11-02 15:49 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/StacktraceLeakModuleTest.groovy
> +    module = registerDependencies(new StacktraceLeakModuleImpl())
Be careful before merging the PR, this part has changed and now the injection is done via constructor (sorry for that)

2023-11-02 15:49 UTC, manuel-alvarez-alvarez approved these changes

2023-11-02 15:52 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/StacktraceLeakModuleTest.groovy
> +    module = registerDependencies(new StacktraceLeakModuleImpl())
```suggestion
    module = new StacktraceLeakModuleImpl(dependencies)
```

2023-11-02 15:53 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/StacktraceLeakModuleImpl.java
> +  @Override
```suggestion
  public StacktraceLeakModuleImpl(Dependencies dependencies) {
    super(dependencies);
  }

  @Override
```

2023-11-03 08:16 UTC, smola approved these changes

2023-11-03 08:16 UTC, merged