IAST - Added instrumentation for getRequestURI, getPathTranslated and getPat…
DataDog/dd-trace-java pull request #5814
Opened 2023-08-31 07:38 UTC by DDJavierSantos

# What Does This Do
Added instrumentation for getRequestURI, getPathTranslated and getPathInfo in ServletRequest 

# Motivation
To cover all of the cases where intput needs to be tainted in order to detect vulnerabilities.

# Additional Notes

2023-08-31 10:56 UTC, jandro996 commented on dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletRequestCallSiteTest.groovy
> +  void 'test getRequestURI'() {
Not a big deal but tested method could be parametrised to have one new test instead of three

2023-08-31 10:56 UTC, jandro996 approved these changes

2023-09-01 07:22 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
> +    ctx.getTaintedObjects()
The source `http.request.path.parameter` should be used only for those path fragments that are mapped to variables and as such they always have a nave  (e.g.: `/resource/{id}` where `id` is the name). In your case you can do the following:

- `getPathInfo()` and `getPathTranslated`: use `http.request.path`
- `getRequestURI`: it probably deserves it's own source like `http.request.uri`

2023-09-06 17:14 UTC, DDJavierSantos commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
> +    ctx.getTaintedObjects()
suggestion applied

2023-09-13 07:59 UTC, smola requested changes
On hold until the new source is added to the spec.

2023-09-19 07:02 UTC, smola commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +    if (null != retValue && retValue.length() > 0) {
```suggestion
    if (null != retValue && !retValue.isEmpty()) {
```

2023-09-19 07:02 UTC, smola commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +          module.onUnexpectedException("afterGetRequestURIOrPath threw", e);
```suggestion
          module.onUnexpectedException("afterGetRequestPathInfo threw", e);
```

2023-09-19 07:02 UTC, smola commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +          module.onUnexpectedException("afterGetRequestURIOrPath threw", e);
```suggestion
          module.onUnexpectedException("afterGetRequestURI threw", e);
```

2023-09-19 07:02 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
> +    ctx.getTaintedObjects()
See the above. As far as I see, not applied in the current version.

2023-09-25 15:53 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +    if (null != retValue && retValue.length() > 0) {
applied

2023-09-25 15:53 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +          module.onUnexpectedException("afterGetRequestURIOrPath threw", e);
applied

2023-09-26 08:46 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
> +0 org.springframework.util.*
There are already entries for the package, can you be more specific with the classes you want to be instrumented? (maybe not the whole package is needed)

2023-09-26 13:14 UTC, smola requested changes

2023-09-26 13:14 UTC, smola commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +  @CallSite.After("java.lang.String javax.servlet.http.HttpServletRequest.getPathTranslated()")
`getPathTranslated` and `getPathInfo` seem to be about `http.request.path`, not `http.request.uri`?

2023-09-29 15:42 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +  @CallSite.After("java.lang.String javax.servlet.http.HttpServletRequest.getPathTranslated()")
I added http.request.uri to Sources and use it now

2023-10-02 07:54 UTC, smola requested changes

2023-10-02 07:54 UTC, smola commented on internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
>    private static final byte[] VALUES = {
New sources need to be added here too.

2023-10-02 07:54 UTC, smola commented on internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
> +        return SourceTypes.REQUEST_PATH_STRING;
New sources need to be added here too.

2023-10-02 12:03 UTC, DDJavierSantos commented on internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
>    private static final byte[] VALUES = {
Done

2023-10-02 12:04 UTC, DDJavierSantos commented on internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
> +        return SourceTypes.REQUEST_PATH_STRING;
Done

2023-10-05 16:29 UTC, ygree approved these changes
Looks good to me

2023-10-06 10:18 UTC, smola commented on dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
> +          module.onUnexpectedException("afterGetRequestURI threw", e);
```suggestion
          module.onUnexpectedException("afterGetPathInfo threw", e);
```

2023-10-06 10:19 UTC, smola approved these changes

2023-10-09 07:45 UTC, manuel-alvarez-alvarez approved these changes

2023-10-09 11:42 UTC, merged