Add instrumentation support for Apache Pekko
DataDog/dd-trace-java pull request #5858
Opened 2023-09-08 06:43 UTC by scoquelin

# What Does This Do

This PR adds initial instrumentation support for [Apache Pekko](https://pekko.apache.org/what-is-pekko.html) based on the existing Akka instrumentation

# Motivation
Codebases migrating from Akka (now with closed license) to Apache Pekko will need proper instrumentation support  upfront in order to ensure a smooth transition and seamlessly continue to benefit from APM/tracing in DataDog.

# Additional Notes
Closes #5811

2023-09-08 19:12 UTC, scoquelin commented on dd-java-agent/instrumentation/pekko-http-1.0/build.gradle
> +  //  testImplementation project(':dd-java-agent:instrumentation:scala-promise:scala-promise-2.13')
Noticed that we get test [failures](https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/28926) with `propagate trace id when we ping pekko-http concurrently` locally and on the CI when `scala-promise` instrumentations are enabled so commenting it for now

2023-09-11 12:58 UTC, bantonsson requested changes
Hi @scoquelin and thanks for the contribution. There are two things that popped out during the first pass that would need to be fixed.

2023-09-11 12:58 UTC, bantonsson commented on dd-java-agent/instrumentation/pekko-http-1.0/build.gradle
> +  //  testImplementation project(':dd-java-agent:instrumentation:scala-promise:scala-promise-2.13')
Commenting out that is not really a viable solution since the Scala promise instrumentation is very much enabled in the final product.

From the failures, it looks like 1-2 spans are escaping in some way, which is probably related to the fact that there is no `pekko-concurrent` instrumentation, that does the same things as the `akka-concurrent` one. See this comment in `AkkaActorCellInstrumentation`:
```
  /**
   * This instrumentation is defensive and closes all scopes on the scope stack that were not there
   * when we started processing this actor message. The reason for that is twofold.
   *
   * <p>1) An actor is self contained, and driven by a thread that could serve many other purposes,
   * and a scope should not leak out after a message has been processed.
   *
   * <p>2) We rely on this cleanup mechanism to be able to intentionally leak the scope in the
   * {@code AkkaHttpServerInstrumentation} so that it propagates to the user provided request
   * handling code that will execute on the same thread in the same actor.
   */
```

2023-09-11 12:58 UTC, bantonsson commented on dd-java-agent/instrumentation/pekko-http-1.0/build.gradle
> +  lagomTestMaxJavaVersionForTests = JavaVersion.VERSION_1_8
I don't see any `lagom` tests in this code base.

2023-09-11 16:07 UTC, scoquelin commented on dd-java-agent/instrumentation/pekko-http-1.0/build.gradle
> +  //  testImplementation project(':dd-java-agent:instrumentation:scala-promise:scala-promise-2.13')
Yeah I kind of knew i was not a viable solution but wanted to relay my observations so that I could - hopefully - get just that kind of feedback, now it makes sense, thank you! Initially I thought a `pekko-concurrent` instrumentation would not be necessary but looks like it is ! Will work on that...

2023-09-11 16:08 UTC, scoquelin commented on dd-java-agent/instrumentation/pekko-http-1.0/build.gradle
> +  lagomTestMaxJavaVersionForTests = JavaVersion.VERSION_1_8
Yes forgot to clean up that part after some copy pasta from Akka HTTP instrumentation :grimacing:

2023-09-11 20:51 UTC, scoquelin commented on dd-java-agent/instrumentation/pekko-http-1.0/build.gradle
> +  //  testImplementation project(':dd-java-agent:instrumentation:scala-promise:scala-promise-2.13')
OK so essentially I ported most of `akka-concurrent` to a new `pekko-concurrent` except for the things related to `akka.dispatch.forkjoin.ForkJoinTask` which was removed for Akka `2.6.x` at the time and replaced by `java.util.concurrent` classes alltogether

2023-09-13 09:59 UTC, bantonsson commented on dd-java-agent/instrumentation/pekko-concurrent/src/test/groovy/RejectedExecutionTest.groovy
> +class RejectedExecutionTest extends AgentTestRunner {
This test serves no purpose since it's now testing the `java.util.concurrent.ForkJoinPool` which is tested elsewhere. Please remove it.

2023-09-13 10:01 UTC, bantonsson commented on dd-java-agent/instrumentation/pekko-concurrent/src/test/groovy/PekkoExecutorInstrumentationTest.groovy
> +class PekkoExecutorInstrumentationTest extends AgentTestRunner {
Same thing here. The test is now a duplicate of the `java.util.concurrent.*` tests for this.

2023-09-13 10:01 UTC, bantonsson commented on dd-java-agent/instrumentation/pekko-concurrent/src/test/groovy/ForkJoinPoolPropagationTest.groovy
> +class ForkJoinPoolPropagationTest extends AgentTestRunner {
And this test as well.

2023-09-13 10:06 UTC, bantonsson reviewed
Thanks for fixing the `pekko-concurrent` part as well. All the executor only tests and support classes can be removed, and only the actor tests need to remain.

2023-09-13 14:44 UTC, cataphract commented on dd-java-agent/instrumentation/pekko-http-1.0/build.gradle
> +  latestDepTestImplementation group: 'org.apache.pekko', name: 'pekko-stream_2.13', version: '1.0.1'
unless there's a good reason for it, latestDepTestImplementation should fetch the latest version of the library, using version wildards, like `+`, or `1.+`

2023-09-13 16:25 UTC, scoquelin commented
@bantonsson removed the mentioned tests and @cataphract addressed your feedback regarding latest deps wildcard

2023-09-13 16:33 UTC, scoquelin commented on dd-java-agent/instrumentation/pekko-http-1.0/build.gradle
> +  latestDepTestImplementation group: 'org.apache.pekko', name: 'pekko-stream_2.13', version: '1.0.1'
Thanks for catching this one! :+1:

2023-09-15 14:29 UTC, bantonsson approved these changes
Thanks a lot @scoquelin for the contribution

2023-09-15 14:30 UTC, merged