IAST - bug fix for new clas in spring boot 2.7.5
DataDog/dd-trace-java pull request #5867
Opened 2023-09-11 11:14 UTC by DDJavierSantos

# What Does This Do
Fixes instrumentation for spring boot 2.7.5 

# Motivation
Maintenance bug fix for the new version of spring boot using a new class NonClosingStream that was in the instrumentation exclussion list.

# Additional Notes

2023-09-11 15:24 UTC, smola requested changes

2023-09-11 15:24 UTC, smola commented on dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
> +0 org.springframework.util.*
It's probably better to be more precise, setting this to `0` only for the specific class we want to instrument. Also adding a comment to note it's needed for IAST. See, for example:

https://github.com/DataDog/dd-trace-java/pull/5867/files#diff-c154dcf8283beb4f1b67579ba190f14675ea92fe9fb3a20fa34753468743069cR324-R325

2023-09-12 13:26 UTC, DDJavierSantos commented on dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
> +0 org.springframework.util.*
I have removed the package and added the specific class:

2023-09-12 15:30 UTC, smola commented on dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
> +0 org.springframework.util.StreamUtils$NonClosingInputStream
Please, add a comment stating this is for the IAST instrumenter. Otherwise it's going to be hard figuring out why we need this, since there is no explicit mention to this class in the instrumenters.

2023-09-13 07:55 UTC, smola approved these changes

2023-09-13 09:01 UTC, smola approved these changes
Benchmark looks good now.

2023-09-13 13:50 UTC, mcculls approved these changes

2023-09-13 18:08 UTC, merged