API Security
DataDog/dd-trace-java pull request #5888
Opened 2023-09-14 13:23 UTC by ValentinZakharov

# What Does This Do
Added AppSec Api Security (schema extraction)

2023-09-15 14:37 UTC, nayeem-kamal reviewed
The config changes look good to me. I was just wondering if the new config variables should be included in the config string that is logged at the end of `Config.java` to aid with support when logging is enabled. 
As for the AppSec changes, I don't have much context on the codebase but is there anything in particular you want reviewed by APM Core?

2023-09-22 10:59 UTC, ValentinZakharov commented
@nayeem-kamal, good point! I totally forgot about config logger, thanks.

2023-09-25 11:09 UTC, smola requested changes

2023-09-25 11:09 UTC, smola commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +              log.warn("Unable to commit api security schemes");
```suggestion
              log.warn("Unable to commit api security schemas");
```

What does this mean? When could it happen? Can users do something about it when it happens (AKA do we want an escalation in this scenario)?

2023-09-25 11:09 UTC, smola commented on dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
> +  public static final String API_SECURITY_ENABLED = "experimental.api-security.enabled";
Let's describe these settings and defaults in the PR description (e.g. in additional notes).

2023-09-25 11:09 UTC, smola commented on dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/api/security/ApiSecurityRequestSamplerTest.groovy
> +    DEFAULT_SAMPLE_RATE      | [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  // Default sample rate - 10%
It seems a bit weird that we start by not sampling in the first values, but I guess it does not really matter much.

2023-09-26 12:17 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/resources/default_config.json
> +      "id": "preprocessor-001",
Removed config, because the feature is experimental.

2023-09-26 12:18 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/api/security/ApiSecurityRequestSampler.java
> +      // We don't support disabling IAST by setting it, so we set it to 100%.
Thanks, fixed

2023-09-26 12:22 UTC, ValentinZakharov commented on dd-java-agent/appsec/build.gradle
> +  implementation group: 'io.sqreen', name: 'libsqreen', version: '8.0.0'
Splitted.
Second PR is #5942

2023-09-26 12:24 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +              log.warn("Unable to commit api security schemes");
Switched to `debug`. This error could happen if trace segment or list of collected schemas are `null`. This case should never happen.

2023-09-26 12:24 UTC, ValentinZakharov commented on dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
> +  public static final String API_SECURITY_ENABLED = "experimental.api-security.enabled";
This is experimental feature flag (for internal use). I'm not sure if we should reveal it.

2023-09-27 07:59 UTC, smola commented on dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
> +  public static final String API_SECURITY_ENABLED = "experimental.api-security.enabled";
In the PR description we should. This is all public anyway :wink: 

Even if it's experimental, the PR should explain what this feature is, how it works, how it is configured. It will later be useful for ourselves too.

2023-09-27 21:29 UTC, ValentinZakharov commented on dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
> +  public static final String API_SECURITY_ENABLED = "experimental.api-security.enabled";
Added PR description

2023-09-28 08:36 UTC, smola commented on dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
> +  public static final String API_SECURITY_REQUEST_SAMPLING = "api-security.request-sampling";
I think this was going to be renamed to `_SAMPLE_RATE`? Or that change was not approved?

2023-09-28 09:18 UTC, ValentinZakharov commented on dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
> +  public static final String API_SECURITY_REQUEST_SAMPLING = "api-security.request-sampling";
This is fixed in #5942

2023-09-28 09:50 UTC, smola approved these changes

2023-09-28 11:12 UTC, merged