IAST Multipart instrumentation for Servlet
DataDog/dd-trace-java pull request #5918
Opened 2023-09-20 07:21 UTC by DDJavierSantos

# What Does This Do
Adds instrumentation for Multipart headers so they can be tainted for IAST use

# Motivation
To cover all of the possible tainted object sources.

# Additional Notes

2023-09-20 10:19 UTC, manuel-alvarez-alvarez commented on dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
> +import okhttp3.*
Check the [CONTRIBUTING.md](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md) I think you have the imports badly configured

2023-09-20 10:21 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
This is a `SourceTypes.REQUEST_HEADER_NAME`

2023-09-20 10:26 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/MultipartInstrumentation.java
> +    return "javax.servlet.http.Part";
If I'm not mistaken `javax.servlet.http.Part` was introduced in servlet 3.0 so this instrumentation should be moved to dd-`java-agent/instrumentation/servlet/request-3`

2023-09-20 10:43 UTC, manuel-alvarez-alvarez requested changes

2023-09-20 10:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
```suggestion
    @Source(SourceTypes.REQUEST_HEADER_NAME)
```

2023-09-20 10:43 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +          module.onHeaderNames(Collections.singleton(name));
I think it will be better to use the actual header name containing the name of the part:

```java
      final PropagationModule module = InstrumentationBridge.PROPAGATION;
      if (module != null) {
        try {
          module.taint(SourceTypes.REQUEST_HEADER_VALUE, "Content-Disposition", value);
        } catch (final Throwable e) {
          module.onUnexpectedException("afterGetName threw", e);
        }
      }
      return value;
```

2023-09-20 10:43 UTC, manuel-alvarez-alvarez commented on dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
> +    hasVulnerability { vul -> vul.type == 'XSS' }
Do not rely on vulnerabilities to test sources (if XSS logic breaks this unrelated test will fail too), use:
```suggestion
    hasTainted { tainted ->
      tainted.value == 'theFileName' &&
        tainted.ranges[0].source.name == 'Content-Disposition' &&
        tainted.ranges[0].source.origin == 'http.request.header'
    }
```

2023-09-20 10:44 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/MultipartInstrumentation.java
> +          module.onHeaderNames(Collections.singleton(name));
Same suggestion as in the jakarta one.

2023-09-20 10:44 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/MultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
```suggestion
    @Source(SourceTypes.REQUEST_HEADER_NAME)
```

2023-09-20 12:48 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +          module.onHeaderNames(Collections.singleton(name));
done

2023-09-20 12:49 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/MultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
done

2023-09-20 13:07 UTC, DDJavierSantos commented on dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
> +import okhttp3.*
fixed

2023-09-20 13:20 UTC, DDJavierSantos commented on dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
> +    hasVulnerability { vul -> vul.type == 'XSS' }
fixed

2023-09-20 14:28 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/MultipartInstrumentation.java
> +          module.onHeaderValues("Content-Disposition", Collections.singleton(name));
```suggestion
          module.onHeaderValues(name, Collections.singleton(value));
```

2023-09-20 14:29 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_NAME)
```suggestion
    @Source(SourceTypes.REQUEST_HEADER_VALUE)
```

2023-09-20 15:00 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/MultipartInstrumentation.java
> +    return "javax.servlet.http.Part";
moved

2023-09-20 15:06 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/MultipartInstrumentation.java
> +          module.onHeaderValues("Content-Disposition", Collections.singleton(name));
applied

2023-09-20 15:06 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_NAME)
applied

2023-09-21 08:13 UTC, smola requested changes

2023-09-21 08:13 UTC, smola commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +        named("getName").and(isPublic()), getClass().getName() + "$GetNameAdvice");
Use `takeArguments(0)` (if I recall correctly).

2023-09-21 08:13 UTC, smola commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +        try {
You can remove the try catch in bytebuddy advices. `@Advice.OnMethodExit(suppress = Throwable.class)` already provides exception handling.

2023-09-21 08:13 UTC, smola commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +        @Advice.Return Collection<String> headerValues) {
You don't need this parameter, since you're not modifying the return value, the function can have `void` return.

2023-09-21 08:13 UTC, smola commented on dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
> -    'responseBody' | 'test'
Was this case removed intentionally?

2023-09-22 09:38 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +        named("getName").and(isPublic()), getClass().getName() + "$GetNameAdvice");
added

2023-09-22 09:39 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +          module.onHeaderValues(name, Collections.singleton(name));
```suggestion
          module.onHeaderValues(name, Collections.singleton(value));
```

2023-09-22 09:40 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +    public static String onExit(@Advice.Return final String name) {
As @smola mentioned all return values in bytebuddy advices have a different meaning, you can safely remove all of them and make them void.

2023-09-22 09:41 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
```suggestion
    @Source(SourceTypes.REQUEST_HEADER_NAME)
```

2023-09-22 09:42 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
Did it change? I still see `@Source(SourceTypes.REQUEST_HEADER_VALUE)`

2023-09-22 09:45 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +          module.onHeaderValues(name, Collections.singleton(name));
Applied

2023-09-22 09:45 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
missed this one, applied now

2023-09-22 09:45 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +    public static String onExit(@Advice.Return final String name) {
done

2023-09-22 09:53 UTC, DDJavierSantos commented on dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
> -    'responseBody' | 'test'
It is removed in master, so after merging it wil not matter. In any case I have reverted it for the sake of clarity.

2023-09-26 06:17 UTC, jandro996 commented on log.txt
I think this file should be deleted

2023-09-26 12:16 UTC, DDJavierSantos commented on log.txt
Deleted

2023-09-28 06:44 UTC, manuel-alvarez-alvarez approved these changes

2023-10-02 07:20 UTC, manuel-alvarez-alvarez requested changes

2023-10-02 07:20 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
> +  public static final String REQUEST_MULTIPART_HEADER_STRING = "http.request.multipart.parameter";
If we are going to introduce a new source type then we have to revisit the annotations of the advices in this PR, as they are annotated with:

- `@Source(SourceTypes.REQUEST_HEADER_VALUE)`
- `@Source(SourceTypes.REQUEST_HEADER_NAME)`

2023-10-03 08:51 UTC, DDJavierSantos commented on internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
> +  public static final String REQUEST_MULTIPART_HEADER_STRING = "http.request.multipart.parameter";
done

2023-10-04 10:24 UTC, smola approved these changes
Good to go once system-tests are ready.

2023-10-04 11:55 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
```suggestion
    @Source(SourceTypes.REQUEST_MULTIPART_PARAMETER)
```

2023-10-04 11:55 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_NAME)
```suggestion
    @Source(SourceTypes.REQUEST_MULTIPART_PARAMETER)
```

2023-10-04 11:55 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
```suggestion
    @Source(SourceTypes.REQUEST_MULTIPART_PARAMETER)
```

2023-10-04 12:47 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
fixed

2023-10-04 12:47 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
fixed

2023-10-04 12:47 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
fixed

2023-10-04 12:47 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
fixed

2023-10-04 12:47 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_NAME)
fixed

2023-10-04 12:47 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
> +    @Source(SourceTypes.REQUEST_HEADER_VALUE)
fixed

2023-10-05 11:24 UTC, manuel-alvarez-alvarez approved these changes

2023-10-05 18:47 UTC, merged