Update IAST vulnerability hash
DataDog/dd-trace-java pull request #5926
Opened 2023-09-21 07:15 UTC by jandro996

# What Does This Do

# Motivation

# Additional Notes

2023-09-21 08:17 UTC, smola commented on dd-java-agent/agent-iast/build.gradle
> +  implementation project(':dd-trace-core')
I think this dependency might lead to duplicated classes in the jar? Needs to be checked.

2023-09-21 08:23 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java
> +              span, new Vulnerability(VulnerabilityType.HSTS_HEADER_MISSING, getServiceName(span)));
The span can be null for vulnerabilities not inside a request, can we delay this further down the line? (since we will have the newly created span later on)

2023-09-21 08:52 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/SinkModuleBase.java
> +      if (context instanceof DDSpanContext) {
With `MutableSpan` you can have access to the service name without the new dependency

2023-09-22 05:28 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java
> +              span, new Vulnerability(VulnerabilityType.HSTS_HEADER_MISSING, getServiceName(span)));
current implementation updated the vulnerability with the new span before report it, check dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java

this suits you?

2023-09-26 07:53 UTC, manuel-alvarez-alvarez requested changes
There are some methods `HttpResponseHeaderModuleImpl` that are not reporting the service name, I thing we should sightly update the PR to the following:

1. Move the service name to the location class
2. Change the method `Location.forSpanAndStack(long spanId, StacktraceElement stack)` to `Location.forSpanAndStack(AgentSpan span, StacktraceElement stack)` and extrac the span id and service name from there.
3. Make sure that all vulnerabilities are created with a non null location.

2023-09-27 10:57 UTC, smola approved these changes

2023-10-02 07:16 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Vulnerability.java
> +        hash = type.calculateHash(this);
It might be more future proof to always recalculate the hash, but it's OK for me.

2023-10-02 07:16 UTC, manuel-alvarez-alvarez approved these changes

2023-10-02 09:30 UTC, merged