track payload size for messaging integrations
DataDog/dd-trace-java pull request #6045
Opened 2023-10-13 09:51 UTC by vandonr

Jira ticket: [AIT-8557]

2023-10-13 11:13 UTC, vandonr commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
> +  private static long computePayloadSizeBytes(ConsumerRecord<?, ?> val) {
this code is duplicated from the instrumentation for kafka_clients, but I don't really know where to put it to share it between the two integrations

2023-10-13 11:13 UTC, vandonr commented on dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
> +      // else no idea how to handle the value, don't compute size.
didn't know how to handle `Object` so I took inspiration from how it's done in .net
https://github.com/DataDog/dd-trace-dotnet/blob/a0f98c75c25e195c39bd53157ad2a138128ac159/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/RabbitMQ/RabbitMQIntegration.cs#L92-L116

2023-10-13 11:13 UTC, vandonr commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
> +      long payloadSizeBytes) {
maybe it'd make sense to make this new parameter optional given how many places I had to put zero.

2023-10-13 11:17 UTC, vandonr commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
> +            .setCheckpoint(span, sortedTags, record.timestamp(), 0);
This one, the version `27` of the method, has a type that does't expose much (`ProcessorRecordContext`), so I didn't see how to compute the payload size for this.

2023-10-13 12:10 UTC, vandonr commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/StatsPoint.java
> +    this.payloadSizeBytes = payloadSizeBytes;
I still have to propagate this somewhere where it'll be sent to DD

2023-10-13 12:12 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
> +      long payloadSizeBytes) {
I would probably have left the original method signature since it's public. Instead, you can create another signature with also this parameter so it won't create signature mismatches.

2023-10-13 12:24 UTC, amarziali commented on dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
> +        headersSize += h.value().length + h.key().getBytes().length;
looking on kafka-clients code (in the part where the headers are written):
```
            byte[] utf8Bytes = Utils.utf8(headerKey);
```
So the key (that's a string in java) it's assumed to be encoded in UTF8. In this charset, generally speaking, the length of a string is not equal to the number of bytes needed to encode it

2023-10-13 12:25 UTC, vandonr commented on dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
> +        headersSize += h.value().length + h.key().getBytes().length;
Yeah ok, I just need to specify the UTF8 encoding as a parameter of `getBytes` then

2023-10-13 12:29 UTC, amarziali commented on dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
> +        .setCheckpoint(span, SERVER_PATHWAY_EDGE_TAGS, 0, 0);
If you don't know the payload size (or if you don't need to calculate for some integrations) what should be reported as payload statistics? 0 or just nothing? Since in this case the semantic to use on the API is different.

2023-10-13 12:31 UTC, vandonr commented on dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
> +        .setCheckpoint(span, SERVER_PATHWAY_EDGE_TAGS, 0, 0);
I think we can register it as zero internally, and then exclude zeros in the reporting code since I don't think a payload of size zero is a realistic value (given the fact that we consider headers)

2023-10-13 15:59 UTC, tabgok commented on dd-java-agent/instrumentation/armeria-grpc/src/main/java/datadog/trace/instrumentation/armeria/grpc/server/TracingServerInterceptor.java
> +        .setCheckpoint(span, SERVER_PATHWAY_EDGE_TAGS, 0, 0);
The focus is on Kafka for now, so I believe gRPC can be put aside for now.

2023-10-13 15:59 UTC, vandonr commented on dd-java-agent/instrumentation/armeria-grpc/src/main/java/datadog/trace/instrumentation/armeria/grpc/server/TracingServerInterceptor.java
> +        .setCheckpoint(span, SERVER_PATHWAY_EDGE_TAGS, 0, 0);
yes I realized that later :p

2023-10-13 17:40 UTC, kr-igor commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
> +            .setCheckpoint(span, sortedTags, record.timestamp(), 0);
I believe you can get precise size by using `serializedKeySize+serializedValueSize` from `RecordMetadata` (ProcessorRecordContext is inherited from it)
https://github.com/a0x8o/kafka/blob/54eff6af115ee647f60129f2ce6a044cb17215d0/clients/src/main/java/org/apache/kafka/clients/producer/RecordMetadata.java#L112

2023-10-16 13:10 UTC, vandonr commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
> +            .setCheckpoint(span, sortedTags, record.timestamp(), 0);
Ha, so this is troubling, the inheritance of `RecordMetadata` was added in https://github.com/apache/kafka/commit/69790a1463bafc1f63e3c288a6636b3f4586c1b4#diff-85c25edc2dbc410907fe3d4706dc5799005e0e70950af191ce8a4d70dbf3f650L32
which was merged 3 years ago. 
However, the jar I have in my local project, which was resolved by gradle I think, is kafka-streams 0.11 from Jun 22, 2017. I suppose this is because that's the minimal version we're supporting ?

What should we do from there ? Can we bump the version ? How can we do something where clients get the size only if they have a more recent kafka ?

2023-10-16 13:11 UTC, vandonr commented on dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
> +            .setCheckpoint(span, sortedTags, record.timestamp(), 0);
If I judge just from the dates, that inheritance should be there for versions >= 2.6.1

2023-10-19 11:21 UTC, PerfectSlayer commented
Context? Goal? Description?

2023-10-19 11:45 UTC, vandonr commented
> Context? Goal? Description?

I added a little paragraph in the description, but I don't have a whole lot of info to add.

2023-10-24 08:36 UTC, PerfectSlayer requested changes
One change request for internal tracer API.
I will let the two other default reviewiers review the PR.

2023-10-24 08:36 UTC, PerfectSlayer commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentDataStreamsMonitoring.java
> +
Can you avoid overloading this method? (not creating a duplicate with different parameters)
It is usually a good practice but we already have too many methods in the _tracer_ classes.

There are less than 10 different calls for those methods so it will be fine to add 0 as last default parameter in all calls. Thanks! 

Note: It's fine in `PathwayContext` as it will only impact DSM object only 👌

2023-10-24 08:36 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/Utils.java
> +public class Utils {
What about making the class final with a private constructor?

2023-10-24 09:33 UTC, vandonr commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentDataStreamsMonitoring.java
> +
hmm ok, the initial reasoning was that since this code is in `/api/` we wanted to avoid breaking changes to the interfaces.

2023-10-24 13:54 UTC, PerfectSlayer commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentDataStreamsMonitoring.java
> +
You are inside `internal-api`. So it is safe to change it if you take care of other teams relying on it (only DSM here). Thanks for caring 🙏

2023-10-27 13:24 UTC, PerfectSlayer reviewed
Thanks for the API edition

2023-10-27 15:30 UTC, kr-igor approved these changes
LGTM

2023-10-30 08:50 UTC, amarziali commented on dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
> +          .setCheckpoint(span, sortedTags, produceMillis, 0);
Nit: since you have the signature without the payload size you can just use it (and leave that class unchanged). It will generate a smaller diff (the same applied for all the other decorators)

2023-10-30 08:51 UTC, amarziali approved these changes
Looks ok. I left a comment. Please let apm-java also review that PR

2023-10-30 08:52 UTC, vandonr commented on dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
> +          .setCheckpoint(span, sortedTags, produceMillis, 0);
no I don't have it anymore, @PerfectSlayer asked in https://github.com/DataDog/dd-trace-java/pull/6045#discussion_r1369804322 that I remove it !

2023-10-30 09:38 UTC, PerfectSlayer approved these changes
LGTM

2023-10-30 09:38 UTC, PerfectSlayer commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/StatsGroup.java
> +    if (payloadSizeBytes != 0) payloadSize.accept((double) payloadSizeBytes);
I don't even know spotless would agree to use such kind of one-liner... 🤔

2023-10-31 10:17 UTC, merged