Implement extra_services for remote config
DataDog/dd-trace-java pull request #6130
Opened 2023-11-02 10:52 UTC by jandro996

# What Does This Do

Add  extraService field to RemoteConfigRequest with all the different service names in the spans

New ExtraServiceProvider to manage extra services that satisfies the next conditions:

- Limited to 64 elements
- New service name can be added if its different from the global one, is not null and is not in the current list
- When comparing service names, it should be don in a case-insensitive manner
- if the list is empty it should return null

It has been decided to attempt adding a new extra service when the span will be finished. This approach is used by other languages like dotNet. Any suggestions from @DataDog/apm-java ?

# Motivation

Knowing all service names used by a tracer instances help the UI give better feedback to the user.
The agent version v7.46.0 contains an new field "extra_services" in the remote config client, that allows clients to list any additional services that are used within tracer spans.

# Additional Notes

Jira ticket: [APPSEC-9907]

2023-11-03 07:40 UTC, smola commented on remote-config/src/main/java/datadog/remoteconfig/state/ExtraServicesProvider.java
> +      log.debug(
Once we hit the limit, we'll be logging this for all closed spans, which is excessive. Maybe it should be logged just once.

2023-11-08 14:55 UTC, manuel-alvarez-alvarez commented on remote-config/src/main/java/datadog/remoteconfig/tuf/RemoteConfigRequest.java
> +          String[] extraServices,
I'll rather use a `List<String>` so we don't have to convert to array and it mimics the `List<String> tags` property.

2023-11-08 15:43 UTC, manuel-alvarez-alvarez commented on remote-config/src/main/java/datadog/remoteconfig/state/ExtraServicesProvider.java
> +  private static final ConcurrentHashMap<String, String> extraServices = new ConcurrentHashMap<>();
I'm not a super fan of static sateful classes (e.g. they are usually a source of flaky tests). 

If we remove static attributes and add a field of type `datadog.remoteconfig.state.ExtraServicesProvider` to `datadog.trace.core.CoreTracer` we can have a better design:
```mermaid
classDiagram
    CoreTracer 
    DDSpanContext .. CoreTracer
    DDSpan .. DDSpanContext
    SharedCommunicationObjects .. CoreTracer
    ConfigurationPoller .. SharedCommunicationObjects
    PollerRequestFactory .. ConfigurationPoller

    class CoreTracer{
      -ExtraServicesProvider extraServices
    }

    class DDSpanContext{
      +maybeAddService(String serviceName)
    }

    class DDSpan{
    }

    class SharedCommunicationObjects{
    }

    class ConfigurationPoller {
    }

    class PollerRequestFactory {
    }
```

PS: Has it ever been discussed in the tracer the usage of something like [Dagger](https://dagger.dev/) to have some sort of dependency injection at compile time?

2023-11-10 11:59 UTC, jpbempel commented on remote-config/src/main/java/datadog/remoteconfig/state/ExtraServicesProvider.java
> +    return extraServices.isEmpty() ? null : new ArrayList<>(extraServices.values());
why not returning `Collections.emptyList()` instead of `null` ?

2023-11-11 11:26 UTC, jandro996 commented on remote-config/src/main/java/datadog/remoteconfig/state/ExtraServicesProvider.java
> +  private static final ConcurrentHashMap<String, String> extraServices = new ConcurrentHashMap<>();
I've tried the suggested approach and it seems that the complexity is increasing substantially :S 

I've reworked the ExtraServiceProvider with a singleton approach. Can you review it again and see if it looks good to you?

2023-11-11 11:27 UTC, jandro996 commented on remote-config/src/main/java/datadog/remoteconfig/state/ExtraServicesProvider.java
> +  boolean limitReachedLogged = false;
Done! Thanks for the advice!

2023-11-11 11:31 UTC, jandro996 commented on remote-config/src/main/java/datadog/remoteconfig/state/ExtraServicesProvider.java
> +    return extraServices.isEmpty() ? null : new ArrayList<>(extraServices.values());
In the end the ExtraServiceProvider is used by remote config to collect all serviceNames and send it in a json format, i'm returning null to avoid the "extra_service" field if there are no extra services.

2023-11-14 20:19 UTC, mcculls requested changes
Since this happens on every single call to finish a span this has the potential to noticeably affect performance. Have we done any performance measurements with real-world applications to gauge the impact?

Rather than compare the span's service name against the local service name on `finish` (which is an extremely hot code path) is there a way we could collect this information as the naming schema(s) are accessed? There are potentially ways to do that so we only add the extra service name to the bucket once, the first time the naming schema is accessed.

2023-11-15 09:52 UTC, DDJavierSantos approved these changes

2023-11-16 10:59 UTC, jandro996 commented
> Since this happens on every single call to finish a span this has the potential to noticeably affect performance. Have we done any performance measurements with real-world applications to gauge the impact?
> 
> Rather than compare the span's service name against the local service name on `finish` (which is an extremely hot code path) is there a way we could collect this information as the naming schema(s) are accessed? There are potentially ways to do that so we only add the extra service name to the bucket once, the first time the naming schema is accessed.

Thanks for the suggestion! we are looking for another way to do it

2023-11-20 11:41 UTC, jandro996 commented
We have evaluated different approaches to solve the problem and we have decided to change the call to the ExtraServiceProvider from the span completion to when the service name changes in the context.

@mcculls, we have considered the suggestion you provided regarding the naming schemas, and although it is the most efficient in terms of performance, it has certain drawbacks that influenced our decision, but fundamentally the main issue is that we found an inconsistent use of naming schemas through the code, there are several classes where a service name is set through other means, which would likely involve refactoring to give consistency. For instance:

`datadog.trace.instrumentation.aws.v0.AwsSdkClientDecorator`

```
private static final String SQS_SERVICE_NAME =
   AWS_LEGACY_TRACING || SQS_LEGACY_TRACING ? "sqs" : Config.get().getServiceName();

private static final String SNS_SERVICE_NAME =
   SpanNaming.instance().namingSchema().cloud().serviceForRequest(AWS, "sns");
private static final String GENERIC_SERVICE_NAME =
   SpanNaming.instance().namingSchema().cloud().serviceForRequest(AWS, null);

...

public AgentSpan onRequest(final AgentSpan span, final Request request) {

...
switch (awsRequestName.toString()) {
   case "SQS.SendMessage":
   case "SQS.SendMessageBatch":
   case "SQS.ReceiveMessage":
   case "SQS.DeleteMessage":
   case "SQS.DeleteMessageBatch":
     if (SQS_SERVICE_NAME != null) {
       span.setServiceName(SQS_SERVICE_NAME);
     }
     break;
   case "SNS.Publish":
     if (SNS_SERVICE_NAME != null) {
       span.setServiceName(SNS_SERVICE_NAME);
     }
     break;
   default:
     if (GENERIC_SERVICE_NAME != null) {
       span.setServiceName(GENERIC_SERVICE_NAME);
     }
     break;
 }

...

}
```


In order to have some numbers to compare each approach we have counted the number of calls to ExtraServiceProvider#maybeAddExtraService in the system tests default scenario. For instance with the current approach we are calling the method 45 times vs 685 with the span finished approach

A deeper explanation of the discussion is registered in a document called "Discussed Solution" linked to the Jira ticket: [APPSEC-9907](https://datadoghq.atlassian.net/browse/APPSEC-9907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)

2024-02-08 08:59 UTC, jandro996 commented
After discussions with @mcculls  and @amarziali , it has been decided that the service names will be obtained through the naming schema

2024-02-12 11:19 UTC, amarziali commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +  private static final int MAX_EXTRA_SERVICE = 64;
can we have this configurable (with a default of 64)? Just in case it overflows (even if not likely possible) users can just rise on demand without needing any further code changes from us

2024-02-12 11:27 UTC, amarziali reviewed
It's OK to me. You also have to add the same on the TagInterceptor when the service name is inferred from the servlet context (the case of multi-services for webapps). Also, relying on the naming schema will exclude manual spans from the extra services but this is probably a limitation we can accept

2024-02-14 09:24 UTC, amarziali commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +  private final ConcurrentHashMap<String, String> extraServices = new ConcurrentHashMap<>();;
```suggestion
  private final ConcurrentHashMap<String, String> extraServices = new ConcurrentHashMap<>((int)(MAX_EXTRA_SERVICE / 0.75) + 1));
```

2024-02-14 09:25 UTC, amarziali approved these changes

2024-02-14 09:25 UTC, amarziali commented on internal-api/src/test/groovy/datadog/trace/api/naming/ExtraServiceProviderNamingV0ForkedTest.groovy
> +    injectSysConfig(TracerConfig.TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED, "false")
this should not be required since it's false by default

2024-02-14 09:43 UTC, jpbempel approved these changes

2024-02-14 09:43 UTC, jpbempel commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +  private final ConcurrentHashMap<String, String> extraServices = new ConcurrentHashMap<>((int)(MAX_EXTRA_SERVICE / 0.75) + 1);
in practice the 0.75 factor for initial capacity is useless because `ConcurrentHashMap` is using a power of 2 table size.
even `LOAD_FACTOR` constant is not used inside the `ConcurrentHashMap` 😁 
just put the `MAX_EXTRA_SERVICE` and you will be fine

2024-02-14 09:46 UTC, amarziali commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +  private final ConcurrentHashMap<String, String> extraServices = new ConcurrentHashMap<>((int)(MAX_EXTRA_SERVICE / 0.75) + 1);
oh didn't know about this thanks ! :)

2024-02-14 10:26 UTC, jandro996 commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +  private final ConcurrentHashMap<String, String> extraServices = new ConcurrentHashMap<>((int)(MAX_EXTRA_SERVICE / 0.75) + 1);
thanks!

2024-02-15 06:49 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +    remoteConfigMaxExtraServices = configProvider.getInteger(REMOTE_CONFIG_MAX_EXTRA_SERVICES, 64);
It might be nice to extract a constant with the default value.

2024-02-15 06:50 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +            "extra service limit({}) reached: service {} can't be added",
We could add the `SEND_TELEMETRY` marker, so we get notified if this situation is common.

2024-02-15 06:50 UTC, manuel-alvarez-alvarez approved these changes

2024-02-15 09:55 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +package datadog.trace.util;
This is not technically a utility class, perhaps `datadog.trace.api.telemetry` would be a better package since it already contains similar collectors? Or `datadog.trace.api.remoteconfig`?

2024-02-15 09:59 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +public class ExtraServicesProvider {
Suggest renaming this to `ServiceCollector` or `ServiceNameCollector` because that's what it does - it is used to populate the extra services field in RC, but it could also be used elsewhere. (Generally I prefer naming classes based on what they do.)

2024-02-15 11:11 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +  public void maybeAddExtraService(final String serviceName) {
Shorten to `addService` or `recordService` ?

2024-02-15 11:11 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +  private final ConcurrentHashMap<String, String> extraServices =
`services`

2024-02-15 11:15 UTC, mcculls approved these changes
Just minor suggestions around naming

2024-02-15 11:47 UTC, jandro996 commented on internal-api/src/main/java/datadog/trace/util/ExtraServicesProvider.java
> +public class ExtraServicesProvider {
Thanks for the suggestion!

2024-02-16 07:17 UTC, merged