DBM-APM: Selectively pre/append sql comments depending on DBMS typeq
DataDog/dd-trace-java pull request #6160
Opened 2023-11-06 19:59 UTC by jmeunier28

# What Does This Do

This PR updates the logic for the APM-DBM link feature introduced in https://github.com/DataDog/dd-trace-java/pull/4847. It changes from prepending the sql comments, containing the APM trace context, to appending them to the raw sql for **SQL Server driver implementations only**. This requires no changes on the DBM side of things in either the agent or our backend.

Jira ticket: [DBMON-2759](https://datadoghq.atlassian.net/browse/DBMON-2759)

# Motivation

This fixes an issue, which has been reported by several customers that executing `CallableStatement`s with the following syntax causes exceptions to be thrown when enabling APM-DBM link:

> The customer’s code base makes a CallableStatement statementvariable = connection.prepareCall("{call some_function_namehere(?,?,?) }";) and whenever both of these are active, the Java application starts throwing syntax error at or near "{" over and over.

We were able to reproduce this, using the latest version of the java tracer && an internal application. It seems to be caused by the SQL comments we inject being _prepended_ instead of _appended_.  For example, the issue of prepending the comment was reproduced with a simple java application (without APM-DBM link enabled), which did the following:

```java
  final String storedProcedureCall = "/*test commnet*/ {call foo(?, ?)}";
  CallableStatement callableStmt = con.prepareCall(storedProcedureCall);
  callableStmt.setInt(1,10);
  callableStmt.setInt(2,11);
  callableStmt.execute();
  callableStmt.close(); 
```

... this throws the same exception with message `Incorrect syntax near '{'.`

# Proof of Fix

After doing a custom build of this tracer code, we deployed our test app, which runs a combination of `PreparedStatement`/`Statements`/`CallableStatement` & no longer saw the `Incorrect syntax near '{'.` exception being thrown. 

We were also able to confirm that injection is still working properly, e.g: our events are being properly decorated:

![Screen Shot 2023-10-12 at 5 26 06 PM](https://github.com/DataDog/dd-trace-java/assets/14317240/f66b510e-4544-440c-b561-5f52bf268c20)

![Screen Shot 2023-10-12 at 5 26 15 PM](https://github.com/DataDog/dd-trace-java/assets/14317240/5f019ccd-cf13-4824-80fa-0f749ad59807)

# Expected DBM Behavior for Stored Procedures

Stored Procedures aren't supported for the APM-DBM usecase (unless the same app that is calling them is the thing that created the stored procedure & the linking was enabled). Otherwise, we wouldn't see the comments if someone had code that was simply calling `EXEC proc` or `{call proc}`, since the actual text we see in the activity code is either:

1. The entire stored proc text e.g.:
```tsql
CREATE PROCEDURE foo
BEGIN
-- do stuff
END;
```
2. The [currently executing query](https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/activity.py#L55-L60) in the context of the stored proc

Neither, contains the text `EXEC proc`, which is what would have the comment injected via the tracer.

Obviously, this is of secondary concern here. Updating the tracer to append the comment will fix this edge case being reported by customers. **We really don't want the feature to cause users to see exceptions being thrown in their production code.**

[DBMON-2759]: https://datadoghq.atlassian.net/browse/DBMON-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-11-07 00:02 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMCompatibleConnectionInstrumentation.java
> +  private static final String locationMode = "prepend";
It probably makes more sense for this to be a boolean or an enum.

2023-11-07 00:05 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +  private static final String OPEN_COMMENT_APPEND = " /*";
Why are there two constants for OPEN_COMMENT & OPEN_COMMENT_APPEND?
I also see that there's a use of the string literal as "/*" in the code as well.

I think having 3 of same thing is making the code a bit harder to follow.

2023-11-07 00:05 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +  private static final String PREPEND = "prepend";
I'd replaced these with an enum or a boolean for the two different modes.

2023-11-07 00:07 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +      if (sb.length() == OPEN_COMMENT_APPEND.length() + sql.length()) {
It isn't immediately obvious to me what this check is doing.
I'm guessing that it is checking whether the comment was able to be injected, but it is hard to tell.

If that's the case, I'd prefer to see toComment return a boolean indicating success.
That would make the code flow easier to follow.

2023-11-07 00:08 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +    if (locationMode.equals(APPEND)) {
I think I'd prefer to see this as an if / else - rather than an if with an early return.
To me, that would make the code easier to understand.

2023-11-07 00:10 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/test/groovy/SQLCommenterTest.groovy
> +    query                                                                                         | ddService      | ddEnv  | dbService    | ddVersion     | injectTrace | locationMode
The diff is hard to read.  Is there a test here that tests the edge case where the injection fails?

2023-11-07 00:12 UTC, dougqh requested changes
I find the logic hard to follow in places.
I'd like to see a bit of clean-up.

I also think the append vs prepend could be better handled with a boolean or an enum.

2023-11-07 15:54 UTC, jmeunier28 commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +      if (sb.length() == OPEN_COMMENT_APPEND.length() + sql.length()) {
yeah sure, that makes sense

2023-11-07 17:18 UTC, mcculls commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMCompatibleConnectionInstrumentation.java
> +  private static final String locationMode = "prepend";
boolean would be preferred in this case - avoids having to list all the enum classes as helpers

2023-11-08 09:39 UTC, mcculls commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMCompatibleConnectionInstrumentation.java
> +        sql = SQLCommenter.inject(sql, DECORATE.getDbService(dbInfo), appendComment);
Have you considered providing two methods `SQLCommenter.append` and `SQLCommenter.prepend` which each just call `SQLCommenter.inject` with the appropriate boolean flag?

I think that would be much more self-documenting.

2023-11-08 18:01 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
> +  public static String append(final String sql, final String dbService) {
I like the splitting of the functions.

2023-11-08 18:02 UTC, dougqh approved these changes

2023-11-08 18:02 UTC, dougqh commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMCompatibleConnectionInstrumentation.java
> +        sql = SQLCommenter.inject(sql, DECORATE.getDbService(dbInfo), appendComment);
Yes, that was a nice improvement.  Thanks for doing that.

2023-11-08 18:38 UTC, am312 approved these changes

2023-11-08 23:15 UTC, jmeunier28 commented
the test failures are unrelated to my PR && is fixed in here https://github.com/DataDog/dd-trace-java/pull/6177

Going to merge this since we have confidence based on the relevant unit / system tests passing

2023-11-08 23:15 UTC, merged