IAST - org.json package instrumentation
DataDog/dd-trace-java pull request #6165
Opened 2023-11-07 19:49 UTC by DDJavierSantos

# What Does This Do
Adds instrumentation for the org.json package so we can propagate vulnerabilities through the library.

# Motivation
To make sure that propagation of tainted input works through all of the major infrastructure libraries.

# Additional Notes

Jira ticket: [PROJ-IDENT]

2023-11-15 07:54 UTC, PerfectSlayer approved these changes
LGTM

2023-11-16 11:58 UTC, manuel-alvarez-alvarez commented
Can you set ASM as codeowners for this new module?

2023-11-16 12:02 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/json/src/test/groovy/JSONObjectInstrumentationTest.groovy
> +    1 * module.taintIfTainted(_ as JSONTokener, _ as String)
Can you change the wilcards (`_`) at least for strings? I think it makes the tests much more readable

2023-11-16 12:03 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/json/src/test/groovy/JSONObjectInstrumentationTest.groovy
> +class JSONObjectInstrumentationTest extends AgentTestRunner {
Can add more complex JSON object scenarios? (e.g. with child objects/arrays)

2023-11-17 10:10 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/json/src/test/groovy/JSONObjectInstrumentationTest.groovy
> +    1 * module.taintIfTainted(_ as JSONTokener, _ as String)
I have applied the suggestion

2023-11-17 10:11 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/json/src/test/groovy/JSONObjectInstrumentationTest.groovy
> +class JSONObjectInstrumentationTest extends AgentTestRunner {
I have added a test with a nested level in the json string and search for the name inside the nested level

2023-11-17 11:19 UTC, jandro996 commented on dd-java-agent/instrumentation/json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +    @Advice.OnMethodExit(suppress = Throwable.class, inline = false)
It's really necessary to not inline the method?

2023-11-17 11:20 UTC, jandro996 commented on dd-java-agent/instrumentation/json/build.gradle
> +
It will be nice to add a muzzle pass check

2023-11-17 11:25 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +    @Advice.OnMethodExit(suppress = Throwable.class, inline = false)
That was for debugging. Removing

2023-11-17 12:30 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/json/build.gradle
> +
added

2023-11-17 13:10 UTC, smola commented on settings.gradle
> +include ':dd-java-agent:instrumentation:json'
Probably would call the module (and the instrumentation name) as `org-json` to avoid being overly generic and be confused with other libraries.

2023-11-20 08:31 UTC, DDJavierSantos commented on settings.gradle
> +include ':dd-java-agent:instrumentation:json'
Change applied

2023-11-20 11:25 UTC, smola requested changes

2023-11-20 11:25 UTC, smola commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONCookieInstrumentation.java
> +    super("json");
```suggestion
    super("org-json");
```

2023-11-20 11:25 UTC, smola commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +    super("json");
```suggestion
    super("org-json");
```

2023-11-20 11:25 UTC, smola commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONTokenerInstrumentation.java
> +    super("json");
```suggestion
    super("org-json");
```

2023-11-20 11:25 UTC, smola commented on dd-java-agent/instrumentation/org-json/src/test/groovy/JSONCookieInstrumentationTest.groovy
> +    then:
```suggestion
```

2023-11-21 08:07 UTC, jandro996 commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +    super("json");
I think it's not resolved :)

2023-11-21 08:09 UTC, jandro996 commented on dd-java-agent/instrumentation/org-json/src/test/groovy/JSONCookieInstrumentationTest.groovy
> +    then:
Still unresolved :)

2023-11-21 09:03 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/json/src/test/groovy/JSONObjectInstrumentationTest.groovy
> +class JSONObjectInstrumentationTest extends AgentTestRunner {
I'm still missing the case where you have an array of strings:

2023-11-21 09:11 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +        iastModule.taintIfTainted(result, self);
In here we have to check the case when the result might be an array, it might produce a instance of `Collection`/`JSONArray` that we must take care of.

2023-11-21 09:13 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +            .and(named("get"))
There is another [opt](https://www.javadoc.io/doc/org.json/json/20171018/org/json/JSONObject.html#opt-java.lang.String-) that we should instrument (it does not throw an exception if the key is not present in the object)

2023-11-21 09:15 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +    transformation.applyAdvice(
There are a couple of methods: [names](https://www.javadoc.io/doc/org.json/json/20171018/org/json/JSONObject.html#names--), [keySet](https://www.javadoc.io/doc/org.json/json/20171018/org/json/JSONObject.html#keySet--) that might be interesting (but I'm not sure if it'w worth the effort)

2023-11-21 15:19 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/json/src/test/groovy/JSONObjectInstrumentationTest.groovy
> +class JSONObjectInstrumentationTest extends AgentTestRunner {
I have added a test that uses this exact Json and retrieves the first element of the array and checks it gets tainted

2023-11-21 15:19 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +        iastModule.taintIfTainted(result, self);
Fixed

2023-11-21 15:19 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +            .and(named("get"))
Implemented

2023-11-22 08:09 UTC, smola reviewed
Looks good to me. Although looking at tests I wonder: does `get/opt` work properly when the values are not strings (e.g. numbers, arrays, nested objects)?

2023-11-22 10:20 UTC, smola approved these changes

2023-11-22 12:31 UTC, DDJavierSantos commented on dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
> +    transformation.applyAdvice(
We will implement this on a following PR

2023-11-22 16:22 UTC, jandro996 approved these changes

2023-11-23 10:19 UTC, smola approved these changes

2023-11-23 10:19 UTC, manuel-alvarez-alvarez approved these changes

2023-11-23 16:23 UTC, merged