add DSM support to SQS v1
DataDog/dd-trace-java pull request #6259
Opened 2023-11-22 10:12 UTC by vandonr

# What Does This Do

Add the pathway context injection necessary for DSM support to SQS when used with the v1 java sdk.

It's not as clean as I would have liked to be, and I resorted to using the `FieldBackedContextStore` to pass an unactivated span.
The SDK v1 provides 2 methods we can hook onto: `beforeMarshalling` and `beforeRequest`, and also provides a way to pass context around, in the request handler context, but that context is only available in the `beforeRequest` method.
To be compatible with the current implem of DSM in v2, I wanted to use the message attributes, and those attributes are not modifiable anymore once we reach `beforeRequest`, so I had to find a way to do my deep in `beforeMarshalling`, without access to the handler context.

The SDK v2 implem didn't need that because the v2 provides more hook methods, and also offers a context in all of them.

# Motivation

DSM support had already been added to the SQS v2 client, adding support to v1 will allow more clients to benefit from it.

# Additional Notes

Jira ticket: [AIT-8676]

2023-11-22 13:52 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +      DECORATE.afterStart(span);
I could avoid one context store usage by doing this in SqsInterceptor's `beforeMarshalling` but doing it here allows me to call the `afterStart`, well, after I start it.
We could also leave the afterStart in `beforeRequest`, below. I'm not sure what are all the implications.

2023-11-22 13:57 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsClientInstrumentation.java
I wrote this by mixing [the V2 instrumentation](https://github.com/DataDog/dd-trace-java/blob/2b28420f512e247394da30d40f7f93bdd588a718/dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsClientInstrumentation.java) and what was done in [the aws sdk v1 instrumentation](https://github.com/DataDog/dd-trace-java/blob/2b28420f512e247394da30d40f7f93bdd588a718/dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/HandlerChainFactoryInstrumentation.java)

2023-11-22 13:58 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsInterceptor.java
written with [the V2 implem](https://github.com/DataDog/dd-trace-java/blob/2b28420f512e247394da30d40f7f93bdd588a718/dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsInterceptor.java) as reference

2023-11-23 10:26 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +      FieldBackedContextStores.getContextStore(
The right way to obtain a context store is to use the `InstrumentationContext.get(..)` api and not using this directly

2023-11-23 10:30 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +      FieldBackedContextStores.getContextStore(
ah, ok, but `InstrumentationContext` only works within an `Advice`, and it's not the case here :'(

2023-11-23 10:31 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
> +  @IgnoreIf({ instance.isDataStreamsEnabled() })
why?

2023-11-23 10:34 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsClientInstrumentation.java
> +      handlers.add(new SqsInterceptor());
here you can obtain a context store and pass it to the interceptor constructor

2023-11-23 10:35 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
> +  @IgnoreIf({ instance.isDataStreamsEnabled() })
Ah yes, it's a mistake on my part when synchronizing this with the V2 tests, will remove that line.

2023-11-23 10:35 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +      FieldBackedContextStores.getContextStore(
You can obtain on an advice and pass where you need it

2023-11-23 10:36 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsClientInstrumentation.java
> +      handlers.add(new SqsInterceptor());
hmm interesting, I'll try that.

2023-11-23 10:47 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
> +  @IgnoreIf({ instance.isDataStreamsEnabled() })
Ah, it was not a mistake from me ! It's disabled in V2 as well !
I suppose the logic is that whether DSM is enabled or not has no impact on the expecations of the test, so we ignore it to not run the same test twice.
One could also argue that we could run it to make sure we didn't change the behavior with DSM. But in any case, I think it should be coherent between v1 and v2 if tests are ignored or not.

2023-11-23 11:05 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsInterceptor.java
The sdk v1 also has a `beforeExecution` method but only starting from a certain version. It could be an option to support DSM only starting from this version (leaving out legacy sdk versions). That can be a quick win to reuse exactly the same logic

2023-11-23 11:13 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +        span =
You should just use the request context (see below) to store and retrieve this span without adding complexity (and unneeded bytecode manipulations with context stores):

```
      request.addHandlerContext(SPAN_CONTEXT_KEY, span);
```

2023-11-23 11:14 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +      DECORATE.afterStart(span);
what if `beforeMarshalling` fails? That span will be leaked out and never closed

2023-11-23 11:17 UTC, amarziali requested changes
I left some comments that should be addressed on this PR. I think that the implementation can be also simplified a bit

2023-11-23 12:07 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +        span =
Yes I would, but the request context is only available on an `Request` object (like the one we have in `beforeRequest`), not on the `AmazonWebServiceRequest` object that we have in `beforeMarshalling`.

2023-11-23 12:57 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +        span =
yes true on the 1.11.0 it's not there. However in the 1.11.116 it has been added and the IRequestHandler supports also `beforeExecute`. Probably supporting dsm only starting from 1.11.116 (released on April 2017) it's a good tradeoff to simplify

2023-11-23 13:04 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +        span =
ok, fair point

2023-11-24 09:20 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
> +        span = request.getHandlerContext(SPAN_CONTEXT_KEY);
idk if it's better to check on the request type first, or if I should just try getting the span every time, since we have the if null below to handle the case where it's missing.
At least with the explicit type check, we know what's the expected behavior.

2023-11-24 09:20 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/TracingIterator.java
we only support DSM in v1.11.106 for the producer, but we don't need the new features for the consumer, so it can be in v1.0 (even though it's pretty unlikely that customers would use mismatching versions between producer and consumer ?)

2023-11-24 09:20 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.11.106/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsInterceptor.java
> +      AgentSpan span = startSpan("aws.sqs.send");
hardcoded the span name because I don't want to pull dependencies just to access the cache that is normally used to get the name https://github.com/DataDog/dd-trace-java/blob/62d6d15c3fdb685d049a47679171dc84ca01551e/dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java#L60
and since we know what kind of request we're dealing with here, it'd always be the same value anyway.

2023-11-27 09:12 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sqs-1.11.106/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsInterceptor.java
> +      AgentSpan span = startSpan("aws.sqs.send");
why a span is started here? For the sdk v2 is not happening andt the reason is that the tracing for the send should already done by the aws sdk instrumentation.

2023-11-27 09:23 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.11.106/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsInterceptor.java
> +      AgentSpan span = startSpan("aws.sqs.send");
in the sdk v2 instrumentation, the spans are always started early, in `beforeExecution`, which is a method that doesn't exist in v1, but takes place even before `beforeMarshalling`. This allows access to the span in all methods basically.
https://github.com/DataDog/dd-trace-java/blob/275ed3a6479cddcdb5b7ab42f8c0b43f62d8da72/dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java#L49
(it is activated only later)

In the sdk v1 instrumentation, the span is both created and started in the same method, in `beforeRequest`, which means it's not available in `beforeMarshalling`, where I need it. I could create the span in the `beforeMarshalling` method of the sdk instrumentation, but we already discussed [here](https://github.com/DataDog/dd-trace-java/pull/6259#discussion_r1403239316) that it'd be better to create it right where I need it, in the SQS instrumentation, which saves one use of the context, and also avoids potential leaking span issues.

2023-11-27 11:31 UTC, amarziali commented
If it can help an easy implementation can be found in #6281 . It has to be completed for extracting the context on receive side but it will be easy to do

2023-11-27 12:32 UTC, vandonr commented
> If it can help an easy implementation can be found in #6281 . It has to be completed for extracting the context on receive side but it will be easy to do

I don't understand, it's more or less what I did initially, but then we discussed the fact that it'd be better to use the handler context that is available from 1.11.106 to store the span in [this discussion](https://github.com/DataDog/dd-trace-java/pull/6259#discussion_r1403357343).

I do note the improvements you added: 
 - changing the span operation name to avoid having to add dependencies where we start it (I can use that here)
 - removing it from the context store when you use it to free memory faster

Are you suggesting that after trying it yourself, you think using a context store is a better idea than relying on the post-1.11.106 handler context ?

2023-12-01 13:39 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/HandlerChainFactoryInstrumentation.java
> +    map.put(AmazonWebServiceRequest.class.getName(), AgentSpan.class.getName());
we use not to refer classes that are not on the bootstrap classloader. This can be changed to the qualified name of the class `com.amazonaws.AmazonWebServiceRequest`

2023-12-01 13:40 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/HandlerChainFactoryInstrumentation.java
> +              InstrumentationContext.get(AmazonWebServiceRequest.class, AgentSpan.class)));
Same as above we can use String class name here

2023-12-01 13:41 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsClientInstrumentation.java
> +        AmazonWebServiceRequest.class.getName(), AgentSpan.class.getName());
Also here the ` com.amazonaws.AmazonWebServiceRequest` key should be used. The agentSpan.class.getName can be kept as is (it will be on the boostrap classpath)

2023-12-01 13:46 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsClientInstrumentation.java
> +      handlers.add(
nit: if datastreams is not enabled you can avoid adding this extra handler since it won't be needed

2023-12-01 14:12 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsClientInstrumentation.java
> +      handlers.add(
yes right. I'll look into how I can get the DSM on/off information at this point.

2023-12-11 13:26 UTC, vandonr commented
> You might also ask a double review form the apm java core team (or dsm folks since it's dsm related)

@PerfectSlayer or @mcculls could you give this a look ?

I don't think a DSM review is necessary, because I really copied what was done in the V2 implem, so there was no functional question, only technical ones.

2023-12-12 10:38 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/MessageAttributeInjector.java
> +      String jsonPathway = String.format("{\"%s\": \"%s\"}", key, value);
Don’t you fear some `key` or `value` value might break the JSON? Like `some"thing`?

2023-12-12 10:38 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsClientInstrumentation.java
> +    super(INSTRUMENTATION_NAME);
Should this instrumentation have some aliases more? Like "sqs" or similar? (I am not familiar with the whole AWS ecosystem)

2023-12-12 15:56 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/MessageAttributeInjector.java
> +      String jsonPathway = String.format("{\"%s\": \"%s\"}", key, value);
that's a good point, but also this line of code was taken from https://github.com/DataDog/dd-trace-java/blob/5afa55c4c750cc298bd6d7d15db14ed79adef4e6/dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/MessageAttributeInjector.java#L18
so... idk, maybe I can fix both at the same time.

2023-12-12 15:58 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsClientInstrumentation.java
> +    super(INSTRUMENTATION_NAME);
I was trying to stay consistent with the existing v2 instrumentation that uses the `aws-sdk` name too
https://github.com/DataDog/dd-trace-java/blob/5afa55c4c750cc298bd6d7d15db14ed79adef4e6/dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsClientInstrumentation.java#L17-L20

2023-12-13 14:50 UTC, vandonr commented on dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/MessageAttributeInjector.java
> +      String jsonPathway = String.format("{\"%s\": \"%s\"}", key, value);
Looking at the dotnet implementation, it's implemented that way as well.
https://github.com/DataDog/dd-trace-dotnet/blob/e8735bc26f63534356e7f40b650c5e91a43b111a/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/AWS/SQS/ContextPropagation.cs#L84
I'd say we keep it like this, and it may be worth it to fix it if we get an escalation for it.
Also, AWS is usually pretty restrictive on what it accepts for names, so we have that on our side.

2023-12-20 09:44 UTC, mcculls approved these changes

2023-12-20 09:48 UTC, merged