Added Api Security configuration via remote-config
DataDog/dd-trace-java pull request #6340
Opened 2023-12-10 22:50 UTC by ValentinZakharov

# What Does This Do
Improvement allows API Security to set request sample rate for API Security using remote-config. Assumed API Security can be deactivated if the value set to `0`. Default value for sample rate is `0.1` (means - will be applied to 10% of sampled requests)

The `ASM_FEATURE` product extended with extra object/value
```
{
  "api_security": {
    "request_sample_rate": 0.1
  }  
}
```
In the case that ASM is disabled, the API Security feature will be automatically disabled as well. However, the tracer will keep the last value of `request_sample_rate` to be used as soon as ASM is enabled again.

# Motivation
Customers want to have option to deactivate API Security remotely.

# Additional Notes

Two possible states for the tracer with API Security activated with `DD_EXPERIMENTAL_API_SECURITY_ENABLED=true`

ASM is activated by one click remote config. The tracer must register the `ASM_FEATURES` product and receive all information, both for asm activation and api sample rate.

ASM is activated by an env var `DD_APPSEC_ENABLED=true`. The tracer must register the `ASM_FEATURES` product (this is new from previous tracers behaviour) and only receive information about api sample rate.

Jira ticket: [APPSEC-16674]

2023-12-11 15:48 UTC, smola requested changes

2023-12-12 11:48 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
> +    if (tracerConfig.getAppSecActivation() != ProductActivation.FULLY_DISABLED) {
Rolled back changes according to a new fixed behaviour

2023-12-12 11:49 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/api/security/ApiSecurityRequestSampler.java
> +            if (newConfig != null && newConfig.apiSecurity != null) {
Added checking for the empty config `AppSecConfigServiceImpl`

2023-12-14 10:01 UTC, smola reviewed
I think there was a dirty merge or febase here, so many unrelated changes...

2023-12-14 10:01 UTC, smola commented on .gitlab/benchmarks.yml
> +.dsm-kafka-benchmarks:
Does this belong to this PR?

2023-12-19 09:24 UTC, nikita-tkachenko-datadog commented on remote-config/src/main/java/datadog/remoteconfig/state/ProductState.java
> +    this.listeners = new LinkedList<>();
Any specific reason `LinkedList` is used here and not the array list? The latter is more efficient in terms of memory and when it comes to iteration (which is what we seem to be doing here)

2023-12-19 09:24 UTC, nikita-tkachenko-datadog commented on remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
> +        this.productStates.computeIfAbsent(product, p -> new ProductState(product));
As a side-note, `productStates` could be an `EnumMap`

2023-12-19 09:24 UTC, nikita-tkachenko-datadog commented on remote-config/src/main/java/datadog/remoteconfig/state/ProductState.java
> +        listener.accept(configKey, content, hinter);
Not sure whether relevant or not, but if a single listener fails here, those that come after it in the list will not receive the notification. Same goes for remove/commit operations.

2023-12-19 09:24 UTC, nikita-tkachenko-datadog commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/api/security/ApiSecurityRequestSampler.java
> +  private int sampling;
There seems to be no synchronization where this field is being read. If I understood correctly, the listener that modifies it will be called in a task scheduler thread, while the `sampleRequest` method is registered as a callback in the `SubscriptionService` which can be called from many different threads. In absence of synchronization changes to the field might not be visible.

2023-12-19 15:05 UTC, ValentinZakharov commented on .gitlab/benchmarks.yml
> +.dsm-kafka-benchmarks:
Thanks, Rebased

2023-12-19 15:54 UTC, ValentinZakharov commented on remote-config/src/main/java/datadog/remoteconfig/state/ProductState.java
> +    this.listeners = new LinkedList<>();
Right. If I recall correctly ArrayList's default size is 10, and we have only few listeners per product - there will never happens reallocation, so we can easily use ArrayList.

2023-12-19 15:55 UTC, ValentinZakharov commented on remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
> +        this.productStates.computeIfAbsent(product, p -> new ProductState(product));
Replaced with `EnumMap`

2023-12-19 16:00 UTC, ValentinZakharov commented on remote-config/src/main/java/datadog/remoteconfig/state/ProductState.java
> +        listener.accept(configKey, content, hinter);
The problem here is - in current implementation config state is a single value, so if problem happens, we can report only one exception. So as a workaround I decided to interrupt iteration and report problem in case if issue arises.
I suppose, we might need to improve remote-config state system in future implementations.

2023-12-19 16:03 UTC, nikita-tkachenko-datadog approved these changes

2023-12-19 16:07 UTC, nikita-tkachenko-datadog commented on remote-config/src/main/java/datadog/remoteconfig/state/ProductState.java
> +        listener.accept(configKey, content, hinter);
Makes sense. An alternative could be to have a single exception and link exceptions from individual listeners as suppressed, although I'm not familiar enough with the remote config to know whether it'd be acceptable

2023-12-28 04:35 UTC, ygree commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
> +            final boolean newState = newConfig.asm.enabled;
Looks like ASM can be enabled/disabled via remote config? If so, we need to update the telemetry to report product changes. Now it's only reported once at the start of the sending application. See TelemetryRequest.writeProducts()

2023-12-28 04:36 UTC, ygree approved these changes
One question about Telemetry. Otherwise looks good to me!

2023-12-29 23:09 UTC, ygree commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
> +            final boolean newState = newConfig.asm.enabled;
I've created a Jira ticket [APMJAVA-1174] to generate product change events when Appsec is turned on/off at runtime.

2024-01-23 07:15 UTC, jandro996 commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/api/security/ApiSecurityRequestSampler.java
> +  public ApiSecurityRequestSampler(final Config config, ConfigurationPoller configurationPoller) {
Not relevant! IMHO you can reduce the cognitive overhead if you avoid nested if statements if it's possible. For instance:

```
if (configurationPoller != null) {
return;
}
```
//continue with the logic

2024-01-23 07:25 UTC, jandro996 approved these changes

2024-01-24 09:55 UTC, jandro996 approved these changes

2024-01-24 09:58 UTC, smola approved these changes
@ValentinZakharov  Looks good to me, assuming the possible interaction with ASM enable/disable via remote config has been tested.

2024-01-24 10:24 UTC, merged