Spark Executor Tasks Instrumentation
DataDog/dd-trace-java pull request #6515
Opened 2024-01-18 10:14 UTC by paul-laffon-dd

# What Does This Do

Add a new instrumentation `spark-executor` to trace tasks running on spark executors

The existing spark instrumentation is running on the spark driver, capturing spark internals (spark.sql, spark.job, spark.stage...), while this new instrumentation will trace task being run on spark executors.

# Motivation

Generate traces for `spark.task`, with underlying spans (like s3 or database calls) being linked. 

# Additional Notes

- each `spark.task` is a distinct trace and not on the existing `spark.application` / `spark.job` traces:
  - a spark job/application can have millions on tasks, making it unpractical to have everything in one trace
  - sampling should be applied to `spark.task`, while all `spark.application` and `spark.job` traces are kept  
  - Span link will be used to link the `spark.task` to other spark traces

- task errors are not captured for now
  - spark [catch all throwable](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/executor/Executor.scala#L801-L841) in task execution, making it complex to retrieve it from the instrumentation

2024-01-19 15:38 UTC, raphaelgavache approved these changes
lgtm, looks great!

2024-02-05 22:31 UTC, bm1549 reviewed
Can you also update CODEOWNERS so that [data-jobs-monitoring](https://github.com/orgs/DataDog/teams/data-jobs-monitoring) owns the instrumentation files here?

2024-02-06 16:53 UTC, paul-laffon-dd commented
@bm1549 In order to add the team [@DataDog/data-jobs-monitoring](https://github.com/orgs/DataDog/teams/data-jobs-monitoring) as CODEOWNERS, it need to have access to the repository

<img width="639" alt="image" src="https://github.com/DataDog/dd-trace-java/assets/99249445/bdf09ae0-f4f8-4be7-b95b-99cd0bfd67b0">

2024-02-06 18:46 UTC, bm1549 commented
@paul-laffon-dd it seems like that team is not a subteam of https://github.com/orgs/DataDog/teams/dev which is causing the issue

@tiffon as maintainer of the team, can you update the parent team to be dev?
https://github.com/orgs/DataDog/teams/data-jobs-monitoring/edit

2024-02-13 14:43 UTC, paul-laffon-dd commented
Thanks @bm1549, we updated the team settings and the CODEOWNERS file is now valid

2024-02-14 18:10 UTC, dougqh requested changes
Scope.close and span.finish should probably be in finally blocks; otherwise, you risk traces not being published in a timely fashion.

2024-02-15 13:20 UTC, paul-laffon-dd commented on dd-java-agent/instrumentation/spark-executor/src/main/java/datadog/trace/instrumentation/spark/SparkExecutorInstrumentation.java
> +      scope.close();
Move those in finally block

2024-02-26 15:05 UTC, dougqh commented on dd-java-agent/instrumentation/spark-executor/src/main/java/datadog/trace/instrumentation/spark/SparkExecutorInstrumentation.java
> +        scope.close();
I think this is probably fine, but typically each clean-up needs to be in its own finally block.
In this case - if scope.close raises an exception then you won't perform span.finish.

2024-02-26 15:06 UTC, dougqh approved these changes

2024-02-27 09:42 UTC, merged