Introduced trace post-processing
DataDog/dd-trace-java pull request #6800
Opened 2024-03-12 00:03 UTC by ValentinZakharov

# What Does This Do
Introduced experimental trace post processing mechanism. It allows to call Instrumentation Gateway, after the request finished and just before trace serialised. The post-processing happens only for traces with flag `RequiresPostProcessing` and sampling priority > 0 (not dropped).

# Motivation
The idea is to have mechanism that can safely do extra computations without bringing overhead in requests latency.
This is preparation for new API Security sampling, where heavy schema extraction should happen after the request finished when we have information about span sampling priority. We intent to compute schema only if span will be retained.

# Additional Notes

2024-03-13 20:02 UTC, dougqh requested changes
I have a few questions about the overall approach.

2024-03-13 20:02 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      Thread thread =
Why do we need to split off a separate thread here?
Given the join further down, it looks this is basically still operating synchronously.

2024-03-13 20:23 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      Thread thread =
IIRC the intent was to limit the post-processing time, i.e. allow cancellation of post-processing when the limit was exceeded.

If the post-processing can be represented as a loop, where each iteration is small enough, then this could be achieved without using a separate thread - by checking whether the limit has been exceeded on each iteration and breaking out of the loop early.

2024-03-13 20:35 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      Thread thread =
The code as it is assumes that the post-processing work can be safely interrupted...

Now that I see the overall PR I think a better approach would be for the post-processor to accept a `BooleanSupplier` (or `Predicate` if there's a context object shared between the worker and post-processor) 

The post-processor could then call that at the start of each loop to decide whether it needs to abort or not.

Then all the worker would need to do is provide an implementation of that `BooleanSupplier` which changes the result when the time has been exceeded. Another benefit of this approach is that testing could provide a different implementation, which uses a different condition.

2024-03-14 22:16 UTC, ValentinZakharov commented on dd-trace-api/src/main/java/datadog/trace/api/internal/TraceSegment.java
> +  void setRequiresPostProcessing(boolean postProcessing);
The idea was, to set (in some way) flag in context, that can be indicative of post-processing requirement. Since `TraceSegment` is implemented in `DDSpanContext`, for me it look like a perfect candidate, that can be used to set `requiresPostProcessing` flag from any request handler code.
But, I suppose, we can easily move it to `DDSpanContext` to avoid exposure.

2024-03-14 22:24 UTC, ValentinZakharov commented on dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
> +  public static final String TRACE_POST_PROCESSING_ENABLED = "trace.post-processing.enabled";
Good point. I was imaging in future, we can have various independent post-processing tasks (each called by `dd-post-processor` thread one-by-one). They could be represented as list:
```
class TraceProcessingWorker {
     List<TracePostProcessor> tracePostProcessors
     ...
}
```
And for each TracePostProcessor will have to have it's own way to disable it (via config).

2024-03-14 22:37 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      Thread thread =
I confirm, my intention to use a thread was due to the need to interrupt it with a timeout. I think, post-processing duration could be related to amount of data (imagine request with very huge body).

@mcculls, good point! I'll try to get rid of creating new threads. The only concern here - in my particular case, I will need to call WAF (native module) during the post-processing, and there will be no way to interrupt native code execution (apart of built-in WAF timeout mechanism)

2024-03-18 23:57 UTC, ValentinZakharov commented on dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
> +  public static final String TRACE_POST_PROCESSING_ENABLED = "trace.post-processing.enabled";
Removed option to disable post-processing. Instead will be used disabling for each post-processor

2024-03-18 23:57 UTC, ValentinZakharov commented on dd-trace-api/src/main/java/datadog/trace/api/internal/TraceSegment.java
> +  void setRequiresPostProcessing(boolean postProcessing);
`setRequiresPostProcessing` is fully moved to `DDSpanContext`

2024-03-18 23:58 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      Thread thread =
Removed thread creating and introduced `timeoutCheck` as discussed

2024-03-27 11:03 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
> +    TRACE_POST_PROCESSOR("dd-trace-post-processor"),
This is no longer needed?

2024-03-27 11:05 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/postprocessor/SpanPostProcessor.java
> +  boolean process(DDSpan trace, DDSpanContext context, BooleanSupplier timeoutCheck);
```suggestion
  boolean process(DDSpan span, DDSpanContext context, BooleanSupplier timeoutCheck);
```

2024-03-27 11:06 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +  private boolean requiresPostProcessing;
does this need to be `volatile`?

2024-03-27 11:15 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +        if (timeoutCheck.getAsBoolean()) {
This will incur a cost of calling `System.currentTimeMillis()` for every span in the trace, even if no spans need post-processing. How about doing an initial loop to collect any spans that need post-processing and only setup the timeout check, etc. when we know we have spans to post-process?

You could also lazily create the collection to hold the spans to post-process, ie. only create it when you find a span to post-process, in which case for traces with no spans to post-process the only cost would be that first iteration to check the flag (ie. no allocation or time calls).

2024-03-27 11:18 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/postprocessor/SpanPostProcessor.java
> +public interface SpanPostProcessor {
javadoc explaining how to implement this, expectations, etc. would be appreciated

2024-03-27 11:20 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +          spanPostProcessor.process(span, context, timeoutCheck);
The `process` method returns a `boolean` but it's value isn't checked here - is the plan to use it to abort the post-processing or should the `process` method be changed to return `void`?

2024-03-27 11:23 UTC, mcculls requested changes
`maybeTracePostProcessing` should be changed to do an initial scan of the spans and collect those requiring post-processing. If no spans need post-processing it can exit early. Otherwise setup the timeout check, etc. and start post-processing the smaller subset of spans that need it.

Also the description mentions a feature-flag `dd.trace.post-processing.enabled` to control this feature, but that doesn't appear to be implemented yet?

2024-03-27 15:13 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
> +    TRACE_POST_PROCESSOR("dd-trace-post-processor"),
Thanks, missed from pervious implementation, removed

2024-03-27 15:13 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +  private boolean requiresPostProcessing;
Right, my bad

2024-03-27 15:14 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +        if (timeoutCheck.getAsBoolean()) {
Reworked as suggested

2024-03-27 15:14 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/core/postprocessor/SpanPostProcessor.java
> +public interface SpanPostProcessor {
Added explanation

2024-03-27 15:15 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +          spanPostProcessor.process(span, context, timeoutCheck);
Yeah, I've missed it. Changed the logic to check return value

2024-03-27 15:27 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +          log.debug("Span post-processing is interrupted due to timeout.");
```suggestion
          log.debug("Span post-processing interrupted due to timeout.");
```

2024-03-27 15:37 UTC, mcculls approved these changes
I'm OK with the updated implementation - just a question about whether we should leave the no-op `AppSecPostProcessor` in place before merging

2024-03-27 15:37 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      this.spanPostProcessor = new AppSecPostProcessor();
Since `AppSecPostProcessor` is currently a no-op, how about leaving `spanPostProcessor` as `null` for the initial merge? You could then check `spanPostProcessor != null` before calling `maybeTracePostProcessing` (or check it inside that method) so the post-processing only happens when there's a registered post-processor...

2024-03-27 15:54 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      this.spanPostProcessor = new AppSecPostProcessor();
Good point. Please, let me add that.

2024-03-27 18:42 UTC, dougqh commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +    this.tracePostProcessingTimeout = configProvider.getLong(TRACE_POST_PROCESSING_TIMEOUT, 1000);
I'd like to see the default as its own variable.

2024-03-27 18:45 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      this.spanPostProcessor = new AppSecPostProcessor();
I don't to write our code to satisfy the coverage tool.  The coverage tool is suppose to help make code better not worse.

I have to believe there's a better solution.

2024-03-27 18:45 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +  public void setRequiresPostProcessing(boolean postProcessing) {
I don't particularly like that these methods are public.

2024-03-27 18:47 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/postprocessor/SpanPostProcessor.java
> +  boolean process(DDSpan span, BooleanSupplier timeoutCheck);
Why the BooleanSupplier?  Would it not be better to just have two different methods to cover the two different cases?

2024-03-27 19:55 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/postprocessor/SpanPostProcessor.java
> +  boolean process(DDSpan span, BooleanSupplier timeoutCheck);
The idea of the supplier was for situations where the processor was doing something non-trivial - assuming that processing could be broken down into smaller chunks then the supplier would allow it to check to see if the timeout had been exceeded mid-processing (otherwise there's no easy way for a processor to check to see if it should abort its processing)

In other words _during_ the `process` call the value returned by the supplier could change, and it's not possible to represent that as two methods.

This is only really needed when the `process` call might take a while and need to be cancelled mid-call.

2024-03-27 20:00 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      this.spanPostProcessor = new AppSecPostProcessor();
Two options:
1. expose a way to set a test post-processor, used to test out the implementation
   * this would also help you test edge conditions as well as do micro-benchmarking
2. exclude the class from the code-coverage requirements
   * this is not ideal, but for some situations it is necessary

2024-03-27 20:04 UTC, dougqh commented on dd-trace-core/src/main/java/datadog/trace/core/postprocessor/SpanPostProcessor.java
> +  boolean process(DDSpan span, BooleanSupplier timeoutCheck);
Ah, that makes sense.  Thanks for the clarification.

2024-03-27 21:39 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/core/postprocessor/SpanPostProcessor.java
> +  boolean process(DDSpan span, BooleanSupplier timeoutCheck);
I'm sorry, didn't get how two methods can help with timeout?

2024-03-27 21:42 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
> +  public void setRequiresPostProcessing(boolean postProcessing) {
In my case, `setRequiresPostProcessing`, should be called from `appsec` module, so we need to expose it in some way. Either in `TraceSegmet`, either in `DDSpanContext`.
Do you have any other options in mind?

2024-03-27 21:50 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +    this.tracePostProcessingTimeout = configProvider.getLong(TRACE_POST_PROCESSING_TIMEOUT, 1000);
Added default value

2024-04-12 13:04 UTC, ValentinZakharov commented on dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
> +      this.spanPostProcessor = new AppSecPostProcessor();
Done + added test

2024-04-16 21:23 UTC, dougqh approved these changes

2024-04-16 21:25 UTC, merged