Instrument Google protobuf
DataDog/dd-trace-java pull request #6865
Opened 2024-04-01 19:31 UTC by piochelepiotr

# What Does This Do

Add protobuf instrumentation for serialize / deserialize operations.
If data streams monitoring is enabled, capture schemas of messages.

# Motivation

# Additional Notes

[It impacts the GRPC instrumentation](https://ddstaging.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Apiotr&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=false&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&traceQuery=&view=spans&start=1711130875088&end=1711131775088&paused=false)

since it adds spans for serialize / deserialize

Jira ticket: [PROJ-IDENT]

2024-04-02 14:39 UTC, dougqh commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/AbstractParserInstrumentation.java
> +        DESERIALIZER_DECORATOR.attachSchemaOnSpan((AbstractMessage) message, span);
This seems like work that would probably be better done in a background thread.
There is a mechanism for doing that, but I think it could use some improvement.

For now, I'm fine with this as is - as long as it is not on by default.

2024-04-02 14:40 UTC, dougqh commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/Decorator.java
> +    Integer prio = span.forceSamplingDecision();
There probably needs to a product specific code for why the decision was forced.
You should check with APM ingestion.

2024-04-02 14:42 UTC, dougqh commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/OpenAPIFormatExtractor.java
> +    return "{"
This is not properly escaped

2024-04-02 14:42 UTC, dougqh commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/OpenAPIFormatExtractor.java
> +    StringBuilder schema = new StringBuilder();
This is not properly escaped - you should probably use a JSON API instead

2024-04-02 14:44 UTC, piochelepiotr commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/OpenAPIFormatExtractor.java
> +    StringBuilder schema = new StringBuilder();
Do you think it's ok to add the dependency to JSON API?
It would make the code easier indeed. But add a dependency

2024-04-02 14:44 UTC, dougqh requested changes
I have concerns that JSON is not done using JSON API and is not properly escaped.
I also have concerns with the altering of the sampling decision.
When altering the sampling decision, I believe we should be adding information about which product made that decision.  We should check that with APM ingestion.

2024-04-04 16:20 UTC, dumontg commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/Decorator.java
> +    Integer prio = span.forceSamplingDecision();
Indeed, if a customer pays for the ingestion of a span, we want to be able to tell why it was ingested (it’s also pretty useful for troubleshooting). The tracer set a specific attribute called `_dd.p.dm` depending on the sampling mechanism ([see all potential values that exist](https://datadoghq.atlassian.net/wiki/spaces/APM/pages/2564915820/Trace+Ingestion+Mechanisms#Propagated-tags%3A-_dd.p.dm-(sampling-mechanism-aka-decision-maker))).

Questions:
* When you override the sampling decision, do you just want the span or the whole trace?
* Do you expect a lot of spans coming in? Once per tracer process maybe?

2024-04-04 16:20 UTC, dumontg commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/Decorator.java
> +    System.out.println("schema is: " + schema);
Unsure you wanted to leave this

2024-04-05 04:01 UTC, piochelepiotr commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/Decorator.java
> +    Integer prio = span.forceSamplingDecision();
I checked a bit more the code, it doesn’t look like forceSamplingPriority is going to increase sampling rate, is that correct?
It looks like it’s going to force the sampling decision to be taken earlier.
What I can do, is reverse the two samplings.
Today, the code extracts only 1 schema every 30 seconds, so I can do that sampling first. That way, the change would only affect the sampling decision of 1 trace every 30 seconds, what do you think?

2024-04-05 08:35 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/SchemaExtractor.java
> +        break;
This code will end up in a `StackOverflowError` in case there are cycles in the schema, see the example:

```
message DummyMessage {
    int32 id = 1;
    string name = 2;
    DummyMessage nested = 3;
}
```

A cache of already processed types will help here and the `SchemaBuilder` should be able to handle cycles. Optionally, we might want to include a limit in the recursion depth and also number of elements visited to deal with problematic/big schemas.

2024-04-05 16:30 UTC, piochelepiotr commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/SchemaExtractor.java
> +        break;
Good catch! Will update the code

2024-04-05 17:39 UTC, piochelepiotr commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/Decorator.java
> +    Integer prio = span.forceSamplingDecision();
I switched the two sampling calls.
Now the forceSamplingDecision is only rarely called (a few times every 30 seconds, 1 time in the best case depending on race conditions).
Also, forceSamplingDecision doesn't force the trace to be sampled. It forces the sampling decision to be made.
So this should not increase sampling rate.

2024-04-05 17:40 UTC, piochelepiotr commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/SchemaExtractor.java
> +        break;
I updated the code & added limits. Thanks for the comment!

2024-04-09 09:29 UTC, dumontg commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/Decorator.java
> +    Integer prio = span.forceSamplingDecision();
Ah that makes sense, I had not understood that initially. If you don't influence sampling I don't think we need to do anything at intake. For accomplishing what you want I am not knowledgeable enough with the tracer itself.

2024-04-10 12:47 UTC, amarziali commented on dd-java-agent/instrumentation/protobuf-3.0.0/build.gradle
> +    assertInverse = false
any particular reason not to test that the instrumentation is disabled on versions < 3?

2024-04-10 13:02 UTC, amarziali commented on dd-smoke-tests/datastreams/kafkaschemaregistry/src/main/java/datadog/smoketest/datastreamskafka/KafkaProducerWithSchemaRegistry.java
> +    System.out.println("duration is " + duration.getSeconds());
a logger should be used to print out this

2024-04-10 13:05 UTC, amarziali commented on internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InternalSpanTypes.java
> +  public static final UTF8BytesString SERIALIZE = UTF8BytesString.create(DDSpanTypes.SERIALIZE);
Perhaps I would have been used `protobuf` as span type since serialize/deserialize are rather operations

2024-04-10 13:08 UTC, amarziali commented on dd-java-agent/agent-tooling/build.gradle
> +
nit: remove this file from the changeset

2024-04-10 13:09 UTC, amarziali commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/AbstractParserInstrumentation.java
> +  static final String DESERIALIZE = "deserialize";
I have same naming concern than "serialize"

2024-04-10 13:13 UTC, amarziali commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/Decorator.java
> +    String schema = SchemaExtractor.extractSchemas(descriptor);
This seems to me a quite expensive operation. Can we cache this? The same for the schemaId being a hash depending on the schema name

2024-04-11 01:23 UTC, piochelepiotr commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/AbstractMessageInstrumentation.java
> +  static final String SERIALIZE = "serialize";
Updated the name, for some reason I can't explain, it doesn't work if I switch to Utf8ByteString 🤷

2024-04-11 01:24 UTC, piochelepiotr commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/Decorator.java
> +    String schema = SchemaExtractor.extractSchemas(descriptor);
I cached based on the schema name, but I'm worried the schema changes, and the schema name doesn't 🤔 
Do you have a better idea on how to cache?

2024-04-11 07:17 UTC, amarziali commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/AbstractMessageInstrumentation.java
> +  static final String SERIALIZE = "serialize";
If you have tests failing is probably because they are comparing String with CharSequence that's not the same thing.
So 
```
String s = "test"
CharSequence cs = UTF8ByteString.create("test")

s.equals(cs) -> false
s.contentEquals(cs) -> true
s.equals(cs.toString()) -> true
```

2024-04-11 07:22 UTC, amarziali commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/Decorator.java
> +    String schema = SchemaExtractor.extractSchemas(descriptor);
Can a schema be dynamically changed at runtime and what is the use case?

2024-04-11 11:38 UTC, amarziali commented on dd-java-agent/instrumentation/protobuf-3.0.0/src/main/java/datadog/trace/instrumentation/protobuf_java/AbstractMessageInstrumentation.java
> +public final class AbstractMessageInstrumentation extends InstrumenterModule.Tracing
Concerning the instrumentation, do we want to systematically trace all the ser/de operations or having this couple of instrumentations enabled by default only when datastreams is enabled? I'm wondering if we're adding too many details for the non dsm users

2024-04-23 07:05 UTC, dougqh approved these changes

2024-04-26 21:51 UTC, merged