Add single parameter `dd.data.jobs.enabled` to enable DJM
DataDog/dd-trace-java pull request #6972
Opened 2024-04-30 09:34 UTC by paul-laffon-dd

# What Does This Do

# Motivation

# Additional Notes

2024-05-02 15:30 UTC, gabe-ochoa commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +          propertyNameToSystemPropertyName("integration.spark-executor.enabled"), "true");
Once the apm intake work is done for #6967, can we just turn on all integrations?

2024-05-02 18:42 UTC, kr-igor requested changes
I think this change may cause some issues for customers who tries to use DSM in combination with DJM, as instrumentations required by DSM will be forcibly disabled. Could you also add "force enable" for DSM instrumentations if DSM_ENABLED = true? You can find these instrumentations by searching setDatastreamsCheckpoints.

2024-05-02 18:44 UTC, kr-igor commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +          propertyNameToSystemPropertyName("integration.spark-executor.enabled"), "true");
Do we want to disable sampling as well? It may be a big issue for some hight throughput systems with millions of operations per second.

2024-05-06 20:39 UTC, paul-laffon-dd commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +          propertyNameToSystemPropertyName("integration.spark-executor.enabled"), "true");
Changed it so that `dd.data.jobs.enabled=true` does not change the default for all integrations (enabled by default), only enables spark/long running spans

2024-05-06 20:39 UTC, paul-laffon-dd commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
> +          propertyNameToSystemPropertyName(TraceInstrumentationConfig.INTEGRATIONS_ENABLED),
The `setSystemPropertyDefault` is only changing the default, if the user explicitly set a parameter it will take precedence over the default

2024-05-06 20:49 UTC, kr-igor approved these changes

2024-05-07 10:07 UTC, merged