Map JSP stack traces to file names
DataDog/dd-trace-java pull request #7005
Opened 2024-05-08 10:59 UTC by jandro996

# What Does This Do

Add StratumManger to deal with SMAP Syntax from [Jakarta Debugging Support for Other Languages](https://jakarta.ee/specifications/debugging/2.0/jdsol-spec-2.0#smap-syntax)

Replace the StackTraceElement used to create the vulnerability location with the original file and line info

# Motivation

If we want to show proper filename for vulnerabilities in JSP, we’ll need to map JSP stack traces to file names.

# Additional Notes

Jira ticket: [APPSEC-4703]

2024-06-20 12:27 UTC, smola reviewed
A few comments, but I still did not review all the parsing logic.

2024-06-20 12:27 UTC, smola commented on internal-api/src/main/java/datadog/trace/api/iast/stratum/SourceMapper.java
> +public interface SourceMapper {
Do we expect more than one implementation?

2024-06-20 12:27 UTC, smola commented on dd-smoke-tests/springboot-tomcat-jsp/src/test/groovy/datadog/smoketest/springboot/IastSpringBootSmokeTest.groovy
> +    //command.add("-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005")
Please, remove debugging leftovers.

2024-06-20 12:27 UTC, smola commented on dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/iast/stratum/StratumManagerImplTest.groovy
> +  void 'test StratumManager analyzeClass'(){
```suggestion
  void 'test analyzeClass'(){
```
(redundant with suite name)

2024-06-20 12:27 UTC, smola commented on dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/iast/stratum/StratumManagerImplTest.groovy
> +  void 'test StratumManager shouldBeAnalyzed'(){
```suggestion
  void 'test shouldBeAnalyzed'(){
```

2024-06-20 12:27 UTC, smola commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/iast/stratum/AbstractStratum.java
> +public abstract class AbstractStratum {
Do we expect more implementations?

2024-06-25 11:54 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/iast-instrumenter/src/main/java/datadog/trace/instrumentation/iastinstrumenter/StratumListener.java
> +    if (StratumManagerImpl.shouldBeAnalyzed(type.getInternalName())) {
This is here just to get access to the class `byte[]` right?, I'm not sure about this approach as it will take a lot of wasted space, it's very likely that only a few jsps will need to have their metadata collected (the ones with vulnerabilities), and it will probably delay startup quite a bit. I think the best approach is to execute it only when computing the stack for a vulnerability.

2024-06-25 12:19 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/iast/stratum/StratumManagerImpl.java
> +        new ClassVisitor(262144) {
```suggestion
        new ClassVisitor(OpenedClassReader.ASM_API) {
```

2024-06-25 12:22 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/iast/stratum/StratumManagerImpl.java
> +        0);
```suggestion
        ClassReader.SKIP_CODE | ClassReader.SKIP_FRAMES);
```

2024-07-05 07:53 UTC, jandro996 commented on internal-api/src/main/java/datadog/trace/api/iast/stratum/SourceMapper.java
> +public interface SourceMapper {
There are two implementations, StratumExt that is what will be stored in the final map, and EmbeddedStratum that is an auxiliar structure to deal with embedded files while the final structure is resolved

2024-07-05 08:39 UTC, jandro996 commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/iast/stratum/AbstractStratum.java
> +public abstract class AbstractStratum {
There are two implementations, StratumExt that is what will be stored in the final map, and EmbeddedStratum that is an auxiliar structure to deal with embedded files while the final structure is resolved

2024-07-05 08:42 UTC, jandro996 commented on internal-api/src/main/java/datadog/trace/api/iast/stratum/SourceMapper.java
> +public interface SourceMapper {
Nope, I've chosen this approach to be able to access the map from agent-iast

2024-07-17 08:05 UTC, smola requested changes

2024-07-17 08:05 UTC, smola commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/iast/stratum/StratumExt.java
> +      LOG.error("Could not get input line number from stratum", e);
Log to debug level, this is unactionable for customers, and it's low impact. Since it has an exception, we'll be getting it through telemetry anyway.

2024-07-17 08:05 UTC, smola commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/iast/stratum/StratumManager.java
> +      LOG.error("Could not get resolved source map from smap", e);
Let's review all log messages in the PR. This one should be debug level too.

2024-07-18 06:34 UTC, jandro996 commented
Al changed reviewed to avoid logging at error level

2024-07-23 13:32 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/iast/stratum/StratumManager.java
> +  private boolean EMPTY_DEBUG_INFO;
What is the purpose of this flag?

2024-07-23 13:36 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +import static datadog.trace.api.config.IastConfig.*;
I think we should not use star imports as per the `CONTRIBUTING.md`

2024-07-23 15:58 UTC, jandro996 commented on internal-api/src/main/java/datadog/trace/api/Config.java
> +import static datadog.trace.api.config.IastConfig.*;
Thanks!!

2024-08-05 08:02 UTC, smola approved these changes

2024-08-07 06:56 UTC, jandro996 commented on dd-java-agent/instrumentation/iast-instrumenter/src/main/java/datadog/trace/instrumentation/iastinstrumenter/StratumListener.java
> +    if (StratumManagerImpl.shouldBeAnalyzed(type.getInternalName())) {
As we decide internally, we will keep the approach, with some limitations. It's disabled by default and if it's enabled by default and if enabled it has a max number of mappings

2024-08-07 08:55 UTC, manuel-alvarez-alvarez approved these changes

2024-08-07 12:36 UTC, merged

2026-01-14 16:26 UTC, bric3 commented
For reference the original spec: is [JSR 45](https://jcp.org/en/jsr/detail?id=45)