Added support for SQLi exploit
DataDog/dd-trace-java pull request #7051
Opened 2024-05-20 22:01 UTC by ValentinZakharov

# What Does This Do

# Motivation

# Additional Notes

Jira ticket: [PROJ-IDENT]

2024-05-27 09:27 UTC, smola requested changes
Missing configuration flag, and possibly RC capability announcement.

2024-05-27 10:07 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
> +          if (dbType != null) {
I believe the type is always non-null and in case of errors parsing the jdbc url it takes the value `database` as default.

2024-05-28 07:50 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
> +  public AgentSpan onStatementRaw(AgentSpan span, String sql) {
good catch, moved to `DatabaseClientDecorator`

2024-05-28 08:30 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
> +          if (dbType != null) {
I'm convinced that is possible to have `null` type

2024-05-28 08:33 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
> +          if (dbType != null) {
For instance here [HibernateDecorator.dbType()](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/hibernate/src/main/java/datadog/trace/instrumentation/hibernate/HibernateDecorator.java#L36-L38)
or here [DatanucleusDecorator.dbType()](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/datanucleus-4/src/main/java/datadog/trace/instrumentation/datanucleus/DatanucleusDecorator.java#L65-L67)

2024-05-29 10:07 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +          if (sql != null && !sql.isEmpty()) {
I've done optimisation, moved to the beginning of section, to skip callback code in case of `null` or empty

2024-05-29 10:07 UTC, ValentinZakharov commented on dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
> +  static final boolean DEFAULT_APPSEC_RASP_ENABLED = true;
done

2024-05-29 10:07 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +          if (dbType != null) {
same here

2024-05-29 11:15 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/gateway/Events.java
> +  static final int DATABASE_CONNECTION_ID = 16;
@ValentinZakharov you can go first, I'll merge mine after yours (still need to update a couple of things)

2024-05-29 11:16 UTC, manuel-alvarez-alvarez approved these changes
For a future PR, we are very close to have it also available for vertx sql.

2024-05-29 12:09 UTC, smola approved these changes

2024-05-29 13:03 UTC, amarziali commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +        DECORATE.onStatementRaw(span, sql);
I would use `copy` here because the original might be modified by dbm

2024-05-29 13:07 UTC, amarziali commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +  public AgentSpan onStatementRaw(AgentSpan span, String sql) {
I would just have one method to call: either `onStatement` for prepared ones either `onRawStatement` for raw ones.  ``onRawStatement` may call `onStatement` upon return

This will leave the orchestration responsability to the decorator and not have to call 2 methods on the instrumentation itself

2024-05-29 15:50 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +        DECORATE.onStatementRaw(span, sql);
Well spotted! Fixed

2024-05-29 15:51 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +  public AgentSpan onStatementRaw(AgentSpan span, String sql) {
Refactored as suggested

2024-05-29 15:53 UTC, amarziali approved these changes
looks ok from instrumentations pov

2024-05-29 16:55 UTC, ygree commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +    return span;
Looks like there's no need to return `span` b/o it's never modified inside of this method.

2024-05-29 17:03 UTC, ygree commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
> +  Address<String> DB_TYPE = new Address<>("server.db.system");
Perhaps add a short javadoc for these new fields, similar to most other fields in this class.

2024-05-29 17:05 UTC, ygree approved these changes
LGTM

2024-05-31 10:12 UTC, smola commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
> +            | CAPABILITY_ASM_RASP_SQLI);
Should probably not announce the capability if RASP is disabled.

2024-06-03 21:02 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +    return span;
Fixed

2024-06-03 21:02 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
> +  Address<String> DB_TYPE = new Address<>("server.db.system");
Done

2024-06-03 21:03 UTC, merged