Add tracer log file to tracer flare when datadog.slf4j.simpleLogger.logFile is NOT defined
DataDog/dd-trace-java pull request #7085
Opened 2024-05-29 12:05 UTC by cecile75

# What Does This Do
Collect tracer logs in a tracer log file in the tracer flare:
Changes:
- handle the case when no tracer log file is configured in the tracer configuration and we're able to create a temporary log file to collect the logs
- move the logic when a tracer log file is configured from TracerFlareService.java to LogReporter.java to avoid having multiple locations for handling the tracer log in tracer flare depending on the use cases

Note that:
- Use case when no tracer log file is configured in the tracer configuration and we're not able to create a temporary log file to collect the logs is not supported right now ( tracer.log file generated but no tracer logs inside)
- Use case when no tracer log file is configured  and the tracer flare is requested by Remote Config without DEBUG log level will lead to tracer flare with no tracer logs ( a tracer.log file is created but with the following content: "No tracer log file specified and no prepare flare event received") 

# Motivation

# Additional Notes

Jira ticket: [[APMAPI-85](https://datadoghq.atlassian.net/browse/APMAPI-85)]

2024-07-01 09:35 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
> +  private static String tmpLogFile;
This should be non-static

2024-07-01 09:48 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
> +      boolean b = parentFile.mkdirs();
Avoid single-character variable names unless the usual loop variables: `i`, etc.

Also elsewhere we're using the new NIO approach to check and create directories, like this:
```
try {
  Path tempPath = Paths.get(...);
  Path parentPath = tempPath.getParent();
  if (!Files.isDirectory(parentPath)) {
    Files.createDirectories(parentPath);
  }
  outputPath = Files.createFile(tempPath);
  PrintStreamWrapper.start(outputPath);
} catch (IOException e) {
  // Nothing to do, file creation failed, we don't have access to log yet
}
```
Note that `getParentFile` may return `null` for certain paths.

2024-07-01 09:53 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
> +        || !(new File(configuredLogFile).exists())) {
This is the same logic as in `prepareForFlare` - you could extract this to a method such as `logFileIsNotConfigured()`

2024-07-01 09:56 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
> +            TracerFlare.addBinary(zip, "tracer.log", readAllBytes(Paths.get(tmpLogFile)));
Why binary when we expect the log file to be text?

2024-07-01 10:00 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatSettings.java
> +        {
brackets are not necessary here

2024-07-01 10:02 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +  private static boolean activate = false;
`captureOutput` would be a better name

2024-07-02 10:44 UTC, cecile75 commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
> +  private static String tmpLogFile;
I'll make the changes

2024-07-02 10:46 UTC, cecile75 commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
> +      boolean b = parentFile.mkdirs();
Noted for the single-character variable names.
Ill make the changes and add a check for parentPath != null as Files.isDirectory(parentPath) in this case will trigger a java.lang.NullPointerException

2024-07-12 10:03 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +      currentSize += x.getBytes().length + lineSeparatorLength;
All the tracer logging should use ASCII encoding, which means `x.getBytes().length` is equivalent to `x.length()`

Using `x.length()` will be much more performant because it avoids creating an array which we don't end up using. Since the logfile limit check is a soft limit, meaning that if we go slightly over it's not really issue, I think this is a reasonable compromise.

2024-07-12 10:06 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +      currentSize += x.getBytes().length + lineSeparatorLength;
We could go a step further and simplify the line encoding estimate as:
```
private static final int lineSeparatorLength = Platform.isWindows() ? 2 : 1;
```

2024-07-12 10:29 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatSettings.java
> +        return new PrintStreamWrapper(System.err);
We could add a `PrintStreamWrapper printStreamWrapper` variable at the top of this method and replace the wrapper `return` statements with assigning this variable followed by `break;`

Then at the end we could call:
```
LogReporter.register(printStreamWrapper);
return printStreamWrapper;
```

We'd call a different reporter method for the situation where we're writing to a file and know we can write to it:
```
outputStream = new FileOutputStream(outputFile); 
PrintStream printStream = new PrintStream(outputStream, true);
LogReporter.register(outputFile);
return printStream;
```

That would avoid the need to have all those static fields/methods in `PrintStreamWrapper`, because `LogReporter` would now have either a `PrintStreamWrapper` instance or the `outputFile` stored as static fields. It would also allow us to remove some logic in `LogReporter` to determine whether we're logging to a file or not.

2024-07-12 10:31 UTC, mcculls requested changes
Suggested some refactoring of `PrintStreamWrapper` and `LogReporter` to reduce the number of static fields, as well as optimizing some of the length checks - all the other file changes look good, it's just cleaning up `PrintStreamWrapper` + `LogReporter` now

2024-07-18 10:33 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +  public OutputStream getMainPrintStream() {
Small suggestion:
```suggestion
  public OutputStream getOriginalPrintStream() {
```
`getOriginalStream` would also be ok

2024-07-18 10:34 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +  private static final int lineSeparatorLength = Platform.isWindows() ? 2 : 1;
Our code-style is to use upper-case for constants
```suggestion
  private static final int LINE_SEPARATOR_LENGTH = Platform.isWindows() ? 2 : 1;
```

2024-07-18 10:36 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +  public void clean() {
```suggestion
  public void stopCapturing() {
```

2024-07-18 10:36 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +  public void start(Path filepath) {
```suggestion
  public void startCapturing(Path filepath) {
```

2024-07-18 10:37 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +  private PrintStream printStream = null;
```suggestion
  private PrintStream capturingStream = null;
```

2024-07-18 10:42 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +  private boolean captureOutput = false;
```suggestion
  private volatile boolean captureOutput = false;
```
If we make this `volatile` then any changes before `captureOutput = true` would be visible to other threads checking `if (captureOutput) {`

2024-07-18 10:43 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +    captureOutput = false;
lets move this to the end - that way when we make `captureOutput` a `volatile` all the preceding changes will be made visible to other threads

2024-07-18 10:56 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +      }
Theoretically this could lead to `currentSize` overflowing and wrapping round.

It's also not safe to use `+=` on multiple threads without synchronization.
```suggestion
      int outputLength = x.length() + lineSeparatorLength;
      if (currentSize + outputLength < LogReporter.MAX_LOGFILE_SIZE_BYTES) {
        synchronized (this) {
          printStream.println(x);
          currentSize += outputLength;
        }
      } else {
        captureOutput = false;
      }
```

2024-07-18 10:57 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +  private int currentSize = 0;
We should also make this `volatile` since we use it for checks outside of `synchronized` that could come from different threads
```suggestion
  private volatile int currentSize = 0;
```

2024-07-18 10:59 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
> +  private static File outputConfiguredFile;
```suggestion
  private static File configuredLogFile;
```

2024-07-18 11:00 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
> +  private static PrintStreamWrapper outputPrintStreamWrapper;
```suggestion
  private static PrintStreamWrapper wrappedPrintStream;
```

2024-07-18 11:02 UTC, mcculls commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
> +  public LogReporter() {}
Make this `private` to stop people from accidentally creating other instances.
```suggestion
  private LogReporter() {}
```

2024-07-18 11:08 UTC, mcculls reviewed
Looks good - just a few minor suggestions then it's ready for merging!

2024-07-18 13:02 UTC, cecile75 commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
> +    captureOutput = false;
Thank you for the blogpost!

2024-07-18 15:26 UTC, merged