add isRemote
DataDog/dd-trace-java pull request #7108
Opened 2024-06-01 17:06 UTC by am312

# What Does This Do

# Motivation

# Additional Notes

Jira ticket: [PROJ-IDENT]

2024-06-02 14:31 UTC, mcculls requested changes
You shouldn't need so many changes, why not just:
* add the `isRemote` argument to just the one `DDSpanContext` constructor used by `CoreTracer.buildSpanContext`
* then update `CoreTracer.buildSpanContext` to set `isRemote` to `true` in the existing block where `parentContext instanceof ExtractedContext` and `false` everywhere else

You don't need to update all the other constructors, just let them default `isRemote` to `false` when calling the updated constructor.

Also whenever you add elements to a constructor, consider creating a new constructor with the additional argument and having the old constructor delegate to the new one with a default for the new argument. (Whether this is appropriate depends on how many places call the original constructor.)

2024-06-03 05:59 UTC, am312 commented
>  just let them default isRemote to false when calling the updated constructor.

Updated as suggested, thanks.  I originally thought passing a default value would not be possible because each test would now need to be evaluated to see if it is remote or not otherwise the default value may be inaccurate.  If the `CoreTracer.buildSpanContext` usage you mention is the only place where `isRemote==true` then that simplifies things a lot.

Do you know if `DDCoreSpecification` can [safely default to false](https://github.com/DataDog/dd-trace-java/blob/ebf3c2870cf62b3c2c98614e4295cf38eba263d1/dd-trace-core/src/test/groovy/datadog/trace/core/test/DDCoreSpecification.groovy#L84) here too?

2024-06-03 08:35 UTC, mcculls commented
> Do you know if DDCoreSpecification can safely default to false here too?

Yes, since the `buildSpan` method is used to test local span behaviour - any new tests that need `iRemote=true`  could use a new method such as `buildRemoteSpan`.

2024-06-03 16:45 UTC, mcculls approved these changes

2024-06-03 16:51 UTC, merged