Ensure manually created OpenTelemetry spans are compliant with trace metrics
DataDog/dd-trace-java pull request #7138
Opened 2024-06-07 10:06 UTC by mcculls

# What Does This Do

Translates the `http.response.status_code` attribute (OpenTelemetry) to `http.status_code` (Datadog)

# Additional Notes

This PR also fixes an issue where the `AttributeKey` form of the `setAttribute` method was not covered for non-array reserved attributes.

2024-06-07 15:18 UTC, amarziali approved these changes

2024-06-07 15:29 UTC, zarirhamza requested changes
`http.request.status_code` is an int value as per [otel](https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/) 

BUT `http.status_code` is a string value following datadog standards

Just want to confirm, does this PR follow those standards?

2024-06-07 18:50 UTC, mcculls commented
Hi @zarirhamza - yes, `setHttpStatusCode` is the method used by all the web integrations.

If you want to follow the sequence it goes:
* [DDSpan.setHttpStatusCode](https://github.com/DataDog/dd-trace-java/blob/v1.34.0/dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java#L508)
* [DDSpanContext.setHttpStatusCode](https://github.com/DataDog/dd-trace-java/blob/v1.34.0/dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java#L670)
* that special `httpStatusCode` is then treated specially when it's sent as metadata
* [DDSpanContext.processTagsAndBaggage](https://github.com/DataDog/dd-trace-java/blob/v1.34.0/dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java#L811)
* [TraceMapperV0_4.accept](https://github.com/DataDog/dd-trace-java/blob/bff441bbdf82a488e4690abc96352fc0b283621f/dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java#L121)

TL;DR is that this is the same method used by Datadog integrations in the Java tracer to set the HTTP statuis for a span, so given that is producing the right payloads this will also produce the expected payload.

2024-06-07 19:23 UTC, zarirhamza approved these changes

2024-06-07 19:23 UTC, merged

2024-06-10 08:51 UTC, PerfectSlayer reviewed
> This PR also fixes an issue where the AttributeKey form of the setAttribute method was not covered for non-array reserved attributes.

Nice catch. Do you think I should also improve the original convention tests to check builder and attribute keys too?

2024-06-10 08:56 UTC, mcculls commented
> Nice catch. Do you think I should also improve the original convention tests to check builder and attribute keys too?

Yes, it would be good to do at some point

2024-06-11 15:25 UTC, PerfectSlayer commented
I just made a PR about it.