Apply appsec rate limiter on event instead of when request end
DataDog/dd-trace-java pull request #7221
Opened 2024-06-19 13:49 UTC by jandro996

# What Does This Do

 - check rate limiter once per request
 - keep cohesion between all appsec events in the same request in terms of rate limit

# Motivation
We need to propagate sampling decision on appsec event,  not on request end

# Additional Notes

Jira ticket: [PROJ-IDENT]

2024-06-21 09:23 UTC, jandro996 commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
> +            RATE_LIMITER,
My bad, it's not necessary anymore since user tracking events are not limited by the appsec rate limiter.

2024-06-24 08:52 UTC, smola requested changes

2024-06-24 08:52 UTC, smola commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +              // Report all collected request headers on user tracking event
Beware conflicts with https://github.com/DataDog/dd-trace-java/pull/7222

2024-06-24 08:52 UTC, smola commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
> +            if (log.isDebugEnabled()) {
No need to check if `isDebugEnabled` if the log call is already `debug` and it doesn't do any extra processing.

2024-06-24 11:28 UTC, jandro996 commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +              // Report all collected request headers on user tracking event
I've talked with @manuel-alvarez-alvarez, and we are aligned

2024-06-25 08:38 UTC, smola approved these changes

2024-06-25 08:52 UTC, ValentinZakharov commented
Can we rename `ReteLimiter` to `WafRateLimiter` and move it to `com.datadog.appsec.powerwaf` ?

2024-06-25 08:54 UTC, manuel-alvarez-alvarez approved these changes

2024-06-25 08:54 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
> +  private static RateLimiter RATE_LIMITER; // static for testing purpose
Is there any particular reason to keep `RateLimiter` in `AppSecSystem`?
I'd rather move it into `PowerWAFModule` 🤔

2024-06-25 09:02 UTC, ValentinZakharov commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
> +            activeSpan.getLocalRootSpan().setTag(Tags.ASM_KEEP, true);
I don't get why you set `ASM_KEEP` in two places here in `PowerWAFModule` and `GatewayBridge` ?

2024-06-25 11:36 UTC, jandro996 commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
> +            activeSpan.getLocalRootSpan().setTag(Tags.ASM_KEEP, true);
I've added a new comment to clarify this

2024-06-25 11:37 UTC, jandro996 commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
> +  private static RateLimiter RATE_LIMITER; // static for testing purpose
I've moved the RateLimiter to PowerWafModule

2024-06-25 13:07 UTC, ValentinZakharov approved these changes

2024-06-26 05:55 UTC, merged