Introduced SQL-injection blocking
DataDog/dd-trace-java pull request #7231
Opened 2024-06-21 22:42 UTC by ValentinZakharov

# What Does This Do
Implemented blocking functionality for the SQL-injection Exploit Prevention.

# Motivation

# Additional Notes
This is part of Exploit prevention initiative (RASP)

Jira ticket: [APPSEC-46818]

2024-06-25 09:30 UTC, smola requested changes

2024-06-25 09:30 UTC, smola commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +        // suppress anything else
Needs to be logged (debug level), just as it happens with suppress = Throwable.

2024-06-25 15:38 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +        // suppress anything else
Good point, added log message!

2024-06-26 07:14 UTC, PerfectSlayer approved these changes
LGTM for `internal-api` 👍

2024-06-26 07:21 UTC, amarziali commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +      "org.slf4j.LoggerFactory",
You shouldn't inject log4j classes

2024-06-26 07:22 UTC, amarziali requested changes
slf4j  classes should never be injected

2024-06-26 07:42 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +          Flow<Void> flow = connectDbCallback.apply(ctx, dbType);
Can we block during the connection phase? (seems weird since we do not have a SQL query yet)

2024-06-26 10:53 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +      "org.slf4j.LoggerFactory",
Thanks, fixed

2024-06-26 11:55 UTC, amarziali commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> -    @Advice.OnMethodEnter(suppress = Throwable.class)
why the suppression has been removed?

2024-06-26 11:58 UTC, amarziali commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> -    @Advice.OnMethodEnter(suppress = Throwable.class)
ok found the answer below. :)

2024-06-26 11:58 UTC, amarziali approved these changes

2024-06-26 12:37 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> -    @Advice.OnMethodEnter(suppress = Throwable.class)
That was in purpose to let blocking exception bubble-up from `StatementAdvice` to http server advices.
The idea is - to suppress everything except `BlockingException`. So, instead of `suppress = Throwable.class`, I used custom `try-catch` to suppress exceptions.

2024-06-26 16:00 UTC, ValentinZakharov commented on dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
> +          Flow<Void> flow = connectDbCallback.apply(ctx, dbType);
We are checking query statement right before it's executed (not when it's built). That's why, we have database connection first and sql query execution, after. 
I think, blocking on connection phase can increase code complexity.

2024-06-27 09:47 UTC, manuel-alvarez-alvarez approved these changes

2024-06-27 17:09 UTC, manuel-alvarez-alvarez commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +          ctx.setDbType(dbType);
Multiple database calls (with potentially different providers) can coexist in a single request and adding this to the context might trigger race conditions. Since we always have the type in the decorator (it's saved in a context store linked to the jdbc Connection), whey don't we pass the type as an argument with the sql callback?

2024-06-28 12:23 UTC, smola commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +          ctx.setDbType(dbType);
As discussed offline, needs to be addressed at libddwaf-level, since it does not seem clear what would be the correct way to pass different pairs of query/dbtype.

2024-07-01 12:08 UTC, smola commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +      return activateSpan(span);
I'm not sure this is equivalent to the previous code. If an exception was thrown at `DECORATE.onStatement(span, copy)`, `activateSpan(span)` would not be called.

2024-07-01 15:31 UTC, ValentinZakharov commented on dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
> +      return activateSpan(span);
Indeed, return value is wrong.
Talked to @mcculls to confirm we need return `null` in case of suppressed `Throwable`.
Fixed

2024-07-05 09:25 UTC, smola approved these changes

2024-07-05 11:25 UTC, merged