Report span metrics for Exploit Prevention
DataDog/dd-trace-java pull request #7273
Opened 2024-07-03 11:45 UTC by ValentinZakharov

# What Does This Do
Added new span metrics for Exploit prevention:

- `_dd.appsec.rasp.duration` - cumulative runtime in nanoseconds of every call to libddwaf thought a RASP instrumentation with a request
- `_dd.appsec.rasp.duration_ext` - cumulative runtime in nanoseconds of libddwaf call + binginds cost through RASP instrumentation with a request
- `_dd.appsec.rasp.rule.eval` - counts the number of times libddwaf calls per request

# Motivation
This is part of Exploit prevention to let collect useful metrics for future analysis of effectiveness.

# Additional Notes

Jira ticket: [APPSEC-47228]

2024-07-04 09:02 UTC, smola requested changes
The overall idea looks good to me. Just a minor comment, and a request for tests.

2024-07-04 09:02 UTC, smola commented on dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFStatsReporterSpecification.groovy
> +  void 'reporter reports war/rasp timings and version'() {
Can we leave the old test and add two new ones? Overall, one with WAF only, one with RASP only, one with both. That would probably cover all code paths.

2024-07-04 09:02 UTC, smola commented on dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFStatsReporterSpecification.groovy
> +  void 'reporter reports war/rasp timings and version'() {
```suggestion
  void 'reporter reports waf/rasp timings and version'() {
```

2024-07-08 08:05 UTC, smola approved these changes

2024-07-08 08:31 UTC, PerfectSlayer approved these changes

2024-07-08 09:50 UTC, merged