Implement debug context propagation to enable live debugging of java applications
DataDog/dd-trace-java pull request #7286
Opened 2024-07-05 15:53 UTC by evanchooly

This PR enhances the exist span origin feature with optional snapshot captures.  It introduces variable configuration via the `_dd.p.debug` tag currently set via propagation tags.  It's a follow on implementation of two RFCs:

1. [Distributed Debugging](https://docs.google.com/document/d/1QJKBGvgAlttqx0PYuQBykhQ2iBVtPPwVCB-z6TclxFM/edit?pli=1#heading=h.o5gstqo08gu5)
2. [Span Origins](https://docs.google.com/document/d/1lhaEgBGIb9LATLsXxuKDesx4BCYixOcOzFnr4qTTemw/edit?pli=1#heading=h.o5gstqo08gu5)

Both specs are currently in flux, however, so to some extent this PR is ahead of the curve.  There are some aspects that could likely be cleaned up and I will try to call out the one specific case I'd like some feedback on in case a better option presents itself.

2024-07-05 15:54 UTC, evanchooly commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
> +    boolean isExcluded(String className);
This was added because I need to filter out classnames in the `debugger-bootstrap` module where there classname filtering type is not available.

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
> +    if (config.isDebuggerEnabled()) {
`isDebuggerEnabled()` is for `dd.dynamic.instrumentation.enabled` so I think we should have dedicated option for that.

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/DebugSnapshotProbe.java
> +public class DebugSnapshotProbe extends LogProbe {
suggestion: Would use the name `SpanDebuggerProbe`

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
> +    }
need to be reverted and rebase to use #7246

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/DebugSnapshotProbe.java
> +  private void applySOTags(AgentSpan span) {
rename to applySpanOriginTags

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/DebugSnapshotProbe.java
> +  }
not always correct!
example: non-public top level classes or inner classes:
in `Main.java`:
```java
public class Main {
  public static class Inner {
  }
}

class TopLevelOne {
}
```

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/DefaultSnapshotHandler.java
> +public class DefaultSnapshotHandler implements DebuggerContext.SnapshotHandler {
Suggestion: Would name DefaultSpanDebugger

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
> +  public interface SnapshotHandler {
would name `SpanDebugger`

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
> +    String handleSnapshot(String signature);
would name `captureSnapshot`

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/DistDebug.java
> +public final class DistDebug {
`SpanDebug`

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/DistDebug.java
> +  public static boolean isDebugEnabled(AgentSpan span, int... levels) {
`isSpanDebugEnabled`

2024-07-08 13:51 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationAcceptor.java
> +    DEBUG,
`SPAN`

2024-07-08 18:15 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
> +    if (config.isDebuggerEnabled()) {
hrm.  any suggestions?  I can only think of rather verbose options.

2024-07-08 18:19 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/DebugSnapshotProbe.java
> +  }
yes, this is a known shortcoming.  I mentioned it to Omer but we haven't circled back on it.  It's only there because the RFC lists the file name as a required field but, as you know, it's a tricky proposition in Java.  In fact, this completely breaks for any JVM language other than Java.

2024-07-08 18:27 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationAcceptor.java
> +    DEBUG,
just `SPAN` and not `SPAN_DEBUG` or something?

2024-07-08 21:07 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
> +    if (config.isDebuggerEnabled()) {
`isSpanDebuggerEnabled` and once we have settled for the official env variable you will wire on that.

2024-07-08 21:08 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/DebugSnapshotProbe.java
> +  }
maybe worth a comment then to explain the shortcoming

2024-07-08 21:10 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationAcceptor.java
> +    DEBUG,
I am fine with `SPAN` as we have already `EXCEPTION` but if you want to be more repcise you can use `SPAN_DEBUG`

2024-07-16 09:26 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDebuggerProbe.java
> +        StackTraceElement entry = entries.get(0);
not sure we are guarantee to have at least element in the list here. we should check at least is not empty

2024-07-16 09:26 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/SpanDebuggerProbeManager.java
> +  public String createProbesForException(StackTraceElement element, String signature) {
`createProbesForSpan`

2024-07-19 10:38 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
> +    }
Why putting this here?
why not having calling it from `DebuggerAgent` along with the call to initExceptionDebugger?

2024-07-19 10:38 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDebuggerProbe.java
> +  }
not sure it's worth to create a specific Status here as you are not storing specific fields in it

2024-07-19 10:38 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDebuggerProbe.java
> +  }
Status is here to carry on some specific data from evaluate phase to commit phase

2024-07-19 10:38 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/Fingerprinter.java
> +  public static String bytesToHex(byte[] bytes) {
by moving the fingerprinting of the Frame in this class, no need to make it public

2024-07-19 10:38 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/DefaultSpanDebugger.java
> +  }
could we move this method to `Fingerprinter` class?

2024-07-19 10:38 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/SpanDebug.java
> +  }
are we still using those methods?

2024-07-19 10:38 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/SpanDebug.java
> +  }
are we still using this method?

2024-07-19 10:38 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/DefaultSpanDebugger.java
> +  }
Can we consider to have a lighter hashing mechanism for the element?
For Exception Replay we are using a digest because we have different elements (exception type + whole stacktrace) but here maybe concatenating the info of the StackTraceElement is enough to give unicity and probably cheaper than a digest on it.
But we could assess it with microbenchmark. as the ultimate goal is to be on by default we need to be careful on this.
But we can keep it like this for this PR and analyze and improve before getting it on by default

2024-07-19 14:15 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDebuggerProbe.java
> +  }
I was wondering about that, too.  I'll just yank it.

2024-07-19 14:20 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/DefaultSpanDebugger.java
> +  }
I agree with the general sentiment.  In one of the future revs/refinements I have in mind, i think we'll change up how we do/use the fingerprinting to be a bit more efficient in general and I think this method might go away but we'll see how that works out.

2024-07-19 14:22 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
> +    }
Currently there are two different values to enable either feature.  If we want to view it as enable-one-enable-all, we could combine but I don't know that we want that yet.

2024-07-19 14:24 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/SpanDebug.java
> +  }
At the moment, no. I was thinking to leave them "just in case" but it's not like it's not trivial to recreate.  I'll remove.

2024-07-19 14:25 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/SpanDebug.java
> +  }
I use it for debugging quite often.

2024-07-19 15:30 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
> +    }
Exception Replay and Span Debugger are not connected for me so it should be separated. Because right now with this code, you need to enable exception replay to make sure Span debugger can work.

2024-07-19 15:35 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
> +    }
forget it I misread, sorry!

2024-07-19 15:35 UTC, jpbempel approved these changes

2024-07-23 18:03 UTC, shatzi commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDebuggerProbe.java
> +public class SpanDebuggerProbe extends LogProbe implements FrameAware {
maybe we should rename this to SpanCodeOriginProbe. to avoid confusion with DebuggerProbe down the line.
at test side of the code you called "code_origin" so it would make sense to see "code_origin/SpanCodeOriginProbeTest"

WDYT?

2024-07-23 18:03 UTC, shatzi commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDebuggerProbe.java
> +    if (isSpanDebugEnabled(span, CAPTURE_ORIGIN_FRAMES, CAPTURE_ALL_PROBES)) {
I don't think CAPTURE_ALL_PROBES is required.. this is just span origin frames. right?

2024-07-23 18:54 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/snapshot/DefaultSpanDebugger.java
> +    String fingerprint = Fingerprinter.fingerprint(element);
it uses only the top most element so a new probe only gets created if different lines are involved.

2024-07-23 19:04 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDebuggerProbe.java
> +      List<StackTraceElement> entries = entries();
item 3 is definitely on my radar and it's something I plan to test for and mitigate hopefully *after* this PR.  I have better testing in place now so creating this scenario won't be difficult.

2024-07-23 19:07 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDebuggerProbe.java
> +public class SpanDebuggerProbe extends LogProbe implements FrameAware {
I'm all for a rename.  This name was picked because it was better than what came before but not super great on its own.  I've been leaning toward `CodeOriginProbe` simply because it seems there are plans to not necessarily tie some things to spans/traces.  Also, `SpanCodeOriginProbe` is a bit of a mouthful.  I haven't really liked this current name because it's far too similar to `SpanDecorationProbe` and autocomplete gets dicey.  I've held off renaming because the actual name of the feature (span origin vs code origin) still has not been settled.

2024-07-23 19:11 UTC, evanchooly commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDebuggerProbe.java
> +    if (isSpanDebugEnabled(span, CAPTURE_ORIGIN_FRAMES, CAPTURE_ALL_PROBES)) {
the names of values, and indeed their bitmask nature, have become less obviously useful the more I code around it.  The bitmask nature of it all is a little awkard as it implies state compositions but i'm not sure it's ever being used that way in practice.  A simple numerical/enum value which implies that "this level and all previous" levels apply is a little less awkward in practice, I think, and fits with the notion that the higher values are suggestive of a wider and wider net we're casting to collect information.

2024-07-24 11:05 UTC, mcculls requested changes
The CI tests show several instrumentation errors related to not finding the `SpanOriginInfo` class - those will need to be fixed before this can be merged.

Also was it intentional to remove the `InstrumenterConfig.get().isSpanOriginEnabled()` checks? Without those the span-origin code will now run everywhere - even when not using live debugging.

2024-07-31 20:39 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/PTagsFactory.java
> +      assert tagPairs == null || tagPairs.size() % DEBUG_PROPAGATION_DEFAULT == 0;
^ this looks like a bad replace from Intellij, the reason for this assert is that the `tagPairs` list is even, i.e. every tag key is accompanied by a tag value - this is not related to `DEBUG_PROPAGATION_DEFAULT` apart from it just happening to have the same value

2024-07-31 20:50 UTC, mcculls commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +        return Integer.parseInt((String) value);
do we know how likely it would be to have a string value under `Tags.PROPAGATED_DEBUG` that isn't a number?

I assume it will be rare/impossible - just want to make sure we don't accidentally introduce a situation where we continually create lots of `NumberFormatException`s. In other words this approach is fine if we're confident the data will parse, with the catch as a failsafe. But for situations where the data could often be non-parseable then we might want to probe the initial character(s) to avoid excessive exceptions being created.

2024-07-31 21:00 UTC, mcculls commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/spanorigin/SpanOriginInfo.java
> +        || "true".equals(System.getProperty("dd.trace.span.origin.enabled"))) {
This won't be performant - you'll end up calling `System.getProperty` repeatedly which has a non-trivial cost.

For testing you should extend `DDSpecification` and use the `injectSysConfig` method to modify the config. (There are also methods to remove system properties, as well as set/remove environment variables/)

The `DDSpecification` class transforms the `Config` and `InstrumenterConfig` objects so they can be safely mutated during testing, while preserving their static nature which is important for performance reasons at runtime.

2024-07-31 21:06 UTC, mcculls commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/spanorigin/SpanOriginInfo.java
> +        || "true".equals(System.getProperty("dd.trace.span.origin.enabled"))) {
If you're not able to use the `DDSpecification` class for some reason then you'll need to use a forked test - to do this change the name of the test class from `SomeTest` to `SomeForkedTest` and our gradle setup will run each test using a different JVM - that would avoid static state leaking across the tests.

2024-07-31 21:07 UTC, mcculls commented on dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/spanorigin/SpanOriginInfo.java
> +        || "true".equals(System.getProperty("dd.trace.span.origin.enabled"))) {
Same comment here - the config code has been carefully designed for performance, and calling `System.getProperty` directly bypasses that

2024-08-01 14:13 UTC, evanchooly commented on dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/PTagsFactory.java
> +      assert tagPairs == null || tagPairs.size() % DEBUG_PROPAGATION_DEFAULT == 0;
oh, wow.  i hadn't even noticed that!  definitely a bad replacement.

2024-08-01 14:16 UTC, evanchooly commented on dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
> +        return Integer.parseInt((String) value);
In a subsequent, update all this will be changed up and this method will go away as it's the only use.  I'd like to leave it for now until we can follow up with that update.  the design around this feature has shifted and the code will be updated soon.

2024-08-01 14:36 UTC, dougqh commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/Fingerprinter.java
> +      MessageDigest digest = MessageDigest.getInstance("SHA-256");
You might be better off doing the getInstance during static initialization.
Then the static will be constant propagated by the JIT, so you have less overhead.

2024-08-02 18:21 UTC, mcculls commented on dd-java-agent/instrumentation/span-origin/src/main/java/datadog/trace/instrumentation/span_origin/EntrySpanOriginInstrumentation.java
> +    this.matcher = NameMatchers.namedOneOf(getAnnotations());
side note: we prefer to static import `NameMatchers` / `HierarchyMatchers` methods in the rest of the codebase

2024-08-02 18:25 UTC, mcculls approved these changes
+1, thanks for your patience!

2024-08-02 18:25 UTC, merged

2024-08-12 12:03 UTC, jpbempel commented on dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/Fingerprinter.java
> +      MessageDigest digest = MessageDigest.getInstance("SHA-256");
Nope! this is not thread safe!!
MessageDigest keeps state