Report telemetry metrics for Exploit Prevention
DataDog/dd-trace-java pull request #7314
Opened 2024-07-12 09:07 UTC by ValentinZakharov

# What Does This Do
Introduced telemetry metrics for Exploit Prevention.
- `appsec.rasp.rule.eval` - counts the number of times a rule type is evaluated
- `appsec.rasp.rule.match` - counts the number of times a rule type has a match
- `appsec.rasp.timeout` - counts the number of times a timeout was hit when evaluating a specific rule type

# Motivation
This is part of Exploit prevention to let collect and report telemetry metrics

# Additional Notes

Jira ticket: [APPSEC-47228]

[APPSEC-47228]: https://datadoghq.atlassian.net/browse/APPSEC-47228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-12 11:21 UTC, smola commented on internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
> +  public void raspRuleEval(final String ruleType) {
Using a HashMap, and converting to string, is far from ideal in terms of performance. There's a fixed number of types, and so there can be a fixed number of counters. An array would do the job, and you wouldn't need to convert to string. We do something like this here:

https://github.com/DataDog/dd-trace-java/blob/63f16d7b20ae8ffdf7910c9419f730b8ce1d62f7/internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetricCollector.java#L105-L121

(that one on IAST needs to do more stuff, so for RASP is doesn't need that much complexity though)

2024-07-15 21:03 UTC, ValentinZakharov commented on internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
> +  public void raspRuleEval(final String ruleType) {
Thanks, fixed

2024-07-17 14:00 UTC, smola approved these changes

2024-07-17 17:10 UTC, jandro996 approved these changes
Not related with this PR

IMHO, we need to think in refactor the GatewayBridge in some way, as we will implement new rasp features seems that this class will contain a lot of logic for different purpose

2024-07-18 08:53 UTC, mcculls commented on internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
> +  private static final Map<RuleType, AtomicLong> respTimeoutCounter = new EnumMap<>(RuleType.class);
Since `RuleType` is an `enum` and there aren't many entries you could replace each of these counter maps with an `AtomicLongArray` with a size of `RuleType.values().length` (you can add a method to the `enum` to make it more readable, like in https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-core/src/main/java/datadog/trace/core/propagation/PropagationTags.java#L42)

Then just use the `ordinal` from the `enum` to access the appropriate element in each `AtomicLongArray`.

2024-07-18 08:59 UTC, mcculls requested changes
Generally looks good, but I'd like to see each `EnumMap` of `AtomicLong` replaced by an `AtomicLongArray` - this simplifies the storage, especially since `EnumMap` is not thread-safe and would require synchronization around `computeIfAbsent`

2024-07-18 11:38 UTC, mcculls approved these changes

2024-07-18 11:53 UTC, merged