Improve smoke tests and progagation for Untrusted Deserialization vulnerability
DataDog/dd-trace-java pull request #7374
Opened 2024-07-31 14:18 UTC by Mariovido

# What Does This Do
This improves the smoke tests and add new instrumentations to ensure the propagation.

# Motivation
Improve the propagation and smoke tests for the Untrusted Deserialization

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [APPSEC-54157]

2024-08-20 11:21 UTC, jandro996 approved these changes
LGTM!

2024-08-21 08:57 UTC, smola requested changes

2024-08-21 08:57 UTC, smola commented on dd-java-agent/instrumentation/commons-fileupload/build.gradle
>    latestDepTestImplementation group: 'org.apache.commons', name: 'commons-fileupload2', version: '+'
You will also need to add a line like this, with a version specifier like `1.+`. We have a CI job and gradle tasks that also run the test with the latest version of the package, rather than just the one used for the main compile/test (e.g. `1.5` in this case).

2024-08-21 08:57 UTC, smola commented on dd-java-agent/instrumentation/commons-fileupload/build.gradle
> +  compileOnly group: 'commons-fileupload', name: 'commons-fileupload', version: '1.5'
Are the classes for fileupload and fileupload2 all different, with different instrumenters? If that's the case, we should probably have two separate modules, `commons-file-upload-1` and `commons-file-upload-2`.

2024-08-21 13:08 UTC, Mariovido commented on dd-java-agent/instrumentation/commons-fileupload/build.gradle
>    latestDepTestImplementation group: 'org.apache.commons', name: 'commons-fileupload2', version: '+'
Already added :)

2024-08-21 13:43 UTC, Mariovido commented on dd-java-agent/instrumentation/commons-fileupload/build.gradle
> +  compileOnly group: 'commons-fileupload', name: 'commons-fileupload', version: '1.5'
As talked in private we will follow with this PR and all references to the commons-fileupload2 will be removed as is not really being used

2024-08-22 08:13 UTC, smola approved these changes

2024-08-22 08:39 UTC, merged