Add instrumentation for snakeyaml
DataDog/dd-trace-java pull request #7406
Opened 2024-08-09 09:22 UTC by Mariovido

# What Does This Do
Adds instrumentation for snakeyaml library versions prior to 2.0

# Motivation
Detect untrusted deserialization vulnerability for the load method in the Yaml class of the snakeyaml library

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [APPSEC-54452]

2024-08-19 11:33 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UntrustedDeserializationModuleImpl.java
> +  public void onReader(@Nullable Reader reader) {
IMHO is easy to have only one method that recieves an Object as in the end we always call SinkModuleBase#checkInjection(VulnerabilityType, Object)

2024-08-19 11:45 UTC, jandro996 commented on dd-java-agent/instrumentation/snakeyaml/src/main/java/datadog/trace/instrumentation/snakeyaml/SnakeYamlInstrumenter.java
> +            if (data instanceof InputStream) {
linking with my previous comment in UntrustredDeserializationModuleImpl we can remove all these data instance of ifs and keep one untrustedDeserialization.onObject(data)

2024-08-19 11:53 UTC, jandro996 commented on dd-java-agent/instrumentation/snakeyaml/src/test/java/foo/bar/TestSnakeYamlSuite.java
> +public class TestSnakeYamlSuite {
If you are using a callee instrumentation it's not necessary to create a Suite class to test it.

2024-08-19 11:56 UTC, jandro996 commented on internal-api/src/main/java/datadog/trace/api/iast/sink/UntrustedDeserializationModule.java
>    void onInputStream(@Nullable InputStream is);
Related with my other comments

```suggestion
  void onObject(@Nullable Object obj); 
```

2024-08-19 11:58 UTC, jandro996 requested changes
IMHO we can improve it a little bit removing some complexity like the multiple Module methods

2024-08-19 12:55 UTC, Mariovido commented on dd-java-agent/instrumentation/snakeyaml/src/test/java/foo/bar/TestSnakeYamlSuite.java
> +public class TestSnakeYamlSuite {
Removed, as doesn't improve legibility or the code

2024-08-19 12:59 UTC, jandro996 commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UntrustedDeserializationModuleTest.groovy
> +  void 'test untrusted deserialization detection with input stream' () {
```suggestion
  void 'test untrusted deserialization detection' () {
```

2024-08-19 13:03 UTC, Mariovido commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UntrustedDeserializationModuleTest.groovy
>      def inputStream = Mock(InputStream)
Agree, I forgot to make the change

2024-08-19 13:07 UTC, jandro996 commented on dd-java-agent/instrumentation/snakeyaml/src/main/java/datadog/trace/instrumentation/snakeyaml/SnakeYamlInstrumenter.java
> +      if (data != null) {
This is not relevant, but as a suggestion when you have multiple if clauses it better to change the condition and short-circuit the method to reduce the cognitive load. For instance

```
if(data==null){
    return;
}
final UntrustedDeserializationModule untrustedDeserialization = InstrumentationBridge.UNTRUSTED_DESERIALIZATION;
if (untrustedDeserialization == null) {
    return;
}
final BaseConstructor constructor = SnakeYamlHelper.fetchConstructor(self);
  if (constructor instanceof Constructor || constructor == null) {
    untrustedDeserialization.onObject(data);
 }
```

2024-08-19 13:12 UTC, jandro996 commented on dd-java-agent/instrumentation/snakeyaml/src/main/java/datadog/trace/instrumentation/snakeyaml/SnakeYamlInstrumenter.java
> +          if (constructor instanceof Constructor || constructor == null) {
Are you sure about this condition?

2024-08-19 13:16 UTC, jandro996 commented on dd-java-agent/instrumentation/snakeyaml/src/test/groovy/SnakeYamlInstrumenterTest.groovy
> +  void 'test snakeyaml load with an input stream'() {
We can simplify this test using one method with a where condition. For instance

```
void 'test snakeyaml load  method'() {
    given:
    final module = Mock(UntrustedDeserializationModule)
    InstrumentationBridge.registerIastModule(module)

    when:
    new Yaml().load(obj)

    then:
    1 * module.onObject(_)

    where:
    obj | _
    new ByteArrayInputStream("test".getBytes()) | _
    new StringReader("test") | _
    "test" | _
  }
```

2024-08-19 13:17 UTC, jandro996 approved these changes

2024-08-19 13:33 UTC, Mariovido commented on dd-java-agent/instrumentation/snakeyaml/src/main/java/datadog/trace/instrumentation/snakeyaml/SnakeYamlInstrumenter.java
> +      if (data != null) {
You're right in this would be better to change the conditions. I'll change it to improve the legibility of the code

2024-08-19 13:36 UTC, Mariovido commented on dd-java-agent/instrumentation/snakeyaml/src/test/groovy/SnakeYamlInstrumenterTest.groovy
> +  void 'test snakeyaml load with an input stream'() {
In this case I don't it could be possible as the load method only accepts a specific type which are InputStream, Reader or String. I cannot pass to it the Object method. One option is to do a casting previous to make the call but IMHO I think it is better to leave it as it is and don't try to simplify it as it will be hard to follow the test

2024-08-21 08:59 UTC, smola requested changes

2024-08-21 08:59 UTC, smola commented on dd-java-agent/instrumentation/snakeyaml/build.gradle
> +  testImplementation group: 'org.yaml', name: 'snakeyaml', version: '1.33'
Add latest version specifier in addition to this. See my comment at https://github.com/DataDog/dd-trace-java/pull/7374#discussion_r1724690549

2024-08-21 08:59 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UntrustedDeserializationModuleImpl.java
> +  public void onObject(@Nullable Object object) {
Would you mind creating a separate PR with just this change?

2024-08-21 12:29 UTC, Mariovido commented on dd-java-agent/instrumentation/snakeyaml/build.gradle
> +  testImplementation group: 'org.yaml', name: 'snakeyaml', version: '1.33'
Added!

2024-08-21 13:32 UTC, Mariovido commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UntrustedDeserializationModuleImpl.java
> +  public void onObject(@Nullable Object object) {
FYI the PR where the change will be made is #7484

After merging it I'll rebase this branch with master

2024-08-22 14:50 UTC, smola approved these changes

2024-08-23 12:01 UTC, merged