Enable error tracking for Java < 11 hosts
DataDog/dd-trace-java pull request #7475
Opened 2024-08-20 06:08 UTC by PerfectSlayer

# What Does This Do

This starts a progressive rollout using product independent sample.

# Motivation

Enabling error tracking for more customers should help to raise any log volume issue, and help with SSI safeguards. 

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [APMLP-102]

2024-08-20 08:30 UTC, smola requested changes

2024-08-20 08:30 UTC, smola commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
> +                "dd.dynamic.instrumentation.enabled", "DD_DYNAMIC_INSTRUMENTATION_ENABLED", false)
This logic should be replicated in Config:
https://github.com/DataDog/dd-trace-java/blob/b0e4869c0bbcfee25eb7c0cfc1069abcd0304863/internal-api/src/main/java/datadog/trace/api/Config.java#L1990-L1998

(yep, this is ugly, but hopefully it'll be gone after 1 release)

2024-08-20 11:10 UTC, PerfectSlayer commented on dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
> +                "dd.dynamic.instrumentation.enabled", "DD_DYNAMIC_INSTRUMENTATION_ENABLED", false)
Good catch! I completely miss this one.
(yup, we can get rid of this part after full rollout)

2024-08-22 08:54 UTC, smola approved these changes

2024-08-22 14:03 UTC, merged