Add LFI exploit prevention support - Smoke test not working
DataDog/dd-trace-java pull request #7487
Opened 2024-08-22 07:08 UTC by jandro996

# What Does This Do

# Motivation

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [PROJ-IDENT]

2024-09-09 15:59 UTC, smola requested changes
Needs to announce RC capability.

2024-09-11 08:57 UTC, smola commented on dd-java-agent/instrumentation/java-io/src/test/groovy/datadog/trace/instrumentation/java/io/FileLoadedRaspHelperForkedTest.groovy
> +    args                                                      |  expected
Can  you format this block?

2024-09-11 10:53 UTC, manuel-alvarez-alvarez commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +        GatewayContext gwCtx = new GatewayContext(false, RuleType.LFI);
```suggestion
        GatewayContext gwCtx = new GatewayContext(true, RuleType.LFI);
```
All RASP operations should be transient

2024-09-11 10:58 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/telemetry/RuleType.java
> +  LFI("lfi"),
:laughing:

2024-09-11 10:59 UTC, manuel-alvarez-alvarez commented on internal-api/src/main/java/datadog/trace/api/gateway/Events.java
> +  static final int FILE_LOADED_ID = 20;
We might have some conflicts here with my [PR](https://github.com/DataDog/dd-trace-java/pull/7591/files#diff-417adb6f8aaf085942b7ea7417a403b0c526bf5ef8e21efddb4aaa0fb2eb2b44)

2024-09-11 11:02 UTC, manuel-alvarez-alvarez commented on dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
> +    gatewayContext.isTransient == false
```suggestion
    gatewayContext.isTransient == true
```

2024-09-12 16:52 UTC, ValentinZakharov approved these changes

2024-09-16 07:50 UTC, smola approved these changes

2024-09-16 08:22 UTC, manuel-alvarez-alvarez approved these changes

2024-09-16 08:23 UTC, merged