Add XSS support for Freemarker
DataDog/dd-trace-java pull request #7497
Opened 2024-08-23 12:57 UTC by Mariovido

# What Does This Do
Adds support to the detection of XSS in the Freemarker library

# Motivation
Being able to detect XSS in the library of Freemarker

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [APPSEC-11285]

2024-08-30 08:47 UTC, smola requested changes

2024-08-30 08:47 UTC, smola commented on dd-java-agent/instrumentation/freemarker-2.3.24/src/main/java/datadog/trace/instrumentation/freemarker24/ObjectWrapperInstrumentation.java
> +    super("freemarker", "object-wrapper");
```suggestion
    super("freemarker");
```

2024-09-03 07:23 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/freemarker-2.3.24/src/main/java/datadog/trace/instrumentation/freemarker24/DollarVariableInstrumentation.java
> +      FREEMARKER_CORE + ".DollarVariable24DatadogAdvice"
We should not add the advice to the helpers, the reason why you need to include it's because of the logger in the advice:

```java
  protected static final Logger log = LoggerFactory.getLogger(DollarVariable24DatadogAdvice.class);
```

2024-09-03 07:23 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/freemarker-2.3.24/src/main/java/freemarker/core/DollarVariable24DatadogAdvice.java
> +        log.debug("Failed to get DollarVariable templateModel", e);
```suggestion
        xssModule.onUnexpectedException("Failed to get DollarVariable templateModel", e);
```

And you can remove the logger declaration and also the advice as a helper.

2024-09-03 07:25 UTC, manuel-alvarez-alvarez commented on dd-java-agent/instrumentation/freemarker-2.3.9/src/main/java/datadog/trace/instrumentation/freemarker9/DollarVariableInstrumentation.java
> +      FREEMARKER_CORE + ".DollarVariable9Helper", FREEMARKER_CORE + ".DollarVariable9DatadogAdvice"
Same as with freemarker 2.3.24 (remove the advice as a helper)

2024-09-03 07:30 UTC, manuel-alvarez-alvarez commented on dd-smoke-tests/springboot-freemarker/src/main/resources/templates/freemarker-2.3.24.ftlh
> +<#ftl output_format="HTML" auto_esc=false>
Can we add a test with `auto_esc=true` and validate that we do not trigger the vuln?

2024-09-03 07:31 UTC, manuel-alvarez-alvarez commented on dd-smoke-tests/springboot-freemarker/src/main/resources/templates/freemarker-2.3.9.ftlh
> +<html>
There are some [directives for escaping](https://freemarker.apache.org/docs/ref_directive_escape.html) in freemarker prior to 2.3.24, it might be interesting to try them

2024-09-03 10:04 UTC, Mariovido commented on dd-java-agent/instrumentation/freemarker-2.3.24/src/main/java/datadog/trace/instrumentation/freemarker24/ObjectWrapperInstrumentation.java
> +    super("freemarker", "object-wrapper");
Changed in the following PR https://github.com/DataDog/dd-trace-java/pull/7532

2024-09-03 10:27 UTC, Mariovido commented on dd-java-agent/instrumentation/freemarker-2.3.24/src/main/java/datadog/trace/instrumentation/freemarker24/DollarVariableInstrumentation.java
> +      FREEMARKER_CORE + ".DollarVariable24DatadogAdvice"
Removed from that place in this https://github.com/DataDog/dd-trace-java/pull/7532 and from the freemarker instrumentation in this one

2024-09-03 10:28 UTC, Mariovido commented on dd-java-agent/instrumentation/freemarker-2.3.24/src/main/java/freemarker/core/DollarVariable24DatadogAdvice.java
> +        log.debug("Failed to get DollarVariable templateModel", e);
The code was moved to the helper in order to avoid to use the logger in the advice

2024-09-03 10:28 UTC, Mariovido commented on dd-java-agent/instrumentation/freemarker-2.3.9/src/main/java/datadog/trace/instrumentation/freemarker9/DollarVariableInstrumentation.java
> +      FREEMARKER_CORE + ".DollarVariable9Helper", FREEMARKER_CORE + ".DollarVariable9DatadogAdvice"
Already removed!

2024-09-03 10:28 UTC, Mariovido commented on dd-smoke-tests/springboot-freemarker/src/main/resources/templates/freemarker-2.3.24.ftlh
> +<#ftl output_format="HTML" auto_esc=false>
Addressed in this PR https://github.com/DataDog/dd-trace-java/pull/7532

2024-09-03 10:28 UTC, Mariovido commented on dd-smoke-tests/springboot-freemarker/src/main/resources/templates/freemarker-2.3.9.ftlh
> +<html>
Same as above https://github.com/DataDog/dd-trace-java/pull/7532

2024-09-09 08:33 UTC, smola requested changes

2024-09-09 08:33 UTC, smola commented on dd-java-agent/instrumentation/freemarker-2.3.9/build.gradle
> +  latestDepTestImplementation group: 'org.freemarker', name: 'freemarker', version: '2.3.23'
`latestDepTest` is supposed to test new releases. However, here we're using a fixed version (correctly, because it will be very unlikely that we get `2.3.23.1` at this point. However, this should preferably not use the `latestDepTest`, but an alternative configuration for that particular version. There's probably a few examples in jetty and akka-http instrumentations.

2024-09-09 08:33 UTC, smola commented on dd-java-agent/instrumentation/freemarker-2.3.9/src/main/java/datadog/trace/instrumentation/freemarker9/DollarVariableDatadogAdvice.java
> +public final class DollarVariableDatadogAdvice {
```suggestion
public final class DollarVariableAdvice {
```

Having `Datadog` included in the name made sense if we were going to inject in the target package, but now that it is under `datadog.*`, this is no longer necessary.

2024-09-09 08:33 UTC, smola commented on dd-java-agent/instrumentation/freemarker-2.3.9/src/main/java/datadog/trace/instrumentation/freemarker9/DollarVariableDatadogAdvice.java
> +  public static class DollarVariableAdvice {
No need for a nested class here.

2024-09-09 08:33 UTC, smola commented on dd-java-agent/instrumentation/freemarker-2.3.9/src/main/java/freemarker/core/DollarVariable9Helper.java
> +public final class DollarVariable9Helper {
`9` (patch version) is not so clear here, `2_3_9` might be preferable.

2024-09-09 08:59 UTC, Mariovido commented on dd-java-agent/instrumentation/freemarker-2.3.9/src/main/java/datadog/trace/instrumentation/freemarker9/DollarVariableDatadogAdvice.java
> +public final class DollarVariableDatadogAdvice {
I removed the Advice class and put the DollarVariableAdvice inside the Instrumentation

2024-09-09 08:59 UTC, Mariovido commented on dd-java-agent/instrumentation/freemarker-2.3.9/src/main/java/datadog/trace/instrumentation/freemarker9/DollarVariableDatadogAdvice.java
> +  public static class DollarVariableAdvice {
Same as previous, the advice was added to the instrumentation class

2024-09-09 09:45 UTC, smola approved these changes

2024-09-09 09:54 UTC, amarziali commented on dd-java-agent/instrumentation/freemarker-2.3.9/build.gradle
> +    versions = '[2.3.24-incubating,]'
this should be `[2.3.9, 2.3.24-incubating]

2024-09-09 09:56 UTC, amarziali commented on settings.gradle
> +include ':dd-java-agent:instrumentation:freemarker-2.3.9'
when multiple version of the same instrumentation exists we tent to group them under a top folder (i.e. `freemarker`) (see [conventions](https://github.com/DataDog/dd-trace-java/blob/master/docs/add_new_instrumentation.md#configuring-gradle))

2024-09-09 09:57 UTC, amarziali commented on settings.gradle
>  include ':dd-java-agent:instrumentation:freemarker-2.3.24'
I would have added the freemarker-2.3.9 module as a test implementation of this one in order to test that only one instrumentation applies as expected. Even if muzzle checks that, adding this is a good practice

2024-09-09 10:26 UTC, amarziali commented on dd-java-agent/instrumentation/freemarker-2.3.9/build.gradle
> +  fail {
I would have tested `pass` with the version that this module is supposed to support. The assertInverse then will check the failure for the complementary range

2024-09-09 10:41 UTC, amarziali commented on dd-java-agent/instrumentation/freemarker-2.3.9/build.gradle
> +    versions = '[2.3.24-incubating,]'
it looks that the maven metadata only keep the last 10 versions so this is not possible.

2024-09-09 10:42 UTC, amarziali commented on dd-java-agent/instrumentation/freemarker-2.3.9/build.gradle
> +  fail {
it looks that the maven metadata only keep the last 10 versions so this is not possible.

2024-09-09 12:11 UTC, Mariovido commented on settings.gradle
> +include ':dd-java-agent:instrumentation:freemarker-2.3.9'
This is being done in the following PR https://github.com/DataDog/dd-trace-java/pull/7579. Once merged I'll do the change in this one

2024-09-09 12:28 UTC, Mariovido commented on settings.gradle
>  include ':dd-java-agent:instrumentation:freemarker-2.3.24'
Already added :)

2024-09-09 12:59 UTC, amarziali approved these changes

2024-09-09 13:13 UTC, merged