Inject trace context into AWS Step Functions input
DataDog/dd-trace-java pull request #7585
Opened 2024-09-09 15:07 UTC by DylanLovesCoffee

# What Does This Do
Enables tracing when a Lambda function invokes a Step Function by injecting the trace context into the Step Function's StartExecutionRequest/StartSyncExecutionRequest.Input object.

The [Logs to Traces Reducer](https://github.com/DataDog/logs-backend/blob/4ec54e460925fbec831cbf5528094740c2b1907b/domains/serverless/apps/logs-to-traces-reducer/src/main/java/com/dd/logs/serverless/logs_to_traces/reducer/output/stepfunction/trace/spanbuilder/control/RootSpanBuilder.java#L55-L62) will read the trace context from the Step Function logs and stitch the spans together. 

# Motivation
Continues the work done in [Python](https://github.com/DataDog/dd-trace-py/pull/7514) and [NodeJS](https://github.com/DataDog/dd-trace-js/pull/4069).

# Additional Notes
Screenshots of feature:
<img width="1751" alt="sfn-exec" src="https://github.com/user-attachments/assets/149dc6f9-47a6-4ef6-8efa-346f32089f54">
<img width="1752" alt="sfn-sync-exec" src="https://github.com/user-attachments/assets/f1917aad-8f82-45c4-810f-130daae78f21">

# Contributor Checklist

- [x] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [x] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [x] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [[SVLS-5249]](https://datadoghq.atlassian.net/browse/SVLS-5249)

2024-09-09 15:28 UTC, amarziali requested changes
Using reflection is not efficient and should be avoided. Instead, MethodHandles can be used.
The pull request lacks also of a minimum test coverage. Test must be added

2024-09-09 15:28 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
> +        ObjectMapper mapper = new ObjectMapper();
This object can be created once since it's thread safe

2024-09-09 15:28 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
> +    if ((clazz.getSimpleName().equals("StartExecutionRequest"))
May `instanceof` be used here?

2024-09-09 15:28 UTC, amarziali commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
> +        Field inputField = clazz.getDeclaredField("input");
This is pretty inefficient and is discouraged. Instead you might obtain (once a `MethodHandle`) and unreflect it in order to avoid paying that extra cost

2024-09-09 17:10 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
> +    if ((clazz.getSimpleName().equals("StartExecutionRequest"))
Main issue is that not all AWS types will be available on the classpath - it depends which parts of the SDK the user deploys. So you can't use types directly like with `instanceof`.

However, I'd prefer to see this use the fully qualified class name, because there is a cost to calling `getSimpleName` and we know the package(s) ahead of time.

2024-09-09 17:19 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
> +        Field inputField = clazz.getDeclaredField("input");
Agreed - I would prefer this to be moved to a step-function specific instrumentation module, like the SNS specific instrumentation module(s) added in https://github.com/DataDog/dd-trace-java/pull/6908 - you can still intercept the request and modify it as appropriate, but you'll have access to the right types and can directly target the appropriate part of the AWS SDK

Trying to do this in the generic AWS SDK instrumentation will make this code convoluted and hard to maintain.

I'd also recommend avoiding adding a dependency to `com.fasterxml.jackson.databind` in the instrumentation, because that might not be accessible in certain deployments - ideally take the same approach as `SnsInterceptor` and just build up the simple string (the JSON isn't that complex)

In fact it's probably a good idea to refactor that `_datadog` JSON building logic out so it can be shared across all the different AWS SDK interceptors that want to add `_datadog` to their requests...

2024-09-10 14:34 UTC, DylanLovesCoffee commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
> +        Field inputField = clazz.getDeclaredField("input");
Ah thanks! That helps a ton. I'll give that a shot to try to clean things up + add test coverage

2024-09-18 14:09 UTC, DylanLovesCoffee commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    int startPos = modifiedInput.indexOf("{");
Hmm StringBuilder.indexOf() does not take a char type

2024-09-20 08:23 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    int startPos = modifiedInput.indexOf("{");
According to the Javadoc:

2024-09-27 12:32 UTC, PerfectSlayer reviewed
I left a bunch of comments about refactoring and testing

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/build.gradle
> +  testImplementation 'software.amazon.awssdk:sfn:2.27.2'
It mismatches muzzle requirements. Is it expected?

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/build.gradle
> +  testImplementation 'org.testcontainers:localstack:1.19.7'
Can you pick the version from `lib.versions` instead to keep it aligned with `testcontainers`?

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +          endPos, String.format(", %s", ddTraceContextJSON)); // prepend comma to existing input
What about using`String.insert()` twice, or simply using string concat?

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +                    .append("\"")
append('"')

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +  public static StringBuilder getModifiedInput(String request, String ddTraceContextJSON) {
Result always used with `.toString()`. Better return `String` here.

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/SfnInterceptor.java
> +      return request.toBuilder().input(modifiedInput.toString()).build();
Can be deduplicated using a dedicated method:
```java
SdkRequest injectTraceContext(request, span) {
      String traceContext = InputAttributeInjector.buildTraceContext(span);
      // Inject the trace context into the Step Function input
      String modifiedInput = InputAttributeInjector.getModifiedInput(request.input(), traceContext);
      return request.toBuilder().input(modifiedInput).build()
}

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/test/groovy/SfnClientTest.groovy
> +  static final LOCALSTACK = new GenericContainer(DockerImageName.parse("localstack/localstack"))
Why not using a shared resource like clients and initialization into `setupSpec`?

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/test/groovy/SfnClientTest.groovy
> +  @Shared SfnClient sfnClient
`close()` missing on `cleanupSpec`

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/test/groovy/SfnClientTest.groovy
> +    def endPoint = "http://" + LOCALSTACK.getHost() + ":" + LOCALSTACK.getMappedPort(4566)
Can be define as fixture field to avoid duplication (already computed at setup)

2024-09-27 12:32 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/test/groovy/SfnClientTest.groovy
> +          operationName "aws.http"
Use `service()` and `operation()` instead

2024-10-09 20:09 UTC, DylanLovesCoffee commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/SfnInterceptor.java
> +      return request.toBuilder().input(modifiedInput.toString()).build();
Since I had to handle both `StartExecutionRequest` and `StartSyncExecutionRequest` param types I ended up doing method overloading for `injectTraceContext()`

2024-10-21 14:41 UTC, DylanLovesCoffee commented
@PerfectSlayer I think I covered all of the comments/corrections, but for some reason the CI's muzzle check is continuing to fail :/

2024-10-24 13:06 UTC, dougqh commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/SfnInterceptor.java
> +  public SdkRequest modifyRequest(
We should probably guard against any exceptions escaping from our listeners.
I'd suggest moving the logic into a modifyRequestImpl and then have modifyRequest wrap modifyRequestImpl and catch any exceptions.

2024-10-24 13:09 UTC, dougqh submitted a review, later dismissed
I'd like to see the Json construction done in a safer way.
I also think we should guard against exceptions propagating out of the listener.

2024-10-24 15:24 UTC, DylanLovesCoffee commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    StringBuilder spanTagsJSON = new StringBuilder();
Ah I updated this with the JsonBuffer but when I run muzzle locally it fails with 
```
error: cannot find symbol
import datadog.trace.bootstrap.JsonBuffer;
                              ^
  symbol:   class JsonBuffer
  location: package datadog.trace.bootstrap
```
Any ideas on if I did something very obviously wrong?

2024-11-20 14:58 UTC, avedmala commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    spanTagsJSON.endObject();
Is this JSON format for the `x-datadog-tags` expected? Not urgent but need to know at some point if we need to handle this format or not.

Usually we expect something like `_dd.p.dm=-0,_dd.p.tid=658b547000000000`

2024-12-03 18:07 UTC, nhulston commented on dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
> +    if ((clazz.getSimpleName().equals("StartExecutionRequest"))
Hey @amarziali, I'm working on this PR now since Dylan is out. Marking this as resolved since it appears we don't use reflection anymore.

2024-12-03 18:12 UTC, nhulston commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    StringBuilder spanTagsJSON = new StringBuilder();
I ran into the same muzzle issue trying to use a JSON parsing library when doing the EventBridge instrumentation. I was basically told we can't use additional libraries in instrumentations and to do the JSON parsing manually with stringbuilder.

There are obviously security concerns with this, so it looks like we're blocked until there is a standardized way to parse JSONs in instrumentations in this repo.

2024-12-04 12:37 UTC, PerfectSlayer commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    StringBuilder spanTagsJSON = new StringBuilder();
I just merge #7973 It should provide API to build JSON payload from instrumentations (see `JsonWriter` and `JsonMapper`).

2024-12-06 13:03 UTC, amarziali commented
@nhulston is this PR ready to be reviewed ? I see tests are failing. Otherwise it can be put in draft for now

2025-01-24 16:17 UTC, DylanLovesCoffee commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    spanTagsJSON.endObject();
Clarifying note here: `x-datadog-tags` should actually be comma separated key values 📝

2025-02-07 16:22 UTC, nhulston commented
Failures are unrelated (looks like AWS never published EventBridge 2.30.15 to Maven?)
https://mvnrepository.com/artifact/software.amazon.awssdk/eventbridge/2.30.15

2025-02-10 09:51 UTC, PerfectSlayer approved these changes
Looking good from Platform PoV. I will let IDM review instrumentation.

About the failing tests, you can retry them following: https://github.com/DataDog/dd-trace-java/blob/master/docs/how_to_test.md#flaky-tests

2025-02-11 10:06 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    return modifiedInput.toString();
This method could be made more performant with the following approach:
* skip trimming the string before finding `{` and `}` to avoid creating an intermediate string
* that would also let you use `request.indexOf('{')` etc. which is faster
* compare the numerical positions of `{` and `}` 
  * if they're next to each other, no need to create/trim anything and you can return `"{" + DATADOG_KEY + ":" + ddTraceContextJSON + "}"`
  * otherwise get the substring between `{` and `}` trim it and store it in `existingJSON`
  * if `existingJSON` is empty you can return `"{" + DATADOG_KEY + ":" + ddTraceContextJSON + "}"`
  * otherwise return `"{" + existingJSON + "," + DATADOG_KEY + ":" + ddTraceContextJSON + "}"`

you could also extract `DATADOG_KEY + ":" + ddTraceContextJSON` to a local variable to avoid repeating it

2025-02-11 10:08 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    return modifiedInput.toString();
Also I assume we know the original string will always be JSON?

2025-02-11 18:21 UTC, nhulston commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +    return modifiedInput.toString();
Yes, the original string must be a JSON string (if empty, it must be `{}`) in order for AWS to accept the request. However, the user could end up putting an incorrect json string; in that case, we can leave the request unchanged so that the user will see the error on from AWS, not from the tracer.

2025-02-12 10:32 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +      throw new IllegalArgumentException(); // leave request unmodified
```suggestion
      return request;
```
ideally we shouldn't be throwing exceptions in our code in case they escape the advice and affect the application

exceptions are also not cheap

2025-02-12 10:32 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +      throw new IllegalArgumentException(); // leave request unmodified
```suggestion
      return request;
```
ideally we shouldn't be throwing exceptions in our code in case they escape the advice and affect the application

exceptions are also not cheap

2025-02-12 10:34 UTC, mcculls commented on dd-java-agent/instrumentation/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/InputAttributeInjector.java
> +      return "{}";
```suggestion
      return null;
```
to match the check in `getModifiedInput` to leave the request unmodified

2025-02-12 10:37 UTC, mcculls approved these changes
Thanks for the work on this - I've suggested a couple of final improvements

2025-02-12 16:21 UTC, amarziali approved these changes

2025-02-19 19:08 UTC, merged