fix: add system tests aws credentials
DataDog/dd-trace-java pull request #7629
Opened 2024-09-16 18:23 UTC by wconti27

# What Does This Do

add aws credentials for new system tests that create aws resources

# Motivation

more testing, more fun

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [PROJ-IDENT]

2024-09-19 14:36 UTC, smola requested changes

2024-09-19 14:36 UTC, smola commented on .circleci/config.continue.yml.j2
> +            git checkout conti/fix-php-errors
Make sure you remove this before merging. Also note that for testing within PRs, it's also possible to change the value of `systemTestsCommit` in this file, to point to a commit hash in your system-tests branch. Anyway, since it's only for testing within a branch, whatever works for you is ok.

2024-09-19 14:36 UTC, smola commented on .circleci/config.continue.yml.j2
> +      - run:
These steps probably belong to the `integrations-system-tests` job.

2024-09-24 16:31 UTC, wconti27 commented on .circleci/config.continue.yml.j2
> +            git checkout conti/fix-php-errors
I've removed this

2024-09-24 16:31 UTC, wconti27 commented on .circleci/config.continue.yml.j2
> +      - run:
done

2024-09-30 16:59 UTC, smola approved these changes

2024-09-30 18:35 UTC, merged