Short circuit for WAF/RASP calls
DataDog/dd-trace-java pull request #7630
Opened 2024-09-16 21:06 UTC by ValentinZakharov

# What Does This Do
Removed hardcoded addresses for WAF/RASP calls, to increase overall performance.

# Motivation
To avoid redundant calls and decrease overhead, call WAF/RASP only when rules contains specific addresses.
If address is absent or disabled in rules, then we should avoid WAF/RASP calls.
Also, no RASP metric should be generated in this case.

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [PROJ-IDENT]

2024-09-19 12:55 UTC, jandro996 commented
Not sure if already exists (I'm don't have deep knowledge this topic), but it will be nice to have some test cases to test what it's explained in the JIRA ticket:

- This short-circuit RASP instrumentations.
- No rasp metric should be generated in this case, especially duration. 
- Short-circuit must happen before.

If you think it's not necessary, feel free to continue with the merge! :)

2024-09-19 13:01 UTC, jandro996 approved these changes

2024-09-19 14:39 UTC, smola requested changes
As discussed offline, we should add the tests. I can see us regressing here without a test.

2024-09-23 12:56 UTC, smola approved these changes

2024-09-24 14:47 UTC, merged