Send IAST vulnerability secure marks to backend
DataDog/dd-trace-java pull request #7645
Opened 2024-09-19 11:32 UTC by jandro996

# What Does This Do

# Motivation

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [PROJ-IDENT]

2024-09-19 14:00 UTC, manuel-alvarez-alvarez commented on dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite-with-marks.yml
> +              { "start" : 74, "length" : 6, "source": { "origin": "http.request.parameter", "name": "cn", "value": "Babs Jensen" } , "marks": 512}
`"marks": 512` is tied to how we implement secure marks in Java, for the common yml it should be a list of vulnerabilities (we can adapt it to our format during parsing)

2024-09-19 14:14 UTC, smola requested changes

2024-09-19 14:14 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Range.java
> +import org.jetbrains.annotations.Nullable;
It seems we generally use `javax.annotation.Nullable`.

2024-09-19 14:14 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
> +  VulnerabilityType[] MARKED_VULNERABILITIES = {
Can you add a comment here describing which vulnerabilities are supposed to be listed here and why?

2024-09-19 14:14 UTC, smola commented on dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite-with-marks.yml
> +              { "start" : 26, "length" : 17, "source": { "origin": "http.request.parameter", "name": "clause", "value": "username = 'john'" } , "marks": 128}
128? Is this supposed to be used by other languages? I don't think these bitflags are language-independent, I'd say they are an implementation detail for Java. Ok for our repo, but it probably won't do for the shared test suite.

2024-09-20 07:38 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Range.java
> +import org.jetbrains.annotations.Nullable;
😱

2024-09-20 07:52 UTC, jandro996 commented on dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite-with-marks.yml
> +              { "start" : 74, "length" : 6, "source": { "origin": "http.request.parameter", "name": "cn", "value": "Babs Jensen" } , "marks": 512}
You're right that the format chosen is specific to the Java tracer. I went with this approach in the first iteration because it was simpler to implement. The reason I did this is that I wanted to have a broader discussion with the team regarding how we're testing the reporting across different languages. This could potentially impact how we're conducting these tests, so I wanted to raise that point for consideration.

That said, I'll go ahead and make the change to improve readability.

2024-09-20 07:53 UTC, jandro996 commented on dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite-with-marks.yml
> +              { "start" : 26, "length" : 17, "source": { "origin": "http.request.parameter", "name": "clause", "value": "username = 'john'" } , "marks": 128}
You're right, please check my previous answer 😄

2024-09-30 08:28 UTC, smola approved these changes

2024-09-30 09:10 UTC, merged