Add propagation to String strip methods
DataDog/dd-trace-java pull request #7651
Opened 2024-09-20 07:34 UTC by Mariovido

# What Does This Do
This adds the instrumentation to propagate the taint values through the methods of `String` called `strip`, `stripLeading` and `stripTrailing`. This method are only available from version 11 of Java.

# Motivation
Increase propagation of String methods

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [APPSEC-5757]

2024-09-20 09:04 UTC, smola requested changes

2024-09-20 09:04 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    "strip"         | false    | "   ==>123<==   " | "==>123<=="
Some things to test (in this or other test functions):
```
    "strip"         | false    | "   ==>123<==   " | "==>123<=="
    "strip"         | false    | "   ==>123<==   " | "==>123<=="
    "strip"         | false    | "==>   123   <==" | "==>123<=="
    "strip"         | false    | "   a==> b <==c   " | "a==> b <==c"
...
```

2024-09-20 09:04 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +  void 'test strip for not empty string cases'() {
What's the difference with `test strip and make sure IastRequestContext is called`? Shouldn't this be just one test, with more cases in `where`?

2024-09-20 09:04 UTC, smola commented on dd-java-agent/instrumentation/java-lang/java-lang-11/src/test/groovy/datadog/trace/instrumentation/java/lang/jdk11/StringCallSiteTest.groovy
> +    "stringStripLeading"  | ' hello ' | 'hello '
stripTrailing not tested?

2024-09-20 09:23 UTC, Mariovido commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    "strip"         | false    | "   ==>123<==   " | "==>123<=="
Added those test

2024-09-20 09:23 UTC, Mariovido commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +  void 'test strip for not empty string cases'() {
There is not difference to be honest so I have merged them into one with multiple wheres

2024-09-20 09:26 UTC, Mariovido commented on dd-java-agent/instrumentation/java-lang/java-lang-11/src/test/groovy/datadog/trace/instrumentation/java/lang/jdk11/StringCallSiteTest.groovy
> +    "stringStripLeading"  | ' hello ' | 'hello '
I was creating an specific test for this one but It didn't make sense. I have merged them into one

2024-09-23 07:09 UTC, smola requested changes
Looks good. A couple of minor issues and we're good to go.

2024-09-23 07:38 UTC, Mariovido commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +    if (!canBeTainted(result) || self == result) {
Changed order

2024-09-23 07:38 UTC, Mariovido commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
> +  @SuppressFBWarnings
Added warning

2024-09-23 07:44 UTC, smola approved these changes

2024-09-23 08:09 UTC, manuel-alvarez-alvarez approved these changes
LGTM, nice one!

2024-09-23 10:18 UTC, merged