Attach stacktrace to IAST vulnerabilities
DataDog/dd-trace-java pull request #7757
Opened 2024-10-11 11:15 UTC by jandro996

# What Does This Do

# Motivation

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [APPSEC-11649]

2024-10-11 11:24 UTC, jandro996 commented on communication/src/main/java/datadog/communication/serialization/Codec.java
> +  private static final class StackTraceBatchWriter implements ValueWriter<StackTraceBatch> {
All these new writers should be improved to avoid serialisation of null or empty elements

2024-10-11 11:25 UTC, jandro996 commented on communication/src/test/java/datadog/communication/serialization/msgpack/MsgPackWriterTest.java
Add more test cases to cover optional fields, as it's preferible to not send null or empty elements

2024-10-11 11:31 UTC, jandro996 commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
> +    2 * span.getRequestContext() >> reqCtx // first time to build the batch vulnerability, second time to build the stack trace
This test case is relevant to discuss what to do, as we don't have the IastRequestContext we are not able to determine the stackId with the current approach so in this case stacktrace wont be added

2024-10-11 11:32 UTC, jandro996 commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
> +  /*  void 'Add vulnerability stack trace' (){
remove leftovers

2024-10-11 11:35 UTC, jandro996 commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
> +  private void assertStackTrace(StackTraceBatch batch, Vulnerability[] vulnerabilities) {
Mock in some way the `StackUtils.generateUserCodeStackTrace()` to return the StackTraceElement used to create the vuln location and check that matches the generated StackTraceFrame

2024-10-11 11:36 UTC, jandro996 commented on dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
> +        Collection<StackTraceEvent> stackTraces = ctx.getStackTraces();
Change all these Collections to List

2024-10-15 11:37 UTC, Mariovido commented on communication/src/main/java/datadog/communication/serialization/Codec.java
> +        return; // This should never happen
If this should never happen, which is the point of checking it?

2024-10-16 06:15 UTC, jandro996 commented on communication/src/main/java/datadog/communication/serialization/Codec.java
> +        return; // This should never happen
I did the check because the lists `exploit` and `vulnerability` are both optional so if we introduce a bug building the StackTraceBatch we are covered

2024-10-17 09:48 UTC, smola requested changes

2024-10-17 09:48 UTC, smola commented on communication/src/main/java/datadog/communication/serialization/Codec.java
> +      boolean hasExploits = value.getExploit() != null && !value.getExploit().isEmpty();
Could we make this product-independent? Not really hardcoding here `exploit`, `vulnerability`, etc?

2024-10-17 09:48 UTC, smola commented on communication/src/main/java/datadog/communication/serialization/Codec.java
> +        LOGGER.warn("No data to serialize in StackTraceBatch");
I would say no warn here, debug + SEND_TELEMETRY?

2024-10-17 09:48 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
> +      if (Config.get().isAppSecStackTraceEnabled()) {
I'd suggest using an IAST-specific flag here (might need to be checked at spec level).

2024-10-17 09:48 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
> +        if (stackId != null) {
Not sure we need an incremental  ID here, since we have the index of the vulnerability in the `VulnerabilityBatch`, which is unique in a given context?

2024-10-17 09:48 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
> +    if (stackTraceBatch == null) {
This is not thread-safe. Multiple products, or even same product setting this from different threads might override each other. A simple way to solve this would be using some internal-api helper to do this op, with it being `synchronized`.

2024-10-17 09:48 UTC, smola commented on dd-trace-api/src/main/java/datadog/trace/api/internal/TraceSegment.java
> +  Object getMetaStructTop(String key);
I would really try to avoid leaking more methods to `TraceSegment` (public API), or try to minimize how many we add. Can't we use an internal interface here?

2024-10-17 11:50 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
> +      if (Config.get().isAppSecStackTraceEnabled()) {
This is something that I've suggested in the RFC and the response was that as appsec was the first that implement the stack trace was preferible to keep this as it is than create another env var.  Let's discuss it internally

2024-10-18 07:03 UTC, jandro996 commented on communication/src/main/java/datadog/communication/serialization/Codec.java
> +      boolean hasExploits = value.getExploit() != null && !value.getExploit().isEmpty();
Done

2024-10-18 07:04 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
> +        if (stackId != null) {
Done

2024-10-18 09:26 UTC, jandro996 commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
> +    2 * span.getRequestContext() >> reqCtx // first time to build the batch vulnerability, second time to build the stack trace
Not relevant any more as we change the approach an remove the dependency on IastaContext

2024-10-21 08:14 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
> +    if (stackTraceBatch == null) {
Done

2024-10-22 14:56 UTC, smola commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
> +      if (Config.get().isAppSecStackTraceEnabled()) {
Ok to move on without this change, but I'd like to follow up on it later.

2024-10-22 15:03 UTC, smola approved these changes

2024-10-22 15:34 UTC, smola commented on internal-api/src/main/java/datadog/trace/util/stacktrace/StackUtils.java
> +    list.addAll(events);
Thread safety of the map was addressed, but `ArrayList` is not thread-safe. We can probably just wrap it with `Collections.synchronizedList`, since I would expect this code path to not be that performance sensitive.

2024-10-23 09:03 UTC, jandro996 commented on dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
> +      if (Config.get().isAppSecStackTraceEnabled()) {
I'll add a product specific variable for enabling/disabling the stacktrace generation, seems that in the iast wg most of us are in agreement

2024-10-24 11:32 UTC, manuel-alvarez-alvarez commented on communication/src/main/java/datadog/communication/serialization/Codec.java
> +    if (StackTraceEvent.class.isAssignableFrom(clazz)) {
Can you register the writers with the codec instead? those if/else are better suited for JDK types.

2024-10-24 11:32 UTC, manuel-alvarez-alvarez commented on communication/src/main/java/datadog/communication/serialization/Codec.java
> +  private static final class StackTraceEventWriter implements ValueWriter<StackTraceEvent> {
I'll rather extract those classes as they are unrelated to codec default functionality.

2024-10-24 11:33 UTC, manuel-alvarez-alvarez commented on communication/src/main/java/datadog/communication/serialization/Codec.java
> +      boolean hasId = value.getId() != null && !value.getId().isEmpty();
Have you considered using a helper method :wink:?

2024-10-24 11:34 UTC, manuel-alvarez-alvarez commented on dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
> +    result.size() == 1
dup

2024-10-24 11:37 UTC, manuel-alvarez-alvarez approved these changes

2024-10-25 09:14 UTC, merged