Support service name overrides for DSM
DataDog/dd-trace-java pull request #7798
Opened 2024-10-17 20:56 UTC by kr-igor

# What Does This Do

# Motivation

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [PROJ-IDENT]

2024-10-18 11:31 UTC, amarziali commented on dd-java-agent/instrumentation/spark-executor/src/main/java/datadog/trace/instrumentation/spark/SparkExecutorDecorator.java
> +        Field prop = taskDescription.getClass().getDeclaredField("properties");
I think you should optimize this by unreflecting a method handle for this getter. It will save access checking costs

2024-10-18 11:32 UTC, amarziali commented on dd-java-agent/instrumentation/spark-executor/src/main/java/datadog/trace/instrumentation/spark/SparkExecutorDecorator.java
> +              .setThreadServiceName(taskRunner.getThreadId(), appName);
Is product wise coherent to have a different service name from what represented by DSM and what represented by the tracing?

2024-10-18 14:25 UTC, piochelepiotr commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
> +    Map<String, List<StatsBucket>> includedBuckets = new HashMap<>();
we could also put the service name in the statsPoint. What do you think? It would avoid doing this grouping logic here.

2024-10-18 14:43 UTC, kr-igor commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
> +    Map<String, List<StatsBucket>> includedBuckets = new HashMap<>();
The service name is reported per bucket. You can put it inside the stats point but then you'll have to modify the writer to correctly split the bucket. Effectively doing similar thing in a different place.

2024-10-18 14:53 UTC, kr-igor commented on dd-java-agent/instrumentation/spark-executor/src/main/java/datadog/trace/instrumentation/spark/SparkExecutorDecorator.java
> +              .setThreadServiceName(taskRunner.getThreadId(), appName);
It makes sense in case with Spark / Flink. It may not be possible to pass the service name from outsize in managed environments (for instance spans generated within Databricks for DJM may have service name == "databricks.all-purpose-cluster.dlt-execution-123"). At the same time customers expect to see the Spark Job name, not the cluster node name.

Also there a cases when a single running application (Task Manager in Flink) runs multiple independent stream processing tasks. Each task has it's own "service name", using node name is incorrect.

The better approach would be to dynamically set global service name depending on the context. This seems like a way large change. Happy to discuss this separately.

2024-10-18 14:57 UTC, amarziali commented on dd-java-agent/instrumentation/spark-executor/src/main/java/datadog/trace/instrumentation/spark/SparkExecutorDecorator.java
> +              .setThreadServiceName(taskRunner.getThreadId(), appName);
actually you can do it by calling `updatePreferredServiceName` (https://github.com/DataDog/dd-trace-java/blob/00856e02d3478ae8b317ec1adc31b565423ef8d0/internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java#L293). Is it what you were looking from?

2024-10-18 16:17 UTC, amarziali commented on dd-java-agent/instrumentation/spark-executor/src/main/java/datadog/trace/instrumentation/spark/SparkExecutorDecorator.java
> +              .setThreadServiceName(taskRunner.getThreadId(), appName);
OK if it depends from the current context then it's not globally applying to the JVM.

2024-11-08 08:51 UTC, amarziali requested changes
I think that addition is a good to have to improve the experience of DSM consumers. I've still some concerns especially around adding an unbounded map to store thread id to name correspondences. It should be done in a threadlocal and actually it might not work if the kafka producer (in this example) is called in a thread different from the spark task one. Also it will be nice to have more e2e testing with spark and kafka

2024-11-08 08:51 UTC, amarziali commented on dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
> +                saved.getServiceNameOverride());
Are message produced in the same thread where the task is running? Also are we testing it? I did not see spark tests with kafka but perhaps I missed it

2024-11-08 08:51 UTC, amarziali commented on dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
> +  private static final ConcurrentHashMap<Long, String> threadServiceNames =
I've some concerns adding unbounded maps here. It might be ok for the spark instrumentation but this has been added to a generic API on DataStreamMonitoring. It can be used in the future in a bad way and start leaking. If service names have to be pinned to a thread, possible a threadlocal variable should be used in order to ensure that that value will go away when the thread is collected.

2024-11-18 07:54 UTC, amarziali approved these changes

2024-11-18 15:26 UTC, merged