Add propagation to StringBuffer substring methods
DataDog/dd-trace-java pull request #7992
Opened 2024-11-21 12:04 UTC by Mariovido

# What Does This Do
This adds the instrumentation to propagate the taint values through the following methods of `StringBuffer`:
- `substring(int)`
- `substring(int, int)`

# Motivation
Increase propagation of `StringBuffer` methods.

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [APPSEC-55369]

2024-11-21 13:45 UTC, jandro996 approved these changes

2024-11-21 16:39 UTC, smola commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    return new StringBuilder(string)
```suggestion
    return new StringBuffer(string)
```

2024-11-21 16:39 UTC, smola requested changes
See above

2024-11-22 09:06 UTC, Mariovido commented on dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
> +    return new StringBuilder(string)
Changed!

2024-11-22 09:32 UTC, smola approved these changes

2024-11-22 10:40 UTC, merged